### ISSUE TITLE
不兼容 HEXO-v6.0.0

### ISSUE THREAD

**Issue by PengCheong** [ppoffice/hexo-theme-icarus#1008]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
未兼容 hexo@6.0.0 。

**系统与环境**
列出你的Hexo和Icarus的版本和配置。

- Hexo，操作系统，和 Node.js 的版本
  ```text
  hexo-cli: 4.3.0
  os: win32 10.0.22000
  node: 16.13.1
  v8: 9.4.146.24-node.14
  uv: 1.42.0
  zlib: 1.2.11
  brotli: 1.0.9
  ares: 1.18.1
  modules: 93
  nghttp2: 1.45.1
  napi: 8
  llhttp: 6.0.4
  openssl: 1.1.1l+quic
  cldr: 39.0
  icu: 69.1
  tz: 2021a
  unicode: 13.0
  ngtcp2: 0.1.0-DEV
  nghttp3: 0.1.0-DEV
  ```
- 除了修改 `_config.yaml` 下的 `theme: icarus`，所有其他配置文件均保持默认
  

**复现方式**

1. 通过 volta 安装 hexo@6.0.0，
    ```powershell
    volta install npm ; volta install yarn ; volta install hexo-cli
    ```

2. 执行 npm 安装 `icarus`
    ```powershell
    npm install hexo-theme-icarus
    ```
    得到错误如下：
    
    ![image](https://user-images.githubusercontent.com/48322394/149074053-bf9b3a31-eecb-45e7-a193-74d77144767e.png)

3. 尝试强制安装 `icarus`
    ```powershell
    npm install hexo-theme-icarus --force
    ```
    安装过程无报错，修改根目录 `_config.yaml` 中的 `themes: icarus`，并 `hexo s -d` 启动 hexo

    ![image](https://user-images.githubusercontent.com/48322394/149074614-99cbb7f5-0915-4801-bd71-c02b87afb7f6.png)

**期望行为**
期望能支持 hexo@6.0.0以在本地正确安装

**截图**
- ![image](https://user-images.githubusercontent.com/48322394/149074915-d9791a43-28a5-4989-803d-d40e56ef6987.png)
- ![image](https://user-images.githubusercontent.com/48322394/149075100-95bd4a24-9c4c-4ffe-80ef-7149f9849a57.png)

**Comment by Lemonawa** [comment]
+1  
文字版
```
Package hexo's version (6.0.0) does not satisfy the required version (^5.0.2).
ERROR Please install the missing dependencies your Hexo site root directory:
ERROR npm install --save hexo@^5.0.2
ERROR or:
ERROR yarn add hexo@^5.0.2
```
望早日解决

**Comment by ppoffice** [comment]
@PengCheong @Lemonawa 
https://github.com/ppoffice/hexo-theme-icarus/releases/tag/5.0.0-rc.1

**Comment by PengCheong** [comment]
@ppoffice [500-rc.1](<https://github.com/ppoffice/hexo-theme-icarus/releases/tag/5.0.0-rc.1>) 得以按照期望安装，但似乎不在我的电脑正确工作，我尝试了新建目录进行以下操作

```powershell
mkdir tmp ; cd tmp
hexo init
npm install hexo-theme-icarus
(Get-Content -path _config.yaml -Raw) -replace 'landscape','icarus''
hexo server
```

## Bug描述

未能正确渲染页面

## 系统与环境



<details>
  <summary>与上文保持一致</summary>
  hexo: 6.0.0 /
  hexo-cli: 4.3.0 /
  os: win32 10.0.22000 /
  node: 16.13.1 /
  v8: 9.4.146.24-node.14 /
  uv: 1.42.0 /
  zlib: 1.2.11 /
  brotli: 1.0.9 /
  ares: 1.18.1 /
  modules: 93 /
  nghttp2: 1.45.1 /
  napi: 8 /
  llhttp: 6.0.4 /
  openssl: 1.1.1l+quic /
  cldr: 39.0 /
  icu: 69.1 /
  tz: 2021a /
  unicode: 13.0 /
  ngtcp2: 0.1.0-DEV /
  nghttp3: 0.1.0-DEV
</details>

## 相关截图

- 已正确安装且服务正常启动
   ![image](https://user-images.githubusercontent.com/48322394/149662086-86625d5e-0b75-4dc0-ad22-5e0343e469c6.png)

- 未能正常渲染页面
   ![image](https://user-images.githubusercontent.com/48322394/149662215-49ef213a-007c-4287-b68a-6844d98c7fc6.png)
   > const { Component } = require('inferno'); const classname = require('hexo-component-inferno/lib/util/classname'); const Head = require('./common/head'); const Navbar = require('./common/navbar'); const Widgets = require('./common/widgets'); const Footer = require('./common/footer'); const Scripts = require('./common/scripts'); const Search = require('./common/search'); module.exports = class extends Component { render() { const { site, config, page, helper, body } = this.props; const language = page.lang || page.language || config.language; const columnCount = Widgets.getColumnCount(config.widgets, config, page); return
; } };

- package.json

   ![image](https://user-images.githubusercontent.com/48322394/149662528-6a3b623a-15e8-4ec3-a5e5-bca8f0ab707d.png)

## 期望行为

我不甚了解前端知识，因此不会确定相关内容是否是我本地特殊情况引起的，抑或是这个版本的问题？

期望能得到你的帮助。

**Comment by ppoffice** [comment]
@PengCheong 删除hexo-renderer-ejs,添加hexo-renderer-inferno

**Comment by PengCheong** [comment]
我尝试使用上述方法，但这似乎引起了一个新的问题？

![image](https://user-images.githubusercontent.com/48322394/149663709-44aa8af1-5993-4d91-8164-ece34eb8505a.png)

以下是我现在的package.json相关信息：

```json
"dependencies": {
    "hexo": "^6.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-inferno": "^0.1.3",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-icarus": "^5.0.0-rc.1",
    "hexo-theme-landscape": "^0.0.3"
  }
```

**Comment by ppoffice** [comment]
hexo clean

**Comment by PengCheong** [comment]
非常感谢，现在工作正常了
