### ISSUE TITLE
在使用 Waline 等评论系统出现的问题

### ISSUE THREAD

**Issue by Nofated095** [ppoffice/hexo-theme-icarus#1021]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**

Waline 会区分类似于 `example.com/example` 和 `example.com/example/` 这两个相同的网址，会导致评论系统无法正常在 `example` 这个页面显示。

类似的有 <https://blog.nofated.win/friends> 和 <https://blog.nofated.win/friends/>，前者无法显示评论，后者可以，但实际上这两个网页是相同的

**系统与环境**

Hexo 5.0

Icarus 4.5.0

**复现方式**
列出复现这个Bug的步骤，如：

1. 访问 ‘https://blog.nofated.win/friends’
2. 下拉到‘评论’，发现没有评论
3. 访问 ‘https://blog.nofated.win/friends/’
4. 下拉到‘评论’，发现有评论

**期望行为**
能使 `example.com/example` 和 `example.com/example/` 都能正常显示评论

我在 waline 在 github 的 仓库上进行了反馈，他们给出了解决方案 <https://github.com/walinejs/waline/discussions/748>

**截图**

![1](https://user-images.githubusercontent.com/49985975/150459201-e8339115-f1f7-4fc1-8c82-2393f52920ce.PNG)
![2](https://user-images.githubusercontent.com/49985975/150459197-d1f5b5c7-279b-42b2-9643-a413244edacf.PNG)

**Comment by ppoffice** [comment]
@Nofated095 严格意义上讲`example.com/example`和`example.com/example/`是两个不同的网址，自然其中一个页面的评论不会显示到另一个页面的评论中。如果因为个人需要把两个网址当作同一个网址的话，建议按照[FAQ - 挂件/评论插件/分享按钮...的布局文件在哪里？我如何个性化内置的挂件/评论插件/分享按钮...？](https://ppoffice.github.io/hexo-theme-icarus/uncategorized/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/#%E5%B8%83%E5%B1%80)的方法自行修改[waline.jsx](https://github.com/ppoffice/hexo-component-inferno/blob/1.0.2/src/view/comment/waline.jsx)。
