### ISSUE TITLE
希望文章页面添加编辑按钮，点击此按钮打开本地 md 文件。

### ISSUE THREAD

**Issue by GanZhiXiong** [ppoffice/hexo-theme-icarus#1023]
## 为什么要实现此功能
很多时候，我们在网页中浏览自己写的文章，突然发现文章有错别字、漏字、写错等，这时我们再在本地文件中去找到此文件再编辑，找文件的过程将比较耗时，若文章页面有个编辑按钮，直接点击此按钮打开本地 md 文件，那就真的太方便、体验太好了！

## 此功能需求实现方案
1. 每次执行 `hexo g` 时，记录下 md 文件所在的路径。
2. 在文章页面添加编辑按钮。
3. 点击编辑按钮，打开 md 文件。
4. 如果文件存在则直接打开，不存在则提示“文件不存在”。

**Comment by ppoffice** [comment]
@GanZhiXiong 如何实现第三部中的“打开md文件”？
首先，如果是在浏览器中打开文件，那么由于浏览器的安全限制无法通过文件的本地地址直接读取文件。
其次，如果是调用系统中已安装的文字编辑器，那么浏览器如何得知用户操作系统中安装了那些编辑器？如果编辑器没有注册URL handler来打开本地文件的话，同样无法实现这个功能。
另外，如果说是通过HTTP API的方式调用Node.js来打开文件，那么用户的电脑上还需要一直运行一个HTTP Server用来处理文件打开的请求。这么做同样不合理。
最后，同样由于浏览器的安全限制，网页无法得知用户本地文件系统中的文件是否存在。

**Comment by GanZhiXiong** [comment]
我觉得可以这样。
1. 文章页面添加一个复制 md 文件路径的按钮。
2. 点击此按钮复制 md 文件路径。
3. 按下 Alfred 的快捷键。
4. 粘贴路径。
5. 回车打开 md 文件。

**虽然这样步骤会多了 3、4、5，但是至少能实现。
3、4、5 也可以通过 Karabiner-Elements 或 BetterTouchTool 配置一个快捷键用来打开剪切板中的路径。

所以只需实现 1 和 2 即可。**

**Comment by GanZhiXiong** [comment]
期待大佬实现此功能

**Comment by W01fh4cker** [comment]
我同样觉得这是一个伪需求，没有必要这么做。
