### ISSUE TITLE
网页logo和社交icon图片无法显示的问题

### ISSUE THREAD

**Issue by Qiaozhi94** [ppoffice/hexo-theme-icarus#1024]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
在_config.icarus.yml文件中我修改了logo和social_links的icon图标，换成了我上传到阿里云oss图床上的svg图片，结果都无法正常显示，但同样的办法和链接用在favicon和avatar上都没有问题，具体可以参见网站：https://qiaozhi94.github.io

**系统与环境**
hexo: 6.0.0
hexo-cli: 4.3.0
os: win32 10.0.22000
node: 14.18.0
v8: 8.4.371.23-node.84
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.3
openssl: 1.1.1l
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
google chrome 96.0.4664.93（正式版本） （64 位）

**复现方式**
列出复现这个Bug的步骤，如：

1. 上传图片到阿里云oss图床
2. 复制url链接粘贴到_config.icarus.yml配置文件中的相应位置
3. 运行 hexo cl && hexo g && hexo d
4. 打开网站出现图片无法显示的问题

**期望行为**
期望能够正常显示url格式下的logo和social_links中的icon图片

**截图**
![image](https://user-images.githubusercontent.com/91832470/151158104-a88226fd-6645-4120-840e-bf39cbaab02b.png)
![image](https://user-images.githubusercontent.com/91832470/151158636-ab6987fb-e7e8-4e84-a3fe-2d6b721cc8b7.png)
![image](https://user-images.githubusercontent.com/91832470/151158487-b7463409-902c-4458-bc05-26f9b87aa55a.png)
![image](https://user-images.githubusercontent.com/91832470/151158525-08ca7013-38ac-4917-a760-9dffa1d6e647.png)

**额外上下文**
在网上查了好几天了都没有答案，也没有修改过其他文件，非常期待大佬能帮忙解决这个问题！

**Comment by ppoffice** [comment]
URL有冒号，要用引号围起来

**Comment by ppoffice** [comment]
`icon`只能使用font-awesome的class name，不可以使用图片链接。
