### ISSUE TITLE
Index and Archives not rendering assets

### ISSUE THREAD

**Issue by joydragon** [ppoffice/hexo-theme-icarus#104]
Hi,

I updated the theme (forgot the previous version) and somehow I found out that whenever I tested the rendering of my posts I got on the index page, and on the archives page that the content will only be the text of my post.
The images were not rendered (there were no image tags on the html) and the footers that I've inserted are only rendered as the brackets and number.
Do you guys have any info on this?

Thanks!

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/wiki/Theme#how-to-add-a-thumbnail-to-a-post

And also there is a significant change in the _config.yml to be noticed.

**Comment by joydragon** [comment]
Thanks for the fast reply, but it's not the thumbnail or banner I'm talking about, it's actual images.
I'm using the  tag to create an excerpt, and that initial part of the post has some images on this format:
 ![text](/2016/02/15/Lo-estamos-haciendo-mal/01.png "text")

I think that something like that is the problem. 
On my hexo _config.yml I use:

post_asset_folder: true
relative_link: false

Should I use the full path on the image? 

Whenever on the excerpt is an image it ends up being not rendered at all, on the archive the thumbnail is there but the images are not.

![post1](https://cloud.githubusercontent.com/assets/4154219/13327031/fa1f2c76-dbc6-11e5-99c7-45f7d7514a10.png)
![archive1](https://cloud.githubusercontent.com/assets/4154219/13327030/fa135f54-dbc6-11e5-9d21-9b988869201c.png)

Thanks again for your help

**Comment by ppoffice** [comment]
I think you are talking about post `banner`.

You can add this to your front-matter:

```yml
banner: /2016/02/15/Lo-estamos-haciendo-mal/01.png
```

**Comment by joydragon** [comment]
Sorry to insist, is not banner or thumbnail in the front-matter

it should look something like this:
![good_post1](https://cloud.githubusercontent.com/assets/4154219/13373202/7dd054b8-dd3f-11e5-8a6a-e4f77711ba51.png)

That was before the update, and now the markdown of the excerpt is not rendered.
I've tried with a fresh installation of hexo and your theme, and it's still not working
I've tried also adding the markdown-it renderer plugin (https://github.com/celsomiranda/hexo-renderer-markdown-it) but it's also not working

Can you help me with this? How can I debug this?

**Comment by ppoffice** [comment]
The formats in the excerpts are not rendered in order to create a clean summary of a article.

You can shorten your excerpts by putting `<!-- more -->` tag forward, or you can edit [scripts/excerpt.js](https://github.com/ppoffice/hexo-theme-icarus/blob/master/scripts/excerpt.js).

**Comment by joydragon** [comment]
Thank you very much!!
I edited the excerpt.js and that was it :+1:
