### ISSUE TITLE
hexo3.2报错了

### ISSUE THREAD

**Issue by imhentai** [ppoffice/hexo-theme-icarus#105]
![qq 20160228155715](https://cloud.githubusercontent.com/assets/8164505/13378116/358133da-de34-11e5-816d-681c18f5c874.png)

**Comment by ppoffice** [comment]
你用到了gallery这个layout，icarus没有这个layout

**Comment by imhentai** [comment]
不止gallery，很多ejs文件都报错了

**Comment by ppoffice** [comment]
刚刚升级到Hexo 3.2，并没有发现你说的问题。
请检查是否其他npm依赖都升级到了最新版本，配置文件有没有正确设置。

**Comment by imhentai** [comment]
重装好了...应该是升级方式不对
