### ISSUE TITLE
Waline评论系统无法关闭

### ISSUE THREAD

**Issue by BowenYoung** [ppoffice/hexo-theme-icarus#1074]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
Waline评论系统无法关闭

**系统与环境**
hexo: 6.1.0
icarus: 5.0.0-rc.1

**复现方式**
1. 新建自定义page
2. front matter添加comments: false
3. Waline系统依然存在，没有被关闭

**期望行为**
Waline系统被关闭并显示文字提示“此处评论已关，暂不支持评论。”

**截图**
![](https://cdn.jsdelivr.net/gh/BowenYoung/myPic@main/img/202205141305940.png)
![](https://cdn.jsdelivr.net/gh/BowenYoung/myPic@main/img/202205141306541.png)

**Comment by ppoffice** [comment]
使用`comment: false`试试？

**Comment by BowenYoung** [comment]
> 使用`comment: false`试试？

救命，我呆了。什么原理:fearful:我好像没记错啊。</br>总之谢谢555
