### ISSUE TITLE
归档页面的建议

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#108]
归档，主要是用来检索，一览过去所有发表的文章
icarus目前设置的归档，和首页显示区别不大，失去了归档的意义

能不能直接按照时间线排序，尽可能的多展示些文章
![qq 20160304154915](https://cloud.githubusercontent.com/assets/8164505/13521088/f3037d1a-e220-11e5-9f4d-c5f36fd48df2.jpg)

类似这种的

**Comment by ppoffice** [comment]
感谢建议，我会考虑在之后优化归档界面的显示

**Comment by ppoffice** [comment]
我更新了Archive等页面的样式，欢迎反馈。

**Comment by tiexo** [comment]
还有点小建议
目前标题和日期分别占一行，感觉有点浪费空间了
而且日期也是可点击属性，打开还是文章链接，显得略微有点重复
能不能将左侧的点改成日期？
![qq 20160318132603](https://cloud.githubusercontent.com/assets/8164505/13869253/9391b214-ed0d-11e5-87c0-2a5de0467d91.jpg)

或者你有其他更好的样式
总的建议就是，把日期的显示等级弱于标题，尤其是取消可点击的属性。。。

**Comment by ppoffice** [comment]
我更新了样式，弱化了日期一栏。
无法完全移除日期一栏，也没有想到调整位置的好方法，因为这一栏一般还是会显示文章的分类和标签信息。

**Comment by tiexo** [comment]
好的，因为我没用标签和分类所有觉得有点没用==
感谢你采纳建议，希望主题越来越好
