### ISSUE TITLE
icarus大bug

### ISSUE THREAD

**Issue by Xjystudio** [ppoffice/hexo-theme-icarus#1086]
```
$ hexo version
hexo-cli: 4.3.0
os: win32 10.0.22621
node: 16.15.1
v8: 9.4.146.24-node.21
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.4
openssl: 1.1.1o+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```
- `_config.yml`新建的文件，未经任何更改，在bug视频中有所体现
- `_config.icarus.yml`新建的文件，未经任何更改，在bug视频中有所体现
- 其他额外的配置文件（文章front-matter，`_config.post.yml`，或`_config.page.yml`）新建的文件，未经任何更改，在bug视频中有所体现
- 浏览器版本chorme 102，bug与此无关

- 说说bug吧，就是新建一个hexo根目录，用landscape主题可以，但按照教程将主题改为icarus就不好使了，无论用git clone或npm源码安装，bug视频[在此](https://user-images.githubusercontent.com/95113890/174439355-5a96d8f6-07ce-431c-b347-0419cefe0a58.mp4)，由于视频访问速度较慢，建议下载后观看

**Comment by Xjystudio** [comment]
@ppoffice 快点解决吧，我的blog废了……

**Comment by Xjystudio** [comment]
视频又打包更新了一个快速的[地址](https://xjystudio.coding.net/p/blog/d/flies/git/raw/master/icarus-big-bug.zip)原视频是在github中上传，速度很慢这个下载速度应该能快一些

**Comment by ppoffice** [comment]
Duplicated #1508

**Comment by Xjystudio** [comment]
谢谢，我是个中学生，那个模板可能不一定完全遵守，希望您能谅解

**Comment by Xjystudio** [comment]
请问下hexo如何退回，麻烦您了

**Comment by Xjystudio** [comment]
![image](https://user-images.githubusercontent.com/95113890/174478172-f79d6cc7-1778-40b1-828a-ac101aa68ac9.png)
成功解决，谢谢！
