### ISSUE TITLE
profile信息为中文时乱码

### ISSUE THREAD

**Issue by cpaladin** [ppoffice/hexo-theme-icarus#111]
你好，我在主题目录下面的_config.yml设置profile的信息是中文时，hexo generate 生成后的内容乱码，求助，谢谢！

**Comment by ppoffice** [comment]
请检查_config.yml的编码，是不是你用的编辑器保存之后编码变了。

**Comment by cpaladin** [comment]
确认是这样，可能编辑的时候被编辑器修改了。谢谢。
另外，问下，导航菜单的Home，Archives等在哪里可以修改成中文？将语言设成zh-CN后，其他地方是中文了，但是导航的没有改变，这个需要修改哪个文件，还是配置一下就可以了？

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/blob/master/_config.yml.example#L3

例如这里，把`Home`改成`主页`就可以了。

**Comment by cpaladin** [comment]
好的，非常感谢！之前试过，当时也是因为编码问题显示不正常，以为不是这样配置。其实是同一个问题
