### ISSUE TITLE
评论插件点击查看评论链接404错误（链接地址有误）

### ISSUE THREAD

**Issue by cpaladin** [ppoffice/hexo-theme-icarus#112]
如题。我使用的是多说评论。然后我到作者的主页http://blog.zhangruipeng.me/hexo-theme-icarus/ 上尝试，也发现了这种错误。

截图在这里，上传好几次截图不行，就放在微博上了：http://photo.weibo.com/1739919151/photos/detail/photo_id/3951801039772431

**Comment by cpaladin** [comment]
还是有问题？我已更新了主题，最后生成的链接还是多了一个路径（_config.yml 的root），导致404错误。

**Comment by ppoffice** [comment]
https://github.com/hexojs/hexo/issues/1775
https://github.com/hexojs/hexo/issues/1812

这个貌似是Hexo的Bug，你可以升级到Hexo 3.2Beta试试。

**Comment by cpaladin** [comment]
好的。多谢。
