### ISSUE TITLE
Google analytics should be disabled during development

### ISSUE THREAD

**Issue by ppwwyyxx** [ppoffice/hexo-theme-icarus#1129]
**Describe the bug**
Google analytics shows me statistics about pages I have not published at all. The only explanation is that even when I'm developing locally (I use `hexo server` or `hexo server --draft`), google analytics is still recording page view data.

I think the correct behavior (or at least, a better default) is to not send analytics data during development.

**System and Environment**
hexo 6.3.0  latest icarus.

I have the following enabled
```
plugins:
    google_analytics:
        tracking_id: UA-XXX
```
- Browser and version: chrome 106

**Comment by ppoffice** [comment]
@ppwwyyxx User should disable plugins in the configuration files.
