### ISSUE TITLE
更新icarus之后发生错误

### ISSUE THREAD

**Issue by bb-coder** [ppoffice/hexo-theme-icarus#115]
更新了最新的版本后，报若干错误
![e9cca303-71c0-43d8-aae6-a2286824b193](https://cloud.githubusercontent.com/assets/7802862/13738522/8826884c-ea00-11e5-9e59-79f9f8d41134.jpeg)

**Comment by ppoffice** [comment]
配置文件的结构更新了：

https://github.com/ppoffice/hexo-theme-icarus/wiki/Configuration

**Comment by Zeroxus** [comment]
在给hexo配置主题时，发生如下错误
Unhandled rejection TypeError: /home/zeroxus/Documents/blog/themes/icarus/layout/post.ejs:1
 >> 1| <%- partial('common/article', { post: page }) %>

**Comment by bb-coder** [comment]
感谢您的解答～另外还有以下2个问题要问：
1.在home页预览每篇文章的时候markdown排版失效了：
更新前：
![markdown3](https://cloud.githubusercontent.com/assets/7802862/13834957/35454f66-ec2e-11e5-9aed-5bceeb161a55.png)
更新后：
![markdown4](https://cloud.githubusercontent.com/assets/7802862/13834958/3b123d46-ec2e-11e5-831b-8b2a34d2a42c.png)

2. markdown的代码块显示异常：
更新前：
![markdown1](https://cloud.githubusercontent.com/assets/7802862/13834962/503d5250-ec2e-11e5-8692-316eab57ae76.png)
更新后：
![markdown2](https://cloud.githubusercontent.com/assets/7802862/13834963/54bdf6d6-ec2e-11e5-9aa9-cdd7a8fb75ff.png)


感谢您的耐心，主题非常棒，超级喜欢。

**Comment by ppoffice** [comment]
@bb-coder 感谢反馈

**Comment by ppoffice** [comment]
我同时更新了下Archive等页面的样式，欢迎反馈。

**Comment by tiexo** [comment]
我还以为是故意的...原来是bug

**Comment by bb-coder** [comment]
<img width="614" alt="screen shot 2016-03-26 at 2 22 08 pm" src="https://cloud.githubusercontent.com/assets/7802862/14058536/2f39692c-f35e-11e5-86cc-28bb1fd07f9b.png">
感谢楼主的更新，现在文章预览的markdown语法没有问题了，只是代码块的样式依旧很奇怪。
