### ISSUE TITLE
hexo s --debug 模式无法自动刷新

### ISSUE THREAD

**Issue by Xu-Hardy** [ppoffice/hexo-theme-icarus#1173]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
简洁清晰地描述你遇到的Bug是什么。

hexo s --debug  修改_config.icarus.yml无法自动刷新

**系统与环境**
列出你的Hexo和Icarus的版本和配置。

win11, variant 5.1.0, 

- Hexo，操作系统，和Node.js的版本（使用`hexo version`命令来查看）
- 站点配置文件`_config.yml`
- 主题配置文件`_config.icarus.yml`或`themes/icarus/_config.yml`
- 其他额外的配置文件（文章front-matter，`_config.post.yml`，或`_config.page.yml`）
- 浏览器版本（如Firefox 70.0，Chrome Android 80.0）

PS C:\Users\Canyon\Desktop\hexo\blog> hexo version
INFO  Validating config
Inferno is in development mode.
INFO  =======================================
 ██╗ ██████╗ █████╗ ██████╗ ██╗   ██╗███████╗
 ██║██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝
 ██║██║     ███████║██████╔╝██║   ██║███████╗
 ██║██║     ██╔══██║██╔══██╗██║   ██║╚════██║
 ██║╚██████╗██║  ██║██║  ██║╚██████╔╝███████║
 ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
=============================================
INFO  === Checking package dependencies ===
INFO  === Checking theme configurations ===
INFO  === Registering Hexo extensions ===
hexo: 6.3.0
hexo-cli: 4.3.0
os: win32 10.0.22621 
node: 18.13.0
v8: 10.2.154.23-node.21
uv: 1.44.2
zlib: 1.2.13
brotli: 1.0.9
ares: 1.18.1
modules: 108
nghttp2: 1.51.0
napi: 8
llhttp: 6.0.10
uvwasi: 0.0.13
openssl: 3.0.7+quic
cldr: 42.0
icu: 72.1
tz: 2022f
unicode: 15.0
ngtcp2: 0.8.1
nghttp3: 0.7.0

**复现方式**
列出复现这个Bug的步骤，如：

1. 访问‘...’
2. 点击’...‘
3. 下拉到‘...’
4. 出现‘...’的错误

**期望行为**
简洁清晰地描述没有这个情况下你期望得到的结果。
如何可以自动刷新
**截图**
如果可以的话，请附上几张截图来帮助说明你遇到的问题。

**额外上下文**
附上与问题有关的其他上下文信息。

**Comment by ppoffice** [comment]
因为Icarus的配置系统较为复杂，此为目前预期的行为。
