### ISSUE TITLE
虽然我知道我这个问题可能不是主题造成的，但还是想问下有遇到过该主题，使用不蒜子统计访客量为什么1次访问被重复计数了呢

### ISSUE THREAD

**Issue by happycodinggirl** [ppoffice/hexo-theme-icarus#118]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully;
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

**Comment by ppoffice** [comment]
这个插件是你自己添加的么？能贴一下代码么？

**Comment by tiexo** [comment]
@ppoffice http://service.ibruce.info/
这个吧

**Comment by ppoffice** [comment]
@tiexo 我感觉 @happycodinggirl  可能把这两行贴的位置不太对……

**Comment by happycodinggirl** [comment]
对的，就是用的这个。我是在D:\Hexo\themes\icarus\layout\common的footer,ejs里面添加的。footer.ejs完整代码如下：
<footer id="footer">
<script async src="https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js">
</script>
    <div class="outer">
        <div id="footer-info" class="inner">
            &copy; <%= date(new Date(), 'YYYY') %> <%= config.author || config.title %><br>
            Powered by <a href="http://hexo.io/" target="_blank">Hexo</a>. Theme by <a href="http://github.com/ppoffice">PPOffice</a>
			</br>本站总访问量<span id="busuanzi_value_site_pv"></span>次，你是来本站的第<span id="busuanzi_value_site_uv"></span>位小伙伴，本文总阅读量<span id="busuanzi_value_page_pv"></span>次
        </div>
	
 
    </div>
	
</footer>

**Comment by happycodinggirl** [comment]
其他地方没加过，不知道为啥，一次被统计为2次

**Comment by ppoffice** [comment]
@happycodinggirl ` <script async src="//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"></script>`这句呢？

**Comment by happycodinggirl** [comment]
这句话就加过1次，就是上述所在目录

**Comment by happycodinggirl** [comment]
奥，好像没有对吧，可能copy错了，在公司，回去再看看

**Comment by happycodinggirl** [comment]
copy错了，加了也会访客被重复统计，完整代码如下：

<footer id="footer">
<script async src="https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js">
</script>
    <div class="outer">
        <div id="footer-info" class="inner">
            &copy; <%= date(new Date(), 'YYYY') %> <%= config.author || config.title %><br>
            Powered by <a href="http://hexo.io/" target="_blank">Hexo</a>. Theme by <a href="http://github.com/ppoffice">PPOffice</a>
			</br>本站总访问量<span id="busuanzi_value_site_pv"></span>次，你是来本站的第<span id="busuanzi_value_site_uv"></span>位小伙伴，本文总阅读量<span id="busuanzi_value_page_pv"></span>次
        </div>
	
 
    </div>
	
</footer>

**Comment by happycodinggirl** [comment]
好奇怪啊，我copy的代码明明有那段script的代码，点击comment，上去的就看不到那块script块。
script内容是：
<script async src="https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js">
</script>
在<footer>和第一个<div>标签之间

**Comment by ppoffice** [comment]
@happycodinggirl  请再检查下layout.ejs和common/scripts.ejs里面有没有添加，我感觉你添加重复了。

**Comment by happycodinggirl** [comment]
去检查了，其他文件也没有添加，我的个人域名下面有2个dns，不知是否跟这个有关，小白，勿笑

**Comment by ppoffice** [comment]
@happycodinggirl 
```html
</br>本站总访问量<span id="busuanzi_value_site_pv"></span>次，你是来本站的第<span id="busuanzi_value_site_uv"></span>位小伙伴，本文总阅读量<span id="busuanzi_value_page_pv"></span>次
```
这段话里边`</br>`打反了，你改成`<br />`试试。HTML解析错误也会导致标签出现奇怪的问题。

**Comment by happycodinggirl** [comment]
还是不可以，好忧桑

**Comment by ppoffice** [comment]
@happycodinggirl 你试试用`hexo clean`命令清除一下缓存。如果还不行，就升级下Hexo，或者重新clone这个主题。

我在本地测试，加上你上面提供的代码并没有出现这种问题。
