### ISSUE TITLE
引导页面多个 h1 标签导致的 SEO 问题

### ISSUE THREAD

**Issue by Scholar-Jr** [ppoffice/hexo-theme-icarus#1185]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
在搜索引擎中，h1 标签起到了至关重要的作用。采用作者的渲染方式会导致引导页面出现多个 h1，从而导致主页 SEO 权重分散。
```javascript
{/* Title */}
{page.title !== '' ? <h1 class="title is-3 is-size-4-mobile">
    {index ? <a class="link-muted" href={url_for(page.link || page.path)}>{page.title}</a> : page.title}
</h1> : null}
```

**期望行为**
- 只允许每个页面出现单个 h1 标签
- 在此处渲染之前增加判断规则，如果是引导页，则使用其他标签输出（可参考 NexT 主题的解决方案）

**Comment by Scholar-Jr** [comment]
非常抱歉因为**手贱**按到 Enter 导致了如此混乱的 Issue 提交。

**Comment by ppoffice** [comment]
已在5.2.1中修复。
