### ISSUE TITLE
中文下归档挂件的月份显示格式

### ISSUE THREAD

**Issue by chuanjin-su** [ppoffice/hexo-theme-icarus#1190]
> 确保你在提交功能建议之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的建议是否已经被他人提出过。

**你的功能建议与某个使用问题相关么？请详述。**

归档挂件的月份显示格式是不太符合中文的习惯的。比如正常应该是“2023年二月” / “2023年2月”，而不是显示“二月 2023”😂

![Snipaste_2023-02-21_18-06-03](https://user-images.githubusercontent.com/49405530/220314582-44ec9224-3b04-4dee-8f3c-b56a94225100.png)

**描述你想要的解决方案**

建议能够把中文的对应显示改为“2023年二月” / “2023年2月” 这样的格式。

**描述你考虑过的替代办法**

暂时我个人是只好将网站设置成英文，作为重度强迫症看着“Feburary 2023”甚至还会舒服一点（x

**额外上下文**

无论如何 感谢开发者的付出~

**Comment by ppoffice** [comment]
@chuanjin-su 请将`hexo-component-inferno`升级到最新版本，然后按照下面的方式修改你的Icarus配置文件：

```diff
widgets:
    ...
    -
        position: left
        type: archives
+       format: YYYY年MM月
    ...
```

**Comment by chuanjin-su** [comment]
安装了`hexo-component-inferno`，调整成功。

再次感谢ppoffice的付出~
