### ISSUE TITLE
Disable comments in specific pages

### ISSUE THREAD

**Issue by bemeurer** [ppoffice/hexo-theme-icarus#120]
I've recently created a 404 page (by adding a `404.md` file to the source folder) but I found an issue; if I go to a page that doesn't exist (i.e. http://meurer.xyz/abcd) people can still comment on it, which doesn't make that much sense considering it's a 404 page.

How may one disable commenting function in some specific pages (e.g. about, 404, ...)

**Comment by ppoffice** [comment]
Did you add `comment: false` to the page's front-matter?
