### ISSUE TITLE
Support for tag label

### ISSUE THREAD

**Issue by noraj** [ppoffice/hexo-theme-icarus#122]
Hi,

I think you're may be interesting in a feedback.

So, for my personal [blog](zerox.ml) I made a dark version of your theme and add some variables to `_variables.styl` to made it easy to change. I also generate a minimal boostrap.css and include it in `style.styl` in order to support [hexo-tag-bootstrap
](https://github.com/wzpan/hexo-tag-bootstrap).

It may be interesting, one day, you add tag label support to you themes in order to do nice things like [that](http://wzpan.github.io/hexo-theme-freemind/2014/03/16/tag-plugins/).

Thanks for your great theme, there is very few hexo theme that have categories, tags, archives, recent posts and thumbnails support in one theme.

See u

**Comment by ppoffice** [comment]
Thanks. I will look into this soon.

**Comment by noraj** [comment]
@ppoffice A close issue without a comment is always frustrating. I wish this is because you don't want to spend more time on this theme?

**Comment by noraj** [comment]
Bulma CSS is so great, I'm glad to hear that Icarus v2 is using it. Thx for the feedback.
