### ISSUE TITLE
#115问题的后续问题。

### ISSUE THREAD

**Issue by bb-coder** [ppoffice/hexo-theme-icarus#123]
<img width="614" alt="screen shot 2016-03-26 at 2 22 08 pm" src="https://cloud.githubusercontent.com/assets/7802862/14058536/2f39692c-f35e-11e5-86cc-28bb1fd07f9b.png">
感谢楼主的更新，现在文章预览的markdown语法没有问题了，只是代码块的样式依旧很奇怪,并且如果存在1行代码很长的情况现在不能横向滚动了。

**Comment by ppoffice** [comment]
我在本地测试没有问题，方便贴下这篇文章的Markdown么？
另外你的Hexo版本是多少？
或者你再更新下主题看看？

**Comment by bb-coder** [comment]
hexo: 3.1.1
os: Darwin 15.4.0 darwin x64
http_parser: 2.6.0
node: 5.3.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e

主题已经更新到最新。

md文件在这里：<https://github.com/bb-coder/MDSets/blob/master/memoryGhostdrawRect.md>

**Comment by ppoffice** [comment]
你改成这样试试：
![image](https://cloud.githubusercontent.com/assets/8849362/14065337/28e77528-f458-11e5-80ad-6079795a3218.png)

**Comment by bb-coder** [comment]
Ok,it works,thanks.

**Comment by ppoffice** [comment]
#128

**Comment by caoler** [comment]
问题解决了吗？我的也是白色代码背景，换不了
