### ISSUE TITLE
Suggestion: Add local search

### ISSUE THREAD

**Issue by online** [ppoffice/hexo-theme-icarus#125]
Hello!

Please, add local search into your cool theme. Read more here:

- http://hahack.com/codes/local-search-engine-for-hexo/
- https://github.com/paichyperiondev/hexo-generator-search

**Comment by tiexo** [comment]
支持...swiftype不是实时抓取的，总的等上几天...

**Comment by online** [comment]
@tiexo, therefore, I propose to add a local search (not swiftype).

**Comment by ppoffice** [comment]
@online @tiexo 
I added a new local search engine named Insight, which uses `hexo-generator-json-content` to create search material.
You can try it out from the `dev` branch, and also please keep me informed of what can be improved before I formally announce the release:smile:

**Comment by tiexo** [comment]
@ppoffice 
本地`hexo s`测试，点击搜索框无反应
看你的online里面会弹窗啊，而且点击搜索按钮后，网址跳转为`http://localhost:4000/?`
页面还是首页

补充：刚刚`hexo d`上传后，和本地测试结果一样。

**Comment by ppoffice** [comment]
@tiexo 你是不是没安装插件或者没改_config.yml?

**Comment by tiexo** [comment]
@ppoffice 
郁闷了，的确是没装插件
可是我安装好以后，在`public`文件夹里也有了一个`content.json`文件
可是点击搜索还是没反应。

**Comment by ppoffice** [comment]
@tiexo

清空下缓存试试？
另外记得切换到dev分支

**Comment by tiexo** [comment]
@ppoffice 
感觉都没错啊，怀疑还是插件的问题。
你帮忙看看步骤错了没
先`npm i -S hexo-generator-json-content`安装
我在`package.json`里面可以看见这个插件，另外`public`里面也有`content.json`
这样应该能说明插件安装成功了吧？
在站点`_config.yml`里面需要定义吗？
```
Plugins:
- hexo-generator-json-content
```
事实上我加不加这句话，结果都是一样。。。
另外主题我是直接dev分支下载，然后放到我的博客目录测试的，就修改了`_config.yml`文件，其他的都和你一样啊
我是直接覆盖，然后修改了search选项，文件其他地方应该没有变动吧？

另外还有一个额外话题
top功能没了？也不知道啥时候突然没了，可是刚刚在js文件里面又看见了代码呢
我现在连这个图标都没了。

**Comment by ppoffice** [comment]
你发下线上地址wo kan xia

**Comment by tiexo** [comment]
@ppoffice 
http://www.tiexo.cn/
原装主题环境，啥也没改...你看看

**Comment by ppoffice** [comment]
@tiexo 是我的问题，我更新了代码

**Comment by tiexo** [comment]
@ppoffice  哈哈，弄好了。
是不是主题设置为两栏，就没有top按钮了？

另外现在既然搜索框不能输入，不如直接改为按钮好了
点击弹窗搜索

**Comment by ppoffice** [comment]
两栏是没有top按钮的

**Comment by online** [comment]
@ppoffice, I have not tested your Insight search on my blog, but in your [demo example](http://blog.zhangruipeng.me/hexo-theme-icarus/#ins-search) I noticed that lacks the function "hide a search block by pressing the `Esc` key". Add it, please.

**Comment by ppoffice** [comment]
@online Good idea:smile:

**Comment by ppoffice** [comment]
@online 
Now you can use <kbd>Esc</kbd>, <kbd>↑</kbd>, <kbd>↓</kbd> and <kbd>Enter</kbd>.

**Comment by online** [comment]
@ppoffice, thank you for such a cool local search, he is wonderful! :+1: 

Please, merge my pull request #126.
