### ISSUE TITLE
Numbers show different in multiline codeblock snippet

### ISSUE THREAD

**Issue by D4mianWayne** [ppoffice/hexo-theme-icarus#1258]
I have been trying to get this theme work with my markdown files and it seems that if the codeblock contains any hex numbers or decimal it just treats it like a one-line code which makes the overall codeblock look uneven. Is there any way to fix this?

**To Reproduce**
Steps to reproduce the behavior, such as:

1. Create a codeblock using backtick and specify language 
2. Regenerate the files and check locally:

**Expected behavior**
I think it should just treat the integer/hex values as it is in the codeblock.

**Screenshots**
![2023-12-30 20_52_19-Clipboard](https://github.com/ppoffice/hexo-theme-icarus/assets/43758020/a39ec695-6201-47a3-bd1a-ce83fb72854b)

**Additional context**
At first, the problem felt like it was related to the syntax/language we want the highlight to be but it doesn't work that way.

**Comment by ppoffice** [comment]
@D4mianWayne I cannot reproduce this with the latest Icarus theme. Can you check whether you are using other code highlight plugins/extensions that may interfere with the code highlighting?

**Comment by D4mianWayne** [comment]
Actually it was happening due to collision of some packages, I did a clean install and it was working as expected. Thank you!
