### ISSUE TITLE
使用自定义字体时首页文章发布时间栏出现滑动条

### ISSUE THREAD

**Issue by zh0ngtian** [ppoffice/hexo-theme-icarus#1263]
> Make sure you go through the [Hexo docs](https://hexo.io), [Icarus user manual](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus-User-Guide/), and [GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues) to see if the bug you are reporting has been already addressed by others.

**Describe the bug**

我更换了自定义的字体，首页文章的发布时间这里就出现了一个滑动条，换回原来的字体就没有了。感觉可能是字号的问题？应该怎么调整下这里的高度让滑动条消失呢？

![](http://img.zh0ngtian.tech/2024_01_10_X8DlDq.png)

**System and Environment**
```json
{
  "name": "hexo-theme-icarus",
  "version": "5.2.1",
  "author": "ppoffice <ppoffice@users.noreply.github.com>",
  "license": "MIT",
  "description": "A simple, delicate, and modern theme for Hexo",
  "keywords": [
    "hexo",
    "theme",
    "icarus"
  ],
  "homepage": "https://github.com/ppoffice/hexo-theme-icarus",
  "repository": "https://github.com/ppoffice/hexo-theme-icarus.git",
  "bugs": {
    "url": "https://github.com/ppoffice/hexo-theme-icarus/issues"
  },
  "engines": {
    "node": ">=12.4.0"
  },
  "scripts": {
    "lint": "eslint --ext .js --ext .jsx --ext .json ."
  },
  "devDependencies": {
    "eslint": "^8.6.0",
    "eslint-config-hexo": "^5.0.0",
    "eslint-plugin-json": "^3.0.0",
    "eslint-plugin-react": "^7.17.0"
  },
  "dependencies": {
    "bulma-stylus": "0.8.0",
    "deepmerge": "^4.2.2",
    "hexo": "^6.0.0",
    "hexo-component-inferno": "^2.0.2",
    "hexo-log": "^3.0.0",
    "hexo-pagination": "^2.0.0",
    "hexo-renderer-inferno": "^0.1.3",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-util": "^2.4.0",
    "inferno": "^7.3.3",
    "inferno-create-element": "^7.3.3",
    "moment": "^2.22.2",
    "semver": ">=5.0.0"
  }
}
```

**To Reproduce**
```jsx
default: fontcdn('JetBrains+Mono:wght@400;600&family=Monda:wght@400;700&family=Noto+Sans+SC:wght@400;700', 'css2'),
```

```styl
$family-sans-serif ?= 'Monda', 'Noto Sans SC', sans-serif
$family-code ?= 'JetBrains Mono', monospace
```

或者直接查看我的首页 http://zh0ngtian.tech/

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ppoffice** [comment]
你的首页 http://zh0ngtian.tech/ 在我这里无法复现这个问题。你用的浏览器是什么？有没有其他复现的页面？

**Comment by zh0ngtian** [comment]
> 你的首页 http://zh0ngtian.tech/ 在我这里无法复现这个问题。你用的浏览器是什么？有没有其他复现的页面？
我用的 edge 浏览器，刚才用手机试了下，似乎手机 edge 浏览器也有这个问题，用别的浏览器好像就没有。暂时没有其他可以复现的页面。

**Comment by ppoffice** [comment]
目前看来与Icarus本身无关。修复方法的话建议在[CSS](https://github.com/ppoffice/hexo-theme-icarus/blob/1b65d5844b5822bca42f56c1b7373b50bcd4fedf/include/style/article.styl#L46)中加入`min-height: 1em`测试。

**Comment by zh0ngtian** [comment]
> 目前看来与Icarus本身无关。修复方法的话建议在[CSS](https://github.com/ppoffice/hexo-theme-icarus/blob/1b65d5844b5822bca42f56c1b7373b50bcd4fedf/include/style/article.styl#L46)中加入`min-height: 1em`测试。

min-height 设成 2em 就可以了，感谢🙏
