### ISSUE TITLE
文章头部是一张照片的效果是怎么弄的？

### ISSUE THREAD

**Issue by jaune162** [ppoffice/hexo-theme-icarus#1272]
![image](https://github.com/ppoffice/hexo-theme-icarus/assets/10142624/8a39242a-0522-4fdc-a799-9094c13b4b3e)

如图，https://ppoffice.github.io/hexo-theme-icarus/ 中文章头部显示了一张图片，然后才是文章内容，同时“RECENTS”中现实的文章标题前面也有这张图片。请问是怎么实现的

**Comment by ppoffice** [comment]
https://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/#%E5%B0%81%E9%9D%A2-%E7%BC%A9%E7%95%A5%E5%9B%BE

**Comment by jaune162** [comment]
谢谢
