### ISSUE TITLE
代码高亮的问题

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#128]
发现对代码高亮的支持不是很友好啊。
看了下官方的demo网址，也基本上没有高亮...

今天发了一篇文章，老大一段代码，一个字符都没亮。。。
是什么原因啊

在本地的md编辑器里面，是有高亮的啊

**Comment by ppoffice** [comment]
#115

**Comment by ppoffice** [comment]
#123

**Comment by tiexo** [comment]
我和他的问题不一样，我是有灰色代码块

![20160415100636](https://cloud.githubusercontent.com/assets/8164505/14549367/c9e1a6cc-02f1-11e6-8380-14ea25dbef69.jpg)
但是没有颜色啊，都是灰底白字

**Comment by ppoffice** [comment]
@tiexo 这个不是主题的问题吧？因为主题使用的是Hexo默认提供的Highlight.js处理后的结果，只要Highlight.js能够正确高亮，主题这边就不会有问题。

你的这段代码是压缩混淆之后的，Highlight.js可能没有正确识别。

**Comment by tiexo** [comment]
好的吧...只能忍了

**Comment by ppoffice** [comment]
@tiexo 
你试试在代码块头部加上`js`：
![image](https://cloud.githubusercontent.com/assets/8849362/14549592/a352f900-02f3-11e6-835d-a9eb190e74e4.png)

另外你也可以选择手动修改Highlight.js到最新版本。

**Comment by tiexo** [comment]
这个试过了，不行。还是没颜色
先这样吧...慢慢研究

**Comment by happycodinggirl** [comment]
为啥我的代码hightlight 不起作用，对主题特别喜欢，就是对代码支持不好啊

**Comment by ppoffice** [comment]
@happycodinggirl 
请使用三个飘号包裹代码块。

\`\`\`java
public void main(){}
\`\`\`

**Comment by happycodinggirl** [comment]
感谢作者，it works ！太喜欢这个主题了，堪称完美，再次感谢！

**Comment by willin** [comment]
Same:  https://sh.gg/posts/2017/vs-code-webpack-intelligence/

source: 

\```js 
```js
resolve: {
    modules: [
      'node_modules',
      path.resolve(__dirname, '../src')
    ],
    extensions: ['.js', '.vue', '.json', '.css'],
    alias: {
      vue$: 'vue/dist/vue.esm.js',
      public: path.resolve(__dirname, '../public'),
      component: path.resolve(__dirname, '../src/component'),
      config: path.resolve(__dirname, '../src/config'),
      lib: path.resolve(__dirname, '../src/lib'),
      i18n: path.resolve(__dirname, '../src/i18n'),
      store: path.resolve(__dirname, '../src/store')
    }
  }
```
\```
