### ISSUE TITLE
The theme is not adaptive as description

### ISSUE THREAD

**Issue by chnmessi** [ppoffice/hexo-theme-icarus#13]
I just install hero and try out the theme of icarus, but the post is not very adaptive and the right sidebar is not work.
The image link:
https://docs.google.com/document/d/1Dgw95e0OqfOWO0BEU5kRviStzAgwlTJBdwfMld0etxM/edit?usp=sharing

I set the config as the description of the Readme about the icarus on github.

**Comment by ppoffice** [comment]
Would you please post your _config.yml here?

**Comment by chnmessi** [comment]
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Freeniu
subtitle:
description:
author: Freeniu
author_title: Null
avatar: css/images/freeniu.png
location: 'China'
follow: https://github.com/chnmessi
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://freeniu.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: icarus

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:chnmessi/chnmessi.github.com.git
  branch: master

# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  
# Content
excerpt_link: Read More
fancybox: true
  
# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  github: https://github.com/chnmessi
  twitter: https://twitter.com/freeniu
  facebook: https://www.facebook.com/freeniub
  #dribbble: '#'
  rss: /atom.xml
  
# Links
links:
  Hexo: http://hexo.io
	
# Disqus
disqus_shortname: freeniu

**Comment by ppoffice** [comment]
I think you may miss the _config.yml in icarus theme folder. You can rename _config.yml.example to _config.yml and take another look.

**Comment by chnmessi** [comment]
oh,Thank you.It has solved and the reason is what you  said.
