### ISSUE TITLE
Utterances评论卡片未出现在文章卡片下，却出现在其他页面

### ISSUE THREAD

**Issue by PaRr0tBoY** [ppoffice/hexo-theme-icarus#1300]
**Bug描述**
简洁清晰地描述你遇到的Bug是什么。

Utterance评论系统配置后，只在我主动创建的页面（hexo new page xxx）下出现评论卡片，但是不出现在文章下，

front-matter已经配置了comment: true,在出现评论卡片的页面使用comment: false也可以正确关闭评论，证明comment是有效的选项，

我以为是issue_term的问题，但是把utterance给的属性都试过了也不行，我猜测是utterance识别不了自定义的permalink？

另外icarus文档给的代码注释说termname和termnumber都是必选项，选填其一，那么究竟是必须都填还是选一个？termname只能填pathname吗？

**系统与环境**
列出你的Hexo和Icarus的版本和配置。
hexo: 7.2.0
Icarus 5.1.0
node v20.14.0
windows11 23H2家庭版
[配置文件对应部分代码](https://github.com/PaRr0tBoY/parr0tboy.github.io/blob/d90d19d09ca4700b97ae04b6778f2b3f29ae1717/_config.icarus.yml#L168-L173)，主题站点配置文件utterances设置部分相同

**复现**
点进文章内部没有单独的评论卡片，但是新建页面有，用嵌入前端代码的方式部署utterance找不到地方更改样式，看utterance官方仓库下的issue好像没办法自定义

**期望行为**
独立的评论卡片出现在每一篇comment设置为true的post下

**Comment by ppoffice** [comment]
@PaRr0tBoY 可以提供出现问题的页面URL和markdown源码么？
