### ISSUE TITLE
How can i limit words of article in the home page?

### ISSUE THREAD

**Issue by nick-ChenZe** [ppoffice/hexo-theme-icarus#131]
Sorry to interrupt you.But i'm still confused to this.I see in you preview page,the post in the index is limited,and a button like read more is bellow.Is it necessary to add words `<!--more-->` in the post by myself,or any other way existed.I didn't see any configuration in the .yml. Thank you a lot.This is my site : chenze2168.com.

**Comment by ppoffice** [comment]
@nick-ChenZe In this case, you should add `<!--more-->` to each post.

**Comment by nick-ChenZe** [comment]
@ppoffice Thank you! That works for me.
