### ISSUE TITLE
代码主题不对了

### ISSUE THREAD

**Issue by AndrWang** [ppoffice/hexo-theme-icarus#132]
![image](https://cloud.githubusercontent.com/assets/10292984/14627249/30357742-0625-11e6-979f-37043fc9f9be.png)
为啥背景是白色 的，highlight: androidstudio用的这个高亮

**Comment by ppoffice** [comment]
你是不是没有设置代码的语言呀？
#128 
#123

**Comment by AndrWang** [comment]
@ppoffice 
![image](https://cloud.githubusercontent.com/assets/10292984/14630104/eedcd628-063d-11e6-9dfa-3dd5fbf92962.png)

**Comment by ppoffice** [comment]
@AndrWang java后面的冒号去掉试下？

**Comment by AndrWang** [comment]
@ppoffice 试过，代码高亮还好，就是代码块的背景有点纠结

**Comment by ppoffice** [comment]
@AndrWang 什么问题呢？

**Comment by AndrWang** [comment]
@ppoffice 代码块背景颜色是白色的啊，不应该是黑色的吗

**Comment by ppoffice** [comment]
@AndrWang 
你用的是Tomorrow主题么？
Tomorrow主题的背景本来就是白色的，你可能想要使用的是tomorrow-night。

**Comment by AndrWang** [comment]
@ppoffice 我用的是androidstudio主题，我试试night吧

**Comment by ppoffice** [comment]
#158

**Comment by caoler** [comment]
问题解决了吗？？我的代码块背景也是白色的，换代码主题也不行

**Comment by caoler** [comment]
@ppofice   我出现了跟题主一样的问题，更换代码主题，night  light，```后添加java 各种方法都试过了，无法解决

**Comment by caoler** [comment]
@ppoffice 我出现了跟题主一样的问题，更换代码主题，night light，```后添加java 各种方法都试过了，无法解决
