### ISSUE TITLE
The search box appearance is not good on IE.

### ISSUE THREAD

**Issue by thomaskim-lab** [ppoffice/hexo-theme-icarus#133]
The search box appearance is not good on IE (only IE! :-(   my IE version is 11).
![search](https://cloud.githubusercontent.com/assets/18393506/14633352/3350b7ce-0658-11e6-86c4-595b15b85ed0.PNG)

Everything else is very awesome! How would this be fixed?

**Comment by ppoffice** [comment]
IE doesn't handle input height correctly, I will fix this soon.
Thank you for reporting this:smile:

**Comment by thomaskim-lab** [comment]
Thank you for the fast feedback!
The search box looks good now on IE 😄
