### ISSUE TITLE
经常会莫名其妙的这样，不知为何

### ISSUE THREAD

**Issue by AndrWang** [ppoffice/hexo-theme-icarus#134]
![image](https://cloud.githubusercontent.com/assets/10292984/14661146/ee91207a-06dd-11e6-8a1f-bbc59fd7231a.png)
就是里面有一些单词都变得不认识了，😄，还有上一篇下一篇这种

**Comment by ppoffice** [comment]
@AndrWang 
设置下语言就好了
https://github.com/ppoffice/hexo-theme-icarus/wiki/FAQ#how-do-i-change-the-sites-language

**Comment by AndrWang** [comment]
@ppoffice 好的我这个还是之前的配置English。。。。😄

**Comment by buweilv** [comment]
参考https://github.com/ppoffice/hexo-theme-icarus/wiki/FAQ#how-do-i-change-the-sites-language，并且删除之前部署的内容，重新部署就解决，thanks
