### ISSUE TITLE
你好 我的网站博客disqus评论下面 不会显示网站其它博客的评论 只显示当前博客的评论 是需要配置些什么么 谢谢咯 

### ISSUE THREAD

**Issue by giraffe0813** [ppoffice/hexo-theme-icarus#135]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully;
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

**Comment by ppoffice** [comment]
@giraffe0813 什么叫其他博客的评论？
你是指其他文章么？

**Comment by giraffe0813** [comment]
对 就是其它文章 ，下面这种的 我的没有显示红框里面的内容~~谢谢了
![image](https://cloud.githubusercontent.com/assets/14157994/14758002/722c2bd2-092c-11e6-935b-872df4409b70.png)

**Comment by ppoffice** [comment]
这个你需要去看看你的Disqus设置

**Comment by giraffe0813** [comment]
恩恩 我还想再问一下 disqus评论的数目是不能显示的么 因为我看你的示例博客的评论数也是没有正常显示的  谢谢
![image](https://cloud.githubusercontent.com/assets/14157994/14758610/9b9dba88-0938-11e6-95a5-861908a2a260.png)

**Comment by ppoffice** [comment]
你看下首页有没有显示？我好想没加这个功能

**Comment by giraffe0813** [comment]
http://yemengying.com/  首页也是不能显示的 我看counter.ejs里有关于disqus的内容啊 我之前用多说做评论时 也是可以正常显示评论数目的 谢谢啦~·

**Comment by ppoffice** [comment]
@giraffe0813 
请更新下代码，然后10分钟后刷新下网页看下（Disqus有10分钟缓存）。

**Comment by giraffe0813** [comment]
可以了耶 谢谢咯~~
