### ISSUE TITLE
article-more-link 怎么显示啊 

### ISSUE THREAD

**Issue by oksite** [ppoffice/hexo-theme-icarus#139]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully;
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

**Comment by ppoffice** [comment]
Duplicate #60

**Comment by oksite** [comment]
well ,I hope to show that reading more, Icarus do not know how to show    Makdown this is also can not look good   My [blog site](http://oksite.github.io/)

**Comment by ppoffice** [comment]
Do you mean Icarus do not format Markdown in the excerpt?

**Comment by oksite** [comment]
I don't know how to do it now. ha-ha @ppoffice

**Comment by oksite** [comment]
The problem is solved now. Thank you.
