### ISSUE TITLE
I an error when using the theme

### ISSUE THREAD

**Issue by HuJian21** [ppoffice/hexo-theme-icarus#140]
![image](https://cloud.githubusercontent.com/assets/11832969/15035195/c96a7212-12b1-11e6-8bc0-45302646f4a3.png)

Like the picture above,i dont know how to make it run success...

**Comment by oksite** [comment]
@HuJian21  Theme download error
Look at this web site ：https://github.com/ppoffice/hexo-theme-icarus/wiki/Installation

**Comment by HuJian21** [comment]
@oksite thanks!
