### ISSUE TITLE
楼主 你这个主题有目录功能吗？

### ISSUE THREAD

**Issue by ganjmeng** [ppoffice/hexo-theme-icarus#142]
Please make sure these boxes are checked before submitting your issue. Thank you!
楼主 你这个主题有目录功能吗？
- [x] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully;
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

**Comment by ppoffice** [comment]
@ganjmeng 
有，使用Hexo默认的方式加上Toc就行了

**Comment by ganjmeng** [comment]
OK了，还有个疑问哦，就是多说怎么给自己加标识啊，就是在 昵称后面 加上 博主  这样的

**Comment by ganjmeng** [comment]
选来选去还是楼主的  主题最好看

**Comment by ganjmeng** [comment]
楼主，最后一个问题，就是目录右下角的评论按钮怎么配置哦？点击跳转的是一个 其他的网页
![image](https://cloud.githubusercontent.com/assets/12026835/15104699/be9af796-15ed-11e6-9c66-5ff089556d3c.png)

**Comment by ppoffice** [comment]
@ganjmeng 请阅读Wiki

**Comment by ganjmeng** [comment]
Wiki 在哪。。有链接么。。😓

**Comment by ppoffice** [comment]
![image](https://cloud.githubusercontent.com/assets/8849362/15168355/68072428-1763-11e6-95cc-312f8a33c205.png)
@ganjmeng

**Comment by ganjmeng** [comment]
我在文章里面加了DISQUS，里面评论是正常的，现在就是 在首页目录点击  评论按钮  会跳转到 夜歌其他的网页，看了文档没有找到 配置的地方，求详解，谢谢楼主！！！😊

**Comment by ganjmeng** [comment]
![image](https://cloud.githubusercontent.com/assets/12026835/15168673/211523f0-1766-11e6-8dd3-4c65671cc715.png)

**Comment by ppoffice** [comment]
#199
