### ISSUE TITLE
楼主，中间的内容区域的宽度可以调整吗？？怎么调整

### ISSUE THREAD

**Issue by ganjmeng** [ppoffice/hexo-theme-icarus#143]
Please make sure these boxes are checked before submitting your issue. Thank you!
楼主，中间的内容区域的宽度可以调整吗？？怎么调整
- [x] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully;
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/_variables.styl#L43-L45

**Comment by yuzh233** [comment]
新版主题中如何将 `内容模块` 宽度加宽呢？

新版中找不到 `/icarus/source/css/_variables.styl` 文件了

**Comment by ppoffice** [comment]
@yuzh233 https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/style.styl#L21-L32
