### ISSUE TITLE
图片如何添加才可以显示在 title 之前？

### ISSUE THREAD

**Issue by agustinwang** [ppoffice/hexo-theme-icarus#146]
preview 中的文章标题都是在图片下的，请问如何设置？谢谢

**Comment by ppoffice** [comment]
并没有这个设置，不过你可以取消预览图，然后再正文头部插入图片。

**Comment by hobartwang** [comment]
恩，我的意思是类似截图的
![image](https://cloud.githubusercontent.com/assets/9262286/15845983/4ce471ca-2cab-11e6-8a36-99c7ff62df10.png)

代码截图
![image](https://cloud.githubusercontent.com/assets/9262286/15846012/8e29315c-2cab-11e6-8726-0aa3b16fc582.png)

显示效果
![image](https://cloud.githubusercontent.com/assets/9262286/15846015/9b076ff6-2cab-11e6-81da-c72522a951a7.png)

依然达不到preview的效果。麻烦指点下，多谢了

**Comment by ppoffice** [comment]
@hobartwang 
这个需要改动布局文件
你需要把：https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.ejs#L3-L5
移动到：https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.ejs#L6-L16
的下面。
我没有测试过，但是应该行得通。如果移动后界面有错误，应该还要改下样式文件。

**Comment by izuolan** [comment]
楼主的意思是 Post Banner 和 Fancybox 的设置吧～～

**Comment by tiexo** [comment]
@ppoffice  默认就是头图在标题上面
我想楼主的意思是，他直接把图片插入到正文，所以显示在标题下面
应该这样写：
---
titie: 
banner: 图片地址
---
就能实现预览的效果了

**Comment by ppoffice** [comment]
@tiexo 
@agustinwang 
原来是这个意思……
https://github.com/ppoffice/hexo-theme-icarus/wiki/Theme#how-to-add-a-thumbnail-to-a-post
当然写成banner应该也是可以的

**Comment by agustinwang** [comment]
@tiexo @ppoffice 非常感谢两位的解答 👍

**Comment by hxverygood** [comment]
@ppoffice 请问banner图的url应该怎么写?
我写成这样banner不显示，不知道为什么：
banner: ![](/images/wedding.jpg)，图片是放在/sources/image下。
谢谢！

**Comment by hxverygood** [comment]
看到其它问题终于明白怎么做了，参考[#78](https://github.com/ppoffice/hexo-theme-icarus/issues/78)，需要在该主题的source文件夹下新建gallery文件夹，将图片资源放进去。
```
banner: /gallery/wedding.jpg
```

**Comment by keziye** [comment]
我把图片放在主题里的source文件下的gallery，然后也添加thumbnail 为true，文章开头添加thumbnail: gallery/xxx.jpg  请问为什么图片显示不出来呢？只有一个框框，没有图片
