### ISSUE TITLE
hide profile bar from post view

### ISSUE THREAD

**Issue by niwox** [ppoffice/hexo-theme-icarus#147]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully;
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

First of all, congrats and thank you for the amazing work on the theme.
I don't have an issue with the theme, it's more of a customization problem.
I would like to enable the "profile bar" on the home page and hide it once a specific post is clicked. Any option for that ?

best,

**Comment by niwox** [comment]
If anyone wants the same customization, edit line 6 in `layout.ejs` to check if page is home
`<% if (theme.customize.profile.enabled && is_home()) { %>`

**Comment by tiexo** [comment]
@ppoffice  我觉得这个提议不错啊
在文章页隐藏左侧信息栏

当文章比较长，滑到下面的时候，内容不是居中的，而左侧又是空白，看起来不对称有点怪异
我按照楼主的方法试了下，好像只是隐藏了...但是内容没有居中显示
