### ISSUE TITLE
Sidebar 文字错误

### ISSUE THREAD

**Issue by yaguuwang** [ppoffice/hexo-theme-icarus#150]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully;
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

<img width="264" alt="2016-06-12 3 01 02" src="https://cloud.githubusercontent.com/assets/17473718/15986963/63743aae-304a-11e6-985d-e0f6054e5154.png">

在按照hexo的文档预览draft时发现sidebar中文字follow，article，tag出现莫名错误，请问该如何修正呢？谢谢！

**Comment by ppoffice** [comment]
Duplicate #134
