### ISSUE TITLE
hexo g style render fail

### ISSUE THREAD

**Issue by toddywang** [ppoffice/hexo-theme-icarus#151]
ERROR Asset render failed: css/style.css
CoercionError: D:/blog/themes/hexo-theme-icarus/source/css/_variables.styl:28:54

下面是对应的代码
logo-width = 0px + hexo-config("customize.logo.width")

_config.yml
配置过对应值

**Comment by toddywang** [comment]
我发现是hexo-config("customize.logo.width")获取不到值。

**Comment by ppoffice** [comment]
你是照着Wiki的步骤安装的么？
