### ISSUE TITLE
for help about the theme

### ISSUE THREAD

**Issue by kklt007** [ppoffice/hexo-theme-icarus#152]
Hi Mr.Zhang,
    This theme is so cool, and I really like it. But, While I make the profile enable false, the main body and the sidebar of my blog are in the left of page. The right has a large gap. Can you help me make things right? 
    Thanks for your help.
    Best wishes

![problem](https://cloud.githubusercontent.com/assets/7539438/16294032/d4bdbbcc-3950-11e6-8ae5-94cb5298455b.png)

**Comment by ppoffice** [comment]
I failed to notice that the config.yml was updated with an `enabled` option added to this file. Please try out the latest code:smile:

**Comment by kklt007** [comment]
Problem solved. Thank you so much again for your help. :)
