### ISSUE TITLE
The path concatenation in thumbnail helper misses a beginning slash.

### ISSUE THREAD

**Issue by Goshin** [ppoffice/hexo-theme-icarus#156]
```javascript
if ((ret = pattern.exec(url)) != null) {
    if(ret[0].length == url.length) {
        url = post.path + ret[1];
    }
} else if ((ret = pattern_.exec(url)) != null) {
    if(ret[0].length == url.length) {
        url = post.path + ret[1];
    }
}
```
In [scripts/thumbnail.js](https://github.com/ppoffice/hexo-theme-icarus/blob/master/scripts/thumbnail.js#L20) , I believe this block of code is to extract a thumbnail from the article content and try to convert it to an absolute path.

Since the `post.path` here is something like `'2016/06/29/article-name/'`, a leading slash in the joined URL is missed, which may cause a 404 path error when browser treats it as a relative path.

Fix: simply add a forward slash at the start. Refer to my commit: https://github.com/Goshin/hexo-theme-icarus/commit/6e6474b44b3698846b6a374eeeaca1bbaa3c61e3

I hope I've explained everything clearly. Feel free to ask for the reproduce details.

**Comment by ppoffice** [comment]
@Goshin Now you have to set thumbnail or banner url explicitly.

**Comment by Goshin** [comment]
Not bad.

By the way, would you consider transforming the relative path to absolute one in the `thumbnail` and `banner` config? It would be more helpful when users assign an image relative path in the article assets directory, giving a consistent performance in the local editor and the deployed pages, like https://github.com/CodeFalling/hexo-asset-image 
If so, I will open a pull request to explain in details and codes.

**Comment by ppoffice** [comment]
You can insert a relative path of the `thumbnail` or `banner` config. The only thing you should take care of is the root path of your blog(`config.url` and `config.root`).
Example: https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/site/source/_posts/An-Ode-To-Earth-%E2%80%93-Baba-Yetu.md

**Comment by Goshin** [comment]
```yaml
title: An Ode To Earth – Baba Yetu
date: 2015-02-03 17:22:23
categories:
- Music
tags:
- Music
banner: /hexo-theme-icarus/gallery/little-girl.jpg
```

No, the banner path in the example you provided starting with a forward slash is an absolute path. It indicates the resource can be found in the `hexo-theme-icarus/gallery/` from the root `/`.

**Comment by ppoffice** [comment]
@Goshin 
I'm sorry for the example thing, it is an absolute path indeed, compared to the root URL. But I think we can only use absolute paths. Currently, there is a bug in Hexo `url_for` helper function. I can not transform relative paths to absolute paths correctly, especially when the blog is under a subdomain(https://github.com/hexojs/hexo/issues/1788, https://github.com/hexojs/hexo/issues/1773, https://github.com/hexojs/hexo/pull/1912). So if you supply a relative-path thumbnail/banner and your blog is in a subdirectory, you will get wrong image URLs.

Please let me know if I missed something, and you are always welcome to create a pull request.
