### ISSUE TITLE
Using Travis CI for auto deplay.Error:Unhandled rejection TypeError

### ISSUE THREAD

**Issue by szpssky** [ppoffice/hexo-theme-icarus#159]
But when I use default theme(landscape) is no problem.
check out  the attachment for more details.
[log.txt](https://github.com/ppoffice/hexo-theme-icarus/files/351659/log.txt)
Maybe this is a bug?

**Comment by ppoffice** [comment]
Did you follow the installation steps?
https://github.com/ppoffice/hexo-theme-icarus/wiki/Installation
You should put your own _config.yml when you build your blog.

**Comment by szpssky** [comment]
是的，在我本机使用的时候没有问题，但是使用Travis CI做自动构建的时候就会报这个错误。配置文件什么的应该都是没问题的

**Comment by ppoffice** [comment]
@szpssky 
注意到：https://github.com/szpssky/szpssky.github.com/blob/blog-source/themes/icarus/.gitignore#L1
这里你的配置被ignore了，所以Travis Build的时候找不到配置，就报错了。

**Comment by szpssky** [comment]
啊。。。还真是。。。一直没注意到这个地方。好像是原本的主题文件里就有个这个gitignore.
okey，thanks

**Comment by wushang1987** [comment]
@ppoffice  @szpssky 我遇到了同样的问题 
 在我本机使用的时候没有问题，但是使用Travis CI做自动构建的时候就会报这个错误

我的config:
https://github.com/wushang1987/wushang1987.github.io/blob/blog/_config.yml
gitgnore:
https://github.com/wushang1987/wushang1987.github.io/blob/blog/.gitignore

但是按照两位的说法没没有找到错误的原因

**Comment by ppoffice** [comment]
@wushang1987 
请对照着这个配置检查下自己的主题目录下的配置：
https://github.com/ppoffice/hexo-theme-icarus/blob/master/_config.yml.example
