### ISSUE TITLE
Is it OK if I install theme by git submodule instead of git clone?

### ISSUE THREAD

**Issue by indrakaw** [ppoffice/hexo-theme-icarus#165]
Please make sure these boxes are checked before submitting your issue. Thank you!
- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

---

Here's the Q: **Is it OK if I install theme by `git submodule add` instead of `git clone`?**

e.g.

```
$ git submodule add https://github.com/ppoffice/hexo-theme-icarus.git themes/icarus
```

Instead of

```
$ git clone https://github.com/ppoffice/hexo-theme-icarus.git themes/icarus
```

Does it affect to `_config.yaml` on theme dir?

**Comment by linkcd** [comment]
Actually i recommend to add all hexo themes as git submodule instead of git clone. See http://fenglu.me/2016/08/12/How-to-setup-a-hexo-based-blog-Part-2/ 

in terms of icarus, you will also need to update the .gitignore file to make sure git track the _config.yml file (by default it is ignored)

**Comment by indrakaw** [comment]
@linkcd Wow. Love it! Thanks for the information.
