### ISSUE TITLE
Link to RSS feed doesn't add to the source code of pages

### ISSUE THREAD

**Issue by online** [ppoffice/hexo-theme-icarus#166]
Hello!

This piece of code for some reason doesn't add to the source code of the pages link to the rss feed:

```
<% if (theme.rss) { %>
    <link rel="alternative" href="<%- theme.rss %>" title="<%= config.title %>" type="application/atom+xml" />
<% } %>
```

https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/head.ejs#L32-L34

Can you, please, tell how to fix it?

**Comment by ppoffice** [comment]
I missed this when I update the structure of `_config.yml`.
Thanks for pointing it out:smile:

**Comment by online** [comment]
@ppoffice, thanks for your reply. I applied your fix, but still link to the RSS feed is not added on the pages.

In file `config.yml` (config file of Icarus theme.) I have the following lines:

```
social_links:
...
        rss: atom.xml
```

What do I need to do?

**Comment by online** [comment]
@ppoffice, I need to get the following line on all pages:

```
<link rel="alternate" type="application/atom+xml" title="My Blog" href="http://mydomain.com/atom.xml" />
```

How is it set up correctly? Link to rss feed must be absolute.

**Comment by ppoffice** [comment]
@online 
You should apply absolute links in your `_config.yml`:
```yml
social_links:
...
        rss: /atom.xml
```

**Comment by online** [comment]
@ppoffice, everything worked correctly after such actions:

In file `head.ejs` I replaced this:

```diff
- <link rel="alternative" href="<%- theme.customize.social_links.rss %>" title="<%= config.title %>" type="application/atom+xml" />
+ <link rel="alternate" type="application/atom+xml" title="<%= config.title %>" href="<%- theme.customize.social_links.rss %>" />
```

And in file `config.yml` I replaced this:

```diff
- rss: /atom.xml
+ rss: http://mydomain.com/atom.xml
```

:+1:

**Comment by ppoffice** [comment]
Did you check out the latest update I mentioned before?

**Comment by online** [comment]
@ppoffice, yes, I saw, but an extension in Chrome and Firefox browsers do not recognize the link to an RSS feed. Everything started to work properly after [this manipulations](https://github.com/ppoffice/hexo-theme-icarus/issues/166#issuecomment-233172379).

Thank you for your help.
