### ISSUE TITLE
请问如何去掉sidebar一栏，让主区域拉伸占据sidebar的位置呢？

### ISSUE THREAD

**Issue by lijianqiang12** [ppoffice/hexo-theme-icarus#171]
我修改了_variables.styl中的属性，并无作用

**Comment by ppoffice** [comment]
@lijianqiang12 
在_config.yml中把sidebar那项置空就可以了

**Comment by lijianqiang12** [comment]
已试过置空，sidebar会不显示，但内容区域还是会保持原状，并不会变宽覆盖sidebar的区域

**Comment by ppoffice** [comment]
@lijianqiang12 我在本地测试完全正常：
![image](https://cloud.githubusercontent.com/assets/8849362/17213523/32d5c296-5507-11e6-92e2-3bb48bf16de9.png)
请尝试更新下主题源码，如果问题依旧，请把博客源文件贴出来我看下

**Comment by lijianqiang12** [comment]
http://pan.baidu.com/s/1eRH87PS
都在这里了

**Comment by ppoffice** [comment]
@lijianqiang12 
请尝试升级下Hexo，我看到你的主题里面用到的Hexo和它的相关插件是上个大版本的

**Comment by lijianqiang12** [comment]
非常感谢

**Comment by enjoyhot** [comment]
看了下代码，主页和文章用的好像是同一个layout，**但是代码一长就得靠横向滚动条拉长**，感觉体验不是很好，文章页应该去掉sidebar或者右侧的内容。假如去掉sidebar主页的也去掉了，不过我觉得主页作者这样挺好，所以我暂时暴力设置文章页的宽度，在手机上体验又变得不友好。不知能不能简单做到文章内容变宽点，主页也能保持原样？

**Comment by ppoffice** [comment]
@enjoyhot 
可以添加一个layout专门给主页用
