### ISSUE TITLE
_source 页面问题

### ISSUE THREAD

**Issue by AnndaGH** [ppoffice/hexo-theme-icarus#172]
增加 _source 文件夹中的页面，就是直接把 _source 复制到 source那么简单么，我的显示不正常，只有 <h2>标题

**Comment by ppoffice** [comment]
就是直接复制，其他的你可以参考这个分支：https://github.com/ppoffice/hexo-theme-icarus/tree/site

**Comment by AnndaGH** [comment]
我的点击首页菜单的categories显示的是这样的，并没有其他内容，但是首页右侧分类中点击分类可以正常显示分类里的内容
title: categories
layout: categories

**Comment by ppoffice** [comment]
能提供下您的博客源文件地址呢？

**Comment by AnndaGH** [comment]
http://www.annda.cn/categories/
http://www.annda.cn/categories/linux
您看一下

**Comment by ppoffice** [comment]
@AnndaGH 
你复制的时候categories和tags文件夹有没有一起复制到sources里面？

**Comment by AnndaGH** [comment]
有的一致 categories tags about 都在目录下，我的路径
hexo-theme-icarus-master\source\categories
hexo-theme-icarus-master\source\tags
hexo-theme-icarus-master\source\about

**Comment by ppoffice** [comment]
@AnndaGH 
是要把这几个文件夹复制到博客根目录里的source文件夹，我看你好像放到了themes里的source文件夹……

**Comment by AnndaGH** [comment]
非常感谢。一直理解错目录了
