### ISSUE TITLE
How do i use a custom font with icarus.

### ISSUE THREAD

**Issue by IbnSaeed** [ppoffice/hexo-theme-icarus#173]
Hello

How do i use a custom font with icarus.

I have the custom font on my pc and its free for use.

I want to use the following 

@font-face {
  font-family: 'Jameel Noori Nastaleeq';
  src: url('http://www.fontsaddict.com/fontface/jameel-noori-nastaleeq.ttf');
}

**Comment by tiexo** [comment]
我也顺便问一下，主题换字体是正确姿势是咋样的
我知道是在css文件里面更改，可是字体的范围是什么呢？有哪些可以选择的字体？
譬如我现在想改成思源黑体，应该怎么弄.....

**Comment by IbnSaeed** [comment]
@tiexo  I did not undertand. Your text is displayed as boxes.

**Comment by ppoffice** [comment]
@IbnSaeed 
Please refer to this folder: https://github.com/ppoffice/hexo-theme-icarus/tree/master/source/vendor/open-sans

**Comment by ppoffice** [comment]
@tiexo 
字体完全任意，可以放到自己博客下面，也可以用CDN。修改方式同上条回复
