### ISSUE TITLE
images are not shown

### ISSUE THREAD

**Issue by omaarr90** [ppoffice/hexo-theme-icarus#174]
Please check my blog

http://blog.omaarr90.website

images for social are not shown. also share comment and search images not shown </3

**Comment by ppoffice** [comment]
@omaarr90 
I found that your site's resource files aren't loaded properly:
![image](https://cloud.githubusercontent.com/assets/8849362/17466807/07c3cdec-5d49-11e6-9394-937d0ae6d8ad.png)
If you open any of those resources in your browser, you will get a `403` error:
![image](https://cloud.githubusercontent.com/assets/8849362/17466821/2e201bbc-5d49-11e6-9545-fa69e080b161.png)
Please check your Nginx permission configurations for static resources folders.

**Comment by omaarr90** [comment]
Can you elaborate more. I do not know how to fix it yet.

**Comment by ppoffice** [comment]
I don't know how you configure your server. I think this might help you: https://www.scalescale.com/tips/nginx/403-forbidden-nginx/

**Comment by ppoffice** [comment]
@omaarr90 
Please check your Hexo root folder's permissions:
```
ls -al
```
You can set the permissions for the files under that folder to 755:
```
chmod -R 755 your_hexo_root
```
