### ISSUE TITLE
关于置顶功能

### ISSUE THREAD

**Issue by yo1995** [ppoffice/hexo-theme-icarus#178]
github门外汉不懂git，希望作者可以考虑通过js增加一个文章置顶功能。如在front-matter中增加排序属性这种？

edit180210 很早之前就解决啦~不过暂时不用了。

**Comment by ppoffice** [comment]
@yo1995 
暂时的办法是在front-matter中设置文章的时间为一个很大的值，这样按时间排序的时候会保持文章在最新一个位置。
至于文章置顶的功能有时间我会考虑下。

**Comment by skyseraph** [comment]
使用： npm install hexo-generator-index-pin-top --save
然后博主再加一个置顶标识即可

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： https://github.com/hexojs/hexo-generator-index/pull/51

**Comment by ACG-Q** [comment]
> Hexo 已实现文章置顶参数： [hexojs/hexo-generator-index#51](https://github.com/hexojs/hexo-generator-index/pull/51)

老哥，使用hexo-theme-icarus@5, 我在文章的front-matter中使用`sticky: 1`，然后博客就直接空白了😿
