### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by nextmvp** [ppoffice/hexo-theme-icarus#179]
在我的主页里面看文章可以显示，但是通过tag进文章，图片就显示不正常了。具体可以查看我的博客：https://nextmvp.github.io

**Comment by tiexo** [comment]
图片404了

**Comment by ppoffice** [comment]
@nextmvp 建议图片使用绝对地址和cdn，现在hexo在处理地址上好像还有点问题

**Comment by nextmvp** [comment]
谢谢各位
