### ISSUE TITLE
Chinese translation didn't fully work.

### ISSUE THREAD

**Issue by LiJinyao** [ppoffice/hexo-theme-icarus#18]
![2015-06-11 23 31 19](https://cloud.githubusercontent.com/assets/3450595/8111074/2e1e2b0e-1092-11e5-9e43-f4133e5f1888.png)
I set
``
language: zh-CN
``
but it haven't change the header to Chinese.
My hexo info:
```
http_parser: 1.0
node: 0.10.25
v8: 3.14.5.9
ares: 1.10.0
uv: 0.10.23
zlib: 1.2.8
modules: 11
openssl: 1.0.1f
```

**Comment by ppoffice** [comment]
顶部的导航栏是需要你在_config.yml中自己输入中文的。。。

**Comment by LiJinyao** [comment]
谢谢。。。新手见笑了嘿嘿。

**Comment by dittocafe** [comment]
我改了中文，但为啥是乱码？[www.dittocafe.com](url)

**Comment by ppoffice** [comment]
@dittocafe 文件编码错误，请使用编辑器保存为UTF8编码
