### ISSUE TITLE
Lightgallery thumbnail grid

### ISSUE THREAD

**Issue by Yakubovich** [ppoffice/hexo-theme-icarus#182]
I am able to use use the newly included lightgallery.js plugin to create a slideshow, but is it also possible to have it generate a grid of thumbnails like the one shown on the lightgallery.js site?

<img width="962" alt="lightgallery__thumbnails" src="https://cloud.githubusercontent.com/assets/1034506/17855357/f1097c10-68aa-11e6-9a8d-c8035fc696ea.png">

**Comment by ppoffice** [comment]
I think that is not generated by lightgallery. You may need to define your own CSS.

**Comment by Yakubovich** [comment]
Ok. I solved this by adding another plugin: https://github.com/ppoffice/hexo-theme-icarus/pull/183
