### ISSUE TITLE
大神，我基于你的主题修改了一下细节部分，然后开源了，这样可以么

### ISSUE THREAD

**Issue by yohnz** [ppoffice/hexo-theme-icarus#185]
Hi,
大神，我基于你的主题修改了一些样式部分，然后放在github上，这样可以么？
[戳这里](https://github.com/yohnz/hexo-theme-card)

**Comment by ppoffice** [comment]
@yohnz
当然可以的，这个主题是MIT License，只要保持原License就欢迎修改:smile:

**Comment by yohnz** [comment]
@ppoffice 好的
