### ISSUE TITLE
请教一个问题 RECENT 怎样做到每条文章记录的图片都不同，谢谢

### ISSUE THREAD

**Issue by D-Rusty** [ppoffice/hexo-theme-icarus#188]
请教一个问题：要做到如下图 RECENT 每一篇文章，图片都不一样，请问应该怎样设置，可以提供一个demo参考吗，谢谢。 我看的是这个网站的效果 http://blog.zhangruipeng.me/hexo-theme-icarus/
![image](https://cloud.githubusercontent.com/assets/17473495/18359623/48bee276-762d-11e6-9f5d-dfb573ac776d.png)

**Comment by ppoffice** [comment]
@D-Rusty 
https://github.com/ppoffice/hexo-theme-icarus/wiki/Theme#thumbnail
