### ISSUE TITLE
页码小细节处理

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#191]
我发现页码显示有点小问题，截图如下

![qq 20160919201525](https://cloud.githubusercontent.com/assets/8164505/18631653/d3276c1e-7ea5-11e6-80d3-848802daa2cf.png)

中间这个省略号和背景颜色一样，导致看起来好像缺了一块
这样局部放大看，还有点痕迹，当你隔远了看真的有点强迫症了，左右不对称

![qq 20160919201818](https://cloud.githubusercontent.com/assets/8164505/18631775/8061507a-7ea6-11e6-88d1-bca4fbca0e70.png)

真是越看越不能忍受了，因此过来反馈下。

**Comment by ppoffice** [comment]
@tiexo 
还真没注意到这个，感谢提醒
