### ISSUE TITLE
点击Categories模块，没有一个Category

### ISSUE THREAD

**Issue by clayclayclay** [ppoffice/hexo-theme-icarus#192]
![image](https://cloud.githubusercontent.com/assets/13716195/19071582/68dfbb62-8a63-11e6-96b1-f27ddad299a1.png)

这是我的一篇文章，可以看到分类为 技术
可点击去Categories后，没有任何一个分类。
请问这是哪里出了问题呢？

**Comment by clayclayclay** [comment]
补充：
![image](https://cloud.githubusercontent.com/assets/13716195/19072037/a509bca8-8a65-11e6-9d04-6c488b69bb5d.png)
![image](https://cloud.githubusercontent.com/assets/13716195/19072054/ae77aebc-8a65-11e6-8dce-c2dfe2de007f.png)

点击文章的分类是可以进去的，但是只点击那个 Categories 菜单，却什么都没有

如图：
![image](https://cloud.githubusercontent.com/assets/13716195/19072073/cceec8e4-8a65-11e6-9de3-5bba066e82b1.png)

**Comment by ppoffice** [comment]
@clayclayclay 
你有把https://github.com/ppoffice/hexo-theme-icarus/tree/master/_source 这个文件夹拷贝到博客根目录和source文件夹合并么？这里有参考示例：https://github.com/ppoffice/hexo-theme-icarus/tree/site

**Comment by clayclayclay** [comment]
请问问一下，我没有找到tree/master/_source 这个目录唉

**Comment by clayclayclay** [comment]
喔喔，找到啦

**Comment by clayclayclay** [comment]
好啦好啦，谢谢！
