### ISSUE TITLE
当文章中有代码时，移动端显示不全

### ISSUE THREAD

**Issue by Thesharing** [ppoffice/hexo-theme-icarus#195]
当文章中有代码时，在移动端无法正常显示内容，只能看到内容的右边部分。

下面也没有横向滚动条。

![image](https://cloud.githubusercontent.com/assets/6576831/19376699/d6179b76-9212-11e6-89ce-203afde7099f.png)

**Comment by ppoffice** [comment]
@Thesharing 
已修复

**Comment by Thesharing** [comment]
已修复，谢谢~
