### ISSUE TITLE
图片点击问题

### ISSUE THREAD

**Issue by meroco** [ppoffice/hexo-theme-icarus#196]
`[![img](img-url)](url)`

给图片做超链接时，点击图片依旧是跳转到图片地址，而不是跳转到超链接地址。请问要如何修改？

**Comment by ppoffice** [comment]
@meroco 
可以尝试启用lightGallery插件

**Comment by meroco** [comment]
已经启用了，点击动作还是打开图片，并不是跳转超链接。

2016-10-14 19:59 GMT+08:00 Ruipeng Zhang <notifications@github.com>:

**Comment by ppoffice** [comment]
@meroco 
能贴一下出问题的页面的地址么？
另外`[![img](img-url)](url)`这个多写了一个左方括号

**Comment by meroco** [comment]
https://blog.misuzu.moe/ 问题出在文章底部的cc by nc sa图像。现在的妥协方法是填写图片名称。点击图片就直接打开图片了。本地md写完是可以做到点击图片跳转的。 星期六, 15 十月 2016, 09:08上午 +08:00 发件人 Ruipeng Zhang  notifications@github.com :

**Comment by meroco** [comment]
顺便问一下，JustifiedGallery要如何启用？

> ``` 
> <div class="mygallery.justified-gallery"> 
> <img>...
> </div>
> ```

这样添加图片不能启用。

**Comment by ppoffice** [comment]
@meroco 
_config.yml里面设置justified-gallery为true了么？
另外代码应该是：
```html
<div class="mygallery justified-gallery"> 
<img>...
</div>
```

**Comment by meroco** [comment]
设置参数里已经启用了，class="justified-gallery"和class="mygallery justified-gallery"都
无法生效。
附上地址：https://misuzu.moe/Aliyun_ECS.html
图片区域是 Title 1和Title 2。

2016-10-20 15:04 GMT+08:00 Ruipeng Zhang <notifications@github.com>:

**Comment by ppoffice** [comment]
@meroco 
可能是插件的问题，我稍后修复下

**Comment by ppoffice** [comment]
@meroco 
当时这个功能是另一个人提的pr，我没有仔细检查就合并了……
现在最新的应该可以正常使用了，感谢反馈。

**Comment by meroco** [comment]
不过好像还是有问题，justifiedgallery中的图片无法被lightgallery调取，会在新标签页打开。禁用图片跳转的话是没问题了。

**Comment by ppoffice** [comment]
@meroco 
我这儿点https://blog.misuzu.moe/Aliyun_ECS.html 图片是可以在light Gallery中展示的
