### ISSUE TITLE
点击more，图片地址变了，图片不显示

### ISSUE THREAD

**Issue by qihoushangshu** [ppoffice/hexo-theme-icarus#198]
我在博客里放的图片，在主页的状态下能够显示https://qihoushangshu.github.io/
但是只要点击more，里边的图片就都不显示了，然后我F12看，发现当我点击more后，图片的地址变了，不再是https://qihoushangshu.github.io/css/images/wuyuan.png
变成了
https://qihoushangshu.github.io/2016/08/14/%E5%BD%92%E5%8E%BB%E6%9D%A5%E5%85%AE%E8%BE%9E/css/images/wuyuan.png
，地址里多了2016/08/14/%E5%BD%92%E5%8E%BB%E6%9D%A5%E5%85%AE%E8%BE%9E，不知道这个在哪里能控制，谢谢

**Comment by ppoffice** [comment]
@qihoushangshu 
图片地址请尽量使用绝对地址

**Comment by qihoushangshu** [comment]
@ppoffice 
多谢，不好意思，还想问一个问题，在示例的博客里（[http://blog.zhangruipeng.me/hexo-theme-icarus/]


每篇文章里都有一个图片，然后这个图片在右侧里是一个缩略图，这个是每次写文章时有什么特殊写法控制的吗，我试了下把图片放到标题上起服务就直接报错了，放到下边的话，图片在文章内，缩略图是默认的那个

**Comment by ppoffice** [comment]
@qihoushangshu 
https://github.com/ppoffice/hexo-theme-icarus/wiki/Theme#how-to-add-a-thumbnail-to-a-post

**Comment by qihoushangshu** [comment]
@ppoffice 
图片能在缩略图显示了，多谢
