### ISSUE TITLE
关于文章目录

### ISSUE THREAD

**Issue by javahuang** [ppoffice/hexo-theme-icarus#199]
挺喜欢这个主题，请问作者有木有给文章加上目录的计划啊？

**Comment by acbetter** [comment]
我已经加了 `toc: true`  到 front-matter。
![image](https://cloud.githubusercontent.com/assets/13360124/20637991/7fcdf2d2-b3d3-11e6-847e-b9194cc95e32.png)
但是这一行代码并没有给文章添加上目录，是否需要安装插件或者进一步配置？
[my blog for test](http://acbetter.com/2016/09/06/%E5%96%B5%E8%AF%BE%E8%A1%A8%F0%9F%90%B1%20on%20iOS/)

**Comment by ppoffice** [comment]
@acbetter 
不是没有TOC，而是你开头的引用块把TOC挡住了😂
你可以尝试挪动引用块，或者在这个地方https://github.com/ppoffice/hexo-theme-icarus/blob/8b818d06acb0e380d486ba2e6dcaa0dfcf755bce/source/css/_partial/article.styl#L353加上一行：
```stylus
    float: none
```

**Comment by acbetter** [comment]
原来是这样啊，好尴尬～
感谢作者大大～
