### ISSUE TITLE
关于评论功能

### ISSUE THREAD

**Issue by suntw2015** [ppoffice/hexo-theme-icarus#200]
disqus、duoshuo、youyan 都不能用  

youyan不支持https  

disqus加载不出来

duoshuo 是js报错

**Comment by ppoffice** [comment]
@suntw2015 
我再本地测试Disqus和多说都是可以正常使用的。
Disqus加载不出来了可能是被墙了，友言目前官方不支持HTTPS。
Disqus的JavaScript报错截图能麻烦贴出来么？

**Comment by D-Rusty** [comment]
您好我用的是duoshuo.我在本地同样遇到无法打开评论窗口的事情谢谢

**Comment by problem233** [comment]
多说已经停止服务了

**Comment by D-Rusty** [comment]
谢谢回复

**Comment by Kayleman** [comment]
我今天刚照着网上的教程弄的,在disqus官网注册了账号,并且绑定了自己的域名,找到自己的shortname,在把
`theme/icarus/_config.yml`中的disques: 后面加上自己的shortname就可以了,不过需要在翻墙的环境下才能刷出来, 我用手机和另一台电脑浏览自己的博客下的评论时如果没翻墙也是显示不出来的.在翻墙之后 马上就显示出来了
