### ISSUE TITLE
报错：找不到vendor下的样式文件

### ISSUE THREAD

**Issue by Lemon23** [ppoffice/hexo-theme-icarus#202]
我已经使用了一段时间了，前天修改了一点样式文件上传后，打开页面发现图标都不显示了，后来看了浏览器控制台发现所有在vendor文件夹下的样式文件和js文件，都报错404NOT FOUND。

尝试删除.deploy_git文件，尝试过hexo clean，都没有用。

各种百度后说是配置文件的url和root属性问题，我也查看过，没有错。而且我是已经使用一段时间了，没有修改过配置文件，不会出错。

我回退到修改之前的版本，也没有作用。按说不应该再报错了，怎么办？

[lemon23.me](http://lemon23.me/)

**Comment by ppoffice** [comment]
@Lemon23 
https://github.com/ppoffice/hexo-theme-hueman/issues/151
可能与Github官网的更新有关

**Comment by ppoffice** [comment]
@Lemon23 
现在使用`hexo generate`可以直接在`public`目录下生成`.nojekyll`文件，但由于`hexo-deploy-git`这个Hexo插件会忽略`.`开头的文件，所以直接使用`hexo deploy`仍然不能将`.nojekyll`文件部署到GitHub上。现在的解决方法是手动部署`public`目录下的文件。我会向Hexo提一个PR，但不能保证一定会Merge。

**Comment by ppoffice** [comment]
已经重命名vendor文件夹，不用考虑上述问题了。。。

**Comment by zthxxx** [comment]
我也遇到这个问题了，是从 2016-11-03 早上开始的，vender 下所有东西无法访问，尝试很多方法未果(http/https、换域名、换 CDN、关 CNAME、换 coding.net)，最后发现只要是主站域名下 /vender/ 文件夹就不行，于是尝试把 vender 换到下一级目录中，成这样 /lib_package/vender/ ，再放到 github pages，就能访问了

**Comment by Lemon23** [comment]
感谢，执行git pull以后，再配置上传，已经没问题了。🙏

**Comment by huangshuwei** [comment]
在网站的根目录添加这个文件就好了：.nojekyll

**Comment by huangshuwei** [comment]
这个不是bug，是github page 的bug，github page 更新后默认只支持[Jekyll](https://github.com/jekyll/jekyll)

**Comment by MertensMing** [comment]
将 vendors 的地址都替换成了 cdn 地址
![image](https://cloud.githubusercontent.com/assets/13334618/20088895/3dd7d5c8-a5be-11e6-97ba-37bed29ce5f6.png)

**Comment by huangshuwei** [comment]
@MertensMing 
在网站根目录添加一个空的 .nojekyll 文件即可

**Comment by donghao526** [comment]
我这里是找不到content.json文件，显示404，页面显示不正常

**Comment by donghao526** [comment]
在本地预览没问题，到git上就无法正常显示
![image](https://cloud.githubusercontent.com/assets/1930500/20603734/cec8ed92-b29d-11e6-8537-b5c8c334e495.png)
