### ISSUE TITLE
Update the vendor path to avoid issue in new Github page

### ISSUE THREAD

**Issue by linkcd** [ppoffice/hexo-theme-icarus#203]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [x] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [x] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [x] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

Due to the changes in Github page https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3, all content vendor folder is blocked. 

Could you pls make the same change as https://github.com/iissnan/hexo-theme-next/issues/1214 did?

thanks,

**Comment by ppoffice** [comment]
Duplicate #202

**Comment by wxytongxue** [comment]
搜索的图标，和返回顶部等都不显示，试了下以上方法，但是没有啥改变
