### ISSUE TITLE
右边sidebar的最新文章所属分类，标题的英文全部变成了大写

### ISSUE THREAD

**Issue by huyongli** [ppoffice/hexo-theme-icarus#206]
首页右边sidebar上面的 最新文章所属分类、标题中的英文全部变成了大写，包括主页文章标题下面的分类和tag也都变成了大写，为什么不保持其原有大小写？

**Comment by ppoffice** [comment]
@huyongli 
为了强调显示

**Comment by huyongli** [comment]
有没有开关可以关闭大写 @ppoffice

**Comment by ppoffice** [comment]
@huyongli 
删掉下面这句
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/_partial/sidebar.styl#L146

**Comment by huyongli** [comment]
thank you @ppoffice
