### ISSUE TITLE
Google Structured Data to Home page

### ISSUE THREAD

**Issue by iamchathu** [ppoffice/hexo-theme-icarus#207]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

Like this can we add these tags to theme so that our sites will have Good SEO 

https://developers.google.com/search/docs/guides/enhance-site

Thank you.

**Comment by van-nguyen** [comment]
+1

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/releases/tag/3.0.0-beta.1
