### ISSUE TITLE
博主你好，我也想在你这个主体的基础上修改一下页面结构，但是我找不到源文件，请问怎么修改源文件代码结构

### ISSUE THREAD

**Issue by Jabinzou** [ppoffice/hexo-theme-icarus#208]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [ ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [ ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [ ] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

**Comment by ppoffice** [comment]
@Jabinzou 
页面结构在这里：https://github.com/ppoffice/hexo-theme-icarus/tree/master/layout
使用的是EJS语法

**Comment by Jabinzou** [comment]
好的  谢谢！

**Comment by Jabinzou** [comment]
还有  那个favicon的地址是把图片放在css/images里面  路径是 写 images/tupian .png  这样的格式吗？

**Comment by ppoffice** [comment]
`css/images/tupian.png`
