### ISSUE TITLE
你这个顶部导航分类和标签是怎么实现的啊

### ISSUE THREAD

**Issue by xjliao** [ppoffice/hexo-theme-icarus#21]
我看了你的实例网站， 顶部的分类和标签是有效的， 然而在我的本地运行后却是无效的，要做什么配置，还是？

**Comment by ppoffice** [comment]
参见README.md
你需要把`<your site>\themes\icarus\_source\`目录下的所有内容拷贝到`<your site>\source`目录下。

**Comment by xjliao** [comment]
粗心了 刚看见。
