### ISSUE TITLE
insight search

### ISSUE THREAD

**Issue by Jabinzou** [ppoffice/hexo-theme-icarus#210]
您好  我又来打扰你了，，，
我按照你的配置文件  配置了 insight search 也安装了hexo-generator-json-content
但是 搜索 框试出来了  但没反应

![1](https://cloud.githubusercontent.com/assets/14176629/20654871/1fd4d392-b558-11e6-9f19-e54a1c68c6eb.png)
但是安装 npm install -S hexo-generator-json-content
但是启动编译时 出现问题了
![2](https://cloud.githubusercontent.com/assets/14176629/20654889/5549eb02-b558-11e6-873a-e731ac1d314c.png)

**Comment by ppoffice** [comment]
#189 
请善用Issue搜索功能

**Comment by Jabinzou** [comment]
我的node版本是最新的 但是还是报上面的错误 好像es6语法不支持

**Comment by ppoffice** [comment]
@Jabinzou 
你的Node和Hexo版本是多少？

**Comment by Jabinzou** [comment]
![2016-11-28_161636](https://cloud.githubusercontent.com/assets/14176629/20660746/0d8b2910-b586-11e6-929a-95a7d164448d.png)

**Comment by Jabinzou** [comment]
![2016-11-28_161720](https://cloud.githubusercontent.com/assets/14176629/20660771/27e9cca8-b586-11e6-98d8-38f5d54754aa.png)

**Comment by ppoffice** [comment]
@Jabinzou 
可能是Node没有默认开启ES6功能，需要添加启动flag，或者升级到6.0

**Comment by Jabinzou** [comment]
。。。怎么升级 nodea啊 在windows下 我按照 npm -g install npm 会出错

**Comment by mspanish** [comment]
I am having the same issue - can you post the solution in English?

**Comment by ppoffice** [comment]
@mspanish Please upgrade your Node.js to at least version 6.

**Comment by mspanish** [comment]
thank you for your speedy reply - your theme is beautiful - thanks for offering it for free.
