### ISSUE TITLE
Google webfont support

### ISSUE THREAD

**Issue by iamchathu** [ppoffice/hexo-theme-icarus#218]
Shall we add google webfont support to this theme. So users can customize the font families they want for headings and content

**Comment by ppoffice** [comment]
@iamchathu 
I used Google Fonts service in this theme in the beginning, but due to its unavailability in some countries, I finally replaced it with self-hosted fonts. Perhaps I should add an opinion for users to decide which service they want to use. Thank you for the advice!

**Comment by iamchathu** [comment]
I really appreciate the effort you put on this theme. 

Yes that would be great

**Comment by ppoffice** [comment]
#235
