### ISSUE TITLE
cnzz 统计功能的实现

### ISSUE THREAD

**Issue by D-Rusty** [ppoffice/hexo-theme-icarus#219]
想在icarus中配置cnzz 统计功能，请问应该怎样设置，wiki中没有找到答案，谢谢

**Comment by ppoffice** [comment]
@D-Rusty 
最简单的方法是在https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/footer.ejs 中添加CNZZ的统计代码。
