### ISSUE TITLE
Commenting System

### ISSUE THREAD

**Issue by meroco** [ppoffice/hexo-theme-icarus#220]
鉴于 Disqus 国内的访问状况，安利两个评论系统 [Muut](https://muut.io/) 和 [Comn(entjit)](https://commentit.io/)。
另外异步加载评论是不是更合适呢？

**Comment by ppoffice** [comment]
@meroco 
感谢建议。另外评论都是异步加载的，造成载入缓慢的原因可能是评论的JavaScript文件加载缓慢。

**Comment by neoFelhz** [comment]
Comn(entjit) 应该不能用在 Hexo 上吧。
