### ISSUE TITLE
Add Reading time estimate to posts

### ISSUE THREAD

**Issue by iamchathu** [ppoffice/hexo-theme-icarus#221]
Inspired by medium shall we add reading time to this theme also. 

little bit of search found below

https://github.com/michael-lynch/reading-time

**Comment by iamchathu** [comment]
https://github.com/nodes-frontend/hexo-readingtime

https://github.com/ngryman/reading-time

**Comment by ppoffice** [comment]
@iamchathu 
You are welcome to add a pull request.
