### ISSUE TITLE
How to accelerate theme load in China? （请教下在国内环境访问如何加快主题的载入速度）

### ISSUE THREAD

**Issue by xiaolai913** [ppoffice/hexo-theme-icarus#228]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [ ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [ ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [ ] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

**Comment by ppoffice** [comment]
@xiaolai913 
目前此主题的JS和CSS都是self-hosted，你可以用国内的CDN来替换这些第三方库的CSS和JS。详情请参见这里：
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/head.ejs#L40-L46
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/plugin/scripts.ejs

**Comment by wonderful60** [comment]
我是通过在coding.net同时部署了一套来加快访问的，相信很多国内的朋友都是这么做的。

**Comment by tiexo** [comment]
战略马克，回去替换下试试

**Comment by xiaolai913** [comment]
@ppoffice @wonderful60 多谢！我试试看
