### ISSUE TITLE
只能使用fontawesome中的图标吗？

### ISSUE THREAD

**Issue by RiseKyle** [ppoffice/hexo-theme-icarus#231]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [x] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [x] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [x] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。
是否只能使用 fontawesome 中提供的图标，好像我没找到知乎的图标，有其他解决办法吗？我尝试使用quora的图标来代替，但是设置quora的图标却不成功

**Comment by ppoffice** [comment]
@RiseKyle 需要自己去替换样式表

**Comment by RiseKyle** [comment]
@ppoffice 好的，谢谢

**Comment by 941968215** [comment]
fontawesome 虽然有 Quora 图标, 但是在分享上无法显示图标, 请问为什么?

**Comment by ppoffice** [comment]
@941968215 更新下FontAwesome的文件
