### ISSUE TITLE
toc 的实现问题

### ISSUE THREAD

**Issue by 941968215** [ppoffice/hexo-theme-icarus#232]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [ ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [ ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [ ] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

我阅读了官方的 Helper 文档, 但是没有相应基础, 照着做还是无法实现 toc 功能, 也谷歌了一些链接, 比如http://wangxin123.com/2016/06/01/Github+Hexo,%E6%90%AD%E5%BB%BA%E4%B8%93%E6%9C%89%E5%8D%9A%E5%AE%A2/ 但是依然无法完成这个功能, 所以来请教下作者, 谢谢

**Comment by 941968215** [comment]
刚刚发现原来目录已经添加了, 但是在文章的右上角, 请问有什么办法调整到正上方吗?

**Comment by ppoffice** [comment]
@941968215 需要自己修改样式表
