### ISSUE TITLE
为什么我开启了share功能，在本地可以使用，但是部署到github之后就不行了

### ISSUE THREAD

**Issue by mgfjxxiexiaolong** [ppoffice/hexo-theme-icarus#233]
![image](https://cloud.githubusercontent.com/assets/13596540/22048716/c8a0c9d4-dd69-11e6-8b88-8c9df132ccd9.png)
如题，样式也加载不出来，点击之后也没有反应

**Comment by ppoffice** [comment]
@mgfjxxiexiaolong 
![image](https://cloud.githubusercontent.com/assets/8849362/22048876/cf690398-dd6a-11e6-8cdf-d1e54dc97f7c.png)
JiaThis没有提供HTTPS的JavaScript资源地址，而你的GitHub Pages强制使用了HTTPS，所以由于安全因素阻止了插件的加载。建议在Repo设置中[关闭强制HTTPS](https://github.com/blog/2186-https-for-github-pages)，或者使用其它分享插件。

**Comment by mgfjxxiexiaolong** [comment]
@ppoffice 我竟然没找到设置  还麻烦给个详细步骤  在此拜谢了
