### ISSUE TITLE
RTL version

### ISSUE THREAD

**Issue by ghaseminya** [ppoffice/hexo-theme-icarus#234]
Hi
I use hexo with your beautiful and delicious theme,
But i wana to change your theme for RTL language, is it possible with little change to create a RTL version of icarus?
Thanks
@ghaseminya

**Comment by ppoffice** [comment]
@ghaseminya It should support RTL with some CSS fix. I will look into it.

**Comment by ppoffice** [comment]
@ghaseminya 
I add some partial supports for RTL posts, an example is here: http://blog.zhangruipeng.me/hexo-theme-icarus/2016/01/30/Arabic-Test/

To mark a post as RTL post, just add the highlighted line to the post's front-matter:
```diff
  title: اختبار اللغة العربية
  date: 2016-01-30 10:15:01
  ...
+ direction: rtl
```

If you feel something is missing or misplaced in RTL posts, please let me know 😄

**Comment by ghaseminya** [comment]
Thanks @ppoffice 
Its very excellent for this fast coding...
Is it possible to change direction for header and sidebar text? I know that sidebar can change from left to tight by _config.xml with this tag= "sidebar: right", but how can we change text direction for all pages section.

**Comment by ppoffice** [comment]
@ghaseminya 
I don't know much about RTL layout styles. You can modify cooresponding styles for the header and sidebar, you can find them in [source/css/_partial](https://github.com/ppoffice/hexo-theme-icarus/tree/master/source/css/_partial), and add [direction css](http://www.w3schools.com/cssref/pr_text_direction.asp) to the elements as you wish:
```css
direction: rtl
```

In the meantime, I hope my last commit will offer you some help on editing the style files.

**Comment by ghaseminya** [comment]
Thanks for @ppoffice 
Ok, i work on it and to be announce

**Comment by toolor** [comment]
支持RTL语言吗?

**Comment by ppoffice** [comment]
@toolor 文章正文支持
http://blog.zhangruipeng.me/hexo-theme-icarus/2016/01/30/Arabic-Test/
