### ISSUE TITLE
 Partial widget/categories does not exist. 

### ISSUE THREAD

**Issue by Lutece** [ppoffice/hexo-theme-icarus#236]
Partial widget/categories does not exist. 

 i don't understand this sentence.
 when i made a category page, i met this

 please! help me

**Comment by ppoffice** [comment]
@Lutece 
Please refer to this [example site](https://github.com/ppoffice/hexo-theme-icarus/tree/site) if you want to add a page showing categories.

**Comment by PolarBearAndrew** [comment]
@Lutece 

#### 1.init a category page

```
$hexo new page categories
```

#### 2.Edit the `categories/index.md`

``` 
title: categories
date: 2017-02-02 19:31:23
layout: categories
type: "categories"
---
```

#### 3. rebuild everything

```
$hexo clean
$hexo generate
```

or just see demo on local dev server

```
$hexo server --watch
```

##### Notes

Same as widget/tags file, you can try to build a tags page also 😄

**Comment by Lutece** [comment]
Thank you.
As you can tell, the category page has been completed.
One more question, how do I make a category visible on a category page like this one?
<img width="758" alt="2017-02-03 12 57 13" src="https://cloud.githubusercontent.com/assets/10138496/22579115/ec4c1bc8-ea10-11e6-8c43-e2e2c699bc22.png">
<img width="733" alt="2017-02-03 12 57 19" src="https://cloud.githubusercontent.com/assets/10138496/22579116/ec4f8146-ea10-11e6-8245-41a0318c02ae.png">

@PolarBearAndrew

**Comment by ppoffice** [comment]
@Lutece 
Simply adding a new category in one of your posts will do the trick.

**Comment by Lutece** [comment]
<img width="706" alt="2017-02-03 3 44 27" src="https://cloud.githubusercontent.com/assets/10138496/22582052/b57def42-ea27-11e6-9882-91b3ba8091f1.png">
<img width="675" alt="2017-02-03 3 44 19" src="https://cloud.githubusercontent.com/assets/10138496/22582056/b86a156e-ea27-11e6-90ac-a179d4fe27df.png">
<img width="717" alt="2017-02-03 3 44 14" src="https://cloud.githubusercontent.com/assets/10138496/22582059/bc13c1e2-ea27-11e6-90c8-193ab759d983.png">
![2017-02-03 3 44 04](https://cloud.githubusercontent.com/assets/10138496/22582060/bec756ec-ea27-11e6-8cdd-1aed0e5e95ca.png)


I added one category to the post, but the category page is not responding. :( Did I miss something?

**Comment by ppoffice** [comment]
@Lutece https://hexo.io/docs/front-matter.html

**Comment by Lutece** [comment]
I really appreciate it. It was my fault that I could not check the API documentation well. It seems that the part that attempted to test with the 'helloword' post made this issue more complicated. 👍

**Comment by PolarBearAndrew** [comment]
@Lutece  try to find the _config.yml and you'll see it

A little guide for you : 

`/source` : the data you put, like : images, articles also categories page and tags page ( although we do nothing 😄 )

`_config.yml` : usually everything you want to change already in it, understand it as more as you can .

By the way, most of time you won't need to edit anything under the `theme` dir.

**Comment by Lutece** [comment]
@PolarBearAndrew thanks! i understood very well!
