### ISSUE TITLE
Solar_Jalaali_calendar

### ISSUE THREAD

**Issue by ghaseminya** [ppoffice/hexo-theme-icarus#237]
Hi
Is it possible to wrap date with Jalaali calendar?
I install moment-jalaali with this help
http://momentjs.com/docs/#/plugins/jalaali/
but i didnt find a good place to change date format to jalaali?

**Comment by ppoffice** [comment]
@ghaseminya 
1. Install `moment-jalaali` via npm in the root folder of you blog:
```sh
npm install moment-jalaali
```
2. Add a Hexo helper script (like jalaali.js) to `themes/icarus/scripts`:
```js
/**
* Moment.js Jalaali Helper
* @description Jalaali Calendar Converter
* @example
*     <%- jalaali(date) %>
*/
var moment = require('moment-jalaali');

hexo.extend.helper.register('jalaali', function (date) {
    return moment(date).format('jYYYY/jM/jD'); // You can change the date format
});
```
3. Edit layout files to use this helper function to format your date. For example, you can edit `themes/icarus/layout/common/post/date.ejs`:
```diff
<% if (post.date) { %>
    <div class="<%= class_name %>">
        <i class="fa fa-calendar"></i>
        <a href="<%- url_for(post.path) %>">
-            <time datetime="<%= date_xml(post.date) %>" itemprop="datePublished"><%= date(post.date, date_format) %></time>
+            <time datetime="<%= date_xml(post.date) %>" itemprop="datePublished"><%= jalaali(post.date) %></time>
        </a>
    </div>
<% } %>
```

**Comment by ghaseminya** [comment]
That work fine...
Thanks @ppoffice 
I open new pull with this title "icarus-rtl-jalaali"
