### ISSUE TITLE
social links in _config.yml not work

### ISSUE THREAD

**Issue by hd5970** [ppoffice/hexo-theme-icarus#241]
social_links:
        github: https://github.com/ppoffice/
    social_link_tooltip: true # enable the social link tooltip, options: true, false

**Comment by hd5970** [comment]
block by chrome extension

**Comment by rajkstats** [comment]
Hi @ppoffice, Thanks for the great theme. I am facing a similar issue like this at my personal website http://rajkstats.rbind.io/. It works fine in safari but not working on chrome, I tried running it in incognito mode too in chrome. Still no luck. Here is the website repo: https://github.com/rajkstats/rajkstats.rbind.io

**Comment by ppoffice** [comment]
@rajkstats I have no problem loading these icons from my PC and Android phone. It may due to the broken link to the FontAwesome CDN or browser caching problem. Please check that first.

**Comment by rajkstats** [comment]
I got it working. Thanks @ppoffice for your response.
