### ISSUE TITLE
请添加任务列表Markdown语法

### ISSUE THREAD

**Issue by hd5970** [ppoffice/hexo-theme-icarus#242]
- [ ] 任务二 已做任务 `- + 空格 + [x]`
- [ ] 任务一 未做任务 `- + 空格 + [ ]`

像上面的语法, icarus generate出来的页面是不支持的

**Comment by ppoffice** [comment]
@hd5970 这个不是Icarus的问题，Hexo中主题只负责页面布局和样式，并不负责markdown的渲染。Markdown的处理是Hexo主程序负责的，如果主程序可以显示radio或checkbox的话，生成的页面也应该会显示。

**Comment by ddabb** [comment]
参考 https://github.com/hexojs/hexo-renderer-marked
