### ISSUE TITLE
markdown blockquote不能渲染

### ISSUE THREAD

**Issue by Jabinzou** [ppoffice/hexo-theme-icarus#243]
您好：
   我的博客里面的markdown的blockquote不能渲染是怎么回事？只是出现一个逗号就像这样：
![2017-02-28_120157](https://cloud.githubusercontent.com/assets/14176629/23391155/d33b7cb8-fdad-11e6-9489-c331fa3fdedf.png)

**Comment by ppoffice** [comment]
@Jabinzou 这个主题里面blockquote的样式就是这样的……

**Comment by Jabinzou** [comment]
好的，谢谢！
