### ISSUE TITLE
如何让此主题支持 latex?

### ISSUE THREAD

**Issue by 941968215** [ppoffice/hexo-theme-icarus#244]
我谷歌了很多方法, 也尝试了很多主题, 发现在如 next主题等 config 文件中有 math 之类的选项的主题往往都能渲染成功(用 hexo-math 插件). 但是像 icarus 这样的 config 文件中没有 math 或 mathjax 选项即使自己加上去也依然无法渲染, 是不是还要装什么东西?

Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [ ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [ ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [ ] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

**Comment by ppoffice** [comment]
MathJax support added. Please refer to [this example](http://blog.zhangruipeng.me/hexo-theme-icarus/2016/07/08/MathJax-Example/) 😄

**Comment by cqlhupt** [comment]
The link of example cannot be open, would you please update it or give me some advices about the latex config. Thanks
