### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by tracy-e** [ppoffice/hexo-theme-icarus#245]
我想实现主页文章分页，归档列表显示全部文章怎么设置？
```
per_page: 10
```
通过上面的参数要分页都分页了，要不分页都没分页。我想单独控制可以吗？我看你的[博客](http://blog.zhangruipeng.me/hexo-theme-icarus/archives/)就实现了。

**Comment by ppoffice** [comment]
@tracy-e 
请参考这里
https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.yml#L62-L74

**Comment by tracy-e** [comment]
Thx
