### ISSUE TITLE
关于搜索功能

### ISSUE THREAD

**Issue by xieyezi** [ppoffice/hexo-theme-icarus#248]
你好，该安装的我都安装了，可是仍然不能使用搜索功能，这是怎么回事呢

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/wiki/Search#insight-search

**Comment by xieyezi** [comment]
谢谢指导，但是这些我都照做了，仍然没用呀，www.xieyezi.com

**Comment by xieyezi** [comment]
谢谢指导，但是这些我都照做了，仍然没用呀，www.xieyezi.com

**Comment by ppoffice** [comment]
@xieyezi 这一步你做了么

> Attention: You need to install `hexo-generator-json-content` before using Insight Search.

> ```
> $ npm install -S hexo-generator-json-content
> ```

**Comment by xieyezi** [comment]
安装了呀，还是不行

**Comment by xieyezi** [comment]
我回去再试一试吧，thank you

**Comment by ppoffice** [comment]
@xieyezi 你在本地测试的时候也是有问题么？

**Comment by xieyezi** [comment]
我在本地测试的时候也是不行的，但是事实上我已经安装了那个插件了。

**Comment by ppoffice** [comment]
@xieyezi 首先，我想请问下你运行`hexo generate`之后`public`目录下面有`content.json`文件么？其次，你的`hexo-generator-json-content`是安装在博客根目录（√）还是`theme/icarus`目录（×）下面呢？

**Comment by xieyezi** [comment]
我安装在hexo/themes/icarus目录下的

**Comment by xieyezi** [comment]
hexo g的时候确实没有生成content.json

**Comment by xieyezi** [comment]
但是我在hexo/目录下安装的时候它直接提示我已经安装了并且把版本号给我显示出来了

**Comment by xieyezi** [comment]
可以了可以了，真的麻烦你了。谢谢你与我分享这么好的主题
