### ISSUE TITLE
Attribute alt="" for banner images in the post

### ISSUE THREAD

**Issue by RomanBogachev** [ppoffice/hexo-theme-icarus#249]
Hi,

How I can do custom value in post to set alt attribute for embedded images?

**banner.ejs**
```
<a href="<%- url_for(post.link) %>" target="_blank" itemprop="url">
        <img src="<%- post.banner %>" class="article-banner" alt="some custom text"/>
    </a>
```

**Comment by ppoffice** [comment]
@RomanBogachev 
You cannot set alt text for banner images. But if you are talking about those in article body, you can do it by this:

```markdown
![](path/to/imge "alt text")
```

**Comment by RomanBogachev** [comment]
My banners with thumbnails are sets at front-matter. 
For example:

title:  MariaDB Galera Cluster
date: 2017-03-28 22:53:30
categories:
- Databases
- MariaDB
tags:
- mariadb
- mysql
- cluster
**banner: mariadb.png** 
**thumbnails: mariadb.png**

How I can set alt attribute  for them?

**Comment by ppoffice** [comment]
@RomanBogachev You can't unless you edit the https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/thumbnail.ejs and replace `<span>` tags with `<img>` tags, and add a front matter option for image alt text.
