### ISSUE TITLE
关于主页左侧个人信息栏

### ISSUE THREAD

**Issue by cuckootan** [ppoffice/hexo-theme-icarus#25]
博客设计得很好看，简洁而又高大上。个人觉得，如果能让左侧的个人信心栏，在往下流览post的时候，也能始终显示在屏幕的左侧就更赞了。

**Comment by ppoffice** [comment]
固定Profile侧边栏对于小屏幕平板不友好，因为横屏下侧栏高度大于屏幕高度，而在用户滚动时，如果固定侧栏位置，用户就会看不到侧栏下面的联系方式部分了。。。
