### ISSUE TITLE
关于自动截取一些文章内容自动添加readmore

### ISSUE THREAD

**Issue by SmallFatCYW** [ppoffice/hexo-theme-icarus#250]
您好，那个能不能添加一个功能，就是自动截取文章多少多少字作为首页文章的展示（这个主题就实现了https://github.com/Ben02/hexo-theme-Anatole）我喜欢这个主题，但无奈自己不会写JS写HTML，所以不能自己DIY了，所以希望您能加上这个功能，省了手打<! readmore>嘛谢谢
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [ ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [ ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [ ] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

**Comment by SmallFatCYW** [comment]
https://github.com/Ben02/hexo-theme-Anatole

**Comment by ppoffice** [comment]
Duplicate #187

**Comment by SmallFatCYW** [comment]
感谢: D
