### ISSUE TITLE
有没有可能实现由用户选择语言?

### ISSUE THREAD

**Issue by tuyunlei** [ppoffice/hexo-theme-icarus#251]
你好，非常感谢你做的这款主题，特别棒，请允许我提个建议。
我的意思是在主页面加个选择语言，浏览我的博客的用户可以选择不同的语言版本。
不同的语言版本的内容可以是照搬复制，也可以是一个新的网页，博文什么的都是自定义。
我是想能够开放给老外 😁

**Comment by ppoffice** [comment]
@tuyunlei 
你是说这个么：https://hexo.io/docs/permalinks.html#Multi-language-Support？

**Comment by tuyunlei** [comment]
好的  谢谢了!

**Comment by Aironoria** [comment]
想问一下这个 最终是通过输URL来切换语言的吗，是否可以达到hexo官网那种使用按钮来切换语言呢
