### ISSUE TITLE
請問能不能在文章後加入繼續閱讀的功能

### ISSUE THREAD

**Issue by racterub** [ppoffice/hexo-theme-icarus#254]
如題,大概就是在首頁的部分針對各文章只秀出文章前幾句,在加個繼續閱讀的按鈕,看要是直接展開或是連至文章連結,如果能實現的話首頁會乾淨些

**Comment by Problem233** [comment]
这个加个 `<!-- more -->` 不就行了吗

**Comment by ppoffice** [comment]
@Problem233 他指的应该是不用加载新页面，点击按钮后直接在首页读完全文。
