### ISSUE TITLE
有關格式問題

### ISSUE THREAD

**Issue by james50428** [ppoffice/hexo-theme-icarus#255]
我目前在建置about的頁面時發現一些小問題
不知道是不是我有打錯
![image](https://cloud.githubusercontent.com/assets/20561837/25857043/7020bfa0-350a-11e7-88d1-06c52dc1e300.png)

如照片所示,從經歷之後的標題似乎都多幾格了
但是在我源代碼中沒有任何縮排
請問是排版出錯還是是我的code有問題?

[源代碼](https://gist.github.com/james50428/3c8bc07571c75a2d954e29a749ead4e7)

**Comment by ppoffice** [comment]
@james50428 
列表和标题之间多加一个换行就可以了。
