### ISSUE TITLE
请问如何折叠首页下的每篇文章?

### ISSUE THREAD

**Issue by tuyunlei** [ppoffice/hexo-theme-icarus#256]
### 首页下的文章怎么才能只显示部分内容？而不是显示全部内容，点开`read more`再显示具体的内容。
![img](https://tuyunlei.coding.me/images/test1.png)
![img](https://tuyunlei.coding.me/images/test2.png)
### 可能由于我阅读不细致，并没有在wiki里找到这个选项，可否方便告知一下？

**Comment by wonderomg** [comment]
在文章中需要折叠处添加即可，文章是收缩了，但是我点击文章标题或查看更多按钮时，并没有跳转到该文章页，没有显示，但是浏览器地址栏地址确已经显示了该文章得地址，不知道是不是哪里我没配置好，看了所有issue和wiki也是没有找到问题所在

**Comment by wonderomg** [comment]
在文章中需要折叠处添加"\<!--more--\>"即可，文章是收缩了，
但是我点击文章标题或查看更多按钮时，并没有跳转到该文章页，
没有显示，但是浏览器地址栏地址确已经显示了该文章得地址，
不知道是不是哪里我没配置好，看了所有issue和wiki也是没有找到问题所在。

**Comment by wonderomg** [comment]
问题解决了，原来是`themes/icarus/layout/post.ejs`中
`<%- partial('_partial/article', {post: page, index: false}) %>`
没有`_partial`这个目录，`article.ejs`是在`common`目录下，改成`common`即可，即：
`<%- partial('common/article', {post: page, index: false}) %>`

**Comment by xiechuanyu** [comment]
到底如何折叠文章？

**Comment by qingjiexingli** [comment]
> 到底如何折叠文章？

我是在文章中添加  就可以了
