### ISSUE TITLE
accented chars not correcty render in search module

### ISSUE THREAD

**Issue by adelcourt** [ppoffice/hexo-theme-icarus#257]
Hi ,  we hace encountered a probleme with the accented in the search module, theirs not rendering  in the search preview ( it works for titles but not for content) 

![capturetheme](https://cloud.githubusercontent.com/assets/19473573/25954816/a761a822-3667-11e7-814a-a4cc1c29d02e.PNG)

**Comment by ppoffice** [comment]
@adelcourt Sorry for the late update. Insight search now can display HTML entities in article or page descriptions.
