### ISSUE TITLE
AMP- Accelerated Mobile Project Support

### ISSUE THREAD

**Issue by iamchathu** [ppoffice/hexo-theme-icarus#267]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

AMP is to serve static content to mobile devices to load sites faster. You can get more information on the (site)[https://www.ampproject.org/].

Can the theme give support to rendering AMP pages like the theme? I found a Hexo generator to do this. https://github.com/tea3/hexo-generator-amp

**Comment by veramartins** [comment]
It would be a nice feature. I tried adding it to my site as per AMP generator instructions, but couldn't do it.

**Comment by ppoffice** [comment]
I'm closing this now since AMP is out of the scope of this project.
