### ISSUE TITLE
ppoffice大哥您好，关于页面渲染错误的问题

### ISSUE THREAD

**Issue by dragon-yuan** [ppoffice/hexo-theme-icarus#268]
ppoffice大哥您好，我使用您这个icarus模版已有数月了，请问在hexo d -g后，总是会造成错误渲染页面，需要多次clean d-g 请问这个原因您知道有什么解决方案嘛，谢谢

**Comment by ppoffice** [comment]
@dragon-yuan 有错误提示的Log么？可以贴出来

**Comment by dragon-yuan** [comment]
没有报什么错误，除了一个The page build completed successfully, but returned the following warning for the `master` branch:You are attempting to use a Jekyll theme, "hexo-theme-icarus", which is not supported by GitHub Pages. 
还有就是渲染出来的错误页面是这个样子：
http://wiki.dragon-yuan.me/1.jpg

**Comment by tiexo** [comment]
这个问题很多人遇到过，还没搜索到统一的解决办法
其他人好像都是重装解决的

**Comment by ppoffice** [comment]
@dragon-yuan 你需要在根_config.yml中指定语言

**Comment by dragon-yuan** [comment]
@ppoffice 好的，那我先去试试，谢谢大哥。
@tiexo 我先去试下，好用告诉您

**Comment by dragon-yuan** [comment]
可以了老哥！感谢感谢！@ppoffice 哎呀，大神就是不一样，笔芯笔芯笔芯！
