### ISSUE TITLE
All resource links are generated with absolute urls which may cause failing to load resource

### ISSUE THREAD

**Issue by juliansxw** [ppoffice/hexo-theme-icarus#269]
As the domain is dynamic, using absolute url for resource may lead to some issues;
For example, I've used enterprise github and GitHub Pages give this url for the site: **https://xxx.github.com/pages/julzhu/blog-lisv2/**

See this html generated: **\<link rel="stylesheet" href="/libs/font-awesome/css/font-awesome.min.css"\>**

With absolute path "/libs/font-awesome/css/font-awesome.min.css", the request will be resolved as:
**https://xxx.github.com//libs/font-awesome/css/font-awesome.min.css**. This should be wrong point.

The right one is like "https://xxx.github.com/**pages/julzhu/blog-lisv2**/libs/font-awesome/css/font-awesome.min.css" which relative path help resolve: 
**\<link rel="stylesheet" href="libs/font-awesome/css/font-awesome.min.css"\>** without  "/" as begin

**Comment by ppoffice** [comment]
@juliansxw This theme uses the Hexo helper function `css()` and `js()` to generate **absolute/relative** URL to the asset files. All you need to do is set proper values to the `root` option and `false` to the `relative_link` option for different subdomains or subdirectories.

Code references:

- https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/head.ejs#L40-L46
- https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/css.js
- https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/url_for.js

**Comment by juliansxw** [comment]
@ppoffice I've updated the `root` from `/` to `/pages/julzhu/blog-lisv2` and it works well. 

Appreciate your great work! BTW, is that more flexible to use relative URL in the default as users need not to update the `_config.yml` manually?

Thanks

**Comment by ppoffice** [comment]
@juliansxw You can try to edit the Hexo source code, make the `url_for` or other equivalent functions return different root under various occasions.
