### ISSUE TITLE
想问一下有关评论的问题

### ISSUE THREAD

**Issue by dgwzq** [ppoffice/hexo-theme-icarus#270]
我用的是YouYan评论，注册了帐号，找到了帐号ID，修改了主题配置文件
修改如下：
# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: 2140719 # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan: # please fill in `appid` and `conf` to enable
        appid:
        conf:
    gitment:
        owner: #your github ID
        repo: #the repo to store comments
        #Register an OAuth application, and you will get a client ID and a client secret.
        client_id: #your client ID
        client_secret: #your client secret

现在的情况是用不了，点击品论进入502页面。我想问一下我是缺少了步骤？还是别的问题？

**Comment by ppoffice** [comment]
@dgwzq 根_config.yml中的yoursite.com是不是没有替换成自己的域名

**Comment by dgwzq** [comment]
是的，没有改。不是很理解这个地方的作用，什么时候要改，之前没修改这里貌似其他功能不影响。
现在改成了这个
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://dgwzq.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
和
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://dgwzq.com/child
root: /child/
permalink: :year/:month/:day/:title/
permalink_defaults:

两种都试过，也是不行，不知道为什么跳转的地方还是叫yoursite.com

**Comment by dgwzq** [comment]
重新布置了一下，用前面那种成功了 (＝^ω^＝) 非常感谢！！！然后还是希望能帮忙解释一下这处修改的作用，不是很懂，谢谢了
