### ISSUE TITLE
怎么让文章图片不可点击？

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#272]
我想让文章内的图片变成不可点击，就跟banner一样
我尝试取消灯箱效果，依然可以点击，只不过变成新标签打开图片了...

这个可以实现吗？万分感谢！

**Comment by ppoffice** [comment]
@tiexo https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/thumbnail.ejs
你试试<a>换成<span>然后删掉href

**Comment by tiexo** [comment]
啊，没看懂，是不是漏了什么？

**Comment by tiexo** [comment]
发现图片点击放大还是有用的...这个需求作废了。

另外提点小意见，lightgallery插件感觉没有之前的fancybox好，主要是视觉体验吧
虽然功能丰富了很多，全屏纯黑的背景和主题简约留白风格不搭。
