### ISSUE TITLE
[gitment]点击展开全文和点击文章title进入文章页面会初始化2次评论，分别会创建不同的issue

### ISSUE THREAD

**Issue by MofiU** [ppoffice/hexo-theme-icarus#281]
这是点击`文章title`发出的请求
`Request URL:https://api.github.com/repos/name/name.github.io/issues?creator=name&labels=https%3A%2F%2Fname.github.io%2F2017%2F10%2F25%2Fgitment-in-hexo%2F`

这是点击`查看更多`发出的请求
`Request URL:https://api.github.com/repos/name/name.github.io/issues?creator=name&labels=https%3A%2F%2Fname.github.io%2F2017%2F10%2F25%2Fgitment-in-hexo%2F%23more`

然后在配置的repo页面会创建2个不同的issue，这是我个人的配置问题还是BUG呢。

**Comment by tiexo** [comment]
是gitment的问题，但可以通过自己修改配置来解决
layout/comment/gitment.ejs里面添加一条代码：
`id: window.location.pathname,`
放在repo后面就行

**Comment by MofiU** [comment]
Much thanks, it works for me !

**Comment by cwc845982120** [comment]
@ppoffice @tiexo 请问如何解决每次发布 都要把全部文章都重新初始化评论的问题 不然好麻烦啊

**Comment by tiexo** [comment]
@cwc845982120 没遇到过你这个问题，应该是你某个地方设置错了吧。
推荐你换gitalk这个项目，兼容性要好很多
