### ISSUE TITLE
您好，请问我怎么设置首页每条数据显示多少字啊

### ISSUE THREAD

**Issue by zhaoyunxing92** [ppoffice/hexo-theme-icarus#284]
我首页显示的是我一个文字的全部字，我想只显示一部分字，点击的时候获取详情

**Comment by tiexo** [comment]
在需要显示的摘要后面添加`<!--more-->`标签

**Comment by zhaoyunxing92** [comment]
这样的话我要在每一篇里面都要添加这个标签了，我是后来修改了源码

**Comment by WhenCoding** [comment]
> 这样的话我要在每一篇里面都要添加这个标签了，我是后来修改了源码

能否告知如何修改源码？
