### ISSUE TITLE
文章中目录无法使用

### ISSUE THREAD

**Issue by caoler** [ppoffice/hexo-theme-icarus#286]
点击目录链接，无法正确定位
xxx.com/blog/title_name#undefined
link-toc 为#undefined
本应该为
xxx.com/blog/title_name#标题

**Comment by strongduanmu** [comment]
我也是同样问题，解决了吗？大兄弟

**Comment by caoler** [comment]
@strongduanmu   没解决，你要是解决了 记得提醒我一下，感谢！

**Comment by ppoffice** [comment]
@caoler 请提供使用的Hexo版本以及相关文章的markdown文件

**Comment by caoler** [comment]
@ppoffice 

$ hexo -version
hexo: 3.4.0
hexo-cli: 1.0.4
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 8.9.0
v8: 6.1.534.46
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

markdown内容：http://note.youdao.com/noteshare?id=f5c03c79b7eb5d6995399bf69ceff34e&sub=0F7BB6F31DA14D0C83BB9B7B32781577


[演示链接](http://caoler.cn/blog/2017/目录测试.html)

**Comment by ppoffice** [comment]
@caoler 可以列出您的博客根目录下的package.json文件么？

**Comment by caoler** [comment]
@ppoffice 

{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.4.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-deployer-heroku": "^0.1.2",
    "hexo-deployer-openshift": "^0.1.2",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.2.11",
    "hexo-renderer-stylus": "^0.2.3",
    "hexo-server": "^0.2.2",
    "hexo-toc": "^1.1.0"
  }
}

**Comment by ppoffice** [comment]
@caoler 你所使用的hexo-toc插件所引用的markdown-toc库的slugify函数存在问题，与本主题甚至Hexo无关。请联系相关开发者进行反馈或者使用Hexo内置的toc函数。

**Comment by caoler** [comment]
@ppoffice  删除了hexo-toc插件之后，目录正常了！感谢！！

**Comment by strongduanmu** [comment]
感谢啊

**Comment by imdreamer2018** [comment]
感谢感谢！
