### ISSUE TITLE
移动端屏蔽最新文章 tags那些乱七八糟的东西

### ISSUE THREAD

**Issue by caoler** [ppoffice/hexo-theme-icarus#289]
#12 中说的 mobile.styl 不存在
求解决方案。

**Comment by ppoffice** [comment]
@caoler https://github.com/ppoffice/hexo-theme-icarus/blob/master/_config.yml.example#L25 此处留空

**Comment by caoler** [comment]
@ppoffice  我说的是移动端，如果此处留空，PC端也会消失呀

**Comment by ppoffice** [comment]
请自行修改styl文件

**Comment by caoler** [comment]
@ppoffice 有详细一点的教程吗
