### ISSUE TITLE
Make the main-nav collapsible on small devices

### ISSUE THREAD

**Issue by andreagattironi** [ppoffice/hexo-theme-icarus#290]
Hi, I'm trying to get the main-nav menu to act like a classic collapsible menu on small devices, but I'm kinda new to all this...

Is there an easy way to change this?

Thanks a lot!

**Comment by ppoffice** [comment]
@andreagattironi There's no built-in collapse menu for Icarus. You may need to edit layout, style and script files to achieve that.
