### ISSUE TITLE
有没有办法点击文章标题的时候外链到另一个地址？

### ISSUE THREAD

**Issue by xiaoouwang** [ppoffice/hexo-theme-icarus#296]
在有些主题里有这个功能，不知icarus行不行呀

**Comment by ppoffice** [comment]
@xiaoouwang 没有这个功能

**Comment by orcmid** [comment]
Do you mean to have a different link in the title?

Is it this function (demonstrated with `landscape` theme)?   http://orcmid.com/BlunderDome/wingnut/2017/12/07/Link/

My thinking is that this function is confusing to users.  

[谷歌翻译]

你的意思是在标题中有不同的链接？

这个功能（用“景观”主题来演示）吗？http://orcmid.com/BlunderDome/wingnut/2017/12/07/Link/

我的想法是，这个功能令用户感到困惑。

**Comment by xiaoouwang** [comment]
absolutely ! I find it very useful :))
