### ISSUE TITLE
The link for justified gallary is not right in the wiki section

### ISSUE THREAD

**Issue by Logan1x** [ppoffice/hexo-theme-icarus#298]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

in the theme docs, the link for justified gallery plugin is wrong it should be [this](https://miromannino.github.io/Justified-Gallery/) instead of [this](https://sachinchoolur.github.io/lightgallery.js/) you can see the link to docs below
https://github.com/ppoffice/hexo-theme-icarus/wiki/Plugins#justified-gallery

**Comment by Logan1x** [comment]
can we edit the wiki locally by cloning the repo and then send a PR? @ppoffice

**Comment by ppoffice** [comment]
@Logan1x Yes, of course.

**Comment by Logan1x** [comment]
@ppoffice the bug is solved, I am closing this issue.
