### ISSUE TITLE
关于Java代码高亮的问题

### ISSUE THREAD

**Issue by RobertoHuang** [ppoffice/hexo-theme-icarus#299]
我在配置文件中配置了 highlight: androidstudio
![b](https://user-images.githubusercontent.com/20842825/34332546-b0a2aa7c-e96c-11e7-9d14-0030e6590959.png)

在配置生效后 我发现我的Java代码并没有高亮 请问是为什么
![a](https://user-images.githubusercontent.com/20842825/34332547-b2f772f8-e96c-11e7-98da-5e35aae8f529.png)

**Comment by ppoffice** [comment]
@RobertoHuang https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by RobertoHuang** [comment]
感谢~
