### ISSUE TITLE
Modify spaces between paragraphs.

### ISSUE THREAD

**Issue by Majirefy** [ppoffice/hexo-theme-icarus#3]
I noticed when it comes with lots of lines in posts, a 1.5x space between each paragraph will be better?
![screen shot 2015-03-30 at 2 30 09 am](https://cloud.githubusercontent.com/assets/3023607/6886978/ba12ec50-d684-11e4-824e-26d810f39472.png)

**Comment by ppoffice** [comment]
I suppose you don't break the line after the code block, so the line-height property doesn't apply to the following paragraph.

**Comment by Majirefy** [comment]
@ppoffice Sorry, I didn't make it clear.
![screen shot 2015-03-30 at 5 35 50 pm](https://cloud.githubusercontent.com/assets/3023607/6893936/96bec3f8-d703-11e4-9784-727c05102b96.png)
In the screenshot, the spaces between each paragraph is much bigger than spaces of each line. Is it possible to modify any file to achieve like that?

**Comment by ppoffice** [comment]
I'll deal with that.
