### ISSUE TITLE
配置gitment之后文章中的“评论”按钮消失

### ISSUE THREAD

**Issue by wonderomg** [ppoffice/hexo-theme-icarus#300]
你好，有没有icarus配置Gitment的教程

**Comment by tiexo** [comment]
主题已经适配了gitment，直接在config里面填写参数就行了啊

**Comment by wonderomg** [comment]
@tiexo 是很早就适配了麽？我去年的版本，我配置了无效，难道和Disqus冲突了?

**Comment by tiexo** [comment]
你看下layout/comment里面有没有gitment.ejs



 
发件人： Lewis
发送时间： 2018-01-18 11:57
收件人： ppoffice/hexo-theme-icarus
抄送： 唐门; Mention
主题： Re: [ppoffice/hexo-theme-icarus] 你好，有没有配置Gitment的教程 (#300)
@tiexo 是很早就适配了麽？我去年的版本，我配置了无效，难道和Disqus冲突了?
―

**Comment by wonderomg** [comment]
layout/comment里面没有gitment.ejs，有其他的changyan、disqus、duoshuo、youyan等ejs

**Comment by tiexo** [comment]
@wonderomg 额，那你把主题更新到最新版就有了。

**Comment by wonderomg** [comment]
@tiexo ok,thanks.

**Comment by wonderomg** [comment]
@tiexo @ppoffice 为何使用Disqus评论时文章右下角分享按钮旁边有“评论”或“comments”的按钮，而使用gitment评论系统时文章右下角分享按钮旁边的“评论”或“comments”按钮确消失了？

**Comment by levin950825** [comment]
我点 `initialize comments` 会报错 ，利用谷歌浏览器发现有 422 (Unprocessable Entity)
