### ISSUE TITLE
请问怎么在主题中配置leancloud 进行访问量统计？

### ISSUE THREAD

**Issue by xqtbox** [ppoffice/hexo-theme-icarus#304]
请问怎么在主题中配置leancloud 进行访问量统计？

**Comment by ppoffice** [comment]
@xqtbox 请参考https://github.com/ppoffice/hexo-theme-icarus/blob/3e66b25aaa06d3147991e165abc7ee64ea44c9ce/_config.yml.example#L68-L74

**Comment by xqtbox** [comment]
valine是一个评论系统啊。请问有简洁的方法统计文章“访问量”吗？

**Comment by ppoffice** [comment]
@xqtbox 那就需要自己修改layout文件了。你可以看下 https://github.com/ppoffice/hexo-theme-icarus/tree/master/layout 这个文件夹下面的文件。

**Comment by xqtbox** [comment]
thanks
