### ISSUE TITLE
Disable archive and archive pages generation

### ISSUE THREAD

**Issue by Ivantiger** [ppoffice/hexo-theme-icarus#305]
How to disable archive and archives pages generation?

Thank you.

**Comment by ppoffice** [comment]
@Ivantiger Maybe you can try to delete this line in your blog's `package.json`: https://github.com/ppoffice/hexo-theme-icarus/blob/site/package.json#L11

**Comment by Ivantiger** [comment]
Ok, thank you very much. Please inform, i create test 10 000 post, not generate site, what problem?
