### ISSUE TITLE
How do i use Custom font?

### ISSUE THREAD

**Issue by sskim91** [ppoffice/hexo-theme-icarus#307]
First, Thank you for creating this theme 
I would like to use Custom fonts for this theme.
Do I need to edit this file?  source/css/_variables.styl

ps. Is OpenSans currently in use for this theme?

**Comment by ppoffice** [comment]
First, you need to copy your font files here:
https://github.com/ppoffice/hexo-theme-icarus/tree/master/source/libs

Then, you should add a reference in the layout file
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/head.ejs#L41

Finally, don't forget to set it as your default font in the stylesheet
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/_variables.styl#L17-L19

**Comment by devillove084** [comment]
Now what should I do if I want to customize the font?
