### ISSUE TITLE
Can I folk this repository and translate it to Korean?

### ISSUE THREAD

**Issue by Blinders** [ppoffice/hexo-theme-icarus#308]
I used this hexo theme.
It seems too good.
So, I want to translate for the other korean(readme.md and code annotation)
And maybe, i need to edit css code. For example header position fixed, mobile reactive padding value, etc.
Of course all this work will be done in my folk repository.
Maybe, If you do not mind, I might be able to create a pull request about edited css.

------------
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [ ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [ ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [ ] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

**Comment by ppoffice** [comment]
@Blinders You can fork this repo and create a flavor of this theme. I think the pull request is not needed because you are going to change a lot of styles.

**Comment by Blinders** [comment]
Thank you for reply!
