### ISSUE TITLE
楼主，请问在文章列表页中头部都显示了图片是怎么设置的？包括打开文章之后头部也是图片

### ISSUE THREAD

**Issue by WinterChenS** [ppoffice/hexo-theme-icarus#309]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [x] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [x] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [x] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

**Comment by chaunceyzhangx** [comment]
同问。

**Comment by WinterChenS** [comment]
我知道怎么弄了
```
thumbnail: http://blog.zhangruipeng.me/hexo-theme-icarus/gallery/snow-wolf.jpg
banner: http://blog.zhangruipeng.me/hexo-theme-icarus/gallery/snow-wolf.jpg
toc: true
```

**Comment by chaunceyzhangx** [comment]
多谢楼上朋友。

**Comment by chaunceyzhangx** [comment]
toc：true可不需要
