### ISSUE TITLE
您好，我有两个疑问：

### ISSUE THREAD

**Issue by vzcoso** [ppoffice/hexo-theme-icarus#310]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [x] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [x] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [x] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

1、搜索的图标的初始颜色是否能够更改？
![search](https://user-images.githubusercontent.com/37802671/38068106-e884c8b6-3341-11e8-8b3c-1bbb4fb4abcb.png)
2、搜索分类或者标签的时候，会跳往另一个网站，怎样避免？
![searchurl](https://user-images.githubusercontent.com/37802671/38068156-45dd7684-3342-11e8-83fc-785c1af82aea.png)

**Comment by ppoffice** [comment]
@vzcoso https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.yml#L16

**Comment by vzcoso** [comment]
@ppoffice
1、非常谢谢您解答第2个问题，关于第2个问题，最终我只改了红色的那一行，问题完美的解决了；因为我继续更改绿色的那一行，网页就会出现格式乱码 （线上和线下我都测试了，也清理了缓存），不知为什么会出现这样的问题。
![bug](https://user-images.githubusercontent.com/37802671/38078963-69e8b6be-3370-11e8-810c-8a1d32b494c7.png)
2、关于第1个问题，我原计划想达到，搜索图标开始为白色，鼠标hover 或者 focus的时候显示深灰色，但是我无法同时配置两种颜色的，只能配置一种，希望您可以解答一下哈。
![searchcolor](https://user-images.githubusercontent.com/37802671/38079238-01694954-3371-11e8-9e52-8c2102032590.png)

**Comment by ppoffice** [comment]
@vzcoso `&:before` 上面添加`color: white`

**Comment by vzcoso** [comment]
不成功，页面会崩溃
![color](https://user-images.githubusercontent.com/37802671/38094389-2e65fd38-33a0-11e8-9cb9-d505260213ba.png)

**Comment by ppoffice** [comment]
@vzcoso 前面，不是里面。另外你尝试下重启hexo能不能解决样式表无法加载的问题。
```stylus
.search-form-submit
    ...
    color: white
    &:before
        ...
```

**Comment by vzcoso** [comment]
您好，图标会消失。
![dispear](https://user-images.githubusercontent.com/37802671/38095406-fd4a7f5a-33a2-11e8-8b25-4081cdcd8a7b.png)

**Comment by ppoffice** [comment]
@vzcoso 抱歉，应该还是要放在`&:before`里面的

**Comment by vzcoso** [comment]
非常感谢您的解答，主题很棒哈！！谢谢~
