### ISSUE TITLE
您好，有个问题想请教下您。

### ISSUE THREAD

**Issue by chaunceyzhangx** [ppoffice/hexo-theme-icarus#311]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [x] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [x] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [x] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

**Comment by chaunceyzhangx** [comment]
就是关于图片的问题：我本地source/_post下存放我的markdown文件，然后source/images存放图片，打开博客首页直接阅读我的博客的话，可以看到图片，但是通过标签或者分类查找后看的话，图片就加载不出来了，请问这是怎么回事呢？

**Comment by ppoffice** [comment]
@chaunceyzhangx 请用图片的绝对路径

**Comment by chaunceyzhangx** [comment]
我用了github图片地址的绝对路径，还是不行哎，本地的绝对路径更不行。tag文件夹跟images文件夹在本地是属于同一层的。

**Comment by chaunceyzhangx** [comment]
![xrhx1bas j5 mfg xn 0y](https://user-images.githubusercontent.com/26669500/38159426-39431a92-34db-11e8-8d42-31da22a14de9.png)
![ncjzbw8l0bxwwd0 bi74t8q](https://user-images.githubusercontent.com/26669500/38159428-3c662d40-34db-11e8-85fb-65ab664ee6ee.png)
上面是相对路径，下面是绝对
@ppoffice

**Comment by ppoffice** [comment]
@chaunceyzhangx 请试下`/images/UML.jpg`

**Comment by chaunceyzhangx** [comment]
@ppoffice 谢谢您，解决了！请问这是什么原因呢？../不是表示先退到上一层吗？

**Comment by ppoffice** [comment]
@chaunceyzhangx 我不太清楚你本地是如何测试的。你是用
```
hexo s
```
测试的么？

**Comment by chaunceyzhangx** [comment]
@ppoffice 是的，然后用hexo d 同步上去

**Comment by ppoffice** [comment]
@chaunceyzhangx 可能是多种原因引起的本地测试图片不显示问题，建议你排查一下hexo的配置是否正确，另外确认下安装的hexo不是过于陈旧的版本。这个问题与主题无关。

**Comment by chaunceyzhangx** [comment]
@ppoffice 好的，谢谢您的耐心解答。
