### ISSUE TITLE
关于主题会弹广告的问题

### ISSUE THREAD

**Issue by WinterChenS** [ppoffice/hexo-theme-icarus#313]
博主，你好，在使用主题的过程中发现了一个问题：
在一个时间区间内，进入博客会在主页弹出一个新闻视窗，暂时也没有找到原因，请问如果去定位这个问题呢，这个新闻网站为：http://sh.qihoo.com/

**Comment by ppoffice** [comment]
@WinterChenS 可能是运营商劫持，与本主题或者hexo无关
