### ISSUE TITLE
Post names cyrillic to translit 

### ISSUE THREAD

**Issue by RomanBogachev** [ppoffice/hexo-theme-icarus#315]
Hi, 

How I can make translate cyrillic text of my post name to translate?

e.g.

mydomain.com/%D0%9A%D0%B0%D0%BA-%D0%B8%D0%B7%D0%BC%D0%B5%D1%80%D0%B8%D1%82%D1%8C-IOPS/

to mydomain.com/kak-izmerit-IOPS/

I found converter https://github.com/greybax/cyrillic-to-translit-js

**Comment by ppoffice** [comment]
@RomanBogachev This is done inside the Hexo engine. You may want to take a look at this: https://hexo.io/docs/permalinks.html

**Comment by RomanBogachev** [comment]
@ppoffice It doesnt work. 

```
permalink: :year/:month/:day/:title/
permalink_defaults:
	lang: en
```

```
hexo new post "ТЕКСТ_НА_РУССКОМ_ЯЗЫКЕ"    <<<---- _HERE_TEXT_ON_RUSSIAN_
INFO  Created: ../public_html/source/_posts/ТЕКСТ_НА_РУССКОМ_ЯЗЫКЕ.md
```

Go to site and nothing happens. 
https://example.com/2018/04/12/%D0%A2%D0%95%D0%9A%D0%A1%D0%A2-%D0%9D%D0%90-%D0%A0%D0%A3%D0%A1%D0%A1%D0%9A%D0%9E%D0%9C-%D0%AF%D0%97%D0%AB%D0%9A%D0%95/

Text doesn't translit from russian. 

I want to see https://example.com/2018/04/12/tekst_na_russkom_yazike

It is need me for SEO.

**Comment by ppoffice** [comment]
How about you create posts using translit? Hexo does not have the ability to translate cyrillic to translit, and it uses the filename to generate the slug.

**Comment by RomanBogachev** [comment]
@ppoffice If I will create messages in translit, then the title will also be in translit. The task is to have the title in russian, but in the link to the transliteration. A long time ago this decision was implemented on the Octopress.

**Comment by RomanBogachev** [comment]
@ppoffice That's straight right there.
https://github.com/hexojs/hexo/issues/506
https://github.com/hexojs/hexo/issues/1479

**Comment by ppoffice** [comment]
@RomanBogachev You can still use Russian title if you set it in the front-matter.

```yaml
title: ТЕКСТ НА РУССКОМ ЯЗЫКЕ
```

**Comment by RomanBogachev** [comment]
@ppoffice =) 
The problems are not in `title:`

I need `title: Заголовок на русском` and URL: `https://example.com/zagolovok-na-russkom`

**Comment by ppoffice** [comment]
@RomanBogachev Try to create a file named `zagolovok-na-russkom.md` and put `title: Заголовок на русском` in it. You will see what I mean.

**Comment by RomanBogachev** [comment]
@ppoffice This is a way out. But I would like to automate this process.
Thank you.

**Comment by dailyrandomphoto** [comment]
@RomanBogachev 
This plugin may help you.

```sh
npm install hexo-unique-post-path

hexo new "Заголовок на русском" --type=latin
=> INFO  Created: ... /source/_posts/zagolovok-na-russkom.md
```

With configuration:
```diff
#_cofig.yml

+ unique_post_path:
+   type: latin
+   auto: true
```

```sh
hexo new "Заголовок на русском"
=> INFO  Created: ... /source/_posts/zagolovok-na-russkom.md

hexo new "ТЕКСТ_НА_РУССКОМ_ЯЗЫКЕ"
=> INFO  Created: ... /source/_posts/tekst_na_russkom_yazyke.md
```

More usage: https://github.com/dailyrandomphoto/hexo-unique-post-path/issues/14
