### ISSUE TITLE
评论相关

### ISSUE THREAD

**Issue by levin950825** [ppoffice/hexo-theme-icarus#317]
icarus 是否有提供`gitment` 相关的文档

**Comment by levin950825** [comment]
点击 `initialize comments` 会报错  `Error: Validation Failed`，谷歌浏览器有 422 (Unprocessable Entity)

**Comment by ppoffice** [comment]
@levin950825 https://github.com/imsun/gitment/issues/116

**Comment by ppoffice** [comment]
@ericzhng https://github.com/ppoffice/hexo-theme-icarus/issues/330
