### ISSUE TITLE
RSS按钮不可用

### ISSUE THREAD

**Issue by yutiya** [ppoffice/hexo-theme-icarus#32]
你好，RSS订阅不可用，只能选择关闭该功能，可以解决吗？谢谢

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-minos/issues/10

**Comment by yutiya** [comment]
你好，为什么clone下来的主题，按照步骤操作后，响应式布局会出问题?

**Comment by ppoffice** [comment]
_config.yml没有重命名或者没有配置好，请仔细阅读readme

**Comment by yutiya** [comment]
```
###Responsive Layout

Icarus knows on what screen size you are browsering the website, and reorganize the layout to fit your device.
```

关于自适应浏览器尺寸的就这一句，我直接clone的主题，重命名主题里的_config.yml.example，使用_config.yml.site.example替换了site的_config.yml，本地运行，自适应就会出现问题，等我上图
![1](https://cloud.githubusercontent.com/assets/12824969/8848277/977eeb14-3168-11e5-9fad-a930f1685bfd.png)

**Comment by ppoffice** [comment]
抱歉，这个确实是我这边的问题，现已提交修改

**Comment by yutiya** [comment]
测试后没问题了，谢谢
顺便问一下，styl 样式都是用的什么语法？ejs 是nodejs？想自学改改主题，谢谢

**Comment by ppoffice** [comment]
stylus
