### ISSUE TITLE
banner 和 thumnail 引用本地图片首页能显示，但是点进文章内部引用出错

### ISSUE THREAD

**Issue by HtPsi** [ppoffice/hexo-theme-icarus#321]
如题，banner引用本地图片 如
```
banner: css/images/salt-lake.jpg
thumbnail: css/images/salt-lake.jpg
```
首页能显示，但是点进文章内部无法显示
![22](https://user-images.githubusercontent.com/30772228/39769115-d62abe18-531d-11e8-8b23-77b664366618.JPG)
![222](https://user-images.githubusercontent.com/30772228/39769121-d97c76a6-531d-11e8-9326-f40f78d0117d.JPG)
![2222](https://user-images.githubusercontent.com/30772228/39769126-dd043ce6-531d-11e8-936d-44b1bd41360d.JPG)
![2](https://user-images.githubusercontent.com/30772228/39768833-fe789c88-531c-11e8-8f29-6a81b5b7bcd3.JPG)
但是如果引用网络地址 则一切正常

**Comment by HtPsi** [comment]
@ppoffice  多谢啦！
问题解决，请大家务必不要把图片放入红色的主题内部css样式文件夹中，而是把图片放入蓝色的

source中的images文件夹中，并且使用路径
```
/images/xxx.jpg
```
如图

![1111](https://user-images.githubusercontent.com/30772228/39794317-4a539e8c-537c-11e8-842d-338cbd8d27c8.JPG)

**Comment by ericzhng** [comment]
The widget recent_post thumbnail images won't show up correctly.

If I specify the path for the thumbnail to be /images/tensorflow.jpg. But if I use images/tensorflow.jpg, it will show up, but only on homepage, not when I jumped into a certain post or any other pages.

Could you help me on this?

**Comment by ppoffice** [comment]
@ericzhng Please using the image paths that are relative to your website's root directory. Or you can simply use the absolute path of your image.

**Comment by ericzhng** [comment]
@ppoffice I figured out that if I use absolute path, it works well. If using relative path such as images/tensorflow.jpg, it only works for home page. But thanks for replying. Icarus is a nice theme for hexo, I like this very much.
