### ISSUE TITLE
Tags page tagcloud 显示问题

### ISSUE THREAD

**Issue by oushiun** [ppoffice/hexo-theme-icarus#322]
tags.ejs 中有设置 min & max fontsize，
``` ejs
<%- tagcloud({min_font: 14, max_font: 28}) %>
```
生成出来的页面 tags 全部都是 font-size: 14px;

问题重现地址: [Tags | oushiun](https://www.oushiun.com/tags/)

**Comment by HtPsi** [comment]
@oushiun 
tags标签的大小应该是跟想关联文章数量相关的 我看你每个tag都只有一篇文章 你试下用同一个tag多发几篇文章试试

**Comment by oushiun** [comment]
@HtPsi  应该是这样的问题. 我先关闭Issues ☕️
