### ISSUE TITLE
The the format for a new page?

### ISSUE THREAD

**Issue by fish98** [ppoffice/hexo-theme-icarus#323]
Hello, I have a simple demand here.
I'd like to show a new page with a lot of posts like those in the _post dir, which means that the new page dir can contain many posts, and of course, It can show as in the index page. I suppose the format for the default _post dir is "post dir"?
For example, when I enter into a page like "share". All the post in the dir "share" can be rendered while other posts in the _post will not be shown~~ 
However, It seems hard to find the correct .ejs file to fix. And to rewrite a new theme can be dull.
So, can you tell me where to configure the problem? Thank you very much~~
[My Website](http://ttfish.top)

**Comment by ppoffice** [comment]
@fish98 You need to tweak a lot of ejs to make this happen. Please refer to the Hexo official document for API documentation and instructions.

**Comment by fish98** [comment]
OKay, Hope I can find a convenient way t o solve it out ~
