### ISSUE TITLE
提点小意见

### ISSUE THREAD

**Issue by note4** [ppoffice/hexo-theme-icarus#329]
其实已经很完美了，如果:

## 代码处理不完整
超出不见了
![_20180609164030](https://user-images.githubusercontent.com/6513389/41189653-ec73cd50-6c03-11e8-9375-f26e488e77ee.png)

## 文章部分
material-flow 
gan jue ke yi jie jian zhe ge zhu ti

**Comment by ppoffice** [comment]
@note4 https://help.github.com/articles/creating-and-highlighting-code-blocks/

你用的应该是inline code block，不适合于单行比较长的代码或者多行代码块。

**Comment by note4** [comment]
没有修改主题的代码样式和使用其他高亮插件

**Comment by ppoffice** [comment]
@note4 https://github.com/ppoffice/hexo-theme-icarus/wiki/Theme#highlight
主题的各种配置请参阅wiki
