### ISSUE TITLE
如何在markdown里面表示分类的子目录？

### ISSUE THREAD

**Issue by xiao7462** [ppoffice/hexo-theme-icarus#332]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [1 ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [1 ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [1] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

请问如何在目录下建个子目录？
比如
`
---
Categories: 
    - 大目录
    - 小目录
 ---
`

**Comment by ppoffice** [comment]
@xiao7462 https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/site/source/_posts/Markdown.md

**Comment by xiao7462** [comment]
3qqq

**Comment by jaclon-m** [comment]
这个页面找不到了，能不能再给个提示？
