### ISSUE TITLE
渲染mardown页面显示乱码

### ISSUE THREAD

**Issue by summerHearts** [ppoffice/hexo-theme-icarus#334]
![](http://ovsiiuil2.bkt.clouddn.com/Xnip2018-06-179_09-30-33.png)
添加进入post之后重启服务。发现页面是如下效果

![](http://ovsiiuil2.bkt.clouddn.com/Xnip2018-06-179_09-32-12.png)

搜了没发现有类似问题，能帮忙看一下嘛，谢谢

so,文章部分也会出现这种情况

![](http://ovsiiuil2.bkt.clouddn.com/Xnip2018-06-179_10-01-56.png)

![](http://ovsiiuil2.bkt.clouddn.com/Xnip2018-06-179_10-01-41.png)

**Comment by ppoffice** [comment]
@summerHearts 可以请你把出问题的文章源文件发一下么？另外请检查下文件的编码是否有问题。

**Comment by summerHearts** [comment]
https://github.com/summerHearts/MySQL/blob/master/MySQL事务.md     其他文件不会又问题，或者是我使用  MWeb编辑器的缘故？ 但是我用其他的Markdown也是一样
