### ISSUE TITLE
请问下rss的图标现在有解决方法么?

### ISSUE THREAD

**Issue by lixhbs** [ppoffice/hexo-theme-icarus#339]
请问下rss的图标现在有解决方法么?
![image](https://user-images.githubusercontent.com/36725387/45457273-c2cf4480-b720-11e8-931f-52e68c2259db.png)

**Comment by lixhubei** [comment]
还有邮箱的图标
![image](https://user-images.githubusercontent.com/36725387/45457480-ae3f7c00-b721-11e8-8e70-9b6ca93558e2.png)

**Comment by ppoffice** [comment]
@lixhbs 目前只能暂时退回到fontawesome 4，或者把按钮硬编码到layout文件中

**Comment by czxa** [comment]
<img width="302" src="https://user-images.githubusercontent.com/32234938/45468311-92a29880-b756-11e8-83cc-a27669d5468f.png">
哈哈，我的解决办法是直接使用emoji表情。

**Comment by lixhbs** [comment]
> <img alt="" width="302" src="https://user-images.githubusercontent.com/32234938/45468311-92a29880-b756-11e8-83cc-a27669d5468f.png">
> 
> 哈哈，我的解决办法是直接使用emoji表情。

这个是咋实现的呀？

**Comment by czxa** [comment]
修改layout文件夹里面的profile.ejs文件，在合适的位置插上图片标签：<img class="github-emoji" src="/img/1.png" height="20" width="20">

**Comment by lixhbs** [comment]
> 修改layout文件夹里面的profile.ejs文件，在合适的位置插上图片标签：`<img class="github-emoji" src="/img/1.png" height="20" width="20">`

谢谢

**Comment by cheng-github** [comment]
大家好....
我发现这个问题导致的原因是由于在5的版本里rss的图标的class应该显示为fas而不是fab
所以我根据这个思路去使用下面的解决方式
修改profile.ejs里的下图部分:
![image](https://user-images.githubusercontent.com/24241010/45765533-d0785300-bc67-11e8-9b00-222b33374c5e.png)
我这里经过测试问题得到解决 ,希望对你们有帮助。

**Comment by lixhbs** [comment]
根据 @cheng-github 解决方式
![](http://paz1myrij.bkt.clouddn.com/20180929170606.png)

![](http://paz1myrij.bkt.clouddn.com/20180929171447.png)

**Comment by cheng-github** [comment]
@lixhbs  如果你想要使用envelop 你需要设置的属性为fal 或 far
具体请查看font-awesome官网

**Comment by lixhbs** [comment]
> @lixhbs 如果你想要使用envelop 你需要设置的属性为fal 或 far
> 具体请查看font-awesome官网

谢谢！

**Comment by changchangjie** [comment]
版本问题，rss应该是fas而不是fab了
修改/themes/icarus/layout/common/profile.ejs
```js
<a href="<%- url_for(theme.customize.social_links[i]) %>" target="_blank" title="<%= i %>" <%= tooltipClass %>>
    <% if (i=='rss') { %>
        <i class="fas fa-<%= i %>"></i>
    <% } else { %>
    	<i class="fab fa-<%= i %>"></i>
    <% } %>
</a>
```
