### ISSUE TITLE
logo移动端显示有点纠结...

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#343]
刚刚试了下最新的V2版主题，发现logo显示有点纠结。
官网移动端是这样的：

![1](https://user-images.githubusercontent.com/8164505/47604860-93a33700-da31-11e8-89c4-8f446005de02.PNG)

但是我设置后是这样的：

![default](https://user-images.githubusercontent.com/8164505/47604867-9f8ef900-da31-11e8-8158-e6eb85781483.PNG)

看起来比较怪，感觉主要原因有两点：

1. 之前的版本logo是文字+图片，V2版本好像只能设置图片，那么对一些logo不包含名称的网站来说，看起来比较怪。
（能不能增加一个文字logo？）

2. 如果导航栏菜单数量少，都会居中显示，不如填充满那样看起来舒服。
（是不是可以考虑菜单居左，搜索图标居右？）

**Comment by ppoffice** [comment]
1. V2同样支持文字logo.
```diff
- logo: /images/logo.svg
+ logo:
+     text: ICARUS
```

2. 如果需要更紧凑的导航栏的话，可以手动修改`source/css/style.styl`.
```diff
diff --git a/source/css/style.styl b/source/css/style.styl
index b35b50b..b73b1b2 100644
--- a/source/css/style.styl
+++ b/source/css/style.styl
@@ -76,13 +76,15 @@ img.thumbnail
             color: hsl(217, 71%, 53%)
             background-color: transparent
     @media screen and (max-width: 1087px)
+        & > .container
+            display: flex
         .navbar-menu
-            justify-content: center
             box-shadow: none
-        .navbar-start
-            margin-right: 0
-        .navbar-end
-            margin-left: 0
+    //         justify-content: center
+    //     .navbar-start
+    //         margin-right: 0
+    //     .navbar-end
+    //         margin-left: 0
```

![image](https://user-images.githubusercontent.com/8849362/47605467-c834d580-d9d4-11e8-814c-2a3e0529ebfb.png)

**Comment by tiexo** [comment]
@ppoffice 按照你说的修改后，发现一个问题。
在移动端点击" X " 标志无法关闭搜索框
![default](https://user-images.githubusercontent.com/8164505/47948993-2a15b200-df76-11e8-92e5-1ab598206eb6.PNG)

**Comment by ppoffice** [comment]
@tiexo 这个是因为关闭按钮正好在搜索按钮的正上方导致点击关闭的时候同时点到了搜索的原因，感谢提醒
