### ISSUE TITLE
How to use image as Thumbnail image from source folder ?

### ISSUE THREAD

**Issue by nirajsonawane** [ppoffice/hexo-theme-icarus#344]
How to add thumbnail image from source folder ? 
I have updated my configuration as 
thumbnail: true // in config.yml 

But how to provide image in blog post for thumbnail? 
+ thumbnail: https://example.com/image.jpg 
I want to use image from my source folder and not from the other website . 

Thanks in advance for the hlep

**Comment by ppoffice** [comment]
@nirajsonawane Just add the following line to the front-matter of your posts:

```yml
thumbnail: /relative/path/to/your/image.jpg
```

**Comment by nirajsonawane** [comment]
Thanks for quick response , it worked for me

**Comment by nirajsonawane** [comment]
the thumbnails is not visible on the home page. but when I click on Article then it's visible. 

![image](https://user-images.githubusercontent.com/11003095/47610987-ccb6c800-da80-11e8-9e4d-d40281c2126e.png)

![image](https://user-images.githubusercontent.com/11003095/47610996-24553380-da81-11e8-91b6-c594f25a56e4.png)

Could you please help , if i am missing anything ?

**Comment by ppoffice** [comment]
@nirajsonawane You need to use the relative path to the root of your website, not to your post. For example, if you are using an image in `source/post1/image.jpg`, you need to put it this way

```yml
/post1/image.jpg
```

**Comment by nirajsonawane** [comment]
@ppoffice  Thanks again for helping . /post1/image.jpg does not worked for me . 
But  below worked 
thumbnail: /2018/10/27/post1/image.jpg

is this correct behaviour ?

**Comment by ppoffice** [comment]
@nirajsonawane It is expected.
