### ISSUE TITLE
图标疑似未对齐

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#347]
![tim 20181101131809](https://user-images.githubusercontent.com/8164505/47834058-cbff9800-ddd8-11e8-9059-563e66ed9af9.png)

应该不是我眼花吧....

**Comment by ppoffice** [comment]
@tiexo https://bulma.io/documentation/elements/notification/

**Comment by tiexo** [comment]
@ppoffice 不是这个文本框，是右上角的github图标和搜索图标，看起来没对齐。

**Comment by ppoffice** [comment]
它们用的是不同的图标字体，会有一些对齐问题，我会寻找一下解决办法，感谢建议

**Comment by tiexo** [comment]
已更新！
