### ISSUE TITLE
error：comment.app_id is not one of the 'boolean' type

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#348]
valine评论系统，配置如下：
comment:
    type: valine
    app_id: abgFVBqdMOLN6JUSYDzs65l7-gzGzoHsz      
    app_key: ABNl0bM58BsayDkGQeombaXF     
    notify: false           
    verify: false           
    placeholder: 友情提醒：你甚至不需要填写昵称、邮箱、网址就能匿名评论！（邮箱可接收回复提醒）  

hexo报错如下：

![tim 20181102131335](https://user-images.githubusercontent.com/8164505/47895208-11d46300-dea2-11e8-9861-5679c838e976.png)

**Comment by czxa** [comment]
我发现这个问题出在`icarus/includes/specs/comment.spec.js`文件中，把第73-84行的中的app_id和app_key的类型改成string，97行placeholder的类型也改成string即可。

**Comment by tiexo** [comment]
@czxa 感谢。
