### ISSUE TITLE
请教一下关于valine评论的字体问题

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#350]
我发现valine评论的字体，跟主题所用的字体不一致。
之前问过别人，说评论样式是可以被主题覆盖的，但实际上好像并没有啊。
看起来有点不协调，有办法修改下么。
![default](https://user-images.githubusercontent.com/8164505/47955081-9ff93800-dfcd-11e8-9bfc-c3f6868f7da1.PNG)

**Comment by ppoffice** [comment]
@tiexo 我看了一下使用valine的页面，字体是没有问题的。https://blog.zhangruipeng.me/hexo-theme-icarus/Translations/icarus%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/

你图片中的页面有在线的版本么？我可以去看一下

**Comment by tiexo** [comment]
最新的commit好像解决了这个问题？

**Comment by tiexo** [comment]
@ppoffice 是的，因为我今天下午同步了最新的commit
