### ISSUE TITLE
一个特殊的字符串引发的bug

### ISSUE THREAD

**Issue by xiaoluoboding** [ppoffice/hexo-theme-icarus#352]
复现步骤：

* 创建空.md文件
* 输入内容如下：

```markdown
---
title: 测试bug
layout: post
---

`<style>`
```

结果：

导致widget加载不出来，控制台会报错。

**Comment by ppoffice** [comment]
@xiaoluoboding 我这里没有问题，可以请你把控制台的错误提示贴出来么？
![image](https://user-images.githubusercontent.com/8849362/48067453-5744a900-e19e-11e8-9237-87965dffb5b5.png)

**Comment by xiaoluoboding** [comment]
hexo: 3.7.0
hexo-theme-icarus: 2.0.0

![image](https://user-images.githubusercontent.com/6118824/48106176-5468b780-e275-11e8-91d6-7f098773f6c2.png)

**Comment by ppoffice** [comment]
@xiaoluoboding 请问你对Icarus本身有什么改动么？另外可以把出问题博客的源文件贴出来么

**Comment by xiaoluoboding** [comment]
@ppoffice 我在本地调试，使用 `hexo clean`依然会报错

**Comment by ppoffice** [comment]
@xiaoluoboding 没有出错的博客配置和在不知道你对博客是否进行任何修改的情况下我无法判断是什麽引起了这个问题

**Comment by xiaoluoboding** [comment]
我没有对hexo进行任何修改，这个问题关闭吧。如果你那边没有出错，可能是个别现象。

**Comment by ppoffice** [comment]
@xiaoluoboding 你可以尝试新建一个hexo博客，然后用浏览器的隐身模式并禁用插件来浏览，看看问题是否能复现

**Comment by xiaoluoboding** [comment]
@ppoffice 谢谢，我再试试
