### ISSUE TITLE
公式中换行符渲染问题

### ISSUE THREAD

**Issue by GanPhua** [ppoffice/hexo-theme-icarus#353]
页面渲染后会将公式中的`\\`换行渲染成单个`\`造成公式渲染错误。
正确公式：（第二行中的两个`\`渲染后变成1个）
```
$$
\begin{split}
\mathop{\min}_{\omega ,b} & \; \frac{1}{2}||\omega||^2 \\
\text{s.t. } & y_i(\omega^Tx_i+b)\geq1,\qquad i=1,2,\cdots,m.
\end{split}
$$
```
渲染后页面中结果（`^2`后面少了一个`\`）：
```
\begin{split} \mathop{\min}_{\omega ,b} & \; \frac{1}{2}\|\|\omega\|\|^2 \ \text{s.t. } & y_i(\omega^Tx_i+b)\geq1,\qquad i=1,2,\cdots,m. \end{split}
```
估计是渲染的锅，希望修复，谢谢~
p.s.
目前暂时的解决办法是将2个`\`写出4个就正常了。

**Comment by ppoffice** [comment]
@GanPhua 这个应该是Markdown语法的问题，与Hexo主题无关
https://enterprise.github.com/downloads/en/markdown-cheatsheet.pdf

**Comment by GanPhua** [comment]
目前暂时修改hexo的渲染源码 `nodes_modules/lib/marked/lib/marked.js` 可以解决问题，这个问题也算是 Hexo 中常见了的。
```escape: /^\\([\\`*{}\[\]()# +\-.!_>])/,```
改为
```escape: /^\\([`*{}\[\]()# +\-.!_>])/,```
取消`\\`的转义
