### ISSUE TITLE
没有主题配置文件？

### ISSUE THREAD

**Issue by WAYRT** [ppoffice/hexo-theme-icarus#354]
主题文件中没有配置文件 _config.yml 啊，是不是要自己添加？

**Comment by ppoffice** [comment]
@WAYRT 在第一次运行任何hexo命令的时候会自动生成
https://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/Theme/configuring-icarus/

**Comment by WAYRT** [comment]
@ppoffice 明白了，谢谢

**Comment by ppoffice** [comment]
For references: https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.theme.yml

**Comment by Ifonly-go2019** [comment]
没有自动生成啊,...我hexo clean && hexo d 整的我以前的东西都删了

**Comment by Lenny1998** [comment]
不会自动生成配置文件 _config.yml
