### ISSUE TITLE
如果想要这种样式和日期图标，还有右边栏的某一项想要隐藏的话怎么弄呢？

### ISSUE THREAD

**Issue by luoxianjiao** [ppoffice/hexo-theme-icarus#355]
https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/site/source/_posts/translation/Chinese.md
![image](https://user-images.githubusercontent.com/37099079/48176586-bc89cd00-e34b-11e8-8384-33948c8532d8.png)
如果想要这种样式和日期图标，icarus我该怎么自己优化呢

**Comment by ppoffice** [comment]
@luoxianjiao 这样自定义的化需要你具有一定的ejs, stylus和hexo开发知识
需要修改的代码位置在：https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/archive.ejs#L20-L35
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/style.styl#L130-L157

**Comment by ppoffice** [comment]
@luoxianjiao 边栏的插件只要在配置文件中删去就可以了
