### ISSUE TITLE
主题打开速度很慢

### ISSUE THREAD

**Issue by WAYRT** [ppoffice/hexo-theme-icarus#356]
发现这个主题有时候打开速度很慢，无论是在PC端或手机iOS端，WiFi还是4G都是一样，不知道是不是主题的原因，或者是我这边网络问题，也不知道其他人有没有遇到这种情况。

以及，有时候字体无法渲染。不知道是不是字体的问题？
![20181111132143](https://user-images.githubusercontent.com/44840983/48309426-c7936600-e5b4-11e8-9df2-bd498f9006b7.png)

**Comment by ppoffice** [comment]
@cdn的问题。
https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/site/source/_posts/translation/Chinese.md
https://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/

**Comment by WAYRT** [comment]
好吧，谢谢了。我再研究研究
