### ISSUE TITLE
column_count方法使用问题？

### ISSUE THREAD

**Issue by SchiehGuan** [ppoffice/hexo-theme-icarus#358]
请教个问题：
column_count这个方法统计数量，layout.ejs的代码如下：
switch (column_count()) {
            case 1:
                return 'is-12';
            case 2:
                return 'is-8-tablet is-8-desktop is-6-widescreen';
            case 3:
                return 'is-8-tablet is-8-desktop is-6-widescreen'
        }
而layout.js的
getWidgets(position).length > 0
这个获取的left和right数组都是大于0，毕竟html里面left和right的都有，
所以switch最后都会选择第三个
按照我的想法的话，这个switch应该只是用来控制column-left,column-main,column-right三个而已，所以这块是否有错？是否改成更精准的column-left,column-right来getWidgets？
谢谢。

**Comment by ppoffice** [comment]
@SchiehGuan 如果你把_config.yml中的所有widgets都删掉，就只有一个column。如果所有widgets的position全是left或right，那就只有两个columns

**Comment by SchiehGuan** [comment]
原来如此，我本意是想在post页的时候，去掉右边侧栏，扩大main的宽度，所以才考虑从这里入手，谢谢大佬解答
