### ISSUE TITLE
如何把页面变成三列的排版

### ISSUE THREAD

**Issue by antuotuto** [ppoffice/hexo-theme-icarus#362]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@antuotuto https://blog.zhangruipeng.me/hexo-theme-icarus/Widgets/sidebar-widgets-overview/
