### ISSUE TITLE
新版本如何自定义字体

### ISSUE THREAD

**Issue by pingao777** [ppoffice/hexo-theme-icarus#366]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
如题，试了issue里的解决方案，貌似都是老版本的

**Comment by ppoffice** [comment]
@pingao777 https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/style.styl#L1-L2

**Comment by pingao777** [comment]
谢谢

**Comment by nameussi** [comment]
@ppoffice 关于字体，我也先问下，新版的英文字体对应的是什么字体，如果我想更换英文字体，比如换成微软雅黑，那要怎么修改呢？我之前也找到了是要修改你说的这两段，但是不知道具体要修改这两段中的哪里。本人小白一个还请见谅。

**Comment by ppoffice** [comment]
@pingao777 把微软雅黑前面的字体删掉就行了

**Comment by nameussi** [comment]
@ppoffice 谢谢

**Comment by ppoffice** [comment]
@scillidan https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/head.ejs#L26 添加字体的话同时需要改这里

**Comment by scillidan** [comment]
@ppoffice 解决了，多谢
