### ISSUE TITLE
使用畅言评论时布局显示错误导致无法注册

### ISSUE THREAD

**Issue by rookielord** [ppoffice/hexo-theme-icarus#369]
畅言服务申请后添加到config中，但是发现无法无限实现登录功能，畅言发布评论时的登录布局无法显示出来。
[http://www.minicoder.cn/2018/09/01/cmake3/](http://www.minicoder.cn/2018/09/01/cmake3/)

**Comment by ppoffice** [comment]
Cause: https://github.com/w3c/csswg-drafts/issues/913

**Comment by rookielord** [comment]
@ppoffice after pulling.It almost fixed.But when I login ChangYan, it can't show my whole title picture.

**Comment by ppoffice** [comment]
@rookielord 请问title picture是指什么？

**Comment by rookielord** [comment]
@ppoffice 就是点击登陆的时候，显示的图标。显示不全

**Comment by ppoffice** [comment]
@rookielord 请问你是在畅言官网上设置的logo图片么？如果是这样的话，这个问题应该是畅言自身的问题
![screenshot from 2018-12-10 10-58-28](https://user-images.githubusercontent.com/8849362/49744415-b77dad80-fc6a-11e8-8e35-0a828fafca1b.png)

如果是在畅言控制台设置图片的话，你可以选择上传一张96px x 60px的图片作为网站logo。否则，你可以在下面这个文件中添加css样式来达到同样的效果
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/comment/changyan.ejs#L6
```html
<style>
#SOHUCS #SOHU_MAIN .changyan-login-dialog-wrapper .cy-logo {
    background-size: 60px 60px;
    background-repeat: no-repeat;
    background-position: center;
}
</style>
```
