### ISSUE TITLE
文章内的图片显示很慢应该如何优化？

### ISSUE THREAD

**Issue by LiYanan2004** [ppoffice/hexo-theme-icarus#370]
文章内的图片显示很慢应该如何优化？

**Comment by ppoffice** [comment]
@LiYanan2004 https://github.com/ppoffice/hexo-theme-icarus/blob/site/package.json#L11

**Comment by LiYanan2004** [comment]
？我用了图床，清楚hexo缓存重新上传了一下，稍微好了一点，是因为国内GitHub访问速度慢的关系吗

**Comment by ppoffice** [comment]
@LiYanan2004 有可能。尽量在能使用CDN的情况下使用CDN来缓存静态文件。

**Comment by zhangzongbo** [comment]
> ？我用了图床，清楚hexo缓存重新上传了一下，稍微好了一点，是因为国内GitHub访问速度慢的关系吗

github国内访问速度确实慢,不考虑这一点也不应该把图片放在静态文件夹里,想想图片多了静态资源占用空间膨胀,图床是必须的
