### ISSUE TITLE
非常棒的Theme，可惜没有donate插件，请问作者有计划添加donate功能吗？

### ISSUE THREAD

**Issue by huotaihe** [ppoffice/hexo-theme-icarus#371]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [Y] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [Y] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@huotaihe http://blog.zhangruipeng.me/hexo-theme-icarus/Plugins/Donation/making-money-off-your-blog-with-donation-buttons/

**Comment by GanPhua** [comment]
@ppoffice 插件有bug？当只剩一个 donate （例如微信）按钮时图片会显示不全
