### ISSUE TITLE
文章详情页，中间的显示区域太窄了，个人认为详情页的焦点在文章本身

### ISSUE THREAD

**Issue by huotaihe** [ppoffice/hexo-theme-icarus#372]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
文章详情页，中间的显示区域太窄了，个人认为详情页的焦点在文章本身

**Comment by PhoenixGS** [comment]
请问在文章页面怎么改呢？

**Comment by oushiun** [comment]
@ppoffice 你好，我也想知道如何将文章页 修改为 两栏布局

**Comment by ppoffice** [comment]
@oushiun 请仔细阅读文档和issues

**Comment by ileadall42** [comment]
@oushiun @PhoenixGS @huotaihe 先让你们看看结果。

![image](https://ws1.sinaimg.cn/large/006qhU4Vgy1fyzd7hogn4j322i16a47g.jpg)

sidebar可左可右。

```
 <% if (!is_post()) { %>
                    <%= main_column_class() %>
                <% } else{ %>
                is-8-tablet is-8-desktop is-10-widescreen
<% }%>
```
这个是在`layout.ejs`文件里面，`mainCloumn`的改变，如果是post页，让其变大，否则沿用原来设计。

接下来是核心的`common/widget.ejs`文件的修改，不太懂js的语法，所以很粗暴的修改。
![image](https://user-images.githubusercontent.com/27263086/50826112-c349b600-1375-11e9-9aa0-237f8364788a.png)

当不是post页面的时候，就沿用以前的设计。

![image](https://user-images.githubusercontent.com/27263086/50826188-ea07ec80-1375-11e9-8312-6b6f6245c38a.png)
当页面是post页面的时候，因为我保留的是右边的sidebar，并且改变了原来`order`函数，放到左边来了，复制一份，就可以了。你想保留那边，什么顺序，看代码很清晰的可以看到。

没有增加太多代码，就是copy了一份，然后用`if`来筛选。

**Comment by oushiun** [comment]
Duplicate of #379

**Comment by telami** [comment]
可以看看我的
https://www.telami.cn
