### ISSUE TITLE
toc希望增加不自动生成序号

### ISSUE THREAD

**Issue by jitwxs** [ppoffice/hexo-theme-icarus#374]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@jitwxs 删除此行
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/widget/toc.ejs#L7

**Comment by NoverNobida** [comment]
请问是怎么打开toc的？要在每篇文章最前面加toc: true还是什么？我生成的网页里面都没有toc。

**Comment by jitwxs** [comment]
> 请问是怎么打开toc的？要在每篇文章最前面加toc: true还是什么？我生成的网页里面都没有toc。

文档：https://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/Posts/table-of-contents-catalogue/

**Comment by NoverNobida** [comment]
可是我在前面加了`toc: true`也没有用哦，配置文件里面也是有的，但是就是不显示toc。
我看另一个问题里面，是不是要删除hexo自带的toc插件？

**Comment by jitwxs** [comment]
@NoverNobida 我没有对插件进行修改，甚至我都没有给文章加 `toc: true`，只是在配置文件中开启了 toc 的 widgets，侧边栏就能够显示目录了。

**Comment by NoverNobida** [comment]
😭😭这样哦，那就不知道怎么回事了。
我对网页之类的完全是小白，不懂怎么修改其他文件。所以想请教一下怎么关掉部分widgets？我在配置文件中删了相应widgets的代码，`hexo g`的时候就会出错，我并不能看懂出错原因，不过大概是在说themes/icarus/layout/layout.ejs这个出错了。所以要怎么关呢？😥

**Comment by jitwxs** [comment]
@NoverNobida 
直接注释掉或者删掉就可以了啊，有可能是你没有删除完整。
![](https://s2.ax1x.com/2019/01/22/kkVcRJ.md.png)

**Comment by scillidan** [comment]
请问3.0.0版要怎么删除序号 @ppoffice

**Comment by ppoffice** [comment]
> 请问3.0.0版要怎么删除序号 @ppoffice 

复制
https://github.com/ppoffice/hexo-component-inferno/blob/master/src/view/widget/toc.jsx
到themes/Icarus/layout/widget目录下，然后删掉
https://github.com/ppoffice/hexo-component-inferno/blob/master/src/view/widget/toc.jsx#L103
试试

**Comment by scillidan** [comment]
@ppoffice 
`hexo g`时报错，页面的`toc`部件也不显示了
![](https://raw.githubusercontent.com/scillidan/scillidan.driver.github/master/icarus_issues_374.png)

**Comment by ppoffice** [comment]
@scillidan 对应的require改成这个
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/widget/profile.jsx#L3
请新开issue

**Comment by scillidan** [comment]
@ppoffice ok，谢谢！

**Comment by declan-haojin** [comment]
请问对应的require是什么意思？
