### ISSUE TITLE
请问能不能有个选项默认每篇文章前面都加了toc: true

### ISSUE THREAD

**Issue by PhoenixGS** [ppoffice/hexo-theme-icarus#378]
- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
RT

**Comment by PhoenixGS** [comment]
哦我知道了
打扰了。。。

**Comment by xqtbox** [comment]
@PhoenixGS  请问怎么弄的？

**Comment by ppoffice** [comment]
@xqtbox 直接在主题的配置文件中加入

```yaml
toc: true
```
