### ISSUE TITLE
搜索感觉很不错，请问如何移植到自己的主题？

### ISSUE THREAD

**Issue by note4** [ppoffice/hexo-theme-icarus#380]
搜索感觉很不错，请问如何移植到自己的主题

**Comment by ppoffice** [comment]
@note4 
将以下文件放入你主题的对应目录中
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/js/insight.js
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/search.css
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/insight.css
https://github.com/ppoffice/hexo-theme-icarus/blob/master/includes/generators/insight.js
然后把一下代码插入到主题布局中的相应位置
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/search/insight.ejs
当然其中一些函数（如`_css`, `_js`）替换成Hexo默认的函数。
