### ISSUE TITLE
No Widget sidebar on either side only for post

### ISSUE THREAD

**Issue by sujays1** [ppoffice/hexo-theme-icarus#382]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

I am trying to disable sidebars (both left and right) for only posts.
So that the width will be whole 99%

Right now this is possible only when the widgets from config.yml are removed. 

I need those for the homepage, but not on blogposts.
I have option of manually overriding the whole thing with css, but I want to prevent that. 

Any help is appreciated.

**Comment by ppoffice** [comment]
@sujays1 

At the front of your post, try to write:

```yml
widgets: []
```

**Comment by sujays1** [comment]
Thats right! 
It worked!
Can you let me know where can I find configurable parameters like these? 
Are they present on Hexo documentations?

**Comment by ppoffice** [comment]
http://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/Theme/configuring-icarus/
