### ISSUE TITLE
请问如何实现文章中图片居中显示？

### ISSUE THREAD

**Issue by jitwxs** [ppoffice/hexo-theme-icarus#386]
除此之外，我很好奇这个代码块的 figcaption 是如何实现的：

![20190102184527.png](https://i.loli.net/2019/01/02/5c2c96c0688e0.png)

Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@jitwxs http://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/Posts/hexo-built-in-tag-helpers/#Code-Block

**Comment by jitwxs** [comment]
多谢 👍

**Comment by ppoffice** [comment]
@jitwxs 居中显示的话直接在图片上下加入
```html
<div style="text-align:center">
图片...
</div>
```

**Comment by jitwxs** [comment]
> @jitwxs 居中显示的话直接在图片上下加入
> 
> ```
> <div style="text-align:center">
> 图片...
> </div>
> ```

我原本是希望所有的图片都能够居中显示，而不是单独对某一张图片居中，我已经通过修改样式实现了。

**Comment by jitwxs** [comment]
@Nover2 

https://github.com/ppoffice/hexo-theme-icarus/blob/cad64ed5a2d599f85c458b79289e2e7308920ce6/source/css/style.styl#L172-L181

将 `article` 部分样式添加如下最后四行代码即可：

```styl
.article
    .article-meta
        margin-bottom: 0.5rem !important
    .content
        font-size: 1.1rem
        blockquote.pullquote
            float: right
            max-width: 50%
            font-size: 1.15rem
            position: relative
        a
            img
                margin: auto
                display: block
```

**Comment by Nover2** [comment]
谢谢，解决了！😆
