### ISSUE TITLE
可以给博客内容加密码吗？

### ISSUE THREAD

**Issue by LiYanan2004** [ppoffice/hexo-theme-icarus#388]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [√] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [√] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by water-mi** [comment]
你可以装一个插件：直接在github上面搜就行了：
hexo-blog-encrypt
