### ISSUE TITLE
又是我，还有一个问题，关于代码高亮

### ISSUE THREAD

**Issue by water-mi** [ppoffice/hexo-theme-icarus#389]
能否使用Prism.js进行高亮呢？
具体怎么做？

**Comment by ppoffice** [comment]
@water-mi https://github.com/Aetf/hexo-prism-plus

**Comment by TechQuery** [comment]
> @water-mi https://github.com/Aetf/hexo-prism-plus

你发的这个包不起效，我用 [hexo-prism-plugin](https://github.com/ele828/hexo-prism-plugin) 解决了：

https://github.com/FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io/blob/5c673bb43275d5a6e64b2328183c8da08545f348/_config.yml#L43-L45
