### ISSUE TITLE
无法使用搜索功能，已安装json在根目录

### ISSUE THREAD

**Issue by LiYanan2004** [ppoffice/hexo-theme-icarus#390]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@LiYanan2004 你的insight.js 有问题，请检查是否被改动过。
https://github.com/LiYanan2004/LiYanan2004.github.io/blob/master/js/insight.js#L239

**Comment by LiYanan2004** [comment]
我重新覆盖一下你的最新的Release吧

**Comment by LiYanan2004** [comment]
> @LiYanan2004 你的insight.js 有问题，请检查是否被改动过。
> https://github.com/LiYanan2004/LiYanan2004.github.io/blob/master/js/insight.js#L239

还是不行！！

**Comment by ppoffice** [comment]
@LiYanan2004 请贴出浏览器控制台（F12）的错误提示以及更新后的博客代码

**Comment by LiYanan2004** [comment]
![image](https://user-images.githubusercontent.com/37542129/51296928-37ace500-1a59-11e9-827a-cb9b760ba97b.png)

**Comment by LiYanan2004** [comment]
insight好像确实有问题

**Comment by LiYanan2004** [comment]
没有使用插件，请问接下来怎么办

**Comment by LiYanan2004** [comment]
当时好像升级了icarus的主题，现在就是这个js后面多了一大堆东西导致的错误，应该怎么办？
手动修改好以后重新渲染又被覆盖掉了

**Comment by LiYanan2004** [comment]
把正确的insight.js单独传上去就能解决问题，但是每次渲染的时候都会把insight.js覆盖掉，就又不行了

**Comment by LiYanan2004** [comment]
js的问题我找到了，搜索也出来了，但是搜所以后没结果是怎么回事儿？

**Comment by ppoffice** [comment]
@LiYanan2004 请不要使用其他的`content.json`生成插件，你博客根目录下的`content.json`格式与搜索所需要的格式不同造成搜索结果无法显示。Icarus内置了`content.json`的生成器。

**Comment by LiYanan2004** [comment]
ok，把Public里的那个content.json删掉了，重新渲染了一下，恢复了，谢谢！！
