### ISSUE TITLE
回到顶端按钮 在顶部没有隐藏

### ISSUE THREAD

**Issue by coolf** [ppoffice/hexo-theme-icarus#391]
点击回到顶端后，按钮没有隐藏

**Comment by ppoffice** [comment]
@didioi 请给出截图和网页源代码

**Comment by didioi** [comment]
![2](http://d.hiphotos.baidu.com/image/%70%69%63/item/b17eca8065380cd742591e17ac44ad3458828181.jpg)

https://apis.nuolkj.com/   这是网址
