### ISSUE TITLE
Question: Create product list 

### ISSUE THREAD

**Issue by pegasusearl** [ppoffice/hexo-theme-icarus#396]
Excuse me, sometimes I see in some website they have product or project content that are similiar to _post but they are collected separatedly like _product or _project. (Hmm I wonder if I explained it right.)

I tried to follow tutorial in https://github.com/hexojs/hexo/issues/2645 but it's abit confusing as the files in layout folder are different than the one in that guide.

How do I do that properly in icarus?

**Comment by ppoffice** [comment]
@pegasusearl Just try to create a new file such as `product.ejs` under `themes/icarus` and put whatever layout you want. Then refer to this layout in your post files' front-matter
```yml
title: some product
layout: product
---
# post content
```
You can check [this layout](https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/tags.ejs) out for example.
