### ISSUE TITLE
widges如何关闭

### ISSUE THREAD

**Issue by ghost** [ppoffice/hexo-theme-icarus#397]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

你好，请问我要如何在首页关闭我不想显示的widges？我试过把config中相应代码删除，或者在其之前加`#`，都不可以，总会在`hexo g`的时候出错。

**Comment by ppoffice** [comment]
@NoverNobida 请贴出错误提示
