### ISSUE TITLE
请问一下read more在什么地方设置

### ISSUE THREAD

**Issue by iceco1a** [ppoffice/hexo-theme-icarus#398]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
找了半天配置文件，没有找到什么地方设置，望告知

**Comment by ppoffice** [comment]
@iceco1a https://blog.zhangruipeng.me/hexo-theme-icarus/uncategorized/faq/

**Comment by CDT** [comment]
[add `<!-- more -->` in the content part of markdown files.](http://orcmid.com/BlunderDome/wingnut/2017/12/01/Excerpt/)
