### ISSUE TITLE
Could you please add Chinese social network support?

### ISSUE THREAD

**Issue by quxiaofeng** [ppoffice/hexo-theme-icarus#4]
duoshuo as http://duoshuo.com/
weibo icon in about
weixin and 2D barcode in about

**Comment by ppoffice** [comment]
多说插件已添加，你可以根据_config.yml.site.example来修改自己的站点的_config.yml。
至于关于页面的weibo和微信图标二维码等等，我感觉博主可以自行根据需要以图片的形式进行添加，没有必要在主题中声明功能。

**Comment by quxiaofeng** [comment]
谢谢
