### ISSUE TITLE
隐藏右侧边栏后，整体都居中，两边空隙过大，如何设置内容自动填充空白

### ISSUE THREAD

**Issue by cikichen** [ppoffice/hexo-theme-icarus#40]
有几点请教下：
1，我隐藏了右边栏，但是会发现原本右边栏占据的空间会空出来，然后个人属性栏和内容栏就自动居中了，两边空白距离不好看，我如何设置内容栏宽度自动变宽？
2，我比较喜欢 **hexo-theme-yilia** 主题的引用样式，我如何修改引用样式为那样的？

谢谢。

**Comment by cikichen** [comment]
第二个问题我直接把另外那个主题的样式复制过来替换就OK 了。求第一个问题解决。

**Comment by ppoffice** [comment]
1. 你是设置的_config.yml 的sidebar为空么？

**Comment by cikichen** [comment]
sidebar: false

**Comment by ppoffice** [comment]
false 好像没用， 你直接置空试下

**Comment by cikichen** [comment]
直接设置为空也是一样，右边栏隐藏后的空间会平均分配到左右两边

**Comment by ppoffice** [comment]
我这边没问题……如果你确定配置没问题的话可以把配置发给我看下。另外你的样式表和模版有没有改过？
![default](https://cloud.githubusercontent.com/assets/8849362/9460338/8890c0f8-4b37-11e5-91a0-9a2c333f0db5.jpg)
![default](https://cloud.githubusercontent.com/assets/8849362/9460319/584f0d32-4b37-11e5-84bb-8823d9d99d93.jpg)

**Comment by cikichen** [comment]
不好意思，可能是我没表达清楚，我希望的效果是能拉伸内容部分的宽度，把两边多余的空白填充掉。谢谢
![](http://ww2.sinaimg.cn/large/62b0904dgw1evev125yxmj20zh0eztau.jpg)

**Comment by ppoffice** [comment]
这个需要改 https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/_variables.styl#L61

**Comment by Antastsy7** [comment]
天啦噜这么快Σ(っ °Д °;)っ
试过了现在没问题啦，真的超级感谢！！！
