### ISSUE TITLE
在移动端端问题,导航栏折叠了

### ISSUE THREAD

**Issue by JakePrim** [ppoffice/hexo-theme-icarus#400]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
![image](https://user-images.githubusercontent.com/9129414/51818780-0fe83780-230b-11e9-894f-d0b2050db36e.png)

**Comment by ppoffice** [comment]
@JakePrim 与`flex-shrink`属性有关。当菜单为whitespace或者中文时会出现父容器宽度小于容器内容的现象。

**Comment by JakePrim** [comment]
好的,已经解决,谢谢
