### ISSUE TITLE
如何关闭特定的一篇文章的评论系统？

### ISSUE THREAD

**Issue by LiYanan2004** [ppoffice/hexo-theme-icarus#403]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@LiYanan2004 
```diff
title: Some post
date: ...
tags: ...
+ comment: false
```

**Comment by LiYanan2004** [comment]
OK谢谢了
