### ISSUE TITLE
Is there any way i can add subscription options  to blog by accepting email id? 

### ISSUE THREAD

**Issue by nirajsonawane** [ppoffice/hexo-theme-icarus#407]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@nirajsonawane You probably need to check if there are any third-party services for this. And if there are, new plugins should be developed to integrate they in Icarus.

**Comment by sudoliyang** [comment]
I submit a PR#548 that supported FeedBurner email subscriptions.
