### ISSUE TITLE
博文时间显示为日期

### ISSUE THREAD

**Issue by chenshen03** [ppoffice/hexo-theme-icarus#409]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

目前博文的时间显示为：**XX天前**
请问下如何将时间显示为：**2019-02-08** 这种提示？
谢谢了~

**Comment by ppoffice** [comment]
@chenshen03 注释掉这几行 https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/js/main.js#L12-L16

**Comment by chenshen03** [comment]
修改成功了，谢谢

**Comment by lzyroot** [comment]
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/js/main.js#L23-L27
