### ISSUE TITLE
页面footer居中问题

### ISSUE THREAD

**Issue by chenshen03** [ppoffice/hexo-theme-icarus#410]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

请问下如何去掉footer右边**Github**的logo，并将左侧内容在footer下**居中**显示？谢谢了~
![image](https://user-images.githubusercontent.com/20432947/52458096-53a73080-2b98-11e9-955e-7e11188d8a0b.png)

**Comment by chenshen03** [comment]
右侧GitHub的logo问题已解决，直接在配置文件下的footer去掉github即可。
但是居中问题仍没有找到解决方法。

**Comment by chenshen03** [comment]
请问下有人知道如何将footer左侧内容居中显示吗？百度尝试了多种方法都没有效果。

**Comment by jerryc127** [comment]
把这个去掉    display: flex;
![image](https://user-images.githubusercontent.com/16351105/54281902-b5aee780-45d5-11e9-8585-29ecf04f5835.png)
添加这个css
![image](https://user-images.githubusercontent.com/16351105/54281919-bd6e8c00-45d5-11e9-9c8a-d06162ad55f6.png)

不过这样做 导致GitHub的logo
![image](https://user-images.githubusercontent.com/16351105/54282053-150cf780-45d6-11e9-8937-18dacf650ff1.png)


如果把GitHub的logo去掉
结果
![image](https://user-images.githubusercontent.com/16351105/54282001-f27ade80-45d5-11e9-97e8-ca78667387ba.png)
