### ISSUE TITLE
中文的toc无法进行跳转

### ISSUE THREAD

**Issue by scillidan** [ppoffice/hexo-theme-icarus#411]
不过可以使用`html标签`。
例如`## 中文`，需写成`<h2 id="text">中文</h2>`，地址栏显示`#text`。

**Comment by ppoffice** [comment]
@scillidan 我这里跳转没有问题。请附上浏览器版本和出错页面的HTML代码

**Comment by scillidan** [comment]
浏览器 `chrome 72.0.3626.96`
代码在这 [link](https://youthidea-1255733840.cos.ap-chengdu.myqcloud.com/cache/test.html)

**Comment by ppoffice** [comment]
@scillidan 这个问题是由你所引入的Aplayer所依赖的smoothscroll造成的，请向这两个项目提出issue。

问题定位：https://github.com/alicelieutier/smoothScroll/blob/master/smoothscroll.js#L99
问题描述：https://gomakethings.com/handling-chinese-and-cyrillic-character-hash-and-href-values-in-javascript/

**Comment by scillidan** [comment]
Aplayer下有相同的问题，已向smoothscroll提交了issue
