### ISSUE TITLE
如何发布站点公告？有考虑增加下这个功能吗，比较需要，感谢了🙏

### ISSUE THREAD

**Issue by LiYanan2004** [ppoffice/hexo-theme-icarus#417]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by jitwxs** [comment]
可以参考 `hexo-theme-icarus/layout/widget` 下的内容，自己定义一个 widget

**Comment by ppoffice** [comment]
@LiYanan2004 此功能可以通过添加widget实现。请参考`hexo-theme-icarus/layout/widget`。

**Comment by zhullyb** [comment]
https://www.hongfs.cn/2019/06/javascript/hexo-theme-icarus-notice/
今天偶然看到了

**Comment by LiYanan2004** [comment]
您的邮件我已收到，谢谢！QQ：1474700628
