### ISSUE TITLE
还有一个比较影响体验的就是insight搜索，能否在搜索结果列表高亮搜索的内容？

### ISSUE THREAD

**Issue by LiYanan2004** [ppoffice/hexo-theme-icarus#418]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by LiYanan2004** [comment]
就是如果我搜索 test ，结果列表中把带有test的页面显示出来的同时定位到第一处含有此关键字的位置并高亮显示

**Comment by note4** [comment]
还有一个问题，搜索程序的索引文件是在加载页面时加载，大大降低了打开速度，如果可以页面出来后再加载想必会更好

**Comment by ppoffice** [comment]
Will be available in version 3.0.0.
