### ISSUE TITLE
如何将“阅读更多”显示在摘要右边?

### ISSUE THREAD

**Issue by chenshen03** [ppoffice/hexo-theme-icarus#419]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

如下图所示，如何将“阅读更多”显示在摘要右边？
![image](https://user-images.githubusercontent.com/20432947/53165049-ace97800-360c-11e9-84b3-b8014a9856da.png)

**Comment by ppoffice** [comment]
@chenshen03 https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.ejs#L66 的下一行加上
```html
</div>
<div class="level-end">
```

**Comment by chenshen03** [comment]
已解决，谢谢。
