### ISSUE TITLE
博文中文路径改成英文路径

### ISSUE THREAD

**Issue by chenshen03** [ppoffice/hexo-theme-icarus#420]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

当博文名称为带有中文时，复制的网址就很不美观。如：
 “https://chenshen.xyz/2019/02/01/Linux系统知识汇总”
复制后就变成：
“https://chenshen.xyz/2019/02/01/Linux%E7%B3%BB%E7%BB%9F%E7%9F%A5%E8%AF%86%E6%B1%87%E6%80%BB/”
如何设置主题，使得每个博文可以设置对应的英文网址路径，如：
“https://chenshen.xyz/2019/02/01/Linux-system-knowledge-summary”

**Comment by ppoffice** [comment]
@chenshen03 https://hexo.io/docs/permalink

**Comment by chenshen03** [comment]
谢谢，已解决。
