### ISSUE TITLE
导航栏链接自动跳转为http协议

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#422]
不知道怎么回事，导航栏的archives和about页面链接会自动跳转为http协议
因为github强制https，所以会导致页面打不开。

配置如下，一直没改过
![tim 20190225133035](https://user-images.githubusercontent.com/8164505/53316127-9b041f80-3901-11e9-8b2e-590993cce7b7.png)
将鼠标放在导航栏上，显示的链接也是https
![tim 20190225133142](https://user-images.githubusercontent.com/8164505/53316158-b53dfd80-3901-11e9-9346-322d5d2e58f9.png)
但是一点击就会跳转为http
http://tiexo.github.io/archives/
而且手动输入https地址也是可以打开的。

网站地址：https://tiexo.github.io
不知道是哪块出问题，麻烦帮我看看，谢谢。

**Comment by ppoffice** [comment]
@tiexo 你这里是https么？ https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.yml#L15

**Comment by tiexo** [comment]
@ppoffice 是的
而且首页和文章都是正常的

**Comment by tiexo** [comment]
https://github.com/tiexo/tiexo.github.io/tree/blog?files=1
这是源文件

**Comment by tiexo** [comment]
谢谢！
