### ISSUE TITLE
Override the theme config using theme_config in "config.yml" of the original hexo project

### ISSUE THREAD

**Issue by MoezGholami** [ppoffice/hexo-theme-icarus#424]
Hi,
Maintaining 2 config.yml files for a website is painful. As Icarus's config should be in its own repository. Usually, maintaining Icarus's config requires forking the repository to update its config file; this makes it difficult to update Icarus to its last version (due to git conflicts). Also, splitting config files into two different repositories (original webiste repo and the sub-module for the theme) is painful (I know, there are some dirty tricks such as symbolic links).
In [Hexo's official documentation](https://hexo.io/docs/configuration.html#Overriding-Theme-Config), there's a proposed way to override theme config inside original Hexo project config.xml file. This makes it way easier to manage website and themes' config at the same time.
However, I tried it for Icarus theme and it did not work. Icarus does not allow Hexo to override its config. It would be good if Icarus integrates with Hexo in this regard.

**Comment by ppoffice** [comment]
@MoezGholami Actually, you can comment out this line and move all theme configs to the site `_config.yml` and see if it works.
https://github.com/ppoffice/hexo-theme-icarus/blob/master/scripts/index.js#L3

**Comment by MoezGholami** [comment]
Nope :(
It doesn't work.

**Comment by ppoffice** [comment]
@MoezGholami What does your config looks like?

**Comment by MoezGholami** [comment]
I was just playing with the menu items to test it.
I am going to work on a pull request to work around it.
Also, I may remove the part of shutting hexo down if there is no theme config file; just a warning can be fine. What do you think @ppoffice ?

**Comment by ppoffice** [comment]
@MoezGholami I think we should keep that before we implement a more comprehensive config checker, which include the site's `_config.yml`. Also, removing this will also cause some unexpected behavior if the user does not have a valid configuration file.

**Comment by ppoffice** [comment]
@MoezGholami I've also tested putting configs in the site's `_config.yml`. It works as expected. What you should do is simply put anything from your theme `_config.yml` into the site one and restart the hexo server (or regenerate the site, otherwise the site config will not be updated in the hexo process).

```diff
# themes/icarus/_config.yml
- navbar:
-    menu:
-        Home: /
-        Archives: /archives
-        Categories: /categories
-        Tags: /tags
-        About: /about
-    links:
-        Download on GitHub:
-            icon: fab fa-github
-            url: 'http://github.com/ppoffice/hexo-theme-icarus'
```

```diff
# _config.yml
title: Icarus
subtitle:
description: Hexo theme - Icarus

...

+ navbar:
+    menu:
+        Home: /
+        Archives: /archives
+        Categories: /categories
+        Tags: /tags
+        About: /about
+    links:
+        Download on GitHub:
+            icon: fab fa-github
+            url: 'http://github.com/ppoffice/hexo-theme-icarus'
```

**Comment by MoezGholami** [comment]
@ppoffice 
Thanks for your guide. I tried it and it worked. But as you said, I should have kept the theme/icarus/_config.yml to make it work (keeping the version line).
However, we still have the problem of required restart and maintaining commits in two repositories (the first commit is required to gut the theme config file). We still need to implement the comprehensive config checker. I am not sure if I should close this issue (you do it if you want) or keep it open to indicate that we need the feature mentioned above.
I am willing to contribute anyway.

**Comment by TheBeachMaster** [comment]
@MoezGholami  this is a good discussion, however, I think the fact that the `_config.yml` in the theme folder is added to `.gitignore` you can very easily add the theme as a submodule make it much easier to maintain since you won't have to touch the theme source itself. 

IMO the separation makes more sense and that's the very reason why I moved from Gatsby, I was looking for the ability to separate themes(starters) from the core generator.
