### ISSUE TITLE
代码高亮配置问题

### ISSUE THREAD

**Issue by Zohar727** [ppoffice/hexo-theme-icarus#428]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

### 关于代码高亮，有几个问题：
- **代码主题配置问题**
> Icarus directly import code highlight themes from the highlight.js package, and makes more than 70 highlight themes available to you.

您介绍提供了70多种主题可选择，可是我看了您的wiki和`highlight.js`的文档，也没有找到可选主题的目录
- **代码高亮不生效**
使用默认配置的主题，代码高亮也不生效，因为没用过`highlight.js`，所以可能我的配置有问题，请您指教。
这是md文件中的代码：https://github.com/Zohar727/myblog/blob/master/source/_posts/20170327.md，
代码虽然被识别出来了，但没有高亮颜色

**Comment by jerryc127** [comment]
网址无效啊
你是不是没写具体得coding name啊
例如
```java

代码
```

**Comment by xiaonuo915** [comment]
'Code highlight theme' can't apply.
`highlight.js` was not found in the page load resource.
