### ISSUE TITLE
About page have a issue

### ISSUE THREAD

**Issue by stephenvuzxc** [ppoffice/hexo-theme-icarus#429]
Hi guy, i really love your theme. 
But when i create about page by command : hexo new page about
In localhost about page's link is /about/ and it works. However, when i deploy it on my domain. My blog notice cannot get /about/. I checked it discovered that about page's link change to /About/. Why? I don't understand that. 'a' upcase to 'A'.
Thank you!

**Comment by ppoffice** [comment]
@stephenvuzxc Maybe this QA will help:
https://stackoverflow.com/questions/6650488/why-are-github-project-document-page-urls-case-sensitive-what-are-the-negative
