### ISSUE TITLE
valine评论系统无法显示

### ISSUE THREAD

**Issue by yangyuanming** [ppoffice/hexo-theme-icarus#431]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ✔️]
 I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [✔️ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

评论框没有显示，按了[教程](https://blog.zhangruipeng.me/hexo-theme-icarus/categories/Plugins/Comment/page/2/)操作，代码都上传到github上了，在其他主题使用没问题，id和key没有填错

**Comment by ppoffice** [comment]
@yangyuanming 你需要把文章头部的`comment: true`删掉
