### ISSUE TITLE
Page deployed to Heroku - styles crashed

### ISSUE THREAD

**Issue by robert-skarzycki** [ppoffice/hexo-theme-icarus#432]
I've create a fresh hexo installation, then installed [hexo-deployer-heroku](https://github.com/hexojs/hexo-deployer-heroku) (what's working like a charm), then I've cloned icarus theme with `git clone https://github.com/ppoffice/hexo-theme-icarus.git themes/icarus` command (one that is on the main github page) and set it as a theme on global `_config.yml`. After that, I've started hexo locally by `hexo serve` - the "hello world" page looks exactly like on the demo page. However, when I deployed it to Heroku with `hexo deploy -g` it doesn't look like correctly - widgets are misplaced and unstyled: https://robert-skarzycki-blog-experim.herokuapp.com/
What's wrong with my setup? (You can see the source code there: https://github.com/robert-skarzycki/personal-blog/tree/for-icarus-issue-reproduction)

P.S. I was wondering why icarus' `_config.yml` is ignored in icarus' `.gitignore` file. I was trying to unignore this, move the icarus' config to the global config file (by appending the content to the latter one), but none of this helped.

------
- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@robert-skarzycki Your style.css (https://robert-skarzycki-blog-experim.herokuapp.com/css/style.css) does not look good. Please check if you cleaned all the previously generated static files and purge any cached files from your host provider.

**Comment by robert-skarzycki** [comment]
@ppoffice, thanks for help - removing `public` and `.heroku-deploy` folders, together with removing the already-existing theme folder (the latter is irrelevant, IMHO) - it did the trick. Now it works!
