### ISSUE TITLE
某一篇文章的content.json可以自己设定吗

### ISSUE THREAD

**Issue by LiYanan2004** [ppoffice/hexo-theme-icarus#433]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@LiYanan2004 `content.json`文件是针对全站的，单独设置的话不仅要改动`hexo-generator`，也需要更改前端的`insight.ejs`。目前没有针对某篇文章单独设置的功能。

**Comment by LiYanan2004** [comment]
我有一篇文章是加密的，然后用的是AES编码，导致了content.json里面有一堆字符，搜索的时候不管什么字母都能搜到那篇，如何处理呢

**Comment by ppoffice** [comment]
@LiYanan2004 可以在这个位置加上对加密文章的判断，设置成如果是加密文章则不加入生成的文章列表中。https://github.com/ppoffice/hexo-theme-icarus/blob/master/includes/generators/insight.js#L33

**Comment by LiYanan2004** [comment]
可以教一下怎么写吗
