### ISSUE TITLE
可否增加内容栏自定义宽度功能

### ISSUE THREAD

**Issue by iarchean** [ppoffice/hexo-theme-icarus#434]
作者你好，我非常喜欢你制作的主题，在使用了一段时间之后，我基本上已经熟练掌握了主题的各项功能，只是个人认为中间内容栏稍微有点窄，在尝试自己修改未果后，想要请你帮忙，不知可否增加自定义宽度功能？非常感谢！

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lxqxsyu** [comment]
这个是12格布局，可以修改`source/css/style.styl`文件中的media样式如下：
```css
@media screen and (min-width: screen-widescreen)
    .is-1-column .container
    .is-2-column .container
        max-width: screen-widescreen - 2 * gap
        width: screen-widescreen - 2 * gap
@media screen and (min-width: screen-fullhd)
    .is-2-column .container
        max-width: screen-fullhd - 2 * gap
        width: screen-fullhd - 2 * gap
    .is-1-column .container
        max-width: screen-desktop - 2 * gap
        width: screen-desktop - 2 * gap
```
然后如果按照 `#379`的方式改为两栏后，可以修改一下`layout/layout.ejs`和`layout/common/widget.ejs`的文件内容如下：

```js
    <% function main_column_class() {
        switch (column_count()) {
            case 1:
                return 'is-12';
            case 2:
                return 'is-8-tablet is-9-desktop is-9-widescreen';
            case 3:
                return 'is-8-tablet is-8-desktop is-6-widescreen'
        }
        return '';
    } %>
```

```js
<% function side_column_class() {
    switch (column_count()) {
        case 2:
            return 'is-4-tablet is-3-desktop is-3-widescreen';
        case 3:
            return 'is-4-tablet is-4-desktop is-3-widescreen';
    }
    return '';
} %>
```

要注意的是对应column的数量和是12，如果是三列就是三列的和，如果是两列就是两列的和。

更改后的效果查看：http://dp2px.com

**Comment by lxqxsyu** [comment]
> 这个是12格布局，可以修改`source/css/style.styl`文件中的media样式如下：
> 
> ```css
> @media screen and (min-width: screen-widescreen)
>     .is-1-column .container
>     .is-2-column .container
>         max-width: screen-widescreen - 2 * gap
>         width: screen-widescreen - 2 * gap
> @media screen and (min-width: screen-fullhd)
>     .is-2-column .container
>         max-width: screen-fullhd - 2 * gap
>         width: screen-fullhd - 2 * gap
>     .is-1-column .container
>         max-width: screen-desktop - 2 * gap
>         width: screen-desktop - 2 * gap
> ```
> 
> 然后如果按照 `#379`的方式改为两栏后，可以修改一下`layout/layout.ejs`和`layout/common/widget.ejs`的文件内容如下：
> 
> ```js
>     <% function main_column_class() {
>         switch (column_count()) {
>             case 1:
>                 return 'is-12';
>             case 2:
>                 return 'is-8-tablet is-9-desktop is-9-widescreen';
>             case 3:
>                 return 'is-8-tablet is-8-desktop is-6-widescreen'
>         }
>         return '';
>     } %>
> ```
> 
> ```js
> <% function side_column_class() {
>     switch (column_count()) {
>         case 2:
>             return 'is-4-tablet is-3-desktop is-3-widescreen';
>         case 3:
>             return 'is-4-tablet is-4-desktop is-3-widescreen';
>     }
>     return '';
> } %>
> ```
> 
> 要注意的是对应column的数量和是12，如果是三列就是三列的和，如果是两列就是两列的和。
> 
> 更改后的效果查看：http://dp2px.com

主题修改我总结了一篇文章：https://dp2px.com/2019/06/04/icarus-theme/

**Comment by molu-ggg** [comment]
不对啊，没有变化

**Comment by raighneweng** [comment]
如果缩小内容左右与网页边缘的空白大小。

**Comment by JonathanTW1990** [comment]
請問怎麼控制多少文字出現 read more? tks

**Comment by removeif** [comment]
> 請問怎麼控制多少文字出現 read more? tks

read more 是自己灵活放置相应的more标签，自己觉得多少字之后合适就放在.md对应位置！
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2020/20200305122700.png)
如下显示：
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2020/20200305123305.png)
