### ISSUE TITLE
how to append site keywords to each post

### ISSUE THREAD

**Issue by sunnycomes** [ppoffice/hexo-theme-icarus#442]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ √ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ √] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

My site keywords in hexo_root/_config.yml are: CJ Sun, Caijun Sun, IOVI. How can I append them to keywords of each post when generating html files? For example, my post **_Learning from Source Code, word2vec_** has 3 tags, respectively are _Machine Learning, Word2vec, Word Embedding_. By default, the generated html will be 

`<meta name="keywords" content="Machine Learning,Word2vec,Word Embedding">`. 

I need it to be 

`<meta name="keywords" content="Machine Learning,Word2vec,Word Embedding, CJ Sun, Caijun Sun, IOVI">`. 

I have read your code and tried to solve it, however it failed. Any solutions? Please give me some hints.

**Comment by ppoffice** [comment]
@sunnycomes You can try to override the keywords for each post. For example, you may put the keywords in your post's front-matter:

```diff
  title: Getting Started with Icarus
  date: 2018-10-22 19:23:59
  thumbnail: /gallery/thumbnails/desert.jpg
  tags:
  - Getting Started
+ keywords: Machine Learning, Word2vec, Word Embedding, CJ Sun, Caijun Sun, IOVI
```

**Comment by BEWINDOWEB** [comment]
resolution：edit `node_modules/hexo-theme-icarus/layout/common/head.jsx`
```jsx
// add the var define like this
let tag_keywords = (page.tags && page.tags.length ? page.tags : undefined) || '';
if (tag_keywords) {
    if (typeof tag_keywords === 'string') tag_keywords = [tag_keywords];
    tag_keywords = tag_keywords.map(tag => tag.name).filter(Boolean).join(',');
}

let config_keywords = config.keywords || '';
if (config_keywords) {
    if (typeof config_keywords === 'string') config_keywords = [config_keywords];
    config_keywords = config_keywords.filter(Boolean).join(',');
}

let keywords = config_keywords + (tag_keywords ? ',' : '') + tag_keywords;

// 下面的渲染html添加：
{keywords ? <meta name="keywords" content={keywords} /> : null}
```
