### ISSUE TITLE
如何设置单独的摘要而不是截取文章开头

### ISSUE THREAD

**Issue by Boycottangent** [ppoffice/hexo-theme-icarus#448]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

用 `<!-- more -->` 只能生成文章开头的预览，是否支持在front-matter单独设置一段文字作为摘要？

**Comment by ppoffice** [comment]
@Boycottangent 不支持。需要手动修改源码。

**Comment by nameussi** [comment]
同希望有这个功能

**Comment by ppoffice** [comment]
@Boycottangent @nameussi 已向Hexo提交代码 https://github.com/hexojs/hexo/pull/3612

如果这个改动被并入Hexo官方repo，可以直接在文章的front matter添加`excerpt`配置来实现自定义摘要：

```yaml
title: 一片文章等等等
excerpt: 文章摘要等等等
---
实际文章内容等等等...
```

**Comment by leimao** [comment]
PR似乎已经被merge了，现在如何单独显示excerpt呢？谢谢

**Comment by leimao** [comment]
npm上的hexo是三个月前发布的，应该还没有这个feature。
