### ISSUE TITLE
请问我想除了首页是两栏内容，其他就只有中间一栏，要如何操作呢，还有就是如何修改菜单栏的颜色呢

### ISSUE THREAD

**Issue by ifdmlab** [ppoffice/hexo-theme-icarus#450]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by telami** [comment]
example：https://www.telami.cn

**Comment by ctrlands** [comment]
[通过辅助函数is_post()去判断，修改layout.ejs.](https://hexo.io/zh-cn/docs/helpers)
<% if (is_post()) { %>
                <% } else { %>
                    <%- partial('common/widget', { position: 'left' }) %>
                    <%- partial('common/widget', { position: 'right' }) %>
                <% } %>
