### ISSUE TITLE
How can turn off the share button for one of the articles?

### ISSUE THREAD

**Issue by zhujinyao822** [ppoffice/hexo-theme-icarus#452]
In some articles (for example 'about' page), I don't want to share functionality. How do I do this?

**Comment by ppoffice** [comment]
@zhujinyao822 In the post's front matter:

```yaml
share: false
```

**Comment by zhujinyao822** [comment]
> @zhujinyao822 In the post's front matter:
> 
> ```yaml
> share: false
> ```

Perfect solution,Thx
