### ISSUE TITLE
文章的字间距、段间距怎么调整呢？

### ISSUE THREAD

**Issue by KunMinX** [ppoffice/hexo-theme-icarus#457]
如图，上图是当前博客的字间距，下图是掘金的字间距，上图会因为字间距稍小了，而感觉不太舒服。我目前对 css 还有 hexo 不太熟，试了 line-height:??px; letter-spacing:??px;  来调整 style 但没有起到我想要的效果，我需要作者的帮助！

![博客](https://upload-images.jianshu.io/upload_images/57036-7d74442c949b42e7.png)
![掘金](https://upload-images.jianshu.io/upload_images/57036-cae92e6a8afee276.png)

**Comment by ppoffice** [comment]
@KunMinX 修改https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/style.styl#L172
```diff
.article
    ...
    .content
        ...
+        letter-spacing: 999px;
+        p
+            margin-bottom: 999px
```

**Comment by KunMinX** [comment]
@ppoffice 修改后，对正文没有影响，并且影响到页面其他栏目的排版了（两边的侧栏被显示到右边，底部的信息变大）。。

![微信截图_20190429120739.png](https://upload-images.jianshu.io/upload_images/57036-4ed6cc8dcb90344a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![微信截图_20190429120749.png](https://upload-images.jianshu.io/upload_images/57036-95f5fda713e4d7ee.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![微信截图_20190429120800.png](https://upload-images.jianshu.io/upload_images/57036-3252030d7215bd88.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

如图，无论设置 999px 还是 2px，都影响不了

**Comment by ppoffice** [comment]
@KunMinX letter-spacing的缩进错了

**Comment by KunMinX** [comment]
@ppoffice  我完全不具备这方面的背景知识，所以具体怎么做才是正确的，望指明 😂

**Comment by ppoffice** [comment]
@KunMinX 仔细看我第一条回复里的代码

**Comment by KunMinX** [comment]
@ppoffice 我比对了，配的是一模一样的

**Comment by KunMinX** [comment]
@ppoffice margin-bottom 影响的是文末对底部的距离，并非每行的间距，letter-spacing 则是完全看不出效果

**Comment by ppoffice** [comment]
@KunMinX 那你在`letter-spacing: 999px`后面加上`!important`。如果你要增加的是行间距而不是段间距的话，你需要的是`line-height: 999px`。

**Comment by KunMinX** [comment]
@ppoffice 666 撒花~ letter-spacing: 999px !important 外加 p 的 line-height: 28px， perfect！
