### ISSUE TITLE
Profile 和 sidebar 的排版

### ISSUE THREAD

**Issue by yuanbaohundan** [ppoffice/hexo-theme-icarus#46]
请问下能不能把sidebar直接放在profile下面了，这样以免左右都出现侧边栏，谢谢

**Comment by edentsai** [comment]
這是我的修改方式給你參考看看：

1. 在 `_config.yml` 裡面設定 `sidebar = false` 將它停用
2. 將 `layout/_partial/sidebar.ejs` 裡面負責 render widgets 的部份複製到 `layout/_partial/profile.ejs` 裡面
3. 調整 `source/css/_variables.styl` 裡面的 main-column 欄位大小，讓 main section 在 sidebar 停用的時候將原本 sidebar 的位置佔滿。

``` diff
diff --git a/_config.yml b/_config.yml
index 6584fd9..75074ea 100644
--- a/_config.yml
+++ b/_config.yml
@@ -18,7 +18,7 @@ profile: true # Whether to show profile bar
 gravatar: true # Whether to use gravatar with the email. If you do, put your email address in your site's `_config.yml`.

 # Sidebar
-sidebar: right # set to false if you don't want a sidebar
+sidebar: false # set to false if you don't want a sidebar
 widgets:
 - recent_posts
 - tagcloud
diff --git a/layout/_partial/profile.ejs b/layout/_partial/profile.ejs
index 8c3a176..aaa81dd 100644
--- a/layout/_partial/profile.ejs
+++ b/layout/_partial/profile.ejs
@@ -35,4 +35,9 @@
     </div>
     <% } %>
   </div>
+
+  <% theme.widgets.forEach(function(widget){ %>
+    <%- partial('_widget/' + widget) %>
+  <% }) %>
+  <div id="toTop" class="fa fa-chevron-up"></div>
 </aside>
diff --git a/source/css/_variables.styl b/source/css/_variables.styl
index 29c55ac..26e7bcb 100644
--- a/source/css/_variables.styl
+++ b/source/css/_variables.styl
@@ -52,6 +52,7 @@ if sidebar
   _sidebar-column = sidebar-column
 else
   _sidebar-column = 0
+  main-column = 10

 if profile
   _profile-column = profile-column
```

**Comment by yuanbaohundan** [comment]
好的，我有时间了试试看，多谢回复，祝好


在 2015年12月5日 下午4:54:11, Eden Tsai (notifications@github.com) 写到:

這是我的修改方式給你參考看看：

在 _config.yml 裡面設定 sidebar = false 將它停用
將 layout/_partial/sidebar.ejs 裡面負責 render widgets 的部份複製到 layout/_partial/profile.ejs 裡面
調整 source/css/_variables.styl 裡面的 main-column 欄位大小，讓 main section 在 sidebar 停用的時候將原本 sidebar 的位置佔滿。
diff --git a/_config.yml b/_config.yml
index 6584fd9..75074ea 100644
--- a/_config.yml
+++ b/_config.yml
@@ -18,7 +18,7 @@ profile: true # Whether to show profile bar
 gravatar: true # Whether to use gravatar with the email. If you do, put your email address in your site's `_config.yml`.

 # Sidebar
-sidebar: right # set to false if you don't want a sidebar
+sidebar: false # set to false if you don't want a sidebar
 widgets:
 - recent_posts
 - tagcloud
diff --git a/layout/_partial/profile.ejs b/layout/_partial/profile.ejs
index 8c3a176..aaa81dd 100644
--- a/layout/_partial/profile.ejs
+++ b/layout/_partial/profile.ejs
@@ -35,4 +35,9 @@
     </div>
     <% } %>
   </div>
+
+  <% theme.widgets.forEach(function(widget){ %>
+    <%- partial('_widget/' + widget) %>
+  <% }) %>
+  <div id="toTop" class="fa fa-chevron-up"></div>
 </aside>
diff --git a/source/css/_variables.styl b/source/css/_variables.styl
index 29c55ac..26e7bcb 100644
--- a/source/css/_variables.styl
+++ b/source/css/_variables.styl
@@ -52,6 +52,7 @@ if sidebar
   _sidebar-column = sidebar-column
 else
   _sidebar-column = 0
+  main-column = 10

 if profile
   _profile-column = profile-column
