### ISSUE TITLE
关于文章头图和正文的问题

### ISSUE THREAD

**Issue by nameussi** [ppoffice/hexo-theme-icarus#460]
- 如何修改头图的高度？试过直接在`img.thumbnail`修改，虽然高度变小但是图片下方会有白边，不会自动缩进
- 文章正文插入视频或aplayer插件时，下边距比上边距小，与正文文字靠太近，这要如何修改？

**Comment by nameussi** [comment]
第一个问题已解决，第二个还不懂

**Comment by ppoffice** [comment]
@nameussi 在这里(https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/style.styl#L423)加上 `margin-bottom`

**Comment by nameussi** [comment]
@ppoffice 加了还是没有效果。Icarus v1 没有这个问题，我再自己看看怎么调吧
