### ISSUE TITLE
关于缩略图设置的问题

### ISSUE THREAD

**Issue by Zheaoli** [ppoffice/hexo-theme-icarus#461]
![image](https://user-images.githubusercontent.com/7054676/57174877-d0843680-6e77-11e9-995a-8afc4a2fb5dd.png)

在社交网站分享的时候，网站的缩略图还是默认自带的图标，没在设置中看到有这样设置存在？

请问如何设置？

**Comment by ppoffice** [comment]
@Zheaoli 请尝试设置[Open Graph](https://hexo.io/docs/helpers#open-graph)
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/head.ejs#L6

**Comment by Zheaoli** [comment]
这个地方搞定了，但是这个地方有个逻辑我自己觉得可能不太妥
目前 icarus 对于 Open Graph 的设置是依赖于文章中设置的 Open Graph，如果没有，则使用 icarus 默认的缩略图

但是实际上一个使用场景是我不太可能去为每篇文章处理一个 Open Graph，我更希望能在 _config.yml 中能有一个统一的入口去设置

如果可以这个地方可以优化一波（我可以提个 PR

@ppoffice

**Comment by ppoffice** [comment]
@Zheaoli https://github.com/ppoffice/hexo-theme-icarus/blob/d674e6b61c0966f85b466d01f5d069cc1096a992/includes/helpers/page.js#L102
