### ISSUE TITLE
Site theme color

### ISSUE THREAD

**Issue by TheBeachMaster** [ppoffice/hexo-theme-icarus#462]
Add options to inject site theme color

```html
<meta name="theme-color" content="#abcdef" />  
``` 

Importance: it is a [__color that user agents should use to customize the display of the page or of the surrounding user interface__.](https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color) 

[Site](https://www.otienoken.me/)

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@TheBeachMaster You could add arbitrary meta tags from `_config.yml` like below with latest Icarus:

```yml
meta:
- name=theme-color;content=#123456
```

**Comment by Icecream-blue-sky** [comment]
> @TheBeachMaster You could add arbitrary meta tags from `_config.yml` like below with latest Icarus:
> 
> ```yaml
> meta:
> - name=theme-color;content=#123456
> ```

I add this in _config.yml with latest Icarus:
meta: 
- name=theme-color;content=#ff4d00
The color is red.But nothing happens since I don't see any red color at my blog.I want to chang the color the follow button and other blue things.Is there something wrong with my operation?
My website:https://zoutq.com/

**Comment by ppoffice** [comment]
@TheBeachMaster https://www.crifan.com/html_meta_theme_color_meaning/

**Comment by TheBeachMaster** [comment]
@ppoffice  and @Icecream-blue-sky 

```yaml
....
meta:
- name=theme-color;content=#512da8
- name=background_color;content=#9c27b0
- name=apple-mobile-web-app-capable;content=yes
- name=apple-mobile-web-app-status-bar-style;content=black-translucent
```

Yields

```html
<meta name="theme-color" content="#512da8" />
<meta name="background_color" content="#9c27b0" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
``` 

See [otienoken.me](www.otienoken.me)
