### ISSUE TITLE
请问如何修改Follow的按钮变成显示contact me？

### ISSUE THREAD

**Issue by H0u5er** [ppoffice/hexo-theme-icarus#463]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@H0u5er https://github.com/ppoffice/hexo-theme-icarus/blob/master/languages/en.yml#L17

**Comment by H0u5er** [comment]
> @H0u5er https://github.com/ppoffice/hexo-theme-icarus/blob/master/languages/en.yml#L17

请问我要如何选择使用其他语言的设置？另外文章是否支持双语切换显示？

**Comment by ppoffice** [comment]
@H0u5er https://github.com/ppoffice/hexo-theme-icarus/issues?utf8=%E2%9C%93&q=language
