### ISSUE TITLE
top-setting ？

### ISSUE THREAD

**Issue by danziw** [ppoffice/hexo-theme-icarus#464]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [✔] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ✔] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
--------------------------------------------------------------
Can you increase the top-setting function of articles?
This is a very useful function.
Thank you

**Comment by ppoffice** [comment]
@danziw What do you mean by `top-setting`?

**Comment by nameussi** [comment]
@danziw 是指文章置顶吗？是的话可以参考这篇https://susreal.com/article/2019/hexo-theme-icarus-2/
当然也希望作者能加入与主题融合得更好的置顶功能样式

**Comment by danziw** [comment]
> @danziw是指文章置顶吗？的的英文话教育可以参考这篇https://susreal.com/article/2019/hexo-theme-icarus-2/
> 当然也。希望作者能加入与主题融合得更好的置顶功能样式

谢谢
