### ISSUE TITLE
Catalogue entry does nothing

### ISSUE THREAD

**Issue by TheBeachMaster** [ppoffice/hexo-theme-icarus#465]
There seems to be a `Catalogue` entry on every post and it does not show or do anything. The entry appears in neither of my `_config.yml` files. 

See screenshot below 
![Screenshot_20190511_123430](https://user-images.githubusercontent.com/9129843/57567992-da62e800-73e9-11e9-86fd-cd13e2107230.png) 

Example link -> [site](https://www.otienoken.me/build-tools/buck/) 

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@TheBeachMaster https://hexo.io/docs/helpers#toc
You need to have subtitles to have the table of content widget (TOC) useful. Otherwise, disable it in `_config.yml`

**Comment by TheBeachMaster** [comment]
D'oh! I had completely forgotten about `toc` ...
