### ISSUE TITLE
如何为博客添加目录 Widget

### ISSUE THREAD

**Issue by KunMinX** [ppoffice/hexo-theme-icarus#467]
icarus 模板用着挺舒服的，并且有个小小的疑问想咨询下：如何在博客右侧添加目录 Widget。

因为我们写作大都是使用 Markdown，希望能在查看正文时，右侧展示目录，以帮助读者快速掌握文章的结构，或快速实现跳转。

![](https://upload-images.jianshu.io/upload_images/57036-91dfa7ee8e6b2538.png)

**Comment by ppoffice** [comment]
@KunMinX https://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/Posts/table-of-contents-catalogue/

**Comment by KunMinX** [comment]
@ppoffice 好的，我试试！原来示例博客中早已提供了完备的使用说明、

**Comment by KunMinX** [comment]
@ppoffice 完美！

**Comment by obiscr** [comment]
@ppoffice 这个链接现在访问不了， https://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/Posts/table-of-contents-catalogue/  

请问新的链接是什么？
