### ISSUE TITLE
文章中自嵌入跳转目录无法正常使用

### ISSUE THREAD

**Issue by WAYRT** [ppoffice/hexo-theme-icarus#468]
比如 demo 中的这篇 https://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/Posts/table-of-contents-catalogue/ 在手机端点击文章内 [TOP] 无法跳转，如果在 PC 端把网页缩放比例调整至只有一栏布局时同样会出现此问题。这个功能还挺有用的，如果是 bug 的话希望可以修复下，谢谢了。

**Comment by ppoffice** [comment]
@WAYRT 这个只是一个示例，并不是功能。如果你需要返回顶部的话，可以使用返回顶部按钮
https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.theme.yml#L203

**Comment by WAYRT** [comment]
@ppoffice 其实我是想用这个方法在文章内部插入目录，因为在手机端 toc widget 不太方便，这个比较好。试了一下在 Hexo 默认主题 landscape 下没有出现这个无法跳转的问题，所以才想着是不是 bug 。
