### ISSUE TITLE
网站统计访问人数busuanzi_container_site_uv

### ISSUE THREAD

**Issue by removeif** [ppoffice/hexo-theme-icarus#469]
开启了统计的，但是页面没效果，看看怎么回事呢
[博客地址](https://removeif.github.io/)

**Comment by imaegoo** [comment]
不能重现。请检查Network中能否访问到`busuanzi.ibruce.info`的服务，以及response是否正常。
![busuanzi ibruce info](https://user-images.githubusercontent.com/20182252/57902742-543d1a80-789d-11e9-936b-91d39a0de919.png)

**Comment by removeif** [comment]
嗯谢谢，已经解决了，原来文章中有个标签是 <meta name="referrer" content="no-referrer">
导致请求统计的接口400了
改成以下就可以了：
<meta name="referrer" content="no-referrer-when-downgrade">

**Comment by removeif** [comment]
<m去掉eta name="referrer" content="no-referrer中文">
<m去掉eta name="referrer" content="no-referrer-w中文hen-downgrade">
