### ISSUE TITLE
目录滚动

### ISSUE THREAD

**Issue by zengzhanhang** [ppoffice/hexo-theme-icarus#470]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

想问一下如果文章左侧的目录太长，怎么滚动呢？？

**Comment by ppoffice** [comment]
@zengzhanhang 目前桌面端没有这个功能，移动端有。建议减少目录的层级，或者将下面一行

https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/widget/toc.ejs#L31

改为

```html
<div class="menu" style="max-height: 400px; overflow: auto;">
```

**Comment by zengzhanhang** [comment]
> @zengzhanhang 目前桌面端没有这个功能，移动端有。建议减少目录的层级，或者将下面一行
> 
> https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/widget/toc.ejs#L31
> 
> 改为
> 
> ```
> <div class="menu" style="max-height: 400px; overflow: auto;">
> ```

完美解决，谢谢！
