### ISSUE TITLE
zh-CN

### ISSUE THREAD

**Issue by jxxiao** [ppoffice/hexo-theme-icarus#471]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

更改了language: zh-CN，但是顶部导航栏还是英文，貌似zh-CN.yml没对顶部导航栏做处理。
第二个是，提供的文档真的有点乱。

**Comment by ppoffice** [comment]
Duplicate https://github.com/ppoffice/hexo-theme-icarus/issues/201
