### ISSUE TITLE
How to display post without any plugins

### ISSUE THREAD

**Issue by syedtocode** [ppoffice/hexo-theme-icarus#472]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

I would like to display the post on the full screen without any plugins with only the top level menu. In other words, I would like to hide all side plugins (like Links, Categories, tag cloud etc.,) when a post is clicked and opened from the main page. Is that possible?

**Comment by ppoffice** [comment]
@syedtocode Please put this in your posts' front-matter:

```yml
widgets: []
```

**Comment by syedtocode** [comment]
Fantastic, many thanks.
