### ISSUE TITLE
用iframe的时候显示是insecure content怎么解决？

### ISSUE THREAD

**Issue by zengzhanhang** [ppoffice/hexo-theme-icarus#473]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

![image](https://user-images.githubusercontent.com/31053687/58747783-bb46fb80-8467-11e9-8bf9-02f83ab5cd88.png)

我iframe的内容是jupyter notebook转成html的文件，用下面代码生成的
```
jupyter nbconvert --to html notebook.ipynb
```

网页的内容是想插入一段code，显示不安全内容后如下

![image](https://user-images.githubusercontent.com/31053687/58747825-648df180-8468-11e9-8792-d1a00ecff4bb.png)

**Comment by ppoffice** [comment]
@zengzhanhang 你的iframe需要和父页面一样使用https的地址

**Comment by zengzhanhang** [comment]
> @zengzhanhang 你的iframe需要和父页面一样使用https的地址

谢谢谢谢，解决了，原来是我少了个s，不太会这些知识，见笑了
