### ISSUE TITLE
设置了busuanzi=true，但是只有访客数量，没有访问量

### ISSUE THREAD

**Issue by telami** [ppoffice/hexo-theme-icarus#474]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

![Snipaste_2019-06-11_22-18-02](https://user-images.githubusercontent.com/25978237/59280400-1d89d280-8c98-11e9-8e31-fd02a3e70fc6.png)

通过release版本发现2.4.0已经支持pv、uv，但设置**busuanzi: true**后，只在页脚显示了共xxx个访客，查看代码，发现确实没有相应样式（busuanzi_value_site_pv）

![image](https://user-images.githubusercontent.com/25978237/59280477-398d7400-8c98-11e9-8869-04f1d1e685a5.png)

通过以下commit记录发现确实有过类似代码，但是不在master分支上。无论是git clone，还是下载source code方式,都没找到这次commit的代码。

[commit记录](https://github.com/ppoffice/hexo-theme-icarus/commit/7c359ba5ae827e212d93fad13fdc7e7ee1ede07f)

还有一个小问题，根目录的下的package.json 【"version": "2.3.0"】，不知道是不是漏改了。

非常喜欢这个主题，点赞~~

**Comment by telami** [comment]
![image](https://user-images.githubusercontent.com/25978237/59281351-b1a86980-8c99-11e9-9564-871757fdd64b.png)
好吧，看了history，这次提交删掉了页脚的pv，把pv提到了每篇文章上。

**Comment by telami** [comment]
Emmm,强迫症，我给加回来了
>footer.ejs 和 zh_CN.yml
```java
<span id="busuanzi_container_site_uv">
      <%- _p('plugin.visitor', '<span id="busuanzi_value_site_uv">0</span>') %>
</span>
<span id="busuanzi_container_site_pv">
      <%- _p('plugin.page-view', '<span id="busuanzi_value_site_pv">0</span>') %>
</span>

plugin:
    backtotop: '回到顶端'
    visit: '%s次访问'
    visitor: '共%s个访客'
    page-view: '共%s访问量'
```

**Comment by ZhongYueHui** [comment]
你好，请问这个目录结构在哪里呢？
