### ISSUE TITLE
长文章动画解析错误，右侧栏目无法展示

### ISSUE THREAD

**Issue by ThatMoment** [ppoffice/hexo-theme-icarus#477]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

我有一篇超过八千字的文章，生成之后头部的动画未解析出来导致页面无法渲染，把动画关闭后页面可以展示，但是右侧的最新文章、归档和标签不见了，如下图所示

![Jietu20190617-145739@2x](https://user-images.githubusercontent.com/7078573/59584351-569aca80-9110-11e9-8df2-07a33aaf1b08.jpg)

**Comment by ppoffice** [comment]
@ThatMoment 可以提供一下实例页面么？

**Comment by ThatMoment** [comment]
我发布到线上就可以了，本地预览的时候始终有问题，估计是哪个动画那个资源文件没加载出来 @ppoffice
