### ISSUE TITLE
gitalk未找到相关的 Issues 进行评论  请联系 @admin 初始化创建

### ISSUE THREAD

**Issue by removeif** [ppoffice/hexo-theme-icarus#478]
接入gitalk后进入页面，会有相关的初始化提示
![](https://raw.githubusercontent.com/removeif/blog_image/master/20190621101747.png)
需要去手动初始化issue,往上查阅有[解决办法](https://www.codercto.com/a/35485.html)
看下有时间可以加入版本中，方便使用

**Comment by removeif** [comment]
还发现自己去初始化还不能够创建需要的labels,不能包含有”，“的labels，这就比较尴尬了，还是我的操作有问题吗？js生成去访问的labels为：labels: Gitalk,5fff53009d151f291201230b0c5bebc0
![](https://raw.githubusercontent.com/removeif/blog_image/master/20190621103740.png)

**Comment by removeif** [comment]
[参考地址](https://removeif.github.io/%E5%8D%9A%E5%AE%A2%E5%9B%BE%E7%89%87%E4%B8%8A%E4%BC%A0picgo%E5%B7%A5%E5%85%B7github%E5%9B%BE%E4%BC%A0%E4%BD%BF%E7%94%A8.html)

**Comment by removeif** [comment]
不好意思，我弄错了，那时两个label，自动化初始issue的有空还是加入一下，感谢了

**Comment by ppoffice** [comment]
@removeif 不清楚你说的能不能用[`createIssueManually`](https://github.com/gitalk/gitalk#options)实现。如果你是指用nodejs程序按照sitemap来发送请求生成Issues的话，这个功能就超出本主题的范围了，建议自行添加。

**Comment by removeif** [comment]
> @removeif 不清楚你说的能不能用[`createIssueManually`](https://github.com/gitalk/gitalk#options)实现。如果你是指用nodejs程序按照sitemap来发送请求生成Issues的话，这个功能就超出本主题的范围了，建议自行添加。

ok,感谢！用**createIssueManually**已经解决了，在配置themes/icarus/layout/comment/gitalk.ejs中加了这个配置属性
![](https://raw.githubusercontent.com/removeif/blog_image/master/20190702143104.png)  
建议有时间可以把这属性加入版本中，这配置还是很需要的，特别针对于gitalk评论，同时也做成类似 client_id 这样的配置放到_config.yml，方便使用。
