### ISSUE TITLE
本站访客数<span id="busuanzi_value_site_uv"></span>人次

### ISSUE THREAD

**Issue by lqwater** [ppoffice/hexo-theme-icarus#479]
[新建文本文档 (2).txt](https://github.com/ppoffice/hexo-theme-icarus/files/3317549/2.txt)
Busuanzi访问人数出现错误怎么修改代码
结果是这个样子的：本站访客数713800人次

**Comment by lqwater** [comment]
代码如下：
footer class="footer">
    <div class="container">
        <div class="level">
            <div class="level-start has-text-centered-mobile">
                <a class="footer-logo is-block has-mb-6" href="<%- url_for('/') %>">
                <% if (has_config('logo.text') && get_config('logo.text')) { %>
                    <%= get_config('logo.text') %>
                <% } else { %>
                    <img src="<%- url_for(get_config('logo')) %>" alt="<%= get_config('title') %>" height="28">
                <% } %>
                </a>
                <p class="is-size-7">
                &copy; <%= date(new Date(), 'YYYY') %> <%= get_config('author') || get_config('title') %>&nbsp;
                Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> & <a
                        href="https://github.com/ppoffice/hexo-theme-icarus" target="_blank">Icarus</a>
                <% if (has_config('plugins.busuanzi') ? get_config('plugins.busuanzi') : false) { %>
                <br>
                <span id="busuanzi_container_site_uv">
                    本站访客数<span id="busuanzi_value_site_uv"></span>人次
                </span>
                <% } %>
                </p>
            </div>
            <div class="level-end">
            <% if (has_config('footer.links')) { %>
                <div class="field has-addons is-flex-center-mobile has-mt-5-mobile is-flex-wrap is-flex-middle">
                <% let links = get_config('footer.links'); %>
                <% for (let name in links) {
                        let link = links[name]; %>
                <p class="control">
                    <a class="button is-white <%= typeof(link) !== 'string' ? 'is-large' : '' %>" target="_blank" title="<%= name %>" href="<%= url_for(typeof(link) === 'string' ? link : link.url) %>">
                        <% if (typeof(link) === 'string') { %>
                        <%= name %>
                        <% } else { %>
                        <i class="<%= link.icon %>"></i>
                        <% } %>
                    </a>
                </p>
                <% } %>
                </div>
            <% } %>
            </div>
        </div>
    </div>
</footer>

**Comment by lqwater** [comment]
- [ ] 

`<footer class="footer">
    <div class="container">
        <div class="level">
            <div class="level-start has-text-centered-mobile">
                <a class="footer-logo is-block has-mb-6" href="<%- url_for('/') %>">
                <% if (has_config('logo.text') && get_config('logo.text')) { %>
                    <%= get_config('logo.text') %>
                <% } else { %>
                    <img src="<%- url_for(get_config('logo')) %>" alt="<%= get_config('title') %>" height="28">
                <% } %>
                </a>
                <p class="is-size-7">
                &copy; <%= date(new Date(), 'YYYY') %> <%= get_config('author') || get_config('title') %>&nbsp;
                Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> & <a
                        href="https://github.com/ppoffice/hexo-theme-icarus" target="_blank">Icarus</a>
                <% if (has_config('plugins.busuanzi') ? get_config('plugins.busuanzi') : false) { %>
                <br>
                <span id="busuanzi_container_site_uv">
                    本站访客数<span id="busuanzi_value_site_uv"></span>人次
                </span>
                <% } %>
                </p>
            </div>
            <div class="level-end">
            <% if (has_config('footer.links')) { %>
                <div class="field has-addons is-flex-center-mobile has-mt-5-mobile is-flex-wrap is-flex-middle">
                <% let links = get_config('footer.links'); %>
                <% for (let name in links) {
                        let link = links[name]; %>
                <p class="control">
                    <a class="button is-white <%= typeof(link) !== 'string' ? 'is-large' : '' %>" target="_blank" title="<%= name %>" href="<%= url_for(typeof(link) === 'string' ? link : link.url) %>">
                        <% if (typeof(link) === 'string') { %>
                        <%= name %>
                        <% } else { %>
                        <i class="<%= link.icon %>"></i>
                        <% } %>
                    </a>
                </p>
                <% } %>
                </div>
            <% } %>
            </div>
        </div>
    </div>
</footer>`

**Comment by lqwater** [comment]
`
[新建文本文档 (2).txt](https://github.com/ppoffice/hexo-theme-icarus/files/3317547/2.txt)

`

**Comment by ppoffice** [comment]
@lqwater 可以贴一下出错页面的地址么？另外你是指人数错误了么还是不蒜子统计有其他问题？

**Comment by lqwater** [comment]
@ppoffice已经解决了，在本地运行时会出现错误，推送到服务器后计数就正常了
