### ISSUE TITLE
How to increase the font for tags <ul> and <li> ?

### ISSUE THREAD

**Issue by online** [ppoffice/hexo-theme-icarus#48]
Hello!

Tell me, please, what kind of `.styl` files I needed to edit in order to increase the font size for these tags?

```
<ul>
<li>...</li>
<li>...</li>
<li>...</li>
</ul>
```

I would like to, for example, that for all `<ul>` and `<li>` tags in posts was specified size 16px. Please excuse me for my english, I hope, you can understand me.

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/_partial/article.styl#L74

**Comment by online** [comment]
@ppoffice, thank you for your reply, but, unfortunately, the size of the text for these elements is not increased.

**Comment by online** [comment]
@ppoffice, sorry, I understood. I have added to the file `icarus\source\css\_variables.styl` this:

```
font-size-ul-li = 16px
```

and then I added this to the file `icarus\source\css\_partial\article.styl`:

```
ul, ol, dl
	margin-top: line-height
	margin-bottom: line-height
	font-size: font-size-ul-li
```

Thanks for the help!
