### ISSUE TITLE
文章页的表格影响小尺寸上响应式布局会有超出内页（如果表格的列比较多）

### ISSUE THREAD

**Issue by lxqxsyu** [ppoffice/hexo-theme-icarus#480]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by removeif** [comment]
发现了此问题，列数少也有类似问题，如图
![](https://raw.githubusercontent.com/removeif/blog_image/master/20190625112557.png)
[地址](https://removeif.github.io/2019/06/25/%E4%B8%80%E6%AC%A1%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E6%AD%BB%E9%94%81%E9%97%AE%E9%A2%98%E6%8E%92%E6%9F%A5%E8%BF%87%E7%A8%8B.html#more)

**Comment by removeif** [comment]
不过这样也便于查看，好像也没啥毛病 [Facepalm]@ppoffice

**Comment by ppoffice** [comment]
@lxqxsyu @removeif 上传了一个简单的fix。另外如果想手动阻止表格溢出的话，也可以在`<table>`外面套上一个`<div class="table-overflow">`。

**Comment by lxqxsyu** [comment]
> @lxqxsyu @removeif 上传了一个简单的fix。另外如果想手动阻止表格溢出的话，也可以在`<table>`外面套上一个`<div class="table-overflow">`。

很赞，但是还是有些不完美，例如下面最右边的样子
![image](https://user-images.githubusercontent.com/7038254/60150840-dad60780-980c-11e9-8c9b-704332e1df44.png)

**Comment by ppoffice** [comment]
@lxqxsyu 可以提供一下页面的源文件么？

**Comment by lxqxsyu** [comment]
> @lxqxsyu 可以提供一下页面的源文件么？

```md
| 网站          | 作者         | 说明   | 链接 |
| :------------ | :----------- | :---- | :----- |
| 计算机图书    | Null         | pdf技术书籍下载  | https://www.codepdf.com   |
| itbook        | Fierce man   | pdf技术书籍下载 | https://itbook.download/  |
```

就类似这样的

**Comment by ppoffice** [comment]
@lxqxsyu 我想你应该是在页面家在完成后调整了浏览器的宽度了吧？如果是这样的话，建议手动加上`<div class="table-overflow">`，引文JavaScript脚本只在页面加载完成后执行一次。

**Comment by lxqxsyu** [comment]
> @lxqxsyu 我想你应该是在页面家在完成后调整了浏览器的宽度了吧？如果是这样的话，建议手动加上`<div class="table-overflow">`，引文JavaScript脚本只在页面加载完成后执行一次。

你猜对了，果然是这个问题，谢谢你的帮助，我感觉这个效果以及很好了

**Comment by lxqxsyu** [comment]
> > @lxqxsyu 我想你应该是在页面家在完成后调整了浏览器的宽度了吧？如果是这样的话，建议手动加上`<div class="table-overflow">`，引文JavaScript脚本只在页面加载完成后执行一次。
> 
> 你猜对了，果然是这个问题，谢谢你的帮助，我感觉这个效果以及很好了

![image](https://user-images.githubusercontent.com/7038254/60151124-2c32c680-980e-11e9-8406-ba6ad90f2c2b.png)

下面有滑块，可以左右滑动查看表格，很棒

**Comment by removeif** [comment]
感谢 @ppoffice 加了fix代码非常完了解决了
![](https://raw.githubusercontent.com/removeif/blog_image/master/20190627102224.png)
