### ISSUE TITLE
偶尔打开页面会一闪（右边文章栏全屏，有种内容错乱感）然后才正常布局，或者在点击上面菜单切换页面的时候也会遇到，特别是文章添加thubnail图片的时候更加明显（因为图片的大小变化明显）

### ISSUE THREAD

**Issue by lxqxsyu** [ppoffice/hexo-theme-icarus#481]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@lxqxsyu 请禁用动画，可能是你选择的cdn加载太慢造成的

**Comment by lxqxsyu** [comment]
> @lxqxsyu 请禁用动画，可能是你选择的cdn加载太慢造成的

好的，谢谢，其实这个问题影响不大
