### ISSUE TITLE
点击分类，如果这个分类下有很多文章则会全部显示出来，问题是没有分页，所以导致整个页面很长很长

### ISSUE THREAD

**Issue by lxqxsyu** [ppoffice/hexo-theme-icarus#483]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@lxqxsyu https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.yml#L71

**Comment by ppoffice** [comment]
#245

**Comment by lxqxsyu** [comment]
> @lxqxsyu https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.yml#L71

谢谢，已解决
