### ISSUE TITLE
使用sharejs的时候，如果文章是中文的，微信分享二维码异常无法扫

### ISSUE THREAD

**Issue by panxiaoguang** [ppoffice/hexo-theme-icarus#484]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@panxiaoguang 可以提供一下出问题的页面么？我在本地无法复现此问题。

**Comment by panxiaoguang** [comment]
> @panxiaoguang 可以提供一下出问题的页面么？我在本地无法复现此问题。
https://panxiaoguang.github.io/2019/06/20/%E4%B8%80%E6%96%87%E8%AF%BB%E6%87%82lncRNA%E5%88%86%E6%9E%90/,这是一篇文章，这里我将文章三栏改成了两栏，是不是因为css文件的原因啊？

**Comment by ppoffice** [comment]
@panxiaoguang 从![页面源代码](view-source:https://panxiaoguang.github.io/2019/06/20/%E4%B8%80%E6%96%87%E8%AF%BB%E6%87%82lncRNA%E5%88%86%E6%9E%90/)上来开你并没有启用微信二维码。请检查你的主题配置文件看下微信二维码的图片地址是否设置。

**Comment by panxiaoguang** [comment]
> @panxiaoguang 从上来开你并没有启用微信二维码。请检查你的主题配置文件看下微信二维码的图片地址是否设置。

抱歉，我可能让您误解了，我的意思不是赞赏的二维码，而是分享的二维码，赞赏我确实只开启了支付宝的

**Comment by ppoffice** [comment]
![Screenshot_20190628-091129](https://user-images.githubusercontent.com/8849362/60344616-f19f6a00-9984-11e9-80d5-45c401981384.png)
@panxiaoguang 我这里没有问题，一切正常呀

**Comment by panxiaoguang** [comment]
> ![Screenshot_20190628-091129](https://user-images.githubusercontent.com/8849362/60344616-f19f6a00-9984-11e9-80d5-45c401981384.png)
> @panxiaoguang 我这里没有问题，一切正常呀

对，二维码显示是正常的，但是手机识别不了，相反，关于我页面的分享就可以很快识别

**Comment by nameussi** [comment]
我试扫了下，可以识别啊，一切正常

**Comment by ppoffice** [comment]
@panxiaoguang 请尝试换个手机扫一下。我这边无论是扫网页还是扫你的截图，二维码均能识别

**Comment by panxiaoguang** [comment]
> @panxiaoguang 请尝试换个手机扫一下。我这边无论是扫网页还是截图，二维码均能识别。
> 可能造成这种不识别的原因是二维码信息量太大而图片尺寸太小，手机摄像头分辨率不高的话可能扫不清楚。解决办法是自己修改sharejs的CSS或者联系其作者增加图片的尺寸。要么就是把文章的路径改为英文的，且长度可以短一点，这样二维码的信息量也会少一些。
> 
> https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.yml#L17
> https://hexo.io/docs/permalinks

好的，万分感谢，现在看来却是因为标题信息量太高而图片太小造成二维码过密的原因
