### ISSUE TITLE
文章下一篇按钮

### ISSUE THREAD

**Issue by tianjindong** [ppoffice/hexo-theme-icarus#485]
文章的底部的下一页按钮，现在显示的是比这篇文章发布时间早的文章，感觉显示比当前的文章发布时间迟的会比较好。
The next page button at the bottom of the article now shows articles earlier than this one. It feels better to show them later than the current one.

**Comment by ppoffice** [comment]
@tianjindong 这与文章的排序有关，如果文章是从旧到新排序的，那么下一片就是更新的文章
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.ejs#L110

**Comment by tianjindong** [comment]
@ppoffice 谢谢您的指导，将/layout/common/article.ejs改为下列代码即可：[更改细节](https://github.com/tianjindong/hexo-theme-icarus/commit/47186e5ad8649f46a0498ed7a4e5792b0e4cfbd8)
