### ISSUE TITLE
deploy后页面空白

### ISSUE THREAD

**Issue by MoveCloudROY** [ppoffice/hexo-theme-icarus#489]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

----

![](https://upload-images.jianshu.io/upload_images/13056869-ac5341662ecae040.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

deploy到coding上后页面空白

可以在[链接](https://maker.movecloud.xyz)上查看

**Comment by ppoffice** [comment]
@MoveCloudROY 请检查你的Hexo博客配置（非主题配置）
https://hexo.io/docs/configuration#URL

**Comment by MoveCloudROY** [comment]
ok


```
url: http://maker.movecloud.xyz
root: 
permalink: :year/:month/:day/:title/
permalink_defaults:
```

变为

```
url: http://maker.movecloud.xyz
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```
