### ISSUE TITLE
多语言和页面宽度问题

### ISSUE THREAD

**Issue by klkucan** [ppoffice/hexo-theme-icarus#490]
1、多语言按照网站的介绍改了，但是目前menu部分仍旧无法做到中文，其它部分都是中文了。
2、当前页面主container两边留白太大，中间的博文部分比较窄，请问如何修改这些宽度呢？

PS：read more这个添加tags无法实现，最后还是在文章中添加了more标签来实现的。不确定这个是不是bug。

**Comment by ppoffice** [comment]
@klkucan 
https://github.com/ppoffice/hexo-theme-icarus/issues/325
https://github.com/ppoffice/hexo-theme-icarus/issues/434

**Comment by ppoffice** [comment]
@klkucan 不太清楚你说的read more和添加tags是什么意思。`<!-- more -->`是实现文章摘要所必需的。

**Comment by klkucan** [comment]
@ppoffice  readmore是指的 https://blog.zhangruipeng.me/hexo-theme-icarus/uncategorized/faq/ 中的描述，不过我发现应该是我理解错了，目前readmore应该只有通过添加标签的途径。

**Comment by timorpic** [comment]
@``
