### ISSUE TITLE
How can I install emoji plugin?

### ISSUE THREAD

**Issue by PeterCha90** [ppoffice/hexo-theme-icarus#493]
Hi.

I'm really appreciate for this concise and  beautiful theme. 

However, there is the one thing I feel sorry to this app, emoji. 
It doesn't support emoji at all as I know. 

If I am misunderstanding your theme, let me know. 
Thank you :)

**Comment by ppoffice** [comment]
@PeterCha90 https://github.com/ppoffice/hexo-theme-icarus/blob/site/package.json#L13

**Comment by PeterCha90** [comment]
Thanx a lot!! 👍 👍 👍 💯
