### ISSUE TITLE
Multi language support: First Steps

### ISSUE THREAD

**Issue by twatzl** [ppoffice/hexo-theme-icarus#494]
Hello, 
I have spent the last 2 days setting up a multi lingual blog using the icarus theme and wanted to share my progress on that. 

My changes are currently available at my fork https://github.com/twatzl/hexo-theme-icarus, because there is still some things to do before it can be merged and I don't know if I should already open a PR.

I have been using the plugin https://github.com/Jamling/hexo-generator-i18n

Basically it generates n versions of the blog. One for each language.

The following issues still need to be addressed:
- wrapper function to make it possible to continue using icarus without the hexo-generator-i18n
- better handling of the internationalization of the menu items
- dynamic management of the language picker
- archive count, categories and tags need more work
- a way to add multilingual posts. i.e. posts which are shown in more than one language. Currently a post is only shown in the language it is written in.
- adaption of the other language files (add lang and Language property, add the supported languages themselves as strings to each file)
- check if all widgets and plugins are adapted

So far I achieved the following
- show only posts of the current language
- change language of all widget headings
- change language of the menu items
- add a dropdown for choosing the language

I would be happy if we could continue on this path, but since I am not a total expert with hexo I might need some help.

Kind Regards

**Comment by Chanmi-Kim** [comment]
Hello, I have a question.
I was very impressed with your customizing.
It was my a priority of problem. 
But, I cannot apply your "**show only posts of the current language**". 
I have no idea how to do that. 
**Would you don't mind, could you explain more detail?** 
I want to apply **Korean** and **English**.
