### ISSUE TITLE
Bug: when `hexo g`  the built-in images folder is also packaged

### ISSUE THREAD

**Issue by zhutmost** [ppoffice/hexo-theme-icarus#495]
When I use `hexo g` to generate static web files, the images folder which comes with this theme will be also packaged. However, they should not to appear on the user's site.

![image](https://user-images.githubusercontent.com/20497382/61857773-58b62d00-aef7-11e9-9cc6-9618b89a1d05.png)

As depicted in the above figure, the generated public folder contains the images folder. The content of this folder is the same as the one in this theme. This pictures and logos should be removed from the hexo-generate flow.

- [Yes] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [Yes] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by zhutmost** [comment]
If users create a folder with the same name `images` in the `BLOG/source/`, Hexo cannot generate a correct path to this folder. The images folder that comes with the theme will partially overwrite the user's one.

**Comment by ppoffice** [comment]
@You can choose to rename your images folder or the theme's one, except you also need to change the code in the latter case.

**Comment by zhutmost** [comment]
I know that. My point is that the built-in folder shouldn't be included on my site.
Renaming the user images folder can only partially solve the problem.

Actually, the images in the `icarus/images` are revoked here and there. This is my `index.html` generated by `hexo g`.
![image](https://user-images.githubusercontent.com/20497382/61935055-3d612580-afbc-11e9-99dc-e26680966c1d.png)
![image](https://user-images.githubusercontent.com/20497382/61935081-4b16ab00-afbc-11e9-9897-58f968b3ab86.png)
The built-in images appears in this file four times.

**Comment by zhutmost** [comment]
These images may mislead the search engine spiders and even the users.

As far as I know, there is no way to configure `og-image`. (Maybe it is another issue.

**Comment by ppoffice** [comment]
@zhutmost Can you give more details on how does this folder name mislead spiders and users?

**Comment by zhutmost** [comment]
Because the OpenGraph revokes the built-in Icarus image as `og:image`, when users share the blog pages to SNS websites, such as Facebook, the shared link may have an incorrect cover image. 

The search engines will catch OG properties for SEO. I am not sure how they deal with the field `og:image`, especially when two websites with the same `og:image`.

We had better add one more option to allow user to specify their own image as `og:image` to avoid this situation.

**Comment by zhutmost** [comment]
As for my original intention in this issue (the built-in folder packaging when hexo-g), I find that it is a common problem for other hexo themes. Anything in the theme source folders will be packaged although some of them are just for an example site. 

Hexo doesn't have an example website mechanism for themes like Hugo. Some Hexo themes encourage users to overwrite the built-in logo/favicon in `theme/source/` as workaround.

**Comment by ppoffice** [comment]
@zhutmost You can set OG custom images either by specifying the path to the image explicitly (`og_image` in post's front-matter) or set the thumbnail of the post as an alternative.

https://github.com/ppoffice/hexo-theme-icarus/blob/3cd4b5dc4737821deb219d4b8b15df369e02c438/includes/helpers/page.js#L63-L86

**Comment by zhutmost** [comment]
Thanks for your workaround. 

Maybe you can add one more option in the `_config.yml` to allow users to specify a site-level default og-image to replace `/images/og_image.png` in the following line. 
```javascript
og_image = getConfig('article.og_image', '/images/og_image.png'); 
```

**Comment by ppoffice** [comment]
@zhutmost Just put this in your theme config:

```yaml
article:
    og_image: /path/to/your/pic.xxx
```
