### ISSUE TITLE
侧栏右上角会显示一些文章的链接，可是图片是空的，如何设置文章图片啊

### ISSUE THREAD

**Issue by molu-ggg** [ppoffice/hexo-theme-icarus#497]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@molu-ggg 请阅读文档和搜索issues.
