### ISSUE TITLE
如何在文章页面隐藏资料卡profile 

### ISSUE THREAD

**Issue by manyhelp** [ppoffice/hexo-theme-icarus#498]
需要在文章阅读的时候隐藏  profile ，那个位置用 toc 代替

**Comment by ppoffice** [comment]
@manyhelp 没有此类设置。你可以选择在文章的front-matter重新设置所有的widgets或者修改源代码。

**Comment by da0mao** [comment]
找到profile.ejs文件
_\Hexo\themes\icarus\layout\widget\profile.ejs_

最外面加上：
```
<% if (page.__page !== true && page.__post !== true) { %>
......
<% } %>
```
效果可以看[我的网站](https://maologue.com)
