### ISSUE TITLE
how to enable pavicon

### ISSUE THREAD

**Issue by IlhamSetiawan** [ppoffice/hexo-theme-icarus#499]
Hello, I'm really happy with your theme.
but there are a few troublesome problems
how to activate the favicon
![xw](https://user-images.githubusercontent.com/37190439/62020622-f0fd2c00-b1ed-11e9-9a1a-cb95c8469f27.png) so it doesn't look like this
thanks !!

**Comment by manyhelp** [comment]
You need to read the document.

https://blog.zhangruipeng.me/hexo-theme-icarus/categories/

**Comment by ppoffice** [comment]
@IlhamSetiawan https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.theme.yml#L4
