### ISSUE TITLE
大佬能否给个详细的压缩方案，感谢

### ISSUE THREAD

**Issue by manyhelp** [ppoffice/hexo-theme-icarus#500]
使用的gulp老没好，JS和图片都没成功。感谢

**Comment by ppoffice** [comment]
@manyhelp https://github.com/ppoffice/hexo-theme-icarus/blob/site/package.json#L11

**Comment by manyhelp** [comment]
@ppoffice  报错了
`\themes\icarus\layout\post.ejs:1
 >> 1| <%- partial('common/article', {post: page, index: false}) %>

Parse Error: <<span class="hljs-name">Connector</span> <span class="hljs-attr">port</span>=<span class="hljs-string">"8081"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">protocol</span>=<span class="hljs-string">"org.apache.coyote.http11.Http11NioProtocol"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">executor</span>=<span class="hljs-string">"tomcatThreadPool"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">compression</span>=<span class="hljs-string">"on"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">maxHttpHeaderSize</span>=<span class="hljs-string">"8192"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">compressionMinSize</span>=<span class="hljs-string">"2048"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">maxThreads</span>=<span class="hljs-string">"30000"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">minSpareThreads</span>=<span class="hljs-string">"512"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">enableLookups</span>=<span class="hljs-string">"false"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">redirectPort</span>=<span class="hljs-string">"8443"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">acceptCount</span>=<span class="hljs-string">"35000"</span></span></span><br><span class="line"><span class="hljs-tag">            <span class="hljs-attr">connectionTimeout</span>=<span class="hljs-string">"40000"</span></span></span><br><span class="line"><span class="hljs-tag">`
