### ISSUE TITLE
标题超长的问题

### ISSUE THREAD

**Issue by manyhelp** [ppoffice/hexo-theme-icarus#502]
主题目前存在标题超长后，显示问题。

需要大佬处理，英文和中文两种情况的超长问题。

字符长度不同

**Comment by manyhelp** [comment]
`出现 NoClassDefFoundError:com/fasterxml/jackson/core/JsonProcessingException`

比如这个标题，在正文里面的话，还会影响手机版本的布局。整个页面放大，可以左右移动

**Comment by ppoffice** [comment]
@manyhelp 我这里在桌面状态下文字会溢出，手机端不会溢出，页面也不会可以缩放。
可以说明一下你用的浏览器并附上出问题的页面截图么？

**Comment by manyhelp** [comment]
@ppoffice  应该是我没表述清楚：
1.标题是在侧栏，文字会溢出
2.标题在首页中间栏，会自动换行。出现空格的话，会在空格处换行（好像是，没详细测试），如标题为：
`Springmvc4 com/fasterxml/jackson/core/JsonProcessingException`
这里Springmvc4后面跟了一个空格
3.手机模式，正文内容如下，会出现文字溢出
`springmvc4 集成 hibernate4 出现 NoClassDefFoundError:com/fasterxml/jackson/core/JsonProcessingException`
这个是一行文字。

**Comment by TieWay59** [comment]
![Screenshot_2019_0806_100204](https://user-images.githubusercontent.com/40034603/62506072-c5072980-b831-11e9-91df-26cd972236eb.jpg)


![Screenshot_2019_0806_100216](https://user-images.githubusercontent.com/40034603/62506120-ecf68d00-b831-11e9-8f93-b37560f32025.png)

我补充两个例子，我手机上截图好像确实也有截断的细节，主要是`长链接`与`菜单栏`，长连接是我写的时候不太注意，意外发现这个有点显示异常···

**Comment by ppoffice** [comment]
@TieWay59  感谢反馈，菜单栏位置问题有可能同样是链接溢出导致了。请更新主题代码到最新版本以测试问题是否解决。

**Comment by TieWay59** [comment]
我的问题修复了，非常棒。
![Screenshot_2019_0806_113252](https://user-images.githubusercontent.com/40034603/62509482-f5ed5b80-b83d-11e9-9740-22b3b02843f3.jpg)
![Screenshot_2019_0806_113245](https://user-images.githubusercontent.com/40034603/62509483-f71e8880-b83d-11e9-9953-f9b3a460377a.jpg)
