### ISSUE TITLE
网站logo favicon 设置无法生效

### ISSUE THREAD

**Issue by yukunshang** [ppoffice/hexo-theme-icarus#503]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [yes ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [yes] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

当我想配置 favicon 的时候， 发现无法生效；

![image](https://user-images.githubusercontent.com/25716306/62542746-011ca780-b88f-11e9-886f-3094d6006d9b.png)
![image](https://user-images.githubusercontent.com/25716306/62542760-07ab1f00-b88f-11e9-89c4-b84ef0bd4546.png)
![image](https://user-images.githubusercontent.com/25716306/62542772-11cd1d80-b88f-11e9-99a8-7d46abb7a68c.png)
清除缓存等排查过后 还是无法生效； 也没有报错信息。

求解答。

**Comment by ppoffice** [comment]
@yukunshang 你是不是改动过主题的源码了？生成的HTML格式明显不对，开头这几行不能放在<html>标签之外。否则Chrome无法正确解析你的网页，自然就不会显示favicon了。
https://github.com/yukunshang/yukunshang.github.io/blob/master/index.html#L2-L4

**Comment by yukunshang** [comment]
@ppoffice 是这样啊 已解决 谢谢。
