### ISSUE TITLE
关于justified-gallery多出p标签

### ISSUE THREAD

**Issue by yukunshang** [ppoffice/hexo-theme-icarus#504]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ yes ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ yes ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

您好， 我在设置`album` 的时候 发现显示不出`justified-gallery`的效果。具体情况如下：
![image](https://user-images.githubusercontent.com/25716306/62562439-bd886480-b8b3-11e9-95cb-fb28b4d65da3.png)
我的md文件如下：
![image](https://user-images.githubusercontent.com/25716306/62562479-d4c75200-b8b3-11e9-9085-f23c5893b8ec.png)
我的`gallery.js` 如下：
![image](https://user-images.githubusercontent.com/25716306/62562548-ead51280-b8b3-11e9-8d36-931bfb7a9c52.png)

可以看到 该页面情况：
![image](https://user-images.githubusercontent.com/25716306/62562636-21ab2880-b8b4-11e9-86ac-e835aa16362b.png)
多出`<p>`标签

求解答。谢谢！

**Comment by jerryc127** [comment]
你解决了吗

**Comment by punksinatra** [comment]
I am having the same issue.. when I view it locally using hexo server all images are justified but after I upload it to my webserver all images not justified

local using hexo server
![hexo local server](https://user-images.githubusercontent.com/22606153/93595271-059c1500-f9ea-11ea-9517-7b10d089797e.PNG)

Online webserver
![hexo online server](https://user-images.githubusercontent.com/22606153/93595290-0e8ce680-f9ea-11ea-93fa-f540eff125ef.PNG)
