### ISSUE TITLE
文章中媒体文件上下边距不一致

### ISSUE THREAD

**Issue by WAYRT** [ppoffice/hexo-theme-icarus#505]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

文章中插入视频或音乐时下边距太靠近文字了，排版上感觉不太美观和舒服，请问有办法修改一下吗？尝试加入过`margin-bottom`，但是没有效果

![eqAWwD.png](https://s2.ax1x.com/2019/08/09/eqAWwD.png)

**Comment by ppoffice** [comment]
@WAYRT 可以提供你博客的网址么？

**Comment by ppoffice** [comment]
@WAYRT 你可以尝试把你的媒体对象用`<p></p>`包裹起来

**Comment by WAYRT** [comment]
@ppoffice 此方法可行，问题解决了，谢谢
