### ISSUE TITLE
自定义widgets问题

### ISSUE THREAD

**Issue by removeif** [ppoffice/hexo-theme-icarus#506]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

您好，麻烦请问一下，我现在要自定义一个widgets,在以下目录增加了一个文件，同时参考links的写了些内容，
![](https://raw.githubusercontent.com/removeif/blog_image/master/img/2019/20190810172620.png)
然后在类似的配置文件中加了内容，编译部署没效果，
![](https://raw.githubusercontent.com/removeif/blog_image/master/img/2019/20190810172928.png)
请问还需要改其他的什么文件吗？谢谢

**Comment by ppoffice** [comment]
@removeif widgets的话单个文件应该能满足需要

**Comment by removeif** [comment]
> @removeif widgets的话单个文件应该能满足需要

啥意思，没太明白？🤣

**Comment by ppoffice** [comment]
@removeif 就是不需要修改其他文件了

**Comment by removeif** [comment]
> @removeif 就是不需要修改其他文件了
嗯 谢谢了 我追了下代码好像其他地方也不没有设置的，这里倒是有一个设置相关的，但是好像也只是默认值，我在多试试吧😂
![](https://raw.githubusercontent.com/removeif/blog_image/master/img/2019/20190810222811.png)

**Comment by removeif** [comment]
> @removeif 就是不需要修改其他文件了

![](https://raw.githubusercontent.com/removeif/blog_image/master/img/2019/20190810224340.png)
应该是哪里还有控制的，复制了一个，一模一样的links1,但是也只展示的links,没展示links1的，有空的时候麻烦帮忙看一下，感谢 🤝

**Comment by ppoffice** [comment]
@removeif `hexo clean`一下试试？另外你重新启动`hexo s`了么

**Comment by removeif** [comment]
> @removeif `hexo clean`一下试试？另外你重新启动`hexo s`了么

@ppoffice 嗯，每次我都是hexo clean， 然后 编译， 然后hexo s 。也没效果，你那里有空麻烦复制一个links试试有没有效果，看看会不会是我的版本啥的不对。

**Comment by ppoffice** [comment]
@removeif 你把你博客的源码包括对主题的修改上传到GitHub上我看下

**Comment by removeif** [comment]
> @removeif 你把你博客的源码包括对主题的修改上传到GitHub上我看下

@ppoffice 仓库项目加你了哦，再次感谢🤝

**Comment by ppoffice** [comment]
@removeif 
```diff
- <% const links = get_config_from_obj(widget, 'links1'); %>
+ <% const links = get_config_from_obj(widget, 'links'); %>
```

**Comment by removeif** [comment]
> @removeif
> 
> ```diff
> - <% const links = get_config_from_obj(widget, 'links1'); %>
> + <% const links = get_config_from_obj(widget, 'links'); %>
> ```

@ppoffice 好嘛，原来是这样对应的，感谢了🤝

**Comment by yuanjh6** [comment]
> @removeif
> 
> ```diff
> - <% const links = get_config_from_obj(widget, 'links1'); %>
> + <% const links = get_config_from_obj(widget, 'links'); %>
> ```

牛批，这种问题很难发现

**Comment by V2beach** [comment]
原来如此
