### ISSUE TITLE
刷新问题

### ISSUE THREAD

**Issue by LeoAshin** [ppoffice/hexo-theme-icarus#507]
能不能就中间内容异步刷新呢, 点什么都会重新刷一次页面有点难受

**Comment by ppoffice** [comment]
@LeoAshin 可以考虑使用pjax

**Comment by LeoAshin** [comment]
昨天尝试过引入,但是对于这种引入有点无从下手 ....

**Comment by LeoAshin** [comment]
已经搞定了, 定义好id 再在main.js里定义一下就OK了

> @LeoAshin 可以考虑使用pjax

**Comment by boxlab** [comment]
你好，请问您可以分享一下您的引入方法吗

**Comment by wonderomg** [comment]
> 

同求具体细节
