### ISSUE TITLE
请问 inline code 是否能在外面加上方框？

### ISSUE THREAD

**Issue by da0mao** [ppoffice/hexo-theme-icarus#508]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

比如`code`在这里可以被框起来，但是在博客中却是高亮为红色， 有什么办法解决吗？
谢谢！

![image](https://user-images.githubusercontent.com/51474403/62830392-d2ad1c80-bc40-11e9-820b-754c951fa7ef.png)

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/style.styl#L342

**Comment by da0mao** [comment]
谢谢！搞定了！
![image](https://user-images.githubusercontent.com/51474403/62830871-78b05500-bc48-11e9-8e3f-e4f517ed043b.png)
