### ISSUE TITLE
个性发布时间BUG，13小时前发布的会显示5小时前

### ISSUE THREAD

**Issue by note4** [ppoffice/hexo-theme-icarus#509]
如图，内容是13小时前提交的，但是由于模板的做法是将多久前更新通过生成功能写入html中所以，这一时间被定格，可能内容是30小时前更新，如果不重新生成页面或者提交，页面中会一直显示5小时前更新。
假设方案，html显示时间，js处理实时运算多久前发布。

![image](https://user-images.githubusercontent.com/6513389/62841921-08eda900-bce0-11e9-8e23-a35263968da9.png)

![image](https://user-images.githubusercontent.com/6513389/62841888-c75cfe00-bcdf-11e9-9930-b9e3c68ed528.png)

**Comment by ppoffice** [comment]
@note4 这个bug很早之前就修复了呀？
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/js/main.js#L12-L16
你用的是什么版本的Icarus？

**Comment by note4** [comment]
version: 2.3.0

> @note4 这个bug很早之前就修复了呀？
> https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/js/main.js#L12-L16
> 你用的是什么版本的Icarus？

version: 2.3.0

**Comment by note4** [comment]
是上月底装的，更新以后好了
