### ISSUE TITLE
Improve generation speed

### ISSUE THREAD

**Issue by jiangtj** [ppoffice/hexo-theme-icarus#513]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

See https://gitlab.com/JiangTJ/performance-test-hexo/-/jobs/271513475

I tested the generate speed of multiple themes in the initial configuration environment with many post files. The default theme is about 36s. But icarus explodes abnormally after a long time of generation (several minutes).

**Comment by ppoffice** [comment]
@jiangtj Please retry your tests with the `oom` branch.

**Comment by jiangtj** [comment]
https://gitlab.com/JiangTJ/performance-test-hexo/-/jobs/272085081
wow, about 13s 👍

**Comment by ppoffice** [comment]
@jiangtj I removed meta_generator from the hexo, which is causing the out of memory issue. I should look into this if I have time

**Comment by jiangtj** [comment]
https://gitlab.com/JiangTJ/performance-test-hexo/-/jobs/272794038
Yeah, meta_generator has issue. And the NexT theme seems to have some other issues that affect performance.

**Comment by jiangtj** [comment]
https://gitlab.com/JiangTJ/performance-test-hexo/-/jobs/272854627
Measured when there are a lot of tags, it seems that icarus is not very good, has been generating

**Comment by ppoffice** [comment]
@jiangtj There was a huge bug in the previous `oom` branch. So I took away that change as well as the performance boost came with that change. I rewrite the optimization part and its in the `oom` branch now.
https://github.com/ppoffice/hexo-theme-icarus/commit/958138f2140010e4953cbecb923945fce85b642c

**Comment by jiangtj** [comment]
```
Test performance running ... 
theme: icarus
INFO  Files loaded in 25 s
INFO  1426 files generated in 38 s
-------------------------------------
```

Good !
