### ISSUE TITLE
js资源加载问题

### ISSUE THREAD

**Issue by LeoAshin** [ppoffice/hexo-theme-icarus#514]
今天出现了https相关的问题, 看了下你的yml配置貌似都是https的连接, 怎么今天加载出来的是http?
![image](https://user-images.githubusercontent.com/8603943/63030610-2dff3900-bee5-11e9-9598-cf7cbe75b878.png)

**Comment by ppoffice** [comment]
@LeoAshin 请升级你的主题版本

**Comment by LeoAshin** [comment]
升级之后, 开始其他错误了
![image](https://user-images.githubusercontent.com/8603943/63104613-e5618180-bfb1-11e9-8c5d-273b1cc0ba71.png)

**Comment by ppoffice** [comment]
@LeoAshin 你运行的时候看到任何的WARNING了么？如果看到了，就说明你的配置文件也要升级了

**Comment by zhouweitong3** [comment]
这个plugin/clipboard升级完配置文件也会有报错，把这个文件补回来就没事了...

**Comment by LeoAshin** [comment]
了解 . 作为一个前端门外汉.  我压力很大
