### ISSUE TITLE
Partial plugin/clipboard does not exist. (in common/head.ejs)

### ISSUE THREAD

**Issue by zhouweitong3** [ppoffice/hexo-theme-icarus#515]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

渲染的时候需要这个 clipboard.ejs，最新的 2.6.0 的 zip 包里面（包括现在的 master 分支里面）都没有这个文件，用 2.5.0 的 clipboard.ejs 复制到 layout/plugin 下可以正常渲染，是不是误删除了这个文件呢...

**Comment by ppoffice** [comment]
@zhouweitong3 https://github.com/ppoffice/hexo-theme-icarus/issues/514#issuecomment-521683646
