### ISSUE TITLE
errors happen when generating

### ISSUE THREAD

**Issue by dlc1994** [ppoffice/hexo-theme-icarus#517]
Could somebody help me fixed this problem ? This problem seems to cause mathjax error in my posts.
![image](https://user-images.githubusercontent.com/13445045/63206354-49d12d80-c0e5-11e9-859a-c470e3f166dd.png)

Please make sure you took care of the following things before you submit this issue. Thank you!

- [√ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [√ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by dlc1994** [comment]
> @dlc1994 What's your Hexo and Icarus version? What's your theme configurations? Did you modify any part of the theme source code?

```
INFO  Checking dependencies
INFO  Validating the configuration file
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.17763 win32 x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```
I do modify some parts of the theme, add many plugins and widgets

**Comment by ppoffice** [comment]
@dlc1994 Please upgrade your dependencies in the package.json. Here is a reference

https://github.com/ppoffice/hexo-theme-icarus/blob/site/package.json

Also, the problem could be caused by your modifications or third party libraries. You should enable them one by one to figure out where this problem comes from.

**Comment by dlc1994** [comment]
Thanks a lot
