### ISSUE TITLE
[Feature]图片延迟加载

### ISSUE THREAD

**Issue by JZLeung** [ppoffice/hexo-theme-icarus#520]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

貌似没找到可以开启延迟加载图片的配置项。
现在博客加入大量图片，不大，但是很多，页面就会一直处在 Loading 状态，十分影响体验。

**Comment by da0mao** [comment]
consider [$npm install hexo-lazyload-image --save](https://maologue.com/Optimize-Hexo-with-Lazy-loading/)

**Comment by ppoffice** [comment]
I'm closing this now since this feature can be achieved using a third-party extension.
