### ISSUE TITLE
首页头像位置乱掉了

### ISSUE THREAD

**Issue by punklu** [ppoffice/hexo-theme-icarus#522]
![7BDF8E3D-921C-4c78-817B-0F8BC6148F6F](https://user-images.githubusercontent.com/50325831/63997814-26b96b80-cb32-11e9-8601-14eb1e049ad4.png)

更新主题之后也没用，希望能修复一下

**Comment by ppoffice** [comment]
@punklu 请提供更多的信息，例如出问题的页面的在线地址，所用的主题配置文件，以及是否对主题进行了任何修改。

**Comment by punklu** [comment]
> @punklu 请提供更多的信息，例如出问题的页面的在线地址，所用的主题配置文件，以及是否对主题进行了任何修改。

我重新复现了一下，是在头像下面的博客昵称名字和个人说明这两个内容输入值多了以后，头像位置乱掉的，如果没有个人说明，昵称长一点位置就稍微偏左一点，加上个人说明之后，头像位置就很偏左了

**Comment by punklu** [comment]
页面在线地址：punklu.tech，
![image](https://user-images.githubusercontent.com/50325831/64084946-5b136e80-cd62-11e9-8fbd-15f8d86cc472.png)
![image](https://user-images.githubusercontent.com/50325831/64084951-66ff3080-cd62-11e9-8f2f-a804e6d2f495.png)
![image](https://user-images.githubusercontent.com/50325831/64084952-6bc3e480-cd62-11e9-828f-7adfb6aed8e4.png)

**Comment by punklu** [comment]
请问这个要怎么更改呢，我在root/.halo/templates/themes/ppoffice_icarus/source/css下面找到了style.styl，但是没在ppoffice_icarus/layout/widget下边找到profile.ejs文件，只找到了profile.etl,我在后台点了更新也没更新下来最新代码，头像还是乱的

**Comment by ppoffice** [comment]
@punklu 我不清楚你用的是什么软件，也不知道profile.etl是什么。但是我已经修复了这个bug，你需要做的就是更新主题到最新的master分支。如果无法更新的话也可以考虑从头开始设置新的博客，导入之前的文章。
