### ISSUE TITLE
Submenu

### ISSUE THREAD

**Issue by vincewenminli** [ppoffice/hexo-theme-icarus#527]
> 请问如何增加二级菜单导航呢
> 例如这样
> ![test](https://camo.githubusercontent.com/10d099122db1ee0ee260227076546fc15435fe1e/68747470733a2f2f7373302e62616964752e636f6d2f364f4e57736a69703051495a387479686e712f69742f753d323439363639363239342c3333383138353735313526666d3d313733266170703d343926663d4a5045473f773d36343026683d33333226733d3438443037313845344433313334383843433030333041313033303031303935)

可否告知修改思路，感觉一级菜单不够用，太多的话又显得冗余，非常感谢您!

_Originally posted by @vincewenminli in https://github.com/ppoffice/hexo-theme-icarus/issues/157#issuecomment-527343452_

How to add such sub-menu item? 
Here is another example https://theme-next.org/docs/getting-started/ .

**Comment by nameussi** [comment]
可以参考主题所用的 Bulma 框架添加下拉菜单 https://bulma.io/documentation/components/navbar/

之前我也试着添加过，后来没成功，放弃了。

**Comment by vincewenminli** [comment]
好的谢谢，我看navbar.ejs里面没有写对dropdown的处理代码，需要自己加。我试试吧...

**Comment by vincewenminli** [comment]
> 可以参考主题所用的 Bulma 框架添加下拉菜单 https://bulma.io/documentation/components/navbar/
> 
> 之前我也试着添加过，后来没成功，放弃了。

好的谢谢，我看navbar.ejs里面没有写对dropdown的处理代码，需要自己加。我试试吧...

**Comment by mychangee** [comment]
> > 可以参考主题所用的 Bulma 框架添加下拉菜单 https://bulma.io/documentation/components/navbar/
> > 之前我也试着添加过，后来没成功，放弃了。
> 
> 好的谢谢，我看navbar.ejs里面没有写对dropdown的处理代码，需要自己加。我试试吧...

大佬成功了吗，我也想改下拉式菜单
