### ISSUE TITLE
使用<table>标签生成表格会出现额外的空白行

### ISSUE THREAD

**Issue by scillidan** [ppoffice/hexo-theme-icarus#539]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

你好，我想在 icarus 内使用 [footable.js](http://fooplugins.github.io/FooTable/l) ，需要使用 table 标签。后来发现，在不引用 footable.js 的情况下，使用 table 标签，表格上方也会出现的很多空白行，使用 markdown 语法时则没有这种情况。

**Comment by ppoffice** [comment]
@scillidan 请尝试更改如下设置
https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.yml#L89

**Comment by scillidan** [comment]
成功了，多谢！

**Comment by scillidan** [comment]
> @scillidan 请尝试更改如下设置
> https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.yml#L89

**Comment by scillidan** [comment]
请问有办法在 `.md` 头部添加 `gfm: false/true` 的选项，来选择单页是否渲染吗？

**Comment by ppoffice** [comment]
@scillidan 应该不可以，这个是由hexo主程序决定的，与Icarus无关

**Comment by scillidan** [comment]
@ppoffice 好的！
