### ISSUE TITLE
sidebar sticky属性设置为true时，widget模糊问题

### ISSUE THREAD

**Issue by ravenxrz** [ppoffice/hexo-theme-icarus#545]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

你好，感谢开源了这么好的博客。不过我在使用过程中发现一个问题，当设置sidebar sticky为true时，页面滑动后，sidebar的widgets会变得模糊（仅在chrome浏览器会有这样的问题，edge无）。您有遇到过这样的问题吗？
原：
![](https://ae01.alicdn.com/kf/H64dd8b639e9c4b8f932aa942bbadf736S.jpg)
sticky: true时：
![](https://ae01.alicdn.com/kf/Had2758bc965b483cb71330b57e32fc90u.jpg)

使用环境：
Win10 + Chrome浏览器。

**Comment by ppoffice** [comment]
@ravenxrz 可能与Chrome的bug有关。你所使用的Chrome版本和屏幕分辨率是什么？

https://bugs.webkit.org/show_bug.cgi?id=159428

请参考下面两个链接测试解决方法是否有效：
https://stackoverflow.com/questions/18146946/sticky-top-bar-rendering-issue-in-chrome
https://stackoverflow.com/questions/47590013/chrome-issue-blurry-text-sticky-position-and-mobile-devices

**Comment by ravenxrz** [comment]
@ppoffice 屏幕分辨率为：1920*1080，chrome版本：77.0.3865.120（正式版本） （64 位）。感谢回复，既然是chrome bug，那就先将sticky 设置为false好了。

**Comment by imaegoo** [comment]
@ravenxrz 分享一下我的 workaround：

添加到 `style.styl`：
``` styl
.is-sticky
    top: 10px
```

原因我也不清楚，用rem作为top的单位就有这个问题，用px单位就是清晰的，而且是只要Chrome有这个问题。
