### ISSUE TITLE
代码高亮解析错误，导致页面解析失败

### ISSUE THREAD

**Issue by vangoleo** [ppoffice/hexo-theme-icarus#547]
添加如下go代码，如下设置都导致整个页面解析失败：
注：试过了设置语言为go，text，不设置。都解析失败。
注：有些go语言是可以正确解析的。
注：某些Java语言也解析失败。
```
func twoSum(nums []int, target int) []int {
    for i := 0; i < len(nums); i ++ {
        for j := i + 1; j < len(nums); j ++{
            if nums[i] + nums[j] == target{
                return []int{i,j}
            }
        }
    }
    return []int{}
}
```

**Comment by ppoffice** [comment]
@vangoleo 你是不是使用了某些HTML minifier？请尝试禁用它们查看是否仍有错误。

**Comment by vangoleo** [comment]
> @vangoleo 你是不是使用了某些HTML minifier？请尝试禁用它们查看是否仍有错误。

你好，你说的HTML minifier是指什么呀？我用的就是官方的主题，然后自己改了少量样式。但没有加新的依赖或库。HTML minifier是这个主题可以设置吗？
我对前端不太懂，麻烦你了。谢谢！！

**Comment by vangoleo** [comment]
你好，问题已解决，就是你说的HTML minifier导致的。我是按照官方demo配置来设置的：
https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.yml

![image](https://user-images.githubusercontent.com/2031602/67652363-8213a880-f97f-11e9-8e50-71d520ad62aa.png)

将all_minifier设置为false即可。
