### ISSUE TITLE
avatar自定义图片不生效

### ISSUE THREAD

**Issue by siyuanWang** [ppoffice/hexo-theme-icarus#549]
widgets:
    -
        type: profile
        position: left
        author: aaa
        author_title: bbb
        location: 中国 北京
        avatar: http://syxtt.xin/image/blog/logo/%E5%8D%9A%E5%AE%A2Logo.jpg

定义如上所示，但是没有拉取我的图片。最终展示的图片，是https://www.gravatar.com/avatar/7630fbf0c940b9bdc1a4861e1b3c8cea?s=128 ，请问是我配置错了嘛？

**Comment by siyuanWang** [comment]
`<% function avatar() {
    const avatar = get_config_from_obj(widget, 'avatar');
    const gravatar_email = get_config_from_obj(widget, 'gravatar');
    if (gravatar_email) {
        return gravatar(gravatar_email, 128);
    }
    if (avatar) {
        return url_for(avatar)
    }
    return url_for('images/avatar.png');
} %>`
依然没有解决

**Comment by ppoffice** [comment]
@siyuanWang 你有设置gravatar么？你的配置文件是什么样子的？

**Comment by siyuanWang** [comment]
logo: /images/logo.svg

navbar:
    menu:
        Home: /
        归档: /archives
        分类: /categories
        标签: /tags
        关于: /about

comment:
    type: changyan
    appid: cyrXKIcmH
    conf: ./

donate:
    -
        type: wechat
        qrcode: http://syxtt.xin/WechatIMG4.jpeg
article:
    thumbnail: true

search:
    type: insight

share:
    type: sharejs

widgets:
    -
        type: profile
        position: left
        author: Mr.Crowley
        author_title: 搜索架构师，微服务架构师
        location: 中国 北京
        avatar: http://syxtt.xin/image/blog/logo/%E5%8D%9A%E5%AE%A2Logo.jpg
        gravatar: wsy2355883@163.com
        follow_link: https://github.com/siyuanWang
        social_links: # add links to your social network here
            Github:
                icon: fab fa-github
                url: 'https://github.com/siyuanWang'
    -
        type: category
        position: left
    -
        type: tagcloud
        position: left
    -
        type: recent_posts
        position: right
    -
        type: archive
        position: right
    -
        type: tag
        position: right
links:
    Google: https://google.com
    Baidu: https://baidu.com

**Comment by ppoffice** [comment]
@siyuanWang 你需要把gravatar留空，否则会先加载gravatar email指向的头像。

**Comment by siyuanWang** [comment]
可以了，多谢，我以为gravatar是联系邮箱，额
