### ISSUE TITLE
 comments on posts

### ISSUE THREAD

**Issue by Leomhl** [ppoffice/hexo-theme-icarus#55]
I have a doubt! How to enable comments on posts? Have a nice day!

**Comment by ppoffice** [comment]
https://hexo.io/docs/front-matter.html

PS:
You need a disqus account, then add your disqus shortname in your site's _config.yml:
https://github.com/ppoffice/hexo-theme-icarus/blob/master/_config.yml.site.example#L73

**Comment by Leomhl** [comment]
Thanks, Icarus it's a exceptional template. Congratulations ;)
