### ISSUE TITLE
recent_posts widget 样式修改无法生效？

### ISSUE THREAD

**Issue by Boycottangent** [ppoffice/hexo-theme-icarus#550]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

一些文章不打算使用thumbnail，也不想在recent_posts部分使用默认的占位图，只想显示标题。所以对`recent_posts.ejs`做了修改，根据post里thumbnail的值判断是否需要显示图片，以及把标题左移，image放在右侧，本地`hexo s`预览时没有问题

<img width="270" alt="image" src="https://user-images.githubusercontent.com/23280916/68219848-a592bf00-0021-11ea-8323-ea393292f762.png">

部署后这个修改始终没有生效..还需要什么其他的修改才可以吗？

**Comment by ppoffice** [comment]
@Boycottangent 请清空浏览器和CDN缓存

**Comment by Boycottangent** [comment]
👌 现在已经可以了（之前清过缓存也没有生效，奇怪
