### ISSUE TITLE
back-to-top feature with a problem

### ISSUE THREAD

**Issue by ShuaiJunlan** [ppoffice/hexo-theme-icarus#554]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

When I click the back-to-top button, the **chrome browser** open a new blank tab page.
You can reproduce this problem by visiting this url (https://blog.shuaijunlan.cn/2019/02/27/leetcode-single-number/#References) and clicking the back-to-top button. 

I am using the `2.6.1 release version` of hexo-theme-icarus.

**Comment by ppoffice** [comment]
@ShuaiJunlan Please use the latest master branch.

**Comment by zhangxu3486432** [comment]
> @ShuaiJunlan There's a breaking change in Hexo 4.0.0. Please use the latest master branch.

remove href="javascript:;" can solve it from back-to-top.ejs

**Comment by zhangxu3486432** [comment]
#556

**Comment by ppoffice** [comment]
@ShuaiJunlan No need to remove that. This bug is fixed in the recent pull request of Hexo.

https://github.com/hexojs/hexo/pull/3812
