### ISSUE TITLE
Toc目录不显示

### ISSUE THREAD

**Issue by siyuanWang** [ppoffice/hexo-theme-icarus#559]
Hi 朋友，用了你的模板，但是指定了toc: true之后，目录还是不显示，求助。
我的博客：
http://siyuanwang.github.io/2019/10/28/java/Java%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B%E6%80%BB%E7%BB%93/

我的配置如下
`title: Java函数式编程总结
date: 2019-10-28 20:33:16
categories: "Java"
comments: true
thumbnail: http://syxtt.xin/image/blog/logo/lambda.jpg
tags: 
	  - 函数式编程
	  - Lambda
toc: true`

**Comment by ppoffice** [comment]
@siyuanWang 你在`_config.yml`中添加widget了么?
https://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/Posts/table-of-contents-catalogue/

**Comment by Honeylemonade** [comment]
Thank you for the answer to the same problem happened to me!

**Comment by siyuanWang** [comment]
按照@ppoffice的要求，配置之后，遇到了锚点undifined的问题，不过已经顺利解决。解决方法如下：
在hexo的_config.yml中添加如下，并去掉package.json中的hexo-toc插件。
markdown:
  anchors:
    level: 3              ## 为三级以上的标题添加目录
    permalinkSymbol: ''
  render:
    html: true        ## 不转义HTML内容
    xhtmlOut: false
    breaks: true        ## 文本换行
    linkify: true       ## 呈现链接
    typographer: true
    quotes: '“”‘’'

**Comment by siyuanWang** [comment]
thanks @ppoffice
