### ISSUE TITLE
移动端怎么隐藏侧边栏？

### ISSUE THREAD

**Issue by imhentai** [ppoffice/hexo-theme-icarus#56]
就是最近文章，标签云，目录之类的
以前有个mobile的css，新的好像木有了

**Comment by ppoffice** [comment]
根据屏幕大小自动隐藏边栏
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/css/_partial/profile.styl#L23
Sidebar也可以通过相同方式更改less文件

**Comment by imhentai** [comment]
问题解决了，感谢。
