### ISSUE TITLE
大佬我的博客主题代码自动有行分割线了

### ISSUE THREAD

**Issue by MySakure** [ppoffice/hexo-theme-icarus#563]
https://blog.mysakure.com/
大佬 这是我的博客地址，不知道是什么问题，会有行分割线
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by ppoffice** [comment]
@MySakure 这个问题是由于`hexo-util`的更新引入了新的代码块HTML结构引起的。我已经把CSS修复并push上来了。但是这次更新还会造成代码拷贝功能无法使用，所以还有等待`hexo-util`维护者那边的回复。或者你也可以将`hexo-util`降级到`1.4.0`。

相关链接：https://github.com/hexojs/hexo-util/issues/145

**Comment by MySakure** [comment]
> @MySakure 这个问题是由于`hexo-util`的更新引入了新的代码块HTML结构引起的。我已经把CSS修复并push上来了。但是这次更新还会造成代码拷贝功能无法使用，所以还有等待`hexo-util`维护者那边的回复。或者你也可以将`hexo-util`降级到`1.4.0`。
> 
> 相关链接：[hexojs/hexo-util#145](https://github.com/hexojs/hexo-util/issues/145)

谢谢大佬指点

**Comment by tiexo** [comment]
@ppoffice  这个问题有新的解决办法吗，刚刚更新完hexo 4.1.0也遇到了这个情况。

**Comment by Creling** [comment]
昨晚hexo-util已经进行了紧急更新，释放了17.0.
在博客目录下执行`npm install hexo`即可解决问题（需要重新生成已有页面）

**Comment by tiexo** [comment]
> 昨晚hexo-util已经进行了紧急更新，先前对hexo-util的修改被回退了。
> 在博客目录下执行`npm install hexo`即可解决问题（需要重新生成已有页面）

有效，感谢

**Comment by ShiroCheng** [comment]
> 昨晚hexo-util已经进行了紧急更新，先前对hexo-util的修改被回退了。
> 在博客目录下执行`npm install hexo`即可解决问题（需要重新生成已有页面）

终于解决了，感谢！
