### ISSUE TITLE
为什么我的博客back_to_top按钮无法使用，一点击就跳转about blank

### ISSUE THREAD

**Issue by Icecream-blue-sky** [ppoffice/hexo-theme-icarus#567]
我按照作者的教程设置type:insight以使用站内搜索功能，但是好像并没有效果，当我点击搜索按钮的时候，它总是跳到一个about:blank#blocked界面，这让我非常困惑，不知道哪里出了问题，我使用的最新的hexo和icarus

**Comment by Icecream-blue-sky** [comment]
我的博客网址是zoutq.com，还在搭建中

**Comment by Icecream-blue-sky** [comment]
我是今天开始再次重头开始搭建的，npm、hexo、icarus版本都是最新的，很幸运搜索功能好了，但是back_to_top功能却不能使用，并且我并没有做任何改动

**Comment by imaegoo** [comment]
Duplicates #554
我的建议是先退到3.9.0版本，4.0.0版本的link有问题，code highlight也有问题，等到下一个Hexo release再测试升级。
编辑`package.json`，修改hexo的version为3.9.0，再`npm install`

**Comment by Icecream-blue-sky** [comment]
> Duplicates #554
> 我的建议是先把Hexo退到3.9.0版本，4.0.0版本的a link有问题，code highlight也有问题，等到下一个Hexo release再测试升级。
> 编辑`package.json`，修改hexo的version为3.9.0，再`npm install hexo@3.9.0 --save`

谢谢，我试试，疑惑了很久，还以为是我不小心改错了代码

**Comment by Icecream-blue-sky** [comment]
> Duplicates #554
> 我的建议是先把Hexo退到3.9.0版本，4.0.0版本的a link有问题，code highlight也有问题，等到下一个Hexo release再测试升级。
> 编辑`package.json`，修改hexo的version为3.9.0，再`npm install hexo@3.9.0 --save`

哇，发现版本回退了所有东西又得重新来一遍？？？我的github.io界面直接404了，把除tags和categories文件夹外全删了，是我操作问题嘛2333

**Comment by stevenjoezhang** [comment]
Hexo已经修复了这一问题。正确的解决方案是等待Hexo 4.1.0发布而不是回滚到3.9.0。
https://github.com/hexojs/hexo/issues/3904

**Comment by imaegoo** [comment]
> Hexo已经修复了这一问题。正确的解决方案是等待Hexo 4.1.0发布而不是回滚到3.9.0。

@stevenjoezhang 
回滚是workaround，我不知道hexo 4.1.0什么时候发布，只好先留在hexo 3.9.0了。

**Comment by stevenjoezhang** [comment]
确实，Hexo一贯办事拖沓，release也不知道要等多久； https://github.com/hexojs/hexo/pull/3896

**Comment by Icecream-blue-sky** [comment]
> Hexo已经修复了这一问题。正确的解决方案是等待Hexo 4.1.0发布而不是回滚到3.9.0。
> [hexojs/hexo#3904](https://github.com/hexojs/hexo/issues/3904)
> 
> 另见 [hexojs/hexo#3876 (comment)](https://github.com/hexojs/hexo/issues/3876#issuecomment-558912106)
好像你引用的hexojs/hexo#3904和hexojs/hexo#3876 (comment)都是我在hexo issue那提出的问题23333，hexo那边让我来这边提

**Comment by Icecream-blue-sky** [comment]
> > Hexo已经修复了这一问题。正确的解决方案是等待Hexo 4.1.0发布而不是回滚到3.9.0。
> 
> @stevenjoezhang
> 回滚是workaround，我不知道hexo 4.1.0什么时候发布，只好先留在hexo 3.9.0了。

你好，我按你的方法回滚，且是在博客文件夹下使用npm install hexo@3.9.0 --save命令，然后弄完后，我的博客的public文件夹下就只剩categories、tags以及content.json三个东西，别的全被删除了，这也直接导致我的博客网站404了，是我哪里操作失误吗？还是需要一些额外的操作

**Comment by imaegoo** [comment]
> 你好，我按你的方法回滚，且是在博客文件夹下使用npm install hexo@3.9.0 --save命令，然后弄完后，我的博客的public文件夹下就只剩categories、tags以及content.json三个东西，别的全被删除了，这也直接导致我的博客网站404了，是我哪里操作失误吗？还是需要一些额外的操作

请运行 `hexo clean` 并 `hexo generate --debug`。
如果public下仍未生成静态文件，请提供您的控制台输出。

**Comment by dailyrandomphoto** [comment]
> 你好，我按你的方法回滚，且是在博客文件夹下使用npm install hexo@3.9.0 --save命令，然后弄完后，我的博客的public文件夹下就只剩categories、tags以及content.json三个东西，别的全被删除了，这也直接导致我的博客网站404了，是我哪里操作失误吗？还是需要一些额外的操作

Try to comment out `ignore:` 

```diff
# _config.yml


  # Include / Exclude file(s)
  ## include:/exclude: options only apply to the 'source/' folder
  include:
  exclude:
-  ignore:
+ # ignore:

```

or set some values.
```diff
  ignore:
+    - "**/node_modules/**"
```

then
```sh
hexo clean && hexo g
```

**Comment by Icecream-blue-sky** [comment]
> > 你好，我按你的方法回滚，且是在博客文件夹下使用npm install hexo@3.9.0 --save命令，然后弄完后，我的博客的public文件夹下就只剩categories、tags以及content.json三个东西，别的全被删除了，这也直接导致我的博客网站404了，是我哪里操作失误吗？还是需要一些额外的操作
> 
> Try to comment out `ignore:`
> 
> ```diff
> # _config.yml
> 
> 
>   # Include / Exclude file(s)
>   ## include:/exclude: options only apply to the 'source/' folder
>   include:
>   exclude:
> -  ignore:
> + # ignore:
> ```
> 
> or set some values.
> 
> ```diff
>   ignore:
> +    - "**/node_modules/**"
> ```
> 
> then
> 
> ```shell
> hexo clean && hexo g
> ```

Thks, it really works! Also, @imaegoo 's  method is  a useful solution for my problem——the back_to_top button works well!You guys are really kind.
