### ISSUE TITLE
page title怎么设置不在页面显示？

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#569]
问题一：page title

以下图为例，保留1，去掉2
![TIM截图20191203172415](https://user-images.githubusercontent.com/8164505/70037703-faf6c780-15f1-11ea-8b25-0635c2d7c131.png)
现在好像只能同时出现或者同时消失

问题二：主题不支持subtitle吗，在config里面设置了好像没用。

**Comment by ppoffice** [comment]
@tiexo 首先复制`layout/common/article.ejs`为`layout/common/article_no_title.ejs`。然后删除第一行
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.ejs#L1
```ejs
<% post = post(); %>
```

以及下面几行https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.ejs#L41_L47
```ejs
<h1 class="title is-size-3 is-size-4-mobile has-text-weight-normal">
  <% if (index) { %>
    <a class="has-link-black-ter" href="<%- url_for(post.link ? post.link : post.path) %>"><%= post.title %></a>
  <% } else { %>
    <%= post.title %>
  <% } %>
</h1>
```

然后复制`layout/page.ejs`为`layout/common/page_no_title.ejs`，并修改其内容为
```ejs
<%- _partial('common/article_no_title', {post: page, index: false}) %>
```

最后，在你的文章头部指定layout为`page_no_title`。
```yaml
title: 留言
layout: page_no_title
---
```

PS：不支持subtitle

**Comment by tiexo** [comment]
@ppoffice 感谢，有效

**Comment by scillidan** [comment]
@ppoffice 
正在从`2.3.0`迁移到`3.0.0`，之前我在`post.md`里用 `title: #`注释了，使主页上不显示标题。
![](https://raw.githubusercontent.com/scillidan/scillidan.driver.github/master/icarus_issues_569.png)
现在注释掉的话会显示`.md`的`文件名`，试着删了这行 https://github.com/ppoffice/hexo-theme-icarus/blob/06a10cca3c38b4361c2cd9d862e25de8acac2058/layout/archive.jsx#L28 但没成功
![](https://raw.githubusercontent.com/scillidan/scillidan.driver.github/master/icarus_issues_569-02.png)

**Comment by ppoffice** [comment]
@scillidan 不存在注释掉标题这个功能。另外请新开issue，不要再以前的issue下回复

**Comment by scillidan** [comment]
> @scillidan 不存在注释掉标题这个功能。另外请新开issue，不要再以前的issue下回复

好的，我以为跟这个issue是一样的
