### ISSUE TITLE
Hexo4.0 code block can only copy the first line

### ISSUE THREAD

**Issue by nineya** [ppoffice/hexo-theme-icarus#570]
In hexo4.0, the style of code block rendering has changed. Click "copy full text" to copy only the first line, and drag the mouse to copy the line number together. How to solve this problem?

![06RC4}`40LR8Z03KSBEL)(2](https://user-images.githubusercontent.com/58282918/70429557-bec0dc80-1ab3-11ea-8593-3c4669da2b89.png)
![4 0 version](https://user-images.githubusercontent.com/58282918/70429558-bec0dc80-1ab3-11ea-89b2-3f25787d7799.png)

**Comment by ppoffice** [comment]
#563

**Comment by tiexo** [comment]
https://github.com/hexojs/hexo/issues/3913

**Comment by ppoffice** [comment]
Please upgrade your `hexo-util` package.

https://github.com/hexojs/hexo-util/pull/153
