### ISSUE TITLE
脚注无法正常渲染

### ISSUE THREAD

**Issue by jitwxs** [ppoffice/hexo-theme-icarus#572]
当我按照 markdown 语法使用脚注功能时，发现无法正常渲染。声明处：

![20191213010422.png](https://i.loli.net/2019/12/13/7Ms4HIqrlNBUD8Q.png)

调用处：

![20191213010435.png](https://i.loli.net/2019/12/13/2eNPgYZaqdnVsfB.png)

线上地址：https://www.jitwxs.cn/17fac167.html

**Comment by ppoffice** [comment]
@jitwxs 你用的是`hexo-renderer-marked`么？`marked.js`不支持`footnote`，这与`Icarus`无关。

https://github.com/markedjs/marked/issues/714

你可以试试换一个渲染插件:

https://github.com/hexojs/hexo-renderer-markdown-it

**Comment by jitwxs** [comment]
感谢，问题已解决。
