### ISSUE TITLE
希望对文章指定代码块进行合并

### ISSUE THREAD

**Issue by leshalv** [ppoffice/hexo-theme-icarus#573]
希望对文章指定代码块进行合并

**Comment by ppoffice** [comment]
@leshalv 请详细描述下怎样对代码块合并，以及为什么要这么做。

**Comment by leshalv** [comment]
文章中添加了一个代码块，其中涉及到一个很大的代码块，造成网页加载速度很慢，全局配置代码块折叠后，性能提高了不少，但是目前并不支持对单个代码块进行折叠，希望能够对单个代码可以处理折叠，或者在文章上顶部加入配置方式配置整个文章代码块折叠

**Comment by ppoffice** [comment]
@leshalv 你可以把_config.yml中整个article的配置外加上把fold设置成你想要的值，复制到文章markdown的头部。这样就可以完成对单个文章代码高亮的设置了。

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/71507347-2aca7f80-28bf-11ea-8ca5-3fab342e1358.png)
亲测无效

**Comment by ppoffice** [comment]
@leshalv 

```diff
  abbrlink: 46538
+ article:
+     highlight:
+         theme: atom-one-light
+         clipboard: true
+         fold: folded
+     thumbnail: true
+     readtime: true
  toc: true
  date: 2019-12-23 23:22:00
---
Markdown content
```

**Comment by V2beach** [comment]
学习一个~
