### ISSUE TITLE
I don't find the _config.yml in folder

### ISSUE THREAD

**Issue by yuluo-ding** [ppoffice/hexo-theme-icarus#575]
I use the command `git clone https://github.com/ppoffice/hexo-theme-icarus.git` in the themes,
but when i switch to hexo-theme-icarus, I don't find the _config.yml.  I download the zip file from [release](https://github.com/ppoffice/hexo-theme-icarus/releases),  I meet the same question. When i open the zip file, ![Snipaste_2019-12-24_19-46-00.png](https://i.loli.net/2019/12/24/2HPXIGW1NmhLSgC.png)

Did I make any mistakes?

**Comment by ppoffice** [comment]
@yuluo-ding #466 Please run any hexo command

**Comment by yuluo-ding** [comment]
I follow the advice and execute the `hexo g` & `hexo s`, but no err, just show the `WARN  No layout: index.html`

My nodejs's version is 10.15.3.

**Comment by ppoffice** [comment]
@yuluo-ding What's your directory structure? Where did you put the theme folder?

**Comment by yuluo-ding** [comment]
> @yuluo-ding What's your directory structure? Where did you put the theme folder?

The root dir
```
├── _config.yml
├── db.json
├── github.io
├── node_modules
├── package-lock.json
├── package.json
├── public
├── scaffolds
├── scripts
├── source
├── themes
├── yulib.config
└── yulib.resource
```

the themes dir
```
├── anodyne
├── freemind
├── hexo-theme-cactus
├── hexo-theme-icarus
├── hexo-theme-spfk
├── landscape
├── landscape-plus
├── maupassant
├── next
└── snippet
```

I also put other theme files in this directory , and never encountered this situation

**Comment by ppoffice** [comment]
@yuluo-ding You need to make sure the `theme` option value in your root `_config.yml` is `hexo-theme-icarus` or your rename `hexo-theme-icarus` directory to `icarus` and set `theme: icarus`.

**Comment by yuluo-ding** [comment]
> @yuluo-ding You need to make sure the `theme` option value in your root `_config.yml` is `hexo-theme-icarus` or you rename `hexo-theme-icarus` directory to `icarus` and set `theme: icarus`.

This is so ashamed of me. I didn't notice the problem. After changing the name and installing the missing dependencies, it is ready to run. thank you so much.

Happy Christmas
