### ISSUE TITLE
请问icarus有什么简单的方法新增一个友链界面，并弄成卡片形式吗？

### ISSUE THREAD

**Issue by Icecream-blue-sky** [ppoffice/hexo-theme-icarus#578]
Icarus自带友链功能(links)，但是只是简单的列表形式，友链一旦多起来就不好看了，请问有什么简单的方法能弄出这样吗？
新建一个友链page，作为一个单独的界面
![QQ图片20191227133035](https://user-images.githubusercontent.com/26771037/71502799-1c736800-28ad-11ea-9ff3-533b25ef21fd.png)
弄成卡片形式
![QQ图片20191227132741](https://user-images.githubusercontent.com/26771037/71502765-e504bb80-28ac-11ea-9533-c0a53444df6c.png)
具体效果：
https://dp2px.com/links/

**Comment by ppoffice** [comment]
https://bulma.io/documentation/elements/box/
https://bulma.io/documentation/layout/media-object/

**Comment by Icecream-blue-sky** [comment]
> https://bulma.io/documentation/elements/box/
> https://bulma.io/documentation/layout/media-object/

Thks!

**Comment by Icecream-blue-sky** [comment]
请问在markdown是不能直接使用bulma吗？bulma的box布局好像在markdown中不生效，是我的操作问题吗？
我的css样式如下：
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <img src="https://pjmike.github.io/css/images/pjmike.jpg" alt="Image" width=128 height=128>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong>pjmike的博客</strong> <a href="https://pjmike.github.io/">https://pjmike.github.io/</a>
          <br>
          努力做一个笔耕者
        </p>
      </div>
    </div>
  </article>
</div>
markdown（VSCode)中运行结果如下：
![~7IR_Q3OW)LIGVV(WWN2UC1](https://user-images.githubusercontent.com/26771037/71553227-6479c280-2a46-11ea-9516-8a76b29649b9.jpg)
问题：
没有出现预期的边框，并且图片和文字的位置未达到预期位置

**Comment by ppoffice** [comment]
@Icecream-blue-sky 请运行`hexo s`或者`hexo g`

**Comment by Icecream-blue-sky** [comment]
> @Icecream-blue-sky 请运行`hexo s`或者`hexo g`查看生成的页面。直接预览的markdown中是没有加载bulma的样式表的。

成功了，再次感谢！

**Comment by bwensun** [comment]
@Icecream-blue-sky 你怎么解决的 没看懂
