### ISSUE TITLE
最新版hexo 使用主题出现这个问题，目前通过手动安装cheerio解决

### ISSUE THREAD

**Issue by leshalv** [ppoffice/hexo-theme-icarus#579]
![image](https://user-images.githubusercontent.com/30397655/71505002-82182200-28b6-11ea-8e0e-55ec51dfe60f.png)

**Comment by ppoffice** [comment]
@leshalv hexo在4.2.0中移除了cheerio依赖，之前的版本都没有问题。预计icarus在之后的版本中跟进移除此依赖。

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/71606333-e125b180-2baa-11ea-8857-9593910af7d2.png)
嗯嗯，新版本速度快了很多

**Comment by hifocus** [comment]
就算手动 `npm install cheerio -g` 也还是报错。

已经通过 `npm uninstall hexo && npm install hexo@4.1.1` 回滚 hexo 版本解决。

**Comment by ppoffice** [comment]
`Cheerio` is dropped from https://github.com/ppoffice/hexo-theme-icarus/releases/tag/3.0.0-beta.1
