### ISSUE TITLE
关于内容宽度

### ISSUE THREAD

**Issue by leshalv** [ppoffice/hexo-theme-icarus#581]
希望官方能给出一个比较好的配置来调整内容宽度，因为现在确实太窄了，代码块展示效果和阅读效果不是很好，很多使用者并不是很专业的前端，无形之中增加了困难度，在官方升级后，也不能很快的升级上来。最好能在文档中指出来一下，因为我看这块isuess挺多的，不过我确实没改出来，我想可能很多使用者也是和我一样的情况。有着这方面需求和苦恼

**Comment by tiexo** [comment]
改成单栏布局就宽了：https://a0shfe.coding-pages.com/

**Comment by ppoffice** [comment]
#434
