### ISSUE TITLE
如何添加readmore

### ISSUE THREAD

**Issue by Royean** [ppoffice/hexo-theme-icarus#582]
文章不希望全部显示，怎么添加readmore按钮呢，文档里没有找到说明

**Comment by ppoffice** [comment]
@Royean https://hexo.io/zh-cn/docs/tag-plugins#%E6%96%87%E7%AB%A0%E6%91%98%E8%A6%81%E5%92%8C%E6%88%AA%E6%96%AD
https://github.com/ppoffice/hexo-theme-icarus/issues?utf8=%E2%9C%93&q=read+more
