### ISSUE TITLE
ability to set a banner image from asset folder

### ISSUE THREAD

**Issue by awalkerca** [ppoffice/hexo-theme-icarus#59]
How can one set a banner/thumbnail image to an image in the asset folder?

**Comment by ppoffice** [comment]
This feature is not supported yet.

**Comment by theRiddler91** [comment]
How do you have a thumbnail/banner on your blog http://blog.zhangruipeng.me/hexo-theme-icarus/2015/11/14/post2/ ? Is the feature now supported?

**Comment by ppoffice** [comment]
@awalkerca 

I think you can set `thumbnail: /path/to/your/image.jpg` in the post's front-matter.

https://github.com/ppoffice/hexo-theme-icarus/wiki/Theme#thumbnail

**Comment by RomanBogachev** [comment]
In posts it works, but on main isn't present as the homepage has no direct access to the folder of a post.

**Comment by chungchi300** [comment]
```
banner : {% asset_path measure.jpg %}   

```
it looks good when this feature existed.
