### ISSUE TITLE
最新主题报这个错是为什么？Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by YuppyHub** [ppoffice/hexo-theme-icarus#594]
<img width="1398" alt="WX20200110-183005@2x" src="https://user-images.githubusercontent.com/20299293/72146429-5e38fe00-33d7-11ea-9bc9-91739c431232.png">
一开始我以为是 live2d 的问题， 后来我换其它主题试了一下不会报错， 只有切换到 icarus 的主题的时候就会报这个错。

**Comment by YuppyHub** [comment]
<img width="1415" alt="WX20200110-183247@2x" src="https://user-images.githubusercontent.com/20299293/72146548-aa843e00-33d7-11ea-8b1a-48dbae0b0bbd.png">

**Comment by YuppyHub** [comment]
我的域名是: yuu.pub

**Comment by ppoffice** [comment]
@YuppyHub 我在本地把你网页中的live2d删去之后MathJax并没有出现同样的问题。我的初步估计是live2d影响到了MathJax的脚本加载。你可以测试下删掉live2d后你网页中的MathJax是否可以正常加载。另外你所说的其他主题没有问题，你是怎样在其他主题中添加live2d和MathJax的呢？请附上你其他主题中添加这两者的HTML。

**Comment by YuppyHub** [comment]
> @YuppyHub 我在本地把你网页中的live2d删去之后MathJax并没有出现同样的问题。我的初步估计是live2d影响到了MathJax的脚本加载。你可以测试下删掉live2d后你网页中的MathJax是否可以正常加载。另外你所说的其他主题没有问题，你是怎样在其他主题中添加live2d和MathJax的呢？请附上你其他主题中添加这两者的HTML。

我是在hexo目录下的 _config.yml 配置的全局live2d，live2d是一样的配置方式不用改，只是改了 _config.yml 的主题属性
