### ISSUE TITLE
文章加密不生效

### ISSUE THREAD

**Issue by AllenSL** [ppoffice/hexo-theme-icarus#595]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by removeif** [comment]
添加这个依赖包
```yaml
    "hexo-blog-encrypt": "^3.0.3"
```
文章头部加入以下就可以了,我这边是生效的
```text
encrypt: true
password: 123456
abstract: 咦，这是一篇加密文章，好像需要输入密码才能查看呢！
message: 嗨，请准确无误地输入密码查看哟！
wrong_pass_message: 不好意思，密码没对哦，在检查检查呢！
wrong_hash_message: 不好意思，信息无法验证！
```

**Comment by removeif** [comment]
这个是使用的，[示例](https://removeif.github.io/private/2019%E6%88%90%E9%95%BF%E8%AE%B001.html)
使用加密后，有些样式不能用，并且toc目录也没有，需要自己个性化更改
hexo-blog-encrypt 插件官网有说明
