### ISSUE TITLE
无法更改主题颜色

### ISSUE THREAD

**Issue by TheInterestingSoul** [ppoffice/hexo-theme-icarus#596]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
---
想把颜色改掉，全局搜索之后改了source/css里的insight.css、progressbar.css和search.css，然后还是有两个地方改不掉，一是导航栏里的候选项颜色，二是“关注我”按钮
这两个地方实在找不到
[![20200112124309.png](https://i.postimg.cc/25DPswrB/20200112124309.png)](https://postimg.cc/Mn9PR1cW)
去style.styl还有/layout/profile.ejs看了下，没有对应颜色，全局搜索也搜不到
#462 没有用

**Comment by hongfs** [comment]
`style.styl` 这个文件是自定义的CSS。

修改导航栏候选项颜色：

```css
# themes\icarus\source\css\style.styl
.navbar-main
    .navbar-start
        .navbar-item
            background-color: #f3f3f3
```

修改关注我颜色：

```html
# themes\icarus\layout\widget\profile.ejs
<% if (get_config_from_obj(widget, 'follow_link')) { %>
    <div class="level">
        <!-- 新增 follow 类来进行控制 -->
        <a class="level-item button is-link is-rounded follow" target="_blank" href="<%= url_for(widget.follow_link) %>">
            <%= __('widget.follow') %></a>
    </div>
<% } %>
```

```css
# themes\icarus\source\css\style.styl
.button.follow
    background-color #ccc
```

你要修改的颜色用的都是 [bulam](https://bulma.io/) 默认定义颜色，通过新增样式去修改避免影响其他。

**Comment by TheInterestingSoul** [comment]
@hongfs 关注我改掉了，导航栏那个死活改不了，各种添加属性无用
[![Screenshot-20200112-193256-mark-via.jpg](https://i.postimg.cc/jSDTmfkH/Screenshot-20200112-193256-mark-via.jpg)](https://postimg.cc/Xr6tyrWq)

**Comment by hongfs** [comment]
完整贴一下你的 `style.styl`

**Comment by TheInterestingSoul** [comment]
https://github.com/TheInterestingSoul/hexo-config/blob/master/themes/icarus/source/css/style.styl

**Comment by hongfs** [comment]
代码没问题，是缩进造成的编译错误。

图一是下载后vscode打开的结果
图二是编译后的结果

![](https://i.loli.net/2020/01/12/ETdthW6BKlQfpiR.png)

![](https://i.loli.net/2020/01/12/1RWkLBl3zX7EyhH.png)

**Comment by TheInterestingSoul** [comment]
@hongfs 感谢老哥…
vim那缩进害死人，还是老老实实用gui
