### ISSUE TITLE
Jekyll和logo的问题

### ISSUE THREAD

**Issue by Nasokin** [ppoffice/hexo-theme-icarus#599]
本来是在搞logo，自己做过svg之后hexo g -d都没有任何错误讯息，但只有footer的可以显示，head则什么都没有……各种clean也无效
然后重命名试试就干脆404了……收到了如下的邮件：

> The page build completed successfully, but returned the following warning for the `master` branch:
You are attempting to use a Jekyll theme, "hexo-Icarus", which is not supported by GitHub Pages. 

看了一下之前的issues，语言也设定了，传了.nojekyll（？）也什么都没有发生……

**Comment by ppoffice** [comment]
@Nasokin 你的配置文件是什么样的？你是怎样重命名的？

**Comment by Nasokin** [comment]
十分感谢您的回复。

这里是根目录config：
[https://github.com/Nasokin/nasokin.github.io/blob/master/_config.yml](url)
这里是图片：
[https://github.com/Nasokin/nasokin.github.io/tree/master/themes/hexo-Icarus/source/images](url)
这里是主题config：
[https://github.com/Nasokin/Temporary/blob/master/theme_config.yml](url)

我只尝试了Icarus→hexo-Icarus / logo.svg→logo1.svg这样的重命名。

**Comment by ppoffice** [comment]
@Nasokin 你的master分支需要上传的是hexo g之后生成的网页

![image](https://user-images.githubusercontent.com/8849362/72272964-830bbc00-35f7-11ea-9eac-d5ecf963b215.png)

**Comment by Nasokin** [comment]
十分感谢您的回复，不知道为什么Hexo自己把根目录给我deploy了……
不过head上面的logo还是显示不出来，footer我应该没改动参数，但迷之变高了……

**Comment by Nasokin** [comment]
footer搞好了，navbar上面的logo还是迷之没有，查了下Inspector也没看出来和footer有什么区别

**Comment by ppoffice** [comment]
@Nasokin 你的svg图片的宽度和高度设置的有问题，请检查你的svg代码

**Comment by Nasokin** [comment]
实在抱歉忘记回复，修改svg代码之后logo没有问题了，favicon虽然尚不清楚原因但应该是我的处理的问题，十分感谢您的帮助，预祝您新春快乐！

**Comment by xdren69** [comment]
@ppoffice 你好，我也遇到了同样的问题，logo中的图片在head上显示不出来，在footer上可以显示出来，我之前没接触过过对于svg源码的修改，麻烦请教一下，是要大小一模一样么？除了大小之外还有什么要求么？
