### ISSUE TITLE
Enable Read more

### ISSUE THREAD

**Issue by Leomhl** [ppoffice/hexo-theme-icarus#60]
How do I enable read more on posts?

# Content
excerpt_link: Read More
fancybox: true

did not work. Thanks

**Comment by ppoffice** [comment]
Use `<!-- more -->` tag in the content part.

**Comment by SandwichZhong** [comment]
关于这个issue。。。能给详细一点的示例吗？实在是没搞懂怎么做。。。

**Comment by SandwichZhong** [comment]
Thanks，我get到了。。。不容易。。。

**Comment by Xiahl1990** [comment]
怎么解决的？

**Comment by Xiahl1990** [comment]
<div class="article-entry" itemprop="articleBody">
        <% if (index && post.excerpt) { %>
            <p><%- post.excerpt %></p>
            <p class="article-more-link">
                <a href="<%- url_for(post.path) %>#more"><%= __('article.more') %></a>
            </p>
        <% } else { %>
            <% if (!index && post.toc) { %>
                <div id="toc" class="toc-article">
                <strong class="toc-title"><%= __('article.catalogue') %></strong>
                    <%- toc(post.content) %>
                </div>
            <% } %>
            <%- post.content %>
        <% } %>
        </div>

这个不是取post.excerpt？

**Comment by life1347** [comment]
@Xiahl1990 在文章的 md 檔內加入

**Comment by xu6148152** [comment]
@life1347 我在``md``里面加了``<!-- more -->``怎么没效果？渲染出来的还是``<!-- more -->``

**Comment by JackyAndroid** [comment]
这个设计对多平台的文章的侵入性太强，希望改进

**Comment by TimSpan** [comment]
> Thanks，我get到了。。。不容易。。。

我按照你们说的 <-- more -->  但是只有一篇文章起作用了。这是为什么？

**Comment by TimSpan** [comment]
> Thanks，我get到了。。。不容易。。。

我按照你们说的  但是只有一篇文章起作用了。这是为什么？

**Comment by TimSpan** [comment]
用了   but only one article take effect,why?
