### ISSUE TITLE
Gitment无法Login

### ISSUE THREAD

**Issue by JankingHuang** [ppoffice/hexo-theme-icarus#610]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

我点击gitment的login出现一下代码：
```html
> <%- _partial('common/head') %> <%- _partial('common/navbar') %> <% function main_column_class() { switch (column_count()) { case 1: return 'is-12'; case 2: return 'is-8-tablet is-8-desktop is-8-widescreen'; case 3: return 'is-8-tablet is-8-desktop is-6-widescreen' } return ''; } %>
<%- body %>
<%- _partial('common/widget', { position: 'left' }) %> <%- _partial('common/widget', { position: 'right' }) %>
<%- _partial('common/footer') %> <%- _partial('common/scripts') %> <% if (has_config('search.type')) { %> <%- _partial('search/' + get_config('search.type')) %> <% } %>
```

**Comment by ppoffice** [comment]
@JankingHuang 你是修改了主题的源文件么？如果是，请附上修改文件的内容或者它的Git地址

**Comment by JankingHuang** [comment]
> @JankingHuang 你是修改了主题的源文件么？如果是，请附上修改文件的内容或者它的Git地址
我修改过footer.ejs 文件，但后来又改回来了。
还有_config.yml也做了相应的配置
下面是我博客主题的全部文件的git地址
> https://github.com/JankingHuang/Theme

**Comment by JankingHuang** [comment]
@ppoffice  
我点击login后，出现的代码；是在layout/layout.ejs中的。

**Comment by ppoffice** [comment]
@JankingHuang 请清理主题目录下所有结尾为`~`的文件。

**Comment by JankingHuang** [comment]
@ppoffice  
清理以~结尾文件后，出现了新的问题
> https://github.com/JankingHuang/Theme/blob/master/1.jpg
> https://github.com/JankingHuang/Theme/blob/master/2.jpg

**Comment by ppoffice** [comment]
@JankingHuang 推荐使用Gitalk。两者功能基本相同，而gitment已经很久没有更新了。

**Comment by JankingHuang** [comment]
谢谢
