### ISSUE TITLE
主题背景

### ISSUE THREAD

**Issue by JankingHuang** [ppoffice/hexo-theme-icarus#612]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
主题的背景太白了，我打算加入背景图片，是配置_config文件，还是修改index.html文件呢？

**Comment by smileorigin** [comment]
modify `/themes/icarus/layout/layout.ejs`

**Comment by smileorigin** [comment]
> Please make sure you took care of the following things before you submit this issue. Thank you!
> 
> * [x]  I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
> * [x]  I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
>   主题的背景太白了，我打算加入背景图片，是配置_config文件，还是修改index.html文件呢？

modify /themes/icarus/layout/layout.ejs

**Comment by JankingHuang** [comment]
@smileorigin  谢谢
