### ISSUE TITLE
GitHub app API query parameter deprecation

### ISSUE THREAD

**Issue by telami** [ppoffice/hexo-theme-icarus#614]
GitHub is going to be deprecating sending the client ID and client secret as query parameters. Gitalk will need to be updated to use basic authentication. For more information see: https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

**Comment by ppoffice** [comment]
https://github.com/gitalk/gitalk/issues/343

**Comment by CHN-ChenYi** [comment]
Gitalk has solved the problem:
https://github.com/gitalk/gitalk/pull/346

**Comment by wxk6b1203** [comment]
Position `gitalk.ejs` and change the version at line 9, 10 to 1.5.2 will fix the problem.

**Comment by ppoffice** [comment]
Will be fixed in version 3.0.0.
