### ISSUE TITLE
Markdown 文章中的图片无法显示！！！！

### ISSUE THREAD

**Issue by JankingHuang** [ppoffice/hexo-theme-icarus#617]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
在Markdown 语法的文章中图片无法显示，该路径下存在图片
Markdown 写法如下：
----
```markdown
 ![](../images/node.jpg) 
```

**Comment by nek0ri** [comment]
I met the same problem, and it happened just from hours ago.
If I run hexo in localhost, it's okay, however after push it to github, it goes wrong.
I don't know what causes that...
不知道楼主是不是和我一样，之前没问题，然后今天下午突然出问题了。
我尝试了一下在`根目录_config.yml`下开启了`post_asset_folder`功能后，使用
    {% asset_img test.jpg %}
这种引用图片的方式在本地显示正常，但是在服务器上跑之后就显示不出来了（变成一个“？”）
但是用楼主所类似的引用方式
    ![](/images/test.jpg) 
是可以本地和服务器都正常显示的。
只是一个猜测，会不会是官方CDN出现了问题，不知楼主是不是使用了官方CDN。
希望能尽快解决吧。

**Comment by JankingHuang** [comment]
@nek0ri  我的CDN是没有修改过的，文章的图片在本地服务(http://localhost:4000)中也显示不出来，但是在我用的Mardown 编辑器typora中可以显示图片。

**Comment by nek0ri** [comment]
> @nek0ri 我的CDN是没有修改过的，文章的图片在本地服务(http://localhost:4000) 中也显示不出来，但是在我用的Mardown 编辑器typora中可以显示图片。

我现在把全部文章改为`![]()的引用方式，就先这样了吧orz
刚才看了一下你的引用路径，是`![](../images/node.jpg) `这样吗？如果你的图片路径是`/source/images/node.jpg`的话，尝试使用这样的引用方式：
```
![](/images/node.jpg)
```
还不行的话尝试升级一下nodejs以及npm。

**Comment by JankingHuang** [comment]
@nek0ri  没错，我受缩略图路径的影响
谢谢

**Comment by originalxun** [comment]
图片地址不加baseurl可以正常访问
