### ISSUE TITLE
希望可以添加Valine EX评论系统

### ISSUE THREAD

**Issue by FFRaycoder** [ppoffice/hexo-theme-icarus#618]
[Valine EX](https://deserts.io/diy-a-comment-system/)

**Comment by tiexo** [comment]
没有太大的必要，还是原生valine更适合作为默认配置

**Comment by FFRaycoder** [comment]
> 没有太大的必要，还是原生valine更适合作为默认配置

还是EX界面更轻爽些

**Comment by FFRaycoder** [comment]
<% if (!has_config('comment.app_id') || !has_config('comment.app_key')) { %>
<div class="notification is-danger">
    You forgot to set the <code>app_id</code> or <code>app_key</code> for Valine. Please set it in <code>_config.yml</code>.
</div>
<% } else { %>
<div id="valineex-thread" class="content"></div>
<script src="https://cdnjs.loli.net/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
<script src="/js/Valineex.min.js"></script>
<script type="text/javascript">
  new Valine({
    lang:"zh-cn",
    av: AV,
    admin_email:"<%= get_config(comment.admin_email) %>",
    el:"#valineex-thread",
    appId:"<%= get_config(comment.app_id) %>",
    appKey:"<%= get_config(comment.app_key) %>",
    emoticon_url:"<%= get_config(comment.emoticon_url) %>",
    emoticon_list:<%= get_config(comment.emoticon_list) %>
    placeholder:"<%= get_config(comment.placeholder) %>",
  });
</script>
<% } %>
差不多这样

**Comment by ppoffice** [comment]
由于此评论插件与Valine配置上基本相似，用户可以在Valine的基础上修改来添加此插件，单独支持意义不大。如果今后此插件与原Valine有较大区别并且有规范的用户和开发者文档之后可再考虑添加。
