### ISSUE TITLE
Select hexo-renderer-markdown-it-plus as the default markdown renderer.

### ISSUE THREAD

**Issue by andylizf** [ppoffice/hexo-theme-icarus#620]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

How to select [hexo-renderer-markdown-it-plus](https://github.com/upupming/hexo-renderer-markdown-it-plus) as the default markdown renderer? I uninstalled hexo-renderer-mark and installed it as it says, but themes\icarus\includes\tasks\check_deps.js checked checked the missing dependencies and tells that
>ERROR Package hexo-renderer-marked is not installed.
ERROR Please install the missing dependencies from the root directory of your Hexo site.

**Comment by andylizf** [comment]
There is something wrong with the Latex render of the default renderer. So it's of necessity to add this support.

**Comment by ppoffice** [comment]
@andylizf `hexo-renderer-marked` is no longer a required dependency for Icarus. Please upgrade theme and try again.
https://github.com/ppoffice/hexo-theme-icarus/blob/master/includes/tasks/check_deps.js#L14

**Comment by zhuo1angT** [comment]
> @andylizf `hexo-renderer-marked` is no longer a required dependency for Icarus. Please upgrade theme and try again.
> https://github.com/ppoffice/hexo-theme-icarus/blob/master/includes/tasks/check_deps.js#L14

Is `hexo-renderer-ejs` still a required dependecy for Icarus?
I have the same problem installing the plugin `hexo-renderer-markdown-it`, if I uninstall `hexo-renderer-ejs`, Icrus simply stopped work.
Is it possible for Icrus to install another renderer?

**Comment by zhuo1angT** [comment]
> @andylizf `hexo-renderer-marked` is no longer a required dependency for Icarus. Please upgrade theme and try again.
> https://github.com/ppoffice/hexo-theme-icarus/blob/master/includes/tasks/check_deps.js#L14

Originally my problem was that the Icarus Markdown does not support the "footer" feature, is it a GFM one that Icrus not support?

**Comment by zhuo1angT** [comment]
![sh](https://user-images.githubusercontent.com/24938839/74525249-9b0a8e80-4f5b-11ea-85f4-0d203bcbbe82.JPG)
When I uninstalled `hexo-renderer-ejs`, the Blog web page show up like this.

**Comment by ppoffice** [comment]
@andylizf Yes, hexo-renderer-ejs is required since the layout files are in ejs format.
