### ISSUE TITLE
使导航栏跟随页面滚动

### ISSUE THREAD

**Issue by moegay** [ppoffice/hexo-theme-icarus#623]
- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
 
请教一下，如何在何处以及如何修改，才能使navbar跟随页面滚动呢？

**Comment by removeif** [comment]
> * [x]  I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
> * [x]  I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
> 
> 请教一下，如何在何处以及如何修改，才能使navbar跟随页面滚动呢？

这个pr有你说的代码 [pr](https://github.com/ppoffice/hexo-theme-icarus/pull/616)，
我以hexo-theme-icarus基础自己改了一部分的[代码](https://github.com/removeif/hexo-theme-icarus-removeif)也有你说的功能，可以参考下

**Comment by moegay** [comment]
> > * [x]   I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
> > * [x]   I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
> > 
> > 请教一下，如何在何处以及如何修改，才能使navbar跟随页面滚动呢？
> 
> 这个pr有你说的代码 [pr](https://github.com/ppoffice/hexo-theme-icarus/pull/616)，
> 我以hexo-theme-icarus基础自己改了一部分的[代码](https://github.com/removeif/hexo-theme-icarus-removeif)也有你说的功能，可以参考下

哈，找了好久的资料..
原来只要把position设为sticky就好啦 ^ ^

**Comment by moegay** [comment]
@removeif 
您的博客我发现在日间模式下，页面刚向上滑动时会有一小部分遮盖导航栏，夜间模式则无此问题。
如图
![IMG_20200216_000543](https://user-images.githubusercontent.com/46620842/74591127-ffb8fe00-4fda-11ea-85b7-0048d3a79266.jpg)

**Comment by removeif** [comment]
> @removeif
> 您的博客我发现在日间模式下，页面刚向上滑动时会有一小部分遮盖导航栏，夜间模式则无此问题。
> 如图
> ![IMG_20200216_000543](https://user-images.githubusercontent.com/46620842/74591127-ffb8fe00-4fda-11ea-85b7-0048d3a79266.jpg)

@moegay 嗯，谢谢，这是滑动的时候判断>50才添加背景色，这个值回头改小一点就可以啦

**Comment by BowenYoung** [comment]
@moegay 请问navbar的position在哪里配置呢
