### ISSUE TITLE
cannot load fontawesome icon

### ISSUE THREAD

**Issue by skks11** [ppoffice/hexo-theme-icarus#626]
![image](https://user-images.githubusercontent.com/39985286/75033729-817ebf00-54e6-11ea-9fa6-4060d99b44be.png)

![image](https://user-images.githubusercontent.com/39985286/75033790-a1ae7e00-54e6-11ea-931c-c5110a866788.png)

**Comment by ppoffice** [comment]
@skks11 Please check if fontawesome is blocked by your ISP. Alternatively, you can switch to another fontawesome CDN by editing https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.theme.yml#L244
