### ISSUE TITLE
新建一个index样式的page能否实现呢？

### ISSUE THREAD

**Issue by moegay** [ppoffice/hexo-theme-icarus#627]
- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
    
在Hexo的source目录下新建一个目录“page“（与目录_posts为平行关系），使得该目录下新建的许多md文档能在 http://网站/page 页面上列出来，就像网站index页面一样。  
简单来讲就是新建一个和主页一样的索引页面。请问大侠这个能否实现呢？
其他issue里提到过一个，说是新建一个友链page，然后友链也弄成卡片状。但我研究了一下，那个是在同一个页面生成许多卡片，和这个和做成index的page还是不同的。

**Comment by ppoffice** [comment]
@moegay 需要自己实现layout

**Comment by moegay** [comment]
> @moegay 需要自己实现layout

自己搞layout对我来说有点复杂，这个太难啦，哈哈。不过我刚刚想出一个法子可曲线救国：  
    首先用 [hexo-generator-index2](https://github.com/Jamling/hexo-generator-index2) 来替代原版的 index generator。因为该插件可以设置首页只显示或隐藏 某path/category/tag 的文章。  
    然后，在_posts文件夹内新建目录，该目录名名称就是一个category。之后在Hexo的config中将category目录设置为 / 。最后在navbar中设置指向这些自定义目录的menu。  
    这样就可以通过category的layout来生成自定义目录下的卡片式index布局了，同时也可以做到在首页隐藏自定义目录下的文章。哈哈🤣

**Comment by moegay** [comment]
> @moegay 需要自己实现layout

解决了。
不需要我上面说的那么麻烦😅

hexo-generator-index2 已经支持 [将多个页面的layout都设置为index](https://github.com/Jamling/hexo-generator-index2/blob/master/README.md#options)
