### ISSUE TITLE
当文章过长的时候,主题有个BUG.侧边栏显示不全

### ISSUE THREAD

**Issue by Shimmer66** [ppoffice/hexo-theme-icarus#628]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
![捕获aaa](https://user-images.githubusercontent.com/47374657/75304820-31ee1980-587f-11ea-809a-eabf58c20166.PNG)
![捕获q](https://user-images.githubusercontent.com/47374657/75304823-34e90a00-587f-11ea-94ac-c19ed7c9b68e.PNG)
![捕获](https://user-images.githubusercontent.com/47374657/75304828-37e3fa80-587f-11ea-9ef1-9d37824b5d1e.PNG)
![捕获a](https://user-images.githubusercontent.com/47374657/75304830-39adbe00-587f-11ea-9bff-573f2e36f672.PNG)

**Comment by ppoffice** [comment]
@Shimmer66 有可能是你的`<!-- more -->`插入的位置有问题。

https://github.com/ppoffice/hexo-theme-icarus/issues/624

**Comment by Shimmer66** [comment]
这个问题是由于文章内如果有一行的长度过长,就会挤掉右边栏,导致这种情况

**Comment by Shimmer66** [comment]
可能是文章排版的问题吧,

**Comment by ppoffice** [comment]
@Shimmer66 我看了下你的博客，你的[这篇文章](https://shimmer66.github.io/2020/02/25/Git%E6%9D%82%E8%AE%B0/)的加粗标签`<b>`没有闭合。请检查你的markdown是否正确。

**Comment by Shimmer66** [comment]
十分抱歉给您带来的不便,的确是<b>未封闭
