### ISSUE TITLE
麻烦问一下，about页面是怎样生成的，在默认状态下about目录中没有index.html文件

### ISSUE THREAD

**Issue by LuciusCS** [ppoffice/hexo-theme-icarus#630]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by duinomaker** [comment]
在 /source 目录(里面有_posts等文件夹)下创建 about 目录，在里面加入一个 index.md 文件
