### ISSUE TITLE
Config `providers.iconcdn` does not work in 3.0

### ISSUE THREAD

**Issue by imaegoo** [ppoffice/hexo-theme-icarus#631]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

Icarus version: **3.0.0-beta.2**

The **default** config name `providers.iconcdn` does not work, I changed to `providers.iconfont` so it works.

![20200229184346](https://user-images.githubusercontent.com/20182252/75606047-e3ad7480-5b23-11ea-85b3-b3977de16d58.png)

@ppoffice , I'm not able to fix it in `hexo-component-inferno` repo.

**Comment by ppoffice** [comment]
@imaegoo Fixed in `hexo-component-inferno@0.0.4`. Please upgrade that package.
