### ISSUE TITLE
I want the archive page to come out first when I first came into the blog...  How can I change the main page('/', Home) to archive('/archive')?

### ISSUE THREAD

**Issue by o-henry** [ppoffice/hexo-theme-icarus#632]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [v] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [v] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

Hello.. I've tried many ways, but it doesn't work so I'm asking for help..
I'd like to use the archives screen as the main page ('/' home), but I don't know what to do. Can you help me?
I want the archive page to come out first when I first came into the blog.
Thank you for reading it.

**Comment by moegay** [comment]
This may be useful: 
Remove hexo-generator-index and install 
 [hexo-generator-index2](https://github.com/Jamling/hexo-generator-index2/blob/master/README.md#options) to set homepage in archives layout.

**Comment by o-henry** [comment]
> This may be useful:
> Remove hexo-generator-index and install
> [hexo-generator-index2](https://github.com/Jamling/hexo-generator-index2/blob/master/README.md#options) to set homepage in archives layout.

Thanks to you, I was able to solve it.
Really REally Thank you very much. !!!!!!!
