### ISSUE TITLE
How to Turn off a Sidebar Widget

### ISSUE THREAD

**Issue by navjotjsingh** [ppoffice/hexo-theme-icarus#634]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

I am trying to get rid of certain sidebar widgets(tagcloud and recent posts) but every time I comment them out, I get errors while running hexo generate command. What is the correct way to turn off/remove a sidebar widget?

**Comment by Evelx0** [comment]
did you find a fix for this?
