### ISSUE TITLE
请问如何隐藏部分post的发布时间呢？

### ISSUE THREAD

**Issue by moegay** [ppoffice/hexo-theme-icarus#637]
- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

意思就是，在index列表界面，post标题上方的“发布时间、分类、阅读所需时间”等，应该在何处改动，才能对这部分内容进行显示控制呢？

如果是让所有post都不显示，我只要删掉 article.ejs 里面的这部分内容就可以解决了。可是如果要让部分post显示，部分不显示的话，我搜索了一下资料，感觉应该采用front-matter来控制。但Hexo官网给的资料说得很不清楚，且我也不知怎样才能将其与主题结合。因此不知从何下手。

请问还有什么方法可以办到吗？恳请大侠赐教。

**Comment by ppoffice** [comment]
@moegay 在markdown的front-matter中添加
```yml
show_date: false
```
然后在下面这处添加`if`语句判断文章是否有`show_date === false`，如果有的话则不渲染日期HTML标签。
https://github.com/ppoffice/hexo-theme-icarus/blob/2.7.0/layout/common/article.ejs

**Comment by moegay** [comment]
> @moegay 在markdown的front-matter中添加
> 
> ```yaml
> show_date: false
> ```
> 
> 然后在下面这处添加`if`语句判断文章是否有`show_date === false`，如果有的话则不渲染日期HTML标签。
> https://github.com/ppoffice/hexo-theme-icarus/blob/2.7.0/layout/common/article.ejs

啊，谢谢大侠。

😅 试了试，才知道原来不能直接用 if 判定`show_date`，否则会报 Syntax Error，提示 missing catch 啥的。

后来回到Hexo文档再转了两圈，在评论区发现了[这篇文章](https://ethanblog.com/tech/details-for-front-matters-of-hexo.html)，才晓得要改成`post.show_date`。哈，解决啦
