### ISSUE TITLE
theme style changed

### ISSUE THREAD

**Issue by surperJin** [ppoffice/hexo-theme-icarus#638]
![image](https://user-images.githubusercontent.com/36074045/76278783-6de59d80-62c7-11ea-9686-65e5cd02a9b9.png)
在启动的时候出现这么一个错误，博客页面样式乱了。请问这个问题怎么解决？

**Comment by ppoffice** [comment]
@surperJin 请附上hexo版本和安装的package.json依赖版本，还有配置文件。另外查看是否hexo有报错。
