### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by KazamaSion** [ppoffice/hexo-theme-icarus#641]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

已在 `hexo/_config.yml` 下设置时区为 `Asia/Hong_Kong`，并修改系统时区为相同时区，但博文攥写时间依旧以 UTC 为标准生成。
Debug 时可以尝试将时间设置在 0-8 点之间。

**Comment by ppoffice** [comment]
@KazamaSion 请附上出问题的文章的地址和正确的发布时间。

**Comment by KazamaSion** [comment]
@ppoffice 不好意思，刚刚在自行 debug 的时候，发现是编辑器在插入时间的时候，少了标识符导致时区没有被正确加载。  
非常抱歉。
