### ISSUE TITLE
创建成功提示主题不支持

### ISSUE THREAD

**Issue by YIZHEV** [ppoffice/hexo-theme-icarus#646]
作者你好，个人感觉您做的主题非常现代化和漂亮。刚入坑博客的我非常喜欢。最近在配置完之后一直会有一个问题，提示build 成功但却不支持主题。而且奇怪的是我用的hexo却提示Jekyll主题。如下：
> The page build completed successfully, but returned the following warning for the `master` branch:

>You are attempting to use a Jekyll theme, "icarus", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll.

我的仓库目录如下：https://github.com/YIZHEV/yizhev.github.io

**Comment by ppoffice** [comment]
@YIZHEV 官方文档已经说的很明白了，为什么不看看呢
https://hexo.io/zh-cn/docs/one-command-deployment.html
