### ISSUE TITLE
您好，本地预览正确 部署到网上出现样式错误求教

### ISSUE THREAD

**Issue by CN-LC** [ppoffice/hexo-theme-icarus#647]
错误提示
jquery.min.js:2 Uncaught ReferenceError: GLOBAL_CONFIG is not defined
    at HTMLDocument.<anonymous> (main.js:2)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
(anonymous) @ main.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2

**Comment by CN-LC** [comment]
hexo: 4.2.0
hexo-cli: 3.1.0
os: Windows_NT 10.0.18363 win32 x64
node: 13.6.0
v8: 7.9.317.25-node.26
uv: 1.34.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 79
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.1
openssl: 1.1.1d
cldr: 36.0
icu: 65.1
tz: 2019c
unicode: 12.1

**Comment by ppoffice** [comment]
@CN-LC Icarus的main.js里面没有`GLOBAL_CONFIG`。你是不是之前用的其他的主题没有清理干净？

**Comment by CN-LC** [comment]
> @CN-LC伊卡鲁斯曼.js]" ？`GLOBAL_CONFIG`

您好，之前确实使用过其他主题；
但用过hexo clean清理过啊 
还是具体要用其他方式清理？？
麻烦了

**Comment by ppoffice** [comment]
@CN-LC 你是如何部署的？是用的`hexojs/hexo-deployer-git`么？如果不是的话，注意不要把之前生成的文件push到git上。

**Comment by CN-LC** [comment]
> @CN-LC 你是如何部署的？是用的`hexojs/hexo-deployer-git`么？如果不是的话，注意不要把之前生成的文件push到git上。`hexo-deployer-git`生成的.deploy_git中不要有任何git的历史commit。

您好，是修改根目录config文件主题然后用 hexo g ，hexo d直接部署的，
本地预览没问题，推上去之后样式出现问题；
请问.deploy_git中历史commit 如何清理，又或者我该如何做？？
我刚接触没有找到合适的方法……麻烦了
请问

**Comment by CN-LC** [comment]
问题解决了 确实是没有清理干净 谢谢作者
生活愉快！
