### ISSUE TITLE
请问支不支持在post页面上用gallery？或者给page加categories？谢谢啦

### ISSUE THREAD

**Issue by noodlemaster** [ppoffice/hexo-theme-icarus#648]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by removeif** [comment]
post页面上用gallery 如下放入post中
```html
<div class="justified-gallery">

![唐艺昕](http://wx1.sinaimg.cn/mw1024/63112839ly1g6k700zidlj21o0280u10.jpg)
![唐艺昕](http://wx1.sinaimg.cn/mw1024/63112839ly1fy0v3evcbcj22j91wgnpd.jpg)
![唐艺昕](http://wx3.sinaimg.cn/mw1024/63112839gy1g423osk4xcj22ox41eb2d.jpg)
![唐艺昕](http://wx4.sinaimg.cn/mw1024/63112839ly1g3g8gkkc15j21cc1sg7wh.jpg)
</div>
```
或者给page加categories ？这是啥意思？

**Comment by noodlemaster** [comment]
> post页面上用gallery 如下放入post中
> 
> ```
> <div class="justified-gallery">
> 
> ![唐艺昕](http://wx1.sinaimg.cn/mw1024/63112839ly1g6k700zidlj21o0280u10.jpg)
> ![唐艺昕](http://wx1.sinaimg.cn/mw1024/63112839ly1fy0v3evcbcj22j91wgnpd.jpg)
> ![唐艺昕](http://wx3.sinaimg.cn/mw1024/63112839gy1g423osk4xcj22ox41eb2d.jpg)
> ![唐艺昕](http://wx4.sinaimg.cn/mw1024/63112839ly1g3g8gkkc15j21cc1sg7wh.jpg)
> </div>
> ```
> 
> 或者给page加categories ？这是啥意思？

太感谢啦，是我自己路径搞错了一点。。。不用管给page加category了。我还有几个新的问题... 
1.  请问在移动端（手机）上如何把profile widget放最上面？
2. 请问在移动端（手机）可不可以把icon和navbar的空白间距缩小一点。。（这个弄不了也没事～）
2. 请问thumbnail如何才能把图片显示全？是要把图片按一定的比例放缩吗？

麻烦啦 🙏
