### ISSUE TITLE
数学公式渲染问题

### ISSUE THREAD

**Issue by noodlemaster** [ppoffice/hexo-theme-icarus#650]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
您好， 在math block里我用//换行在编辑器里能正确显示但在网页上就都连在一起了。
`\Rightarrow\space (cos\alpha +cos\beta +cos\alpha cos\beta+1)^2 =(1-cos^2\alpha)(1-cos^2\beta)\\
\Rightarrow\space (1+cos\alpha)^2(1+cos\beta)^2 =(1-cos\alpha)(1+cos\alpha)(1-cos\beta)(1+cos\beta) \\
\Rightarrow\space (1+cos\alpha)(1+cos\beta)[(1+cos\alpha)(1+cos\beta)-(1-cos\alpha)(1-cos\beta)] =0 \\
\Rightarrow\space 2(1+cos\alpha)(1+cos\beta)(cos\alpha+cos\beta) =0`
<img width="926" alt="Screen Shot 2020-03-24 at 10 35 33 PM" src="https://user-images.githubusercontent.com/38833869/77484531-b00ff280-6e22-11ea-93eb-80313b88449e.png">
`下面是编辑器预览的
<img width="690" alt="Screen Shot 2020-03-24 at 10 58 58 PM" src="https://user-images.githubusercontent.com/38833869/77484688-139a2000-6e23-11ea-8e40-e839a78a5f25.png">
还有个问题就是我每次deploy都会重制github page的个人域名。。。我明明在/source下放了一个CHAME.txt而且/public下也会显示。。。
麻烦啦～

**Comment by ppoffice** [comment]
@noodlemaster 首先你用的是MathJax还是KaTeX？如果是MathJax，你需要在公式前后加上`$$`。另外，是`CNAME`而不是`CHAME`，如果deploy还有问题的话你需要反馈给相应的deployer开发者而不是这里。

**Comment by noodlemaster** [comment]
解决了。。原来貌似要在开头加mathjax：true

谢谢啦，很棒的主题！

**Comment by MakerGYT** [comment]
you can try [markdown-it-latex2img](https://github.com/MakerGYT/markdown-it-latex2img#Hexo)
