### ISSUE TITLE
本地显示正常，部署后首页缺失一部分widgets。

### ISSUE THREAD

**Issue by noodlemaster** [ppoffice/hexo-theme-icarus#653]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.
又是我～实在太麻烦啦
部署前本地预览正常，部署后post页面也正常，但是主页Home页面缺少profile, tagcloud, categories, archieves这几个widget。。上图味本地预览，下图为部署后的页面。再次感谢🙏
<img width="1421" alt="Screen Shot 2020-03-27 at 12 01 15 AM" src="https://user-images.githubusercontent.com/38833869/77707936-8b508200-6fbe-11ea-8def-d64dcd054662.png">
<img width="1435" alt="Screen Shot 2020-03-27 at 12 03 39 AM" src="https://user-images.githubusercontent.com/38833869/77707942-90153600-6fbe-11ea-9d3f-ab71e8147871.png">

**Comment by ppoffice** [comment]
@noodlemaster 重新部署并清空CDN以及浏览器缓存

**Comment by noodlemaster** [comment]
请问如何清空CDN？

**Comment by noodlemaster** [comment]
您好我清空浏览器缓存不起作用，请问如何清空CDN..？

**Comment by ppoffice** [comment]
@noodlemaster 如果你没有使用cloudflare这样的CDN服务的话，就不用清空CDN缓存。请对比你在本地的首页的html和你部署后的html代码有何区别。如果两者不一样而且本地Hexo server预览时没有问题的话，也有可能说明你部署失败了。

**Comment by FFRaycoder** [comment]
清空CDN应该是在控制台清空。

**Comment by noodlemaster** [comment]
两者不一样。。请问部署失败该怎么办。。

**Comment by ppoffice** [comment]
@noodlemaster 删掉`.deploy_git`或者其他`.deploy`开的头的文件夹，重新部署下试试。

**Comment by noodlemaster** [comment]
您好，删掉.deploy_git还是不行诶..

**Comment by FFRaycoder** [comment]
`hexo clean`试过没？

**Comment by noodlemaster** [comment]
hexo clean + hexo g 部署后还是不行诶。。

**Comment by CC-cat** [comment]
报错：
WARN  Icarus cannot load widget "tagcloud"
WARN  Icarus cannot load widget "archive"
WARN  Icarus cannot load widget "category"
WARN  Icarus cannot load widget "tag"
WARN  Icarus cannot load widget "tagcloud"
WARN  Icarus cannot load widget "archive"
WARN  Icarus cannot load widget "category"
WARN  Icarus cannot load widget "tag"
WARN  Icarus cannot load widget "tagcloud"
WARN  Icarus cannot load widget "archive"
WARN  Icarus cannot load widget "category"
WARN  Icarus cannot load widget "tag"
WARN  Icarus cannot load widget "tagcloud"
WARN  Icarus cannot load widget "archive"
WARN  Icarus cannot load widget "category"
WARN  Icarus cannot load widget "tag"

找到原因：主题路径下缺少文件导致报错。
文件路径： hexo-theme-icarus/layout/widget/ 
缺少文件：tagcloud.ejs tagcloud.locals.js 等等...
解决方案：可在我收藏的文件里复制一份 git@github.com:CC-cat/hexo-theme-icarus.git
感谢博主提供的主题，非常喜欢❤️。

**Comment by ppoffice** [comment]
@CC-cat Icarus3.0移除了对tagcloud的支持，在release notes里有写。
