### ISSUE TITLE
config.yaml对canonical的设置

### ISSUE THREAD

**Issue by songouyang** [ppoffice/hexo-theme-icarus#656]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

主题默认生成的 `_config.yaml`  会有 `canonical` 字段的设置。如果一旦在 `_config.yaml` 中设置了 `canonical` 字段，但是没有在 post 中没有设置，会导致多个链接的 canonical 是一致的。

我有两个想法如下：
1. 在 `_config.yaml` 中不生成 `canonical` 的配置，是不是可以避免「用户设置了 config 中 canonical，导致多个链接被搜索引擎认为是一个」
2. 是不是可以加一个自动生成 canonical，如果 post 没有设置 canonical，就采用 hexo 的 full path。

**Comment by ppoffice** [comment]
@songouyang 已从`_config.yml`移除`canonical_url`。但是我认为没有必要自动生成canonical。因为canonical标签是用作在SEO收录时去重，而一般来说Hexo的Post都有唯一的permalink，所以大部分情况下没必要使用Hexo的full path。

**Comment by songouyang** [comment]
@ppoffice 嗯嗯，Hexo 的确会有确定的 permalink，一般不需要 canonical。但是有些托管服务，比如 firebase，会保留它本身的三级域名，并且不会重定向到自定义的域名。这种情况下还是对 SEO 收录有影响吧。
