### ISSUE TITLE
可否将内容三栏格式改成两栏？

### ISSUE THREAD

**Issue by einhhhh** [ppoffice/hexo-theme-icarus#658]
我翻了下以前的issues，发现有类似的问题，当时改的是includes/helpers/下的layout.js。但我下载的是3.0.0版本，对应主题目录下没有相应的目录和文件，有的只是layout/layout.jsx文件，请问这个如何处理呢？

**Comment by ppoffice** [comment]
你把所有的widgets都移动到左边或者右边，自然就是两栏了

**Comment by yuanjh6** [comment]
我个人开发了一个分之，https://github.com/yuanjh6/hexo-theme-icarus，这里默认２栏，效果https://hexo.yuanjh.cn/

**Comment by einhhhh** [comment]
> 你把所有的widgets都移动到左边或者右边，自然就是两栏了
> 
> 如果你想问的是能不能做到首页三栏文章页两栏的话，你可以复制_config.yml到_config.post.yml和_config.page.yml，然后在相应的配置文件中修改widget布局

谢谢您，这块问题解决了。然后还有个问题想请教的是我的内容调成两栏后稍显紧凑，请问能否调整文章栏和widget的布局与宽度呢？

**Comment by einhhhh** [comment]
> > 我翻了下以前的issues，发现有类似的问题，当时改的是includes/helpers/下的layout.js。但我下载的是3.0.0版本，对应主题目录下没有相应的目录和文件，有的只是layout/layout.jsx文件，请问这个如何处理呢？
> 
> 我个人开发了一个分支yuan_dev：https://github.com/yuanjh6/hexo-theme-icarus
> 这里默认2栏，博客效果：https://hexo.yuanjh.cn/
> 你可以试试

您好，您的博客我看了，效果挺棒，请问您怎么调整wdiget和文章主体的宽度的呢？

**Comment by ppoffice** [comment]
@einhhhh https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/base.styl#L23-L27

**Comment by einhhhh** [comment]
@ppoffice 好的可以了，感谢！

**Comment by LeverImmy** [comment]
> > 我翻了下以前的issues，发现有类似的问题，当时改的是includes/helpers/下的layout.js。但我下载的是3.0.0版本，对应主题目录下没有相应的目录和文件，有的只是layout/layout.jsx文件，请问这个如何处理呢？
> 
> 我个人开发了一个分支yuan_dev：https://github.com/yuanjh6/hexo-theme-icarus
> 这里默认2栏，博客效果：https://hexo.yuanjh.cn/
> 你可以试试

这个是老版本的吧，现在的 3.0.0 已经不是这样的了。

**Comment by LeverImmy** [comment]
> @einhhhh https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/base.styl#L23-L27
> 
> 试试把full HD和widescreen的值改小
> 
> 如果不行的话就改这里https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/responsive.styl

我尝试着改了一下 base.yml，然后把 desktop 设置成了 1300px，确实界面的边界留白窄了许多。

但是有个问题，左边的 profile 的大小会 **随着 ** 你设置的 desktop 的大小变大 **而变大**。

如果我想要 **三栏** 时的 profile 的 widget 的大小，即想要 [here](https://hexo.yuanjh.cn/) 的效果，我应该如何处理？

注意到这位这个魔改的老哥用的是老版本的 icarus 主题，在 [这里](https://github.com/yuanjh6/hexo-theme-icarus) 可以看到。

**Comment by LeverImmy** [comment]
简而言之，我应该在哪里处理 widget (profile, tags 等) 的宽度？就是这个宽度是在哪里修改的？

**Comment by Zhounning** [comment]
> 简而言之，我应该在哪里处理 widget (profile, tags 等) 的宽度？就是这个宽度是在哪里修改的？

我现在也遇到了这个问题，也在想怎么改把内容放发一些，感觉好难。。。

**Comment by LeverImmy** [comment]
> > 简而言之，我应该在哪里处理 widget (profile, tags 等) 的宽度？就是这个宽度是在哪里修改的？
> 
> 我现在也遇到了这个问题，也在想怎么改把内容放发一些，感觉好难。。。

#696

**Comment by Zhounning** [comment]
> > 我翻了下以前的issues，发现有类似的问题，当时改的是includes/helpers/下的layout.js。但我下载的是3.0.0版本，对应主题目录下没有相应的目录和文件，有的只是layout/layout.jsx文件，请问这个如何处理呢？
> 
> 我个人开发了一个分支yuan_dev：https://github.com/yuanjh6/hexo-theme-icarus
> 这里默认2栏，博客效果：https://hexo.yuanjh.cn/
> 你可以试试

能悄悄问一下你那个csdn的图标是怎么弄的吗，打扰了

**Comment by telami** [comment]
@zhou-ning 是我这样的效果么
https://www.telami.cn/

**Comment by zhou-ning** [comment]
> @zhou-ning 是我这样的效果么
> https://www.telami.cn/

你那种也很好看，不过我已经弄好了，感谢老铁
