### ISSUE TITLE
Insight.js is not found in the generated static files

### ISSUE THREAD

**Issue by liuyanzhou** [ppoffice/hexo-theme-icarus#659]
When packaging, insight. Js is not packaged in, resulting in the search function can not be used

![image](https://user-images.githubusercontent.com/50945362/78454036-15d46800-76c8-11ea-9e5f-22fbaf5ea8b2.png)

**Comment by ppoffice** [comment]
Please follow the issue template and describe your set up, configuration, and system context.

**Comment by liuyanzhou** [comment]
作者你好，我在配置搜索功能的时候发现了一个问题，生成静态界面中不包含`insight. Js`，所以搜索功能不能运行，而浏览器报错。

错误截图
![image](https://user-images.githubusercontent.com/50945362/78464015-d2551a80-7716-11ea-8b3a-3b5cf1f25aa1.png)

也可以去我的新建博客查看问题:https://mrs_liu.gitee.io/myblog/

icarus 版本： 3.0.0
hexo 版本：   3.1.0
浏览器版本 ：  80.0.3987.163

**Comment by ppoffice** [comment]
@liuyanzhou 请检查你博客下node_modules的hexo-component-inferno的版本，如果不是最新的0.2.1版本的话，升级到0.2.1

**Comment by liuyanzhou** [comment]
问题解决了 谢谢  请问您一下 现在主题使用了jsx语法，那么react那一套支持吗

**Comment by ppoffice** [comment]
@liuyanzhou 只能支持到SSR（服务端渲染）这一层，如果你想实现state之类的浏览器中的动态渲染的话就得自己想办法了。
