### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by iamchathu** [ppoffice/hexo-theme-icarus#66]
How to create a 404 page?

**Comment by ppoffice** [comment]
You can add a `404.html` in your source folder, and add `layout: false` to the front matter.

* https://github.com/hexojs/hexo/issues/1465
* https://hexo.io/docs/front-matter.html

**Comment by riapp** [comment]
I just did that. Not working for me. Still saying `Cannot GET /my-notexisted-page`.
Also I tried to generate 404 page by running `hexo new page 404`. But still have same issue.
Any thoughts?

**Comment by ppoffice** [comment]
Where do you host your site's files?
If you host it on GitHub, you should put 404.html in your root folder according to:
https://help.github.com/articles/custom-404-pages/

**Comment by online** [comment]
@riapp, if you host your blog on GitHub, create a file `404.md` in `source` folder. Here's how it looks:

![2015-12-19 01 20 16](https://cloud.githubusercontent.com/assets/722881/11909398/db22d92a-a5ee-11e5-8245-5c97e9175dda.png)

Then use the standard commands:

- hexo generate
- hexo deploy

**Comment by riapp** [comment]
I just was testing that locally by running `hexo server`

**Comment by online** [comment]
@riapp, yes, you understood correctly. Locally redirection is not working.
