### ISSUE TITLE
Sharethis function is not working

### ISSUE THREAD

**Issue by aweimeow** [ppoffice/hexo-theme-icarus#662]
**Describe the bug**

Hello, I'm trying to deploy icarus theme today, and I've set the sharethis url into `_config.yml`, but the buttons are not showing. As I check, the height of `div` block is set to 0, I'm not sure if this related to my issue.

**System and Environment**
Hexo: 3.1
icarus: master branch

**Expected behavior**
The button should show on the bottom of the post. 

**Screenshots**
<img width="1053" alt="Screen Shot 2020-04-05 at 6 30 34 PM" src="https://user-images.githubusercontent.com/5120010/78472473-a44df580-776b-11ea-9e0f-5e5be92063b3.png">

**Desktop (please complete the following information if applicable):**
 - OS: MacOS 10.14
 - Browser: Chromium 80.0.3987.149

**Additional context**
When I check the usage of sharethis function, I found [this page](https://blog.zhangruipeng.me/hexo-theme-icarus/Plugins/Share/sharethis-share-plugin/) as document, but the buttons were not showing, either.

**Comment by aweimeow** [comment]
Update: I can see the buttons in Safari, but still not in chromium browser :(

**Comment by ppoffice** [comment]
Do you have any adblockers in chrome? Try to visit the page in private mode with all chrome extensions disabled.

**Comment by aweimeow** [comment]
@ppoffice Exactly, you're right, thank you! This theme is my favorite one, thanks for all your works.
