### ISSUE TITLE
首页的文章列表上，怎么不显示文章的标题

### ISSUE THREAD

**Issue by scillidan** [ppoffice/hexo-theme-icarus#663]
像是这样
![](https://raw.githubusercontent.com/scillidan/scillidan.driver.github/master/icarus_issues_569.png)

**Comment by ppoffice** [comment]
@scillidan 这个好像是Hexo 4.x的问题
https://github.com/hexojs/hexo/blob/4.0.0/lib/plugins/processor/post.js#L118-L124
你可以对比下这几行在4.0.0和3.9.0的区别。请到Hexo的GitHub提交issue。

**Comment by ppoffice** [comment]
@scillidan 另外，你可以试试把`title`设置为空，例如
https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/site/source/about/index.md
对应的页面就没有标题
https://blog.zhangruipeng.me/hexo-theme-icarus/about/

**Comment by scillidan** [comment]
@ppoffice 尴尬！我没有表述清楚。
在文章页面可以隐藏标题，但在首页，以及`archives`页面，`recent posts`组件还是会显示文章标题。

**Comment by yuanjh6** [comment]
@scillidan  其他框架，标题出现在2个位置，第一个文章头部的```里面的title：xxx 字段，第二个一般是正文部分首行# xxx，但是这个框架只能保留一个，title：xxx保留，文章正文首行的# xxx，这个删掉才行，否则会出现双标题现象，典型的nexo主题迁移过来就会这样
