### ISSUE TITLE
3.0.0版怎么删除目录序号

### ISSUE THREAD

**Issue by scillidan** [ppoffice/hexo-theme-icarus#664]
已解决 https://github.com/ppoffice/hexo-theme-icarus/issues/374#issuecomment-609418124

**Comment by scillidan** [comment]
报错了！
![](https://raw.githubusercontent.com/scillidan/scillidan.driver.github/master/icarus_issues_664.png)

**Comment by ppoffice** [comment]
@scillidan 你是怎样对toc.jsx改动的？

**Comment by scillidan** [comment]
[toc.jsx](https://raw.githubusercontent.com/scillidan/scillidan.driver.github/master/toc.jsx)
hexo-util版本是`1.8.0`

**Comment by ppoffice** [comment]
你对比下https://github.com/ppoffice/hexo-component-inferno/blob/master/src/view/widget/toc.jsx
我不清楚为什么你要改变第一个require

**Comment by scillidan** [comment]
@ppoffice 啊啊，我记得是高亮了的…但我莫名其妙就复制粘贴了这三行。
这下好了。谢谢！

**Comment by ppoffice** [comment]
相关Issue指路：#669
