### ISSUE TITLE
关于widget的一些问题

### ISSUE THREAD

**Issue by YeWenzhen** [ppoffice/hexo-theme-icarus#667]
1.如果我不想显示social_links 要怎样操作呢，我直接将social_links注释的话，会报错，如果我赋值为空（social_links: ''）的话，生成的时候会有提醒，不知道官方如果解决呢。
2.如果我不想显示recent_posts，我直接注释又报错，那要怎么处理。
很谢谢你为我们提供强大的界面，想问你以上两个问题。

**Comment by ppoffice** [comment]
直接删掉那几行。我感觉你没有注释对，可以去学习下yaml语法

**Comment by YeWenzhen** [comment]
好的，谢谢
