### ISSUE TITLE
How to remove # symbol from the tags page?

### ISSUE THREAD

**Issue by 201507** [ppoffice/hexo-theme-icarus#67]
Hello!

I mean this symbol:

![2015-12-01 21 40 54](https://cloud.githubusercontent.com/assets/13576842/11511904/51ca9b5e-9874-11e5-9256-238e1cc68da1.png)

Thank you in advance for your help.

**Comment by ppoffice** [comment]
Tags are generated by Hexo's `tagcloud` function:

* https://hexo.io/docs/helpers.html#tagcloud
* https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/tags.ejs#L7

But Hexo doesn't provide an option for removing `#`. So I think the best solution is using JavaScript to process results of `tagcloud` and trim down `#`.

**Comment by online** [comment]
@ppoffice, thanks for your reply. Tell me, please, how to do it using JavaScript?

**Comment by 201507** [comment]
@ppoffice, thanks for your reply. Tell me, please, how to do it using JavaScript?

**Comment by PhiLhoSoft** [comment]
Curiously, the tag cloud on the side column doesn't show these hashtags...

**Comment by online** [comment]
@PhiLhoSoft :+1:

**Comment by ppoffice** [comment]
@PhiLhoSoft @online 
Sorry, my mistake...
There is a style controls the `#`:
https://github.com/ppoffice/hexo-theme-icarus/blob/250600d06e38f7b3a5b34c4c640298da43c4e6ab/source/css/_partial/archive.styl#L112

**Comment by online** [comment]
@ppoffice, thank you very much for your help :wink:
