### ISSUE TITLE
[Question] How to overwrite the font-size for laptop only?

### ISSUE THREAD

**Issue by aweimeow** [ppoffice/hexo-theme-icarus#670]
Hello authors, 

I would like to overwrite the font-size for "big screen" (e.g. laptop or larger screen), and I don't want the css style to affect font-size on mobile and tablet, could you guide me to modify it?

Appreciate for your answer in advance :)

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/tree/master/include/style/responsive.styl

**Comment by aweimeow** [comment]
Issue solved, thanks!
