### ISSUE TITLE
能否实现文章目录单独浮动和子目录折叠

### ISSUE THREAD

**Issue by bytepoem** [ppoffice/hexo-theme-icarus#673]
作者你好，目前我使用的 hexo 和 icarus 都是最新版本

### 目前问题

对于一些较长的文章（h1，h2 标题较多），目前主题提供的文章目录功能只能设置左边或右边的widget 整列浮动，且文章目录过长时会导致底部的部分一直在屏幕之外

![文章页面](https://user-images.githubusercontent.com/48577796/79063423-3ad26780-7cd4-11ea-8683-d1ce7e5c4f5c.png)

![文章源文件](https://user-images.githubusercontent.com/48577796/79063447-4f166480-7cd4-11ea-8119-8703589b5e02.png)

### 建议

能否实现

* TOC 这类 widget 单独浮动
* TOC 子目录折叠（自动或者手动）

示例网站：http://theme-next.iissnan.com/getting-started.html#install-next-theme

![示例](https://user-images.githubusercontent.com/48577796/79063307-699c0e00-7cd3-11ea-927c-808a8358e68c.png)

示例网站：http://moxfive.coding.me/2016/06/13/hexo-collapsible-toc/

![示例](https://user-images.githubusercontent.com/48577796/79063558-07dca380-7cd5-11ea-9ee5-a2091923ebcd.png)

**Comment by ppoffice** [comment]
> TOC 这类 widget 单独浮动

请更新主题到master分支的最新commit，并参照[此处](https://github.com/ppoffice/hexo-theme-icarus/issues/669#issuecomment-611399694)复制`toc.jsx`并添加`is-sticky`到

https://github.com/ppoffice/hexo-component-inferno/blob/0.2.3/src/view/widget/toc.jsx#L118

这行的`class="card widget"`的引号之中（变成`class="card widget is-sticky"`）。

> TOC 子目录折叠（自动或者手动）

请参考 https://removeif.github.io/theme/%E5%8D%9A%E5%AE%A2%E6%BA%90%E7%A0%81%E5%88%86%E4%BA%AB.html 和 https://github.com/removeif/hexo-theme-amazing/blob/master/layout/widget/toc.jsx

**Comment by kaiattrib** [comment]
Hi , @ppoffice 您好 !。查过ISSUES了, 代码是当前master最新的，尝试复制并修改toc.jsx 并 重新hexo g生成成功。但是没有效果还累类似上面的 。请教一下，我是可能漏掉了什么配置或错误吗？ 再次感谢您的热情与分享!
![img](https://user-images.githubusercontent.com/48577796/79063423-3ad26780-7cd4-11ea-8683-d1ce7e5c4f5c.png)
