### ISSUE TITLE
自动给博文添加 ReadMore

### ISSUE THREAD

**Issue by LuchaoQi** [ppoffice/hexo-theme-icarus#676]
能否添加一个类似于链接中的功能来按照行数添加read more
https://blog.zthxxx.me/post/hexo-automatic-add-readmore/
3.0 版本更新以后 我试过在article.jsx里面修改但是效果好像不太好

**Comment by ppoffice** [comment]
@LuchaoQi 试试安装此插件，并在它的代码的基础上进行更改。

**Comment by tvp100** [comment]
@LuchaoQi 我并不擅长jsx的代码编写，请问可以提供相关代码吗，我急需这个功能。

**Comment by LuchaoQi** [comment]
> @LuchaoQi 我并不擅长jsx的代码编写，请问可以提供相关代码吗，我急需这个功能。

我也正在摸索中, 效果不是很理想, 一个solution就是回装3.0以前的版本然后在ejs里面使用那部分代码

**Comment by herotiga** [comment]
修改`scaffolds/post.md`文件，添加就可以了。
以后每个new出来的post都会有折叠。

**Comment by LuchaoQi** [comment]
> 修改`scaffolds/post.md`文件，添加就可以了。
> 以后每个new出来的post都会有折叠。

我试过那种方法, 但是有个问题是必须要在readmore之前加入一些内容, 如果前面是空的话就无法生效, 我一般是
```
[TOC]

<!--more-->
```
但发现最后效果还是不太好, 懒人只想找一个不用太care格式的方法:(

**Comment by jinggod** [comment]
> @LuchaoQi 我并不擅长jsx的代码编写，请问可以提供相关代码吗，我急需这个功能。

我已经参考https://blog.zthxxx.me/post/hexo-automatic-add-readmore/，改写了article.jsx，不过我发现用行数不合适，代码块算作一行了，会显得很长，所以就改成长度了，每篇文章的展示内容都差不多。你如果还急用，就看下吧：https://github.com/ppoffice/hexo-theme-icarus/pull/762

**Comment by ppoffice** [comment]
建议使用Hexo插件实现此功能。
