### ISSUE TITLE
html代码预览部分被截取，看图

### ISSUE THREAD

**Issue by CleverBamboo** [ppoffice/hexo-theme-icarus#677]
## hexo-theme-icarus 版本
{
  "name": "hexo-theme-icarus",
  "version": "2.6.0",
  "private": true
}

## 代码和效果截图
* ![TIM截图20200414112250](https://user-images.githubusercontent.com/24216880/79183265-92431580-7e43-11ea-93af-7fa9c176c50d.png)
* ![TIM截图20200414112259](https://user-images.githubusercontent.com/24216880/79183268-940cd900-7e43-11ea-860a-7f31e758db72.png)

**Comment by ppoffice** [comment]
@CleverBamboo 请升级到最新版本的Icarus

**Comment by CleverBamboo** [comment]
是的，升级后就OK了

![image](https://user-images.githubusercontent.com/24216880/79192903-29b46280-7e5c-11ea-9ba3-90e8572c08e7.png)
