### ISSUE TITLE
使用gitalk 配置会一直显示这个提示信息，看图

### ISSUE THREAD

**Issue by CleverBamboo** [ppoffice/hexo-theme-icarus#678]
## "icarus": "version": "3.0.1",

![image](https://user-images.githubusercontent.com/24216880/79211662-18c61a00-7e79-11ea-882c-d3074ea33c65.png)
![image](https://user-images.githubusercontent.com/24216880/79211676-1ebbfb00-7e79-11ea-9b76-fca30a340b12.png)

**Comment by ppoffice** [comment]
admin应该为字符串数组，请参考gitalk官方文档

**Comment by CleverBamboo** [comment]
不好意思
