### ISSUE TITLE
会考虑给文章设置访问密码的功能吗？

### ISSUE THREAD

**Issue by TLHorse** [ppoffice/hexo-theme-icarus#679]
我博客里时常有文章包含不适合公开的信息，所以我希望给文章选择性地添加上访问密码。

访问密码的设置方法，我比较喜欢隔壁[hexo-theme-matery](https://github.com/blinkfox/hexo-theme-matery#detailed-front-matter-options)主题，只需要在全局打开密码特性，然后在需要密码的文章的front-matter里加上password: xxx即可。

访问密码我希望的效果就是，一点开文章或访问链接，先会弹出一个提示框，提示输入密码。成功的话即可进入文章，失败的话就会返回主页。

还有一点就是，在文章front-matter配置密码时，我希望输入的不是明文，而是密码的SHA-256值。因为这个加密算法不可逆，所以即使流传到网上也不会泄漏密码。hexo-theme-matery就是这样做的。

**我原来一直在用hexo-theme-matery主题，后来觉得太花里胡哨，想改成icarus。我觉得有了密码功能，icarus就十全十美了。望作者添加！**

**Comment by imaegoo** [comment]
参考：
https://github.com/ppoffice/hexo-theme-icarus/issues/595#issuecomment-573370112
