### ISSUE TITLE
Open graph meta tags

### ISSUE THREAD

**Issue by iamchathu** [ppoffice/hexo-theme-icarus#68]
How to add open graph meta tags to posts. I need to add banner image to og:images

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/_partial/head.ejs#L23

**Comment by MisterJames** [comment]
@ppoffice Unfortunately that seems to add the same OG tags to all posts.

I would like to specify the image for a particular post so that when it's featured on Twitter/Facebook/etc. that the image I choose from _that_ post is the one that appears. Is this possible?

**Comment by ppoffice** [comment]
@MisterJames 

Now every page has a different og:image thanks to the v0.2.0 release. This is assigned by the post's/page's thumbnail front-matter.

https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/head.ejs#L24

https://github.com/ppoffice/hexo-theme-icarus/wiki/Theme#how-to-add-a-thumbnail-to-a-post

**Comment by walkingice** [comment]
I am wondering how to set og:image for root index page?

**Comment by sudoliyang** [comment]
> @MisterJames
> 
> Now every page has a different og:image thanks to the v0.2.0 release. This is assigned by the post's/page's thumbnail front-matter.
> 
> https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/head.ejs#L24
> 
> https://github.com/ppoffice/hexo-theme-icarus/wiki/Theme#how-to-add-a-thumbnail-to-a-post

Hi, @ppoffice 
It seems not supported after 2.4.0, will this feature come back?

https://github.com/ppoffice/hexo-theme-icarus/commit/b60e51694d516c4cf7e8aae1d13a3aa49901a137#diff-5b14989530ad95f8f7a14c4957e94ac7L24

Thank you.

**Comment by ppoffice** [comment]
@sudoliyang Thanks for the notice.
