### ISSUE TITLE
icarus 3.0.0 tags and categories pages not shown

### ISSUE THREAD

**Issue by raoqinsong** [ppoffice/hexo-theme-icarus#680]
版本3.0.0 tags和categories添加了，但是页面没有展示出来是什么原因

**Comment by imaegoo** [comment]
至少需要有一篇文章配置了tag和category

```
---
title: Hello World
date: 2020-04-14 10:00:00
tags:
- life
categories:
- Diary
---
```

**Comment by raoqinsong** [comment]
<img width="642" alt="Snipaste_2020-04-14_21-30-13" src="https://user-images.githubusercontent.com/48851022/79230828-c5af8f80-7e97-11ea-9a44-f46bfd50d240.png">
<img width="695" alt="Snipaste_2020-04-14_21-30-46" src="https://user-images.githubusercontent.com/48851022/79230843-ca744380-7e97-11ea-88ca-9ed7f5f60267.png">
<img width="925" alt="Snipaste_2020-04-14_21-31-48" src="https://user-images.githubusercontent.com/48851022/79230848-cb0cda00-7e97-11ea-8ed7-6b4fc9876a8c.png">

已经添加了，但是页面就是不显示

**Comment by raoqinsong** [comment]
<img width="642" alt="Snipaste_2020-04-14_21-30-13" src="https://user-images.githubusercontent.com/48851022/79230985-fd1e3c00-7e97-11ea-95f0-275a738ee5b8.png">
<img width="695" alt="Snipaste_2020-04-14_21-30-46" src="https://user-images.githubusercontent.com/48851022/79231002-014a5980-7e98-11ea-836b-03110a33f065.png">
<img width="925" alt="Snipaste_2020-04-14_21-31-48" src="https://user-images.githubusercontent.com/48851022/79231004-027b8680-7e98-11ea-9371-0ae8644dae0a.png">


已经添加了，但是页面还是不显示

**Comment by raoqinsong** [comment]
tags/index.md
---
title: tags
date: 2020-04-14 12:59:27
type: "tags"
tags:  
  - PS3
  - Games
---


categories/index.md
---
title: categories
date: 2020-04-14 12:59:57
type: "categories"
categories:  
  - Diary
  - Life
---

已经这样配置了但是页面还是没有显示

**Comment by imaegoo** [comment]
请将文章放置在 _posts 目录下，放在source下的md文件将被视为page，page没有category和tag

https://hexo.io/zh-cn/docs/writing#%E5%B8%83%E5%B1%80%EF%BC%88Layout%EF%BC%89

**Comment by imaegoo** [comment]
/categories/ 和 /tags/ 两个 page 由 hexo 自动生成，无需创建 `tags/index.md` 和 `categories/index.md`

**Comment by raoqinsong** [comment]
好的谢谢
