### ISSUE TITLE
开启sharethis分享插件后，所有post页面都会无法交互，所有按钮、链接失效，和图片一样。

### ISSUE THREAD

**Issue by declan-haojin** [ppoffice/hexo-theme-icarus#682]
开启sharethis分享插件后，所有post页面都会无法交互，所有按钮、链接失效，和图片一样。主页和其他没有评论插件的页面功能正常。关闭sharethis启用其他的插件之后post页面就好了。请问有什么解决方案吗，谢谢！

**Comment by ppoffice** [comment]
@declan-haojin 我这里没有这个问题。请检查是否是浏览器的广告屏蔽插件导致的。另外你的浏览器和系统版本是什么？

**Comment by declan-haojin** [comment]
安卓chrome浏览器，win10 edge chromium 和 chrome都试了，cookies清除了，广告屏蔽关了还是有问题

**Comment by ppoffice** [comment]
@declan-haojin 可以将你出问题的post上传到github pages么？

**Comment by declan-haojin** [comment]
好的，稍等，刚刚又发现一个问题，hotjar配置正确之后去hotjar验证也是通过但是主页没有hotjar显示。麻烦了，谢谢！

**Comment by declan-haojin** [comment]
https://github.com/declan-haojin/declan-haojin.github.io

![](https://declan-haojin.github.io) 点进helloworld博客之后网页就没有任何交互了，谢谢！

**Comment by declan-haojin** [comment]
所有post都出问题了，我重置了hexo，重建了post也无法解决，谢谢

**Comment by ppoffice** [comment]
@declan-haojin 请把ShareThis的GDPR功能关闭试试

**Comment by declan-haojin** [comment]
好的，谢谢！以后再也不胡点了 😂
谢谢大佬，您做的主题真的很棒！
如果方便的话，可以留下您的邮箱吗，还有一些问题想要请教您！
