### ISSUE TITLE
能否在Navbar和Footer使用不同的logo呢？

### ISSUE THREAD

**Issue by liu-yihong** [ppoffice/hexo-theme-icarus#683]
我自己尝试本地修改了一下源码，但是没有成功。不知道可不可以在Navbar和Footer使用不同的logo呢？

**Comment by ppoffice** [comment]
@liu-yihong 可以。把下面这行
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/footer.jsx#L23
改成
```jsx
<img src="你想要的图片URL" alt={siteTitle} height="28" />
```

**Comment by liu-yihong** [comment]
谢谢😋
