### ISSUE TITLE
version3.0.0,每一个页面都会这样的提示

### ISSUE THREAD

**Issue by CleverBamboo** [ppoffice/hexo-theme-icarus#685]
## 重新搭建的3.0.0版本，只是迁移文章过来，但每个页面都这么显示

![image](https://user-images.githubusercontent.com/24216880/79289287-6b481a80-7efb-11ea-86df-3b80b36b6a1f.png)
![image](https://user-images.githubusercontent.com/24216880/79289322-83b83500-7efb-11ea-9079-046014b234e6.png)

**Comment by TLHorse** [comment]
我的网站也是这样。如果你哪里没配置，icarus就显示红框。但是有时候我明明不想配置，icarus还是提示红框。

**Comment by ppoffice** [comment]
@CleverBamboo @TLHorse 没配置的地方把配置注释掉或者删掉。
