### ISSUE TITLE
Where is Disqus.js plugin?

### ISSUE THREAD

**Issue by daep93** [ppoffice/hexo-theme-icarus#686]
I can't find Disqus.js plugin file in release 3.0.1.

Thx.

**Comment by ppoffice** [comment]
@daep93 https://blog.zhangruipeng.me/hexo-theme-icarus/Plugins/Comment/icarus用户指南-用户评论插件

**Comment by daep93** [comment]
> @daep93 https://blog.zhangruipeng.me/hexo-theme-icarus/Plugins/Comment/icarus-user-guide-comment-plugins/

Yea! I appreciate your help. It works!
