### ISSUE TITLE
_config.yml 缺少网站标题配置

### ISSUE THREAD

**Issue by CleverBamboo** [ppoffice/hexo-theme-icarus#687]
![image](https://user-images.githubusercontent.com/24216880/79297389-8c673600-7f10-11ea-9091-4aefd37cb35e.png)
![image](https://user-images.githubusercontent.com/24216880/79297399-95f09e00-7f10-11ea-8676-cb8026a423bf.png)

**Comment by ppoffice** [comment]
@CleverBamboo 那个是根目录下`_config.yml`中的设置。建议使用Icarus之前先熟练使用Hexo。
