### ISSUE TITLE
导航栏问题

### ISSUE THREAD

**Issue by TLHorse** [ppoffice/hexo-theme-icarus#688]
1. 网站的lang设置成zh-CN，文字都转成了中文，但是网页的导航栏还是英文：
<img width="1762" alt="截屏2020-04-15下午2 58 49" src="https://user-images.githubusercontent.com/38977108/79307658-d4df1d80-7f29-11ea-9b50-a37c3a52af42.png">

2. 导航栏上的logo不显示。不知道是不是yml的问题。

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/issues/18

请善用搜索和官方文档

**Comment by TLHorse** [comment]
那么请问导航栏logo为何不显示？

**Comment by ppoffice** [comment]
@TLHorse 可能是图片路径有问题。请使用图片的绝对路径URL或者仔细检查配置文件中图片的相对路径是否正确。
