### ISSUE TITLE
添加Instagram问题

### ISSUE THREAD

**Issue by alexwan2011** [ppoffice/hexo-theme-icarus#69]
尝试用[这个方法](https://github.com/litten/hexo-theme-yilia/wiki/%E5%90%8C%E6%AD%A5%E4%BD%A0%E7%9A%84instagram%E5%9B%BE%E7%89%87)添加instagram到博客里，但是一直无法显示，目测是调用js文件失败，把js文件复制到了目录下面也不行。请教一下不知道哪里错了。。。或者能不能在这个模板里加入添加instagram的功能？谢谢！

**Comment by ppoffice** [comment]
主题不支持Instagram

**Comment by alexwan2011** [comment]
好的，那就放弃了，谢啦
