### ISSUE TITLE
Change the width of the website

### ISSUE THREAD

**Issue by 0xd3xt3r** [ppoffice/hexo-theme-icarus#690]
How do increase the width of the side and reduce the padding on both the side ? can we have this as a configuration variable?

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/base.styl#L23-L27

https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/responsive.styl

**Comment by 0xd3xt3r** [comment]
thanks for the response. I also want to change the width of the widget and main content. I want to give more space to the content.

Thanks again.
