### ISSUE TITLE
能否实现banner和thumbnail分开？

### ISSUE THREAD

**Issue by declan-haojin** [ppoffice/hexo-theme-icarus#692]
post预览的thumbnail是方形
post的banner是长条形
请问能够把两个设为单独的图片，这样就不用担心图片切割的问题了，谢谢！

**Comment by ppoffice** [comment]
Icarus暂时没有所谓的banner设置。

**Comment by declan-haojin** [comment]
好吧，谢谢了！

**Comment by zhangxu3486432** [comment]
仅供参考 [区分 thumbnail 和 cover/banner](https://github.com/zhangxu3486432/hexo-theme-icarus/commit/29c32ec7d6e42c745da7e0c0c580684675dfe4a6#diff-94d8bc0dfd1443959b331a345d59017a)

**Comment by ppoffice** [comment]
Feature added in 304e8ea3680b8eb8806d288310655f89fa7ed8ba
