### ISSUE TITLE
请问有没有办法优化移动端打开的效果呢

### ISSUE THREAD

**Issue by jensondong** [ppoffice/hexo-theme-icarus#693]

**Comment by YunShu007** [comment]
> _No description provided._

可以参考这篇文章进行一些设置https://www.alphalxy.com/2019/03/customize-icarus/

**Comment by YunShu007** [comment]
> @jensondong 请详细描述什么叫“优化移动端打开的效果”

    用移动端浏览我还遇到一个问题:就是访问某些文章时,双指缩放可以看到右侧会空出来一部分.
,我的icarus版本是2.6.4,由于我已经参照很多教程对icarus进行了修改,所以并不知道是不是icarus本身的问题😂
[这篇文章](https://www.ysblog.xyz/2020/01/25/java_note_1.html),区块中文字突出,导致右侧出现空白.
![图片](https://gitee.com/YunShu007/Blog_images/raw/master//Screenshot_20200419111343.jpg)
[另一篇文章中](https://www.ysblog.xyz/2020/03/04/java_note_2.html),公式块突出导致了右侧出现空白![图片](https://gitee.com/YunShu007/Blog_images/raw/master//Screenshot_20200419111334.jpg)
我找到了一个icarus版本为3.0的[博客](https://tiexo.github.io/faca3062/)发现移动端浏览依然会有这个问题.![图片](https://gitee.com/YunShu007/Blog_images/raw/master//Screenshot_20200419111324.jpg)

**Comment by ppoffice** [comment]
@YunShu007 公式的容器长度是由MathJax控制的，目前没有什么比较好的解决方法。建议将问题从公式中拿出来，并缩短公式长度。
另外两类内容超过容器宽度的问题在最新的commit中修复。

**Comment by YunShu007** [comment]
了解,麻烦了😂

**Comment by duinomaker** [comment]
> @YunShu007 公式的容器长度是由MathJax控制的，目前没有什么比较好的解决方法。建议将问题从公式中拿出来，并缩短公式长度。
> 另外两类内容超过容器宽度的问题在最新的commit中修复。

这个好解决，我的博客里经常用到数学公式，所以总结了这三点经验：

1. 公式过长，可以自动加入水平滚动条。以下方法同时适用 MathJax 和 KaTeX：
```
.katex-display, .MathJax
    overflow-x: auto
    overflow-y: hidden
```

2. 为了避免 KaTeX 内联公式在奇怪的地方换行，可以禁止换行，加入：
```
.katex
    white-space: nowrap
```

3. KaTeX 渲染的公式在苹果手机(iPhone 6s, Safari & Firefox, 其它的没试过)上会出现 “削顶” 的情况，公式顶部会有一部分显示不出来，可以这样解决：
```
.katex-html
    padding-top: 1em
.katex-display
    margin-top: -1em !important
```

我比较懒，就只在评论里说一下啦，哈哈。
