### ISSUE TITLE
"No layout" after upgrade icarus

### ISSUE THREAD

**Issue by kreimben** [ppoffice/hexo-theme-icarus#694]
Hi, I've used icarus version 2.6.0 and I upgraded icarus.

I cloned latest version of it and just copied `_config.yml` file and some of essential files (images) to new cloned icarus folder. (cloned *new* theme and old theme is separated.)

And then install some of tools terminal said that I should install (sorry I don't rememeber what it is...)

Surely, I changed icarus version in front of `_config.yml`.

but when I try to generate and deploy, terminal displays
```
WARN  No layout: Blog/readme/index.html
WARN  No layout: archives/index.html
WARN  No layout: archives/2020/index.html
WARN  No layout: archives/2020/04/index.html
WARN  No layout: index.html
```

and my homepage displays literally *nothing*......

What I have to do from now...?

Thanks :) 🙏

**Comment by ppoffice** [comment]
@kreimben 
1. Don't change the version of `_config.yml`. Icarus will upgrade the configuration file for you.
2. Please copy and paste the `package.json` in the root directory of your blog here. Also please check if the `hexo-renderer-inferno` package is installed.

**Comment by geekeritcom** [comment]
i have same problem when i run `npm g` and how can i solve

**Comment by geekeritcom** [comment]
this is my package.json

{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "accepts": "^1.3.7",
    "bulma-stylus": "^0.8.0",
    "cnpm": "^6.1.1",
    "compressible": "^2.0.17",
    "compression": "^1.7.4",
    "connect": "^3.7.0",
    "deepmerge": "^4.2.2",
    "finalhandler": "^1.1.2",
    "hexo": "^4.2.0",
    "hexo-admin": "^2.3.0",
    "hexo-asset-image": "^1.0.0",
    "hexo-component-inferno": "^0.2.4",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-log": "^1.0.0",
    "hexo-pagination": "^1.0.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-inferno": "^0.1.3",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-scss": "^1.2.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.4.4",
    "hexo-util": "^1.9.0",
    "inferno": "^7.4.2",
    "inferno-create-element": "^7.4.2",
    "vary": "^1.1.2"
  }
}

**Comment by ppoffice** [comment]
You have installed a lot of Hexo plugins. The issue could be caused by some of them. The best way to resolve this is to start a new Hexo project and adding the plugins you need one by one.

If you still want to fix the current setup, please upload your blog's source code so I can replicate the errors you encountered.

**Comment by kreimben** [comment]
> @kreimben
> 
> 1. Don't change the version of `_config.yml`. Icarus will upgrade the configuration file for you.
> 2. Please copy and paste the `package.json` in the root directory of your blog here. Also please check if the `hexo-renderer-inferno` package is installed.

copy and paste WHERE's package.json....?
I've seen it (real) root's and each of theme's....

Can I paste OLD theme's package.json to NEW theme directory?

I'm confused! 🤷‍♂️

**Comment by ppoffice** [comment]
@kreimben 
![image](https://user-images.githubusercontent.com/8849362/79578961-f1e42f80-8094-11ea-86df-51293b1dc73f.png)

Upload it here so I can see what packages you have installed.

**Comment by kreimben** [comment]
Oh OK.

I copied Hexo root's package.json like above guy.

Thanks.

---


{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "cheerio": "^1.0.0-rc.3",
    "hexo": "^4.0.0",
    "hexo-asset-image-fix": "^0.1.0",
    "hexo-asset-link": "^2.0.1",
    "hexo-auto-canonical": "^0.1.1",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.3.0",
    "hexo-generator-seo-friendly-sitemap": "0.0.25",
    "hexo-generator-tag": "^1.0.0",
    "hexo-related-popular-posts": "^4.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-inferno": "^0.1.3",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

**Comment by ppoffice** [comment]
@kreimben I see some of the required packages are missing here. Did you following Icaurs's warning to run the `npm install --save ...` command to install everything you need? You must do that before the theme can ever work correctly.

Please also check out this configuration file of the Icarus site for your reference:
https://github.com/ppoffice/hexo-theme-icarus/blob/site/package.json

**Comment by kreimben** [comment]
NO, NO.
It didn't works....

I re-cloned new 3.0.1 and re-do it again from start, just copy and paste `_config.yml` and install some program. (I checked those program version 3 times... / Of coursely, I checkouted my git before install new version. and updates || upgrades programs on your link.)

Below is terminal's result

Thanks;

---

Inferno is in development mode.
INFO  =======================================
 ██╗ ██████╗ █████╗ ██████╗ ██╗   ██╗███████╗
 ██║██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝
 ██║██║     ███████║██████╔╝██║   ██║███████╗
 ██║██║     ██╔══██║██╔══██╗██║   ██║╚════██║
 ██║╚██████╗██║  ██║██║  ██║╚██████╔╝███████║
 ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
=============================================
INFO  === Checking package dependencies ===
INFO  === Checking the configuration file ===
INFO  Your configuration file is outdated (2.6.0 < 3.0.0). Trying to upgrade it...
INFO  Current configurations are written up to /Users/aksidionkreimben/Documents/Repository/Web Repository/kreimben.com/themes/hexo-theme-icarus-3.0.1/_config.yml.8fdd044b9bf755c2
INFO  /Users/aksidionkreimben/Documents/Repository/Web Repository/kreimben.com/themes/hexo-theme-icarus-3.0.1/_config.yml upgraded successfully.
INFO  We also created an example at /Users/aksidionkreimben/Documents/Repository/Web Repository/kreimben.com/themes/hexo-theme-icarus-3.0.1/_config.yml.example for your reference.
WARN  Configuration file failed one or more checks.
WARN  Icarus may still run, but you will encounter unexcepted results.
WARN  Here is some information for you to correct the configuration file.
WARN  [
  {
    keyword: 'type',
    dataPath: '.donates[1]',
    schemaPath: '#/items/type',
    params: { type: 'object' },
    message: 'should be object'
  }
]
INFO  === Registering Hexo extensions ===
INFO  Deleted database.
INFO  Deleted public folder.
Inferno is in development mode.
INFO  =======================================
 ██╗ ██████╗ █████╗ ██████╗ ██╗   ██╗███████╗
 ██║██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝
 ██║██║     ███████║██████╔╝██║   ██║███████╗
 ██║██║     ██╔══██║██╔══██╗██║   ██║╚════██║
 ██║╚██████╗██║  ██║██║  ██║╚██████╔╝███████║
 ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
=============================================
INFO  === Checking package dependencies ===
INFO  === Checking the configuration file ===
WARN  Configuration file failed one or more checks.
WARN  Icarus may still run, but you will encounter unexcepted results.
WARN  Here is some information for you to correct the configuration file.
WARN  [
  {
    keyword: 'type',
    dataPath: '.donates[1]',
    schemaPath: '#/items/type',
    params: { type: 'object' },
    message: 'should be object'
  }
]
INFO  === Registering Hexo extensions ===
INFO  Start processing
INFO  Files loaded in 2.56 s
ERROR Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null

**Comment by ppoffice** [comment]
@kreimben Could you please upload your blog's source code along with the `_config.yml` files somewhere so I can take a look? Thanks.

**Comment by kreimben** [comment]
My repository is private, and deployed at firebase.

I invited you as a collaborator, so please accept it

**Comment by ppoffice** [comment]
@kreimben The log says something wrong about your theme configuration. The first item of `donates` should be an object. Could you post your theme's configuration here?

**Comment by ppoffice** [comment]
Also, I found out there's a syntax error in your Icarus 2.6 configuration file:

```
# Donation entries
# https://ppoffice.github.io/hexo-theme-icarus/categories/Donation/
donate:
    -
        type: paypal
        business: 'aksidion@kreimben.com'
        currency_code: USD
    -
```

You should delete the last `-` since the array item is empty.

**Comment by kreimben** [comment]
> @kreimben The log says something wrong about your theme configuration. The first item of `donates` should be an object. Could you post your theme's configuration here?

You seem to saw my `_config.yml` file.
Do I have to paste `_config.yml` again?

**Comment by kreimben** [comment]
> Also, I found out there's a syntax error in your Icarus 2.6 configuration file:
> 
> ```
> # Donation entries
> # https://ppoffice.github.io/hexo-theme-icarus/categories/Donation/
> donate:
>     -
>         type: paypal
>         business: 'aksidion@kreimben.com'
>         currency_code: USD
>     -
> ```
> 
> You should delete the last `-` since the array item is empty.

and I changed that `-` and pushed on GitHub.

**Comment by ppoffice** [comment]
@kreimben Please update your theme to the latest commit and try again.

**Comment by kreimben** [comment]
OH IT WORKS!

Thank you for your service!
