### ISSUE TITLE
请问 widget 宽度如何修改？

### ISSUE THREAD

**Issue by LeverImmy** [ppoffice/hexo-theme-icarus#696]
隐藏右侧边栏后，两边空隙过大。

已经尝试过更改 base.yml 中的值，但是 **widget** 的宽度会随着你调整 widescreen 等参数的大小而变化。

我希望能达到 [here](https://sm.ms/image/pAINMHbo47JsU2L) 的效果，而不是 [here](https://sm.ms/image/DKr645xP8Q2Ii19) 的效果。

同时，以前修改 ejs 的解决方法并不适用，因此 #40  #434 #581 所叙述的解决方案并不适用。

望处理，谢谢！

**Comment by ppoffice** [comment]
@LeverImmy 

https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/widgets.jsx#L35-L38
https://bulma.io/documentation/columns/sizes/

**Comment by LeverImmy** [comment]
> @LeverImmy
> 
> https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/widgets.jsx#L35-L38
> https://bulma.io/documentation/columns/sizes/

但这样会导致左右不均衡（左边 widget 到页面左侧的距离与右侧的距离不相等）

**Comment by ppoffice** [comment]
@LeverImmy 同时也要修改主内容栏的宽度，使所有栏的宽度相加等于12。

https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/layout.jsx#L29-L30

**Comment by LeverImmy** [comment]
非常感谢！已解决。

**Comment by Zhounning** [comment]
> 非常感谢！已解决。

诶这样我虽然把widget 减小了，但是主内容栏的宽度的没有变化好像，我想让主内容也变大一些可以吗

**Comment by LeverImmy** [comment]
> > 非常感谢！已解决。
> 
> 诶这样我虽然把widget 减小了，但是主内容栏的宽度的没有变化好像，我想让主内容也变大一些可以吗

麻烦留一下 QQ？方便交流。

这是我的 QQ：506503360

**Comment by Zhounning** [comment]
> > > 非常感谢！已解决。
> > 
> > 
> > 诶这样我虽然把widget 减小了，但是主内容栏的宽度的没有变化好像，我想让主内容也变大一些可以吗
> 
> 麻烦留一下 QQ？方便交流。
> 
> 这是我的 QQ：506503360

已经解决，感谢

**Comment by xiechuanyu** [comment]
请问具体如何设置呢？数字怎么改呢？谁和谁加起来等于 12 ？

**Comment by Lechrond** [comment]
中间的模块大小还是无法调节阿，只能在widget和column-main之间分配这12块大小，但是我想让12块拥有的面积变大要去哪里设置呢？

**Comment by xiechuanyu** [comment]
> 中间的模块大小还是无法调节阿，只能在widget和column-main之间分配这12块大小，但是我想让12块拥有的面积变大要去哪里设置呢？
我也在想这个，好像上面说的不是指总大小。后来觉得很多平台的两边留白都是这么大，自己有点矫枉过正了，就不管了。。。

**Comment by Lechrond** [comment]
> > 中间的模块大小还是无法调节阿，只能在widget和column-main之间分配这12块大小，但是我想让12块拥有的面积变大要去哪里设置呢？
> 
> 我也在想这个，好像上面说的不是指总大小。后来觉得很多平台的两边留白都是这么大，自己有点矫枉过正了，就不管了。。。

是啊，但是也有人修改成功了，所以肯定是可以做到的。我看了好几个issue都没有回答这个问题，或者就是老版的解决方案现在已经不适用了。主要是中间那块真的太窄了，两边留白太多了，看着很不舒服。

**Comment by ppoffice** [comment]
@Lechrond 官网上的中文FAQ中有提到如何修改widget和主内容栏发现，以及页面总大小。

**Comment by Lechrond** [comment]
> @Lechrond 官网上的中文FAQ中有提到如何修改widget和主内容栏发现，以及页面总大小。

常见问题中指出：”如要改变页面的宽度，编辑themes/icarus/include/style/responsive.styl这个样式文件。 此文件定义了不同屏幕尺寸下的页面容器宽度。“
但是我修改了responsive.styl的widescreen中的max-width和width（尝试了改为max-width: $desktop - $gap或者赋固定px的大小），没有任何效果，请问能否给出具体的修改方法？

**Comment by ppoffice** [comment]
@Lechrond 没效果是不是因为你没重启Hexo Server? FAQ中也有提到

**Comment by Lechrond** [comment]
> @Lechrond 没效果是不是因为你没重启Hexo Server? FAQ中也有提到

我是部署在自己的服务器上的，用hexo g生成静态文件然后nginx转发的，应该不存在启动server的问题。

**Comment by Lechrond** [comment]
> @Lechrond 没效果是不是因为你没重启Hexo Server? FAQ中也有提到。另外你是如何修改的？

+widescreen()
    .is-1-column .container, .is-2-column .container
        max-width: $desktop -  $gap
        width: $desktop -  $gap

这里原本是减去两倍的$gap

**Comment by ppoffice** [comment]
@Lechrond 看起来你可能不是两栏布局而是三栏布局。这种情况下需要添加一个`is-3-column`的CSS。不过更简单的做法是直接修改变量的值：

https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/base.styl#L23-L27

**Comment by Lechrond** [comment]
> @Lechrond 看起来你可能不是两栏布局而是三栏布局。这种情况下需要添加一个`is-3-column`的CSS。不过更简单的做法是直接修改变量的值：
> 
> https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/base.styl#L23-L27

这是我的博客：https://lechrond.com/
我的首页是3栏布局，文章是2栏布局，您提到的这些值我在查看$gap，$desktop的值来源的时候，我也修改过了，就是没效果，我今天已经尝试了一个下午了，我也不是很理解.styl的语法，所以很多方法都试了一下，但是没有一个能起作用的。

**Comment by ppoffice** [comment]
@Lechrond 移到gitter上讨论吧，在这里讨论很容易spam

**Comment by zhangferry** [comment]
@Lechrond 能把解决方法贴下吗，遇到了相同的问题。

**Comment by Moosphan** [comment]
@ppoffice 我也遇到相似问题：不论修改 `base.styl` 还是其他配置文件，页面宽度都没有变化，clean过也没用
