### ISSUE TITLE
Front-matter中的updated参数无法显示

### ISSUE THREAD

**Issue by liu-yihong** [ppoffice/hexo-theme-icarus#698]
您好！我在post中尝试使用updated来标注文章更新时间，但是generate之后发现文章中并没有显示。请问icarus支持显示文章更新时间吗？会不会添加这个功能呢？

**Comment by ppoffice** [comment]
@liu-yihong 文章头部显示的是创建时间。若想显示更新时间，可修改此处：
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.jsx#L44

**Comment by liu-yihong** [comment]
> @liu-yihong 文章头部显示的是创建时间。若想显示更新时间，可修改此处：
> https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.jsx#L44

感谢您的回复！可否加入在文章头部显示创建时间，在文章结尾显示更新时间的功能呢？

**Comment by fi6** [comment]
请问木有jsx基础，如何修改可以同时显示updated和date……感谢！

**Comment by liu-yihong** [comment]
@fi6 

> 请问木有jsx基础，如何修改可以同时显示updated和date……感谢！

目前好像还没有更新这个功能，你可以尝试这个教程
[https://blog.vanxnf.top/2018/09/03/Hexo-%E5%8D%9A%E5%AE%A2-Hiker-%E4%B8%BB%E9%A2%98%E5%A2%9E%E5%8A%A0%E6%96%87%E7%AB%A0%E6%9C%80%E5%90%8E%E7%BC%96%E8%BE%91%E6%97%B6%E9%97%B4%EF%BC%8C%E5%B9%B6%E6%8C%89%E7%85%A7%E6%9C%80%E5%90%8E%E7%BC%96%E8%BE%91%E6%97%B6%E9%97%B4%E6%8E%92%E5%BA%8F/](url)

**Comment by fi6** [comment]
> @fi6
> 
> > 请问木有jsx基础，如何修改可以同时显示updated和date……感谢！
> 
> 目前好像还没有更新这个功能，你可以尝试这个教程
> [https://blog.vanxnf.top/2018/09/03/Hexo-%E5%8D%9A%E5%AE%A2-Hiker-%E4%B8%BB%E9%A2%98%E5%A2%9E%E5%8A%A0%E6%96%87%E7%AB%A0%E6%9C%80%E5%90%8E%E7%BC%96%E8%BE%91%E6%97%B6%E9%97%B4%EF%BC%8C%E5%B9%B6%E6%8C%89%E7%85%A7%E6%9C%80%E5%90%8E%E7%BC%96%E8%BE%91%E6%97%B6%E9%97%B4%E6%8E%92%E5%BA%8F/](url)

这个直接复制粘贴的话，jsx和ejs语法好像不一样，会报错。。嘛不过也可以学习一下简单的jsx语法然后改，不过如果有现成的教学当然最好啦

**Comment by ppoffice** [comment]
Feature added in https://github.com/ppoffice/hexo-theme-icarus/commit/670f3142293c1d5395330aa8036e82483bfc699c
