### ISSUE TITLE
Mathjax error各别latex公式 不能识别

### ISSUE THREAD

**Issue by solomy** [ppoffice/hexo-theme-icarus#699]
![image](https://user-images.githubusercontent.com/22640168/79751973-19155800-8346-11ea-94f3-fec7992842f3.png)
![image](https://user-images.githubusercontent.com/22640168/79752019-2e8a8200-8346-11ea-8762-8f7cb6dd0d98.png)

**Comment by ppoffice** [comment]
@solomy 这是因为有些LaTeX符号在Hexo生成页面时被错误的识别成Markdown语法而被渲染成HTML标签了。解决方法有：
1. 在Hexo端渲染MathJax：https://github.com/hexo-next/hexo-filter-mathjax
2. 继续使用前端的MathJax插件，但是提前转义会被识别成Markdown的字符。在这个例子中，为所有的下划线字符：

```
$$
\hat{x}\_{k}=\hat{x}\_{k}^{-}+K\_{t}\left(y\_{k}-H\hat{x}\_{k}^{-}\right)\tag{4}
$$
```

3. 在公式外面包裹一层HTML标签，其内容就不会被Markdown处理器所处理：

```
<div>
$$
\hat{x}_{k}=\hat{x}_{k}^{-}+K_{t}\left(y_{k}-H\hat{x}_{k}^{-}\right)\tag{4}
$$
</div>
```
