### ISSUE TITLE
Add meta description to achieve, category and tags pages 

### ISSUE THREAD

**Issue by iamchathu** [ppoffice/hexo-theme-icarus#70]
How to add Add meta description to achieve, category and tags pages

**Comment by ppoffice** [comment]
All pages and posts use the same header: https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/_partial/head.ejs

You can add `meta` tags here but they will appear in all of your HTML.

**Comment by ShikiSuen** [comment]
……根本沒有这个档案欸。
是不是因为版本更新而改换了目录结构？
