### ISSUE TITLE
平滑升级

### ISSUE THREAD

**Issue by AprilViolet** [ppoffice/hexo-theme-icarus#700]
想问问作者主题有啥平滑升级的方法吗？大版本之间可能难，但是这种小版本之间有啥平滑升级的方法吗？当然我是有修改一些主题的内容的，这种可以吗？求推荐方法QAQ

**Comment by ppoffice** [comment]
直接git pull git merge就行了

**Comment by AprilViolet** [comment]
emmm对哟，也可以这样，突然忘了，感谢
