### ISSUE TITLE
能否在帖子信息前加上作者名字

### ISSUE THREAD

**Issue by zapzqc** [ppoffice/hexo-theme-icarus#703]
**Is your feature request related to a problem? Please describe.**

     想把这个作为团队对外的博客，希望能够在每篇帖子上加入作者的名字。如下图：

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/3996569/80113058-626adf00-85b4-11ea-8377-2dc727ed4893.png)

![image](https://user-images.githubusercontent.com/3996569/80113173-88907f00-85b4-11ea-9968-5386f65af47e.png)

**Comment by zapzqc** [comment]
@ppoffice 不好意思，看了别人的issue，没看到针对现在这个版本的解决方法啊。他们提的要求挺合理的。具体怎么配置才能解决这个问题呢？可否说得详细一点？

**Comment by ppoffice** [comment]
@zapzqc 如果实在需要这个功能，可以修改此处，加上作者的信息：
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.jsx#L43

**Comment by zapzqc** [comment]
嗯，谢谢。下一版是否可以加上这个功能呢：在post中添加了author，就显示author；没添加就不显示，或者在配置中加一个选项。
