### ISSUE TITLE
TOC 能否支持 Page，而不只是Post

### ISSUE THREAD

**Issue by zapzqc** [ppoffice/hexo-theme-icarus#704]
通过Hexo new page '...' 建了个页面，在其中写了一些内容，希望能够使用toc来作为目录放左侧，目前好像不支持？

**Comment by ppoffice** [comment]
请对照文档检查你的是否配置步骤正确。
https://blog.zhangruipeng.me/hexo-theme-icarus/Widgets/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E6%8C%82%E4%BB%B6/#%E6%96%87%E7%AB%A0%E7%9B%AE%E5%BD%95

**Comment by zapzqc** [comment]
已经配置了。文章(post)的目录是能显示的。但普通页面(page)的目录不能显示。

**Comment by zengzhanhang** [comment]
> 请对照文档检查你的是否配置步骤正确。
> https://blog.zhangruipeng.me/hexo-theme-icarus/Widgets/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E6%8C%82%E4%BB%B6/#%E6%96%87%E7%AB%A0%E7%9B%AE%E5%BD%95

你好，请问下如何设置默认每个文章都带toc

**Comment by ppoffice** [comment]
@zapzqc 在`_config.yml`中添加`toc: true`
