### ISSUE TITLE
I have an warring

### ISSUE THREAD

**Issue by hdw0903** [ppoffice/hexo-theme-icarus#705]
WARN  Configuration file failed one or more checks.
WARN  Icarus may still run, but you will encounter unexcepted results.
WARN  Here is some information for you to correct the configuration file.
WARN  [
  {
    keyword: 'type',
    dataPath: '.widgets[7].position',
    schemaPath: '#/items/properties/position/type',
    params: { type: 'string' },
    message: 'should be string'
  }
]
when i hexo generate this warring appears
what was wrong ?
i can't find out where was wrong

**Comment by ppoffice** [comment]
Could you please post your widget config here? Also please check out the documentation for guide to config widgets. https://blog.zhangruipeng.me/hexo-theme-icarus/Widgets/icarus-user-guide-widgets/

**Comment by hdw0903** [comment]
thx, i just delete that i don't need
