### ISSUE TITLE
hexo-tag-aplayer报错

### ISSUE THREAD

**Issue by Xcellerate** [ppoffice/hexo-theme-icarus#706]
WARN  [hexo-tag-aplayer]: <head> not found in C:\...\Xcellerate_plus\themes\icarus\layout\page.jsx, unable to inject script (like 'APlayer.js') in this page.
WARN  [hexo-tag-aplayer]: <head> not found in C:\...\Xcellerate_plus\themes\icarus\layout\post.jsx, unable to inject script (like 'APlayer.js') in this page.
WARN  [hexo-tag-aplayer]: <head> not found in C:\...\Xcellerate_plus\themes\icarus\layout\post.jsx, unable to inject script (like 'APlayer.js') in this page.
WARN  [hexo-tag-aplayer]: <head> not found in C:\...\Xcellerate_plus\themes\icarus\layout\post.jsx, unable to inject script (like 'APlayer.js') in this page.

**Comment by ppoffice** [comment]
@Xcellerate 这个插件不支持本主题。
