### ISSUE TITLE
如何让footer居中……

### ISSUE THREAD

**Issue by DustyDream7** [ppoffice/hexo-theme-icarus#709]
不好意思，本以为看到以前的回答，问题可以解决，我太高估自己了……footer.styl全居中……无从下手orz

**Comment by ppoffice** [comment]
@DustyDream7 请参阅
https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/footer.jsx
https://bulma.io/documentation/layout/level/

**Comment by DustyDream7** [comment]
谢谢，懂了
<div class="level">改成<div class="level-item">就ok了
