### ISSUE TITLE
请问如何改变移动端的显示效果？

### ISSUE THREAD

**Issue by V2beach** [ppoffice/hexo-theme-icarus#710]
我想改变移动端navbar-menu的颜色，但是没有找到修改的位置，请问可以在哪找到呢？

**Comment by ppoffice** [comment]
https://www.github.com/ppoffice/hexo-theme-icarus/tree/master/include%2Fstyle%2Fresponsive.styl

**Comment by V2beach** [comment]
感谢您的回复，我用的是之前的版本，这是我修改后主题的源码https://github.com/V2beach/V2beach.github.io/tree/master/master/themes/icarus。

![blog.v2beach.cn](https://user-images.githubusercontent.com/43137418/80701007-4665c100-8b11-11ea-952d-cb8d8901c422.png)

问题是，我增添了@removeif的夜间主题后，在浏览器尺寸减小时navbar-menu会默认变成白色，我想把这里改成透明，但一直没找到在哪改..

**Comment by ppoffice** [comment]
直接把你在开发者工具栏看到的css复制到responsive.styl里并把white改为transparent就行了。

**Comment by V2beach** [comment]
成功了，我想复杂了......十分感谢您的解答。
