### ISSUE TITLE
How can I change font?

### ISSUE THREAD

**Issue by YeojinKim220** [ppoffice/hexo-theme-icarus#713]
How can I change the font of the Icarus blog? 
I want to change it but I couldn't find the tutorial. 
I am a beginner at making a blog and using web making coding.

**Comment by ppoffice** [comment]
@YeojinKim220 https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/base.styl#L9

**Comment by Srkeo** [comment]
> @YeojinKim220 https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/base.styl#L9

可以引入font.googleapis这种在线字体吗

**Comment by ppoffice** [comment]
> > @YeojinKim220 https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/base.styl#L9
> 
> 可以引入font.googleapis这种在线字体吗

https://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-cdn%E6%8F%90%E4%BE%9B%E5%95%86/
