### ISSUE TITLE
添加gitalk评论有bug

### ISSUE THREAD

**Issue by Jmlong23** [ppoffice/hexo-theme-icarus#714]
**Describe the bug**

**System and Environment**
The version and configuration of Hexo and Icarus.

- Hexo, OS, and node version (use `hexo version` command)
- Site configuration file `_config.yml`
- Theme configuration file `themes/icarus/_config.yml`
- Any additional theme configuration files (post front-matter, `_config.post.yml`, or `_config.page.yml`)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if applicable):**

**Smartphone (please complete the following information if applicable):**

**Additional context**

**Comment by Jmlong23** [comment]
WARN  Configuration file failed one or more checks.
WARN  Icarus may still run, but you will encounter unexcepted results.
WARN  Here is some information for you to correct the configuration file.
WARN  [
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/disqus.json/properties/type/const',
    params: { allowedValue: 'disqus' },
    message: 'should be equal to constant'
  },
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/changyan.json/properties/type/const',
    params: { allowedValue: 'changyan' },
    message: 'should be equal to constant'
  },
像这样子，希望大佬可以解决一下

**Comment by ppoffice** [comment]
@Jmlong23 你的评论配置写错了。请对照https://blog.zhangruipeng.me/hexo-theme-icarus/Plugins/Comment/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E7%94%A8%E6%88%B7%E8%AF%84%E8%AE%BA%E6%8F%92%E4%BB%B6/ 检查错误。

**Comment by Jmlong23** [comment]
大佬，评论配置就是按那里写的，网站可以正常评论就是报这个warn，


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ruipeng Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月3日(星期天) 晚上10:29
收件人:&nbsp;"ppoffice/hexo-theme-icarus"<hexo-theme-icarus@noreply.github.com&gt;;
抄送:&nbsp;"543196687"<543196687@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ppoffice/hexo-theme-icarus] 添加gitalk评论有bug (#714)





 
@Jmlong23 你的评论配置写错了。请对照https://blog.zhangruipeng.me/hexo-theme-icarus/Plugins/Comment/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E7%94%A8%E6%88%B7%E8%AF%84%E8%AE%BA%E6%8F%92%E4%BB%B6/ 检查错误。

**Comment by ppoffice** [comment]
@Jmlong23 你的评论配置是怎么写的

**Comment by Jmlong23** [comment]
themes\icarus\_config.yml
comment:
    type: gitalk
    client_id: bc8a046fee35afa66dfd
    client_secret: 657361040368baf39fd80cbe1d911c92eb0bf8c1
    repo: Jmlong23.github.io
    owner: Jmlong23
    admin: Jmlong23

**Comment by Jmlong23** [comment]
完整warn提示：
INFO  === Checking package dependencies ===
INFO  === Checking the configuration file ===
WARN  Configuration file failed one or more checks.
WARN  Icarus may still run, but you will encounter unexcepted results.
WARN  Here is some information for you to correct the configuration file.
WARN  [
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/disqus.json/properties/type/const',
    params: { allowedValue: 'disqus' },
    message: 'should be equal to constant'
  },
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/changyan.json/properties/type/const',
    params: { allowedValue: 'changyan' },
    message: 'should be equal to constant'
  },
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/disqusjs.json/properties/type/const',
    params: { allowedValue: 'disqusjs' },
    message: 'should be equal to constant'
  },
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/facebook.json/properties/type/const',
    params: { allowedValue: 'facebook' },
    message: 'should be equal to constant'
  },
  {
    keyword: 'type',
    dataPath: '.comment.admin',
    schemaPath: '/comment/gitalk.json/properties/admin/type',
    params: { type: 'array' },
    message: 'should be array'
  },
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/gitment.json/properties/type/const',
    params: { allowedValue: 'gitment' },
    message: 'should be equal to constant'
  },
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/isso.json/properties/type/const',
    params: { allowedValue: 'isso' },
    message: 'should be equal to constant'
  },
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/livere.json/properties/type/const',
    params: { allowedValue: 'livere' },
    message: 'should be equal to constant'
  },
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/utterances.json/properties/type/const',
    params: { allowedValue: 'utterances' },
    message: 'should be equal to constant'
  },
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/valine.json/properties/type/const',
    params: { allowedValue: 'valine' },
    message: 'should be equal to constant'
  },
  {
    keyword: 'oneOf',
    dataPath: '.comment',
    schemaPath: '#/oneOf',
    params: { passingSchemas: null },
    message: 'should match exactly one schema in oneOf'
  }
]
INFO  === Registering Hexo extensions ===
INFO  Deleted database.
INFO  Deleted public folder.

**Comment by Jmlong23** [comment]
我试了其他评论平台就不会报这个warn，比如facebook和changyan

**Comment by Jmlong23** [comment]
github上相关信息：
Homepage URL：
https://github.com/Jmlong23/Jmlong23.github.io
Authorization callback URL：
https://sanguocloud.cn/

**Comment by ppoffice** [comment]
@Jmlong23 这里
```js
{
keyword: 'type',
dataPath: '.comment.admin',
schemaPath: '/comment/gitalk.json/properties/admin/type',
params: { type: 'array' },
message: 'should be array'
},
```
和文档中 https://blog.zhangruipeng.me/hexo-theme-icarus/Plugins/Comment/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E7%94%A8%E6%88%B7%E8%AF%84%E8%AE%BA%E6%8F%92%E4%BB%B6/#Gitalk
已经说的很清楚了。`admin`不是string，而应该是array。

**Comment by Jmlong23** [comment]
好的，谢谢大佬，我看到别人都那么配，以为那里没错，惭愧惭愧，受教了

**Comment by Jmlong23** [comment]
好的，谢谢大佬，我看到别人都那么配，以为那里没错，惭愧惭愧，受教了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ruipeng Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月3日(星期天) 晚上11:13
收件人:&nbsp;"ppoffice/hexo-theme-icarus"<hexo-theme-icarus@noreply.github.com&gt;;
抄送:&nbsp;"543196687"<543196687@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ppoffice/hexo-theme-icarus] 添加gitalk评论有bug (#714)





 
@Jmlong23 你的评论配置是怎么写的
