### ISSUE TITLE
Leancloud切换到国际版以后Valine评论无法显示

### ISSUE THREAD

**Issue by Rickyhohohey** [ppoffice/hexo-theme-icarus#716]
提示
 Code -1: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
是不是因为valine不是最新版本的嗷

**Comment by ppoffice** [comment]
@Rickyhohohey https://github.com/xCss/Valine/issues/301

**Comment by Rickyhohohey** [comment]
我把本地inferno里的valine版本改成1.4.14以后就可以正常显示了。没有做其它变动
