### ISSUE TITLE
搜索框关闭按钮位置固定会导致样式错位

### ISSUE THREAD

**Issue by tiexo** [ppoffice/hexo-theme-icarus#719]
如图所示，我发现这个“x”是固定的，而搜索框的高度会随着输入、点击变化，从而导致样式错位

![9cb35c904e30ccae3de1e21e17203d16](https://user-images.githubusercontent.com/8164505/81164110-63dbd480-8fc2-11ea-96c1-89012be4acfe.jpg)

**Comment by ppoffice** [comment]
请说明浏览器和系统版本

**Comment by tiexo** [comment]
> 请说明浏览器和系统版本

Android10 qq浏览器10.3.0.6730
另外我用miui12自带的浏览器也是这样

**Comment by ppoffice** [comment]
@tiexo 可以在Chrome或Firefox浏览器上测试一下么？我在Android虚拟机中测试QQ浏览器并无此问题。有可能是你Android浏览器自带的Webkit内核有渲染问题。

**Comment by tiexo** [comment]
> @tiexo 可以在Chrome或Firefox浏览器上测试一下么？我在Android虚拟机中测试QQ浏览器并无此问题。有可能是你Android浏览器自带的Webkit内核有渲染问题。

pc上模拟是没问题，我再观察下...

**Comment by imaegoo** [comment]
小米浏览器内核版本为 `71.0.3578.141`。

Android Google Chrome 71 也能够复现该问题，Android Google Chrome 81 不能复现该问题。

![Screenshot_2020-05-08_10-02-24](https://user-images.githubusercontent.com/20182252/81362365-48ccaa00-9113-11ea-9b42-5238bf045f1d.png)
