### ISSUE TITLE
拉下icarus后  运行hexo 报错

### ISSUE THREAD

**Issue by wenyyg** [ppoffice/hexo-theme-icarus#723]
INFO  =======================================
 ██╗ ██████╗ █████╗ ██████╗ ██╗   ██╗███████╗
 ██║██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝
 ██║██║     ███████║██████╔╝██║   ██║███████╗
 ██║██║     ██╔══██║██╔══██╗██║   ██║╚════██║
 ██║╚██████╗██║  ██║██║  ██║╚██████╔╝███████║
 ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
=============================================
INFO  === Checking package dependencies ===
ERROR Package bulma-stylus is not installed.
ERROR Package hexo-component-inferno is not installed.
ERROR Package hexo-renderer-inferno is not installed.
ERROR Package inferno is not installed.
ERROR Package inferno-create-element is not installed.
ERROR Please install the missing dependencies your Hexo site root directory:
ERROR npm install --save bulma-stylus@0.8.0 hexo-component-inferno@^0.2.4 hexo-renderer-inferno@^0.1.3 inferno@^7.3.3 inferno-create-element@^7.3.3

**Comment by ppoffice** [comment]
请查看官方中文文档

**Comment by MaiIDesign** [comment]
分别输入
npm install --save bulma-stylus@0.8.0 回车，装完后再输下面（下面依次是回车，装完再输）
npm install --save hexo-component-inferno@^0.2.4 
npm install --save  hexo-renderer-inferno@^0.1.3
npm install --save  inferno@^7.3.3
npm install --save  inferno-create-element@^7.3.3
