### ISSUE TITLE
Travis CI 部署时，网页除了标题没有任何更改

### ISSUE THREAD

**Issue by ElaBosak233** [ppoffice/hexo-theme-icarus#726]
部署 [**仓库 ElaBosak233/ElaBosak233.github.io**](https://github.com/ElaBosak233/ElaBosak233.github.io)

Pages 在 `master` 上，开发在 `site` 分支上

我在电脑上使用 `hexo s` 预览时，就像图片上这样的，很正常，都调试过了

![捕获.PNG](https://i.loli.net/2020/05/16/Q123itEB5fokcyd.png)

但是通过 Travis CI 后，显示出来是这样的

![捕获.PNG](https://i.loli.net/2020/05/16/NbEJ4fust3loHrD.png)

这是我在 VSCode 里面的界面

![捕获.PNG](https://i.loli.net/2020/05/16/qcFtBKDbl5RHL6A.png)

求个解决方法吧，主题的 `_config.yml` 都是重新设置好了的，但就是没有应用

另外，如何把 CNAME 部署到 pages 上面，否则每次都要去设置，非常麻烦啊

**Comment by ppoffice** [comment]
@ElaBosak233 你Travis日志显示部署成功了么？有没有错误提示？

**Comment by ElaBosak233** [comment]
@ppoffice 成功了的，但是本来该有的都没显示出来，比如我的名字本该是`Ela`，结果还是`Your name`

**Comment by ppoffice** [comment]
@ElaBosak233 你主题的_config.yml在.gitignore的列表里而没有被push到GitHub上。请修改. gitignore或者参考本repo下site分支的.travis.yml文件关于主题配置的处理。

**Comment by ElaBosak233** [comment]
@ppoffice 没有在gitignore里面添加_config.yml，一直都在git里面的，说实在的，我感觉和生成的静态文件有关，但我不知道又错在哪里了

**Comment by ElaBosak233** [comment]
@ppoffice 现在 Travis 部署在master上的所有文件，都有文件名，但是里面**什么也没有**

**Comment by ElaBosak233** [comment]
ok，已经解决了，问题还是在gitignore上，是我疏忽了，原来是主题里面的gitignore
