### ISSUE TITLE
建议添加 爱发电(afdian.net) 赞赏按钮

### ISSUE THREAD

**Issue by ElaBosak233** [ppoffice/hexo-theme-icarus#728]
希望能添加 爱发电 赞赏通道，因为现在很多人可能都需要通过平台进行赞助

如果可以的话，建议能把自定义添加更多赞赏按钮的方法说明一下

**Comment by ppoffice** [comment]
Feature added in https://github.com/ppoffice/hexo-component-inferno/releases/tag/0.6.0
