### ISSUE TITLE
toc 目录固定

### ISSUE THREAD

**Issue by hi-dhl** [ppoffice/hexo-theme-icarus#730]
**Describe the bug**
文章有很多标题，开启toc，目录太长占满整个屏幕，想着固定toc目录，

参考 [https://github.com/ppoffice/hexo-theme-icarus/issues/470](https://github.com/ppoffice/hexo-theme-icarus/issues/470) 这个方案，新版本找不到 toc.ejs

**Comment by ppoffice** [comment]
@hi-dhl https://github.com/ppoffice/hexo-theme-icarus/issues/673

**Comment by hi-dhl** [comment]
> @hi-dhl #673

可能表达意思错了，是 toc目录 高度如何固定

**Comment by ppoffice** [comment]
@hi-dhl https://github.com/ppoffice/hexo-theme-icarus/issues/379#issuecomment-450565631

**Comment by hi-dhl** [comment]
> #379 (comment)
复制 toc.jsx 到layout/widget 目录下，报如下错误
` Error: Cannot find module '../../util/cache' `

**Comment by hi-dhl** [comment]
> @hi-dhl
> 
> 复制https://github.com/ppoffice/hexo-component-inferno/blob/master/src/view/widget/toc.jsx 到layout/widget 目录下，按照https://blog.zhangruipeng.me/hexo-theme-icarus/uncategorized/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/#%E5%B8%83%E5%B1%80 下的指示修改toc.jsx 并加上[#379 (comment)](https://github.com/ppoffice/hexo-theme-icarus/issues/379#issuecomment-450565631) 中提到的CSS样式。

感谢！！ 解决了
