### ISSUE TITLE
验证码关不掉

### ISSUE THREAD

**Issue by hi-dhl** [ppoffice/hexo-theme-icarus#731]
设置 verify: false ，评论的时候还有数字验证码，请问一下是那一块改错了吗，感谢回复

**Comment by ppoffice** [comment]
@hi-dhl 请提供你的配置和网站地址。

**Comment by hi-dhl** [comment]
> @hi-dhl 请提供你的配置和网站地址。

comment:
    type: valine
    app_id: xxxxxx       # (required) LeanCloud application id
    app_key: xxxxx       # (required) LeanCloud application key
    notify: true           # (optional) receive email notification
    verify: false           # (optional) show verification code
    placeholder: ’说点什么‘   # (optional) comment box placeholder text

测试用的网站地址：https://hi-dhl.now.sh/

**Comment by hi-dhl** [comment]
> > @hi-dhl 请提供你的配置和网站地址。
> 
> comment:
> type: valine
> app_id: xxxxxx # (required) LeanCloud application id
> app_key: xxxxx # (required) LeanCloud application key
> notify: true # (optional) receive email notification
> verify: false # (optional) show verification code
> placeholder: ’说点什么‘ # (optional) comment box placeholder text
> 
> 测试用的网站地址：https://hi-dhl.now.sh/

现在突然可以了，感谢

**Comment by hi-dhl** [comment]
我同步了一下代码之后，数字验证码有弹出来了，辛苦能帮我看一下吗

comment:
    type: valine
    app_id: xxxxx      # (required) LeanCloud application id
    app_key: xxxxxxx       # (required) LeanCloud application key
    notify: true           # (optional) receive email notification
    verify: false           # (optional) show verification code
    placeholder: ’说点什么‘   # (optional) comment box placeholder text

测试网站地址：https://hi-dhl.now.sh/2020/05/19/2020-05-19/

**Comment by ppoffice** [comment]
@hi-dhl 请清空浏览器缓存或者使用隐身模式查看网站。

**Comment by hi-dhl** [comment]
> @hi-dhl 请查看你部署网站的地方是否可以清空缓存。另外请查看网页源代码来确定verify设置成false了。

![image](https://user-images.githubusercontent.com/16751752/82322138-9a750e80-9a08-11ea-9925-6f63f2392a55.png)

缓存清除了，源代码 verify 也是false, 截图如上

**Comment by ppoffice** [comment]
@hi-dhl https://github.com/xCss/Valine/issues/20
`notify`和`verify`已在Valine 1.4.0移除。

**Comment by hi-dhl** [comment]
@ppoffice  解决了，感谢
