### ISSUE TITLE
如何隐藏代码行号

### ISSUE THREAD

**Issue by hi-dhl** [ppoffice/hexo-theme-icarus#732]
请问一下如何隐藏文章代码的行号，没有在 issues 找到相关的问题答案

**Comment by ppoffice** [comment]
@hi-dhl https://www.github.com/ppoffice/hexo-theme-icarus/tree/site/_config.yml#L44

**Comment by hi-dhl** [comment]
> @hi-dhl https://www.github.com/ppoffice/hexo-theme-icarus/tree/site/_config.yml#L44

感谢作者，辛苦了

**Comment by hi-dhl** [comment]
感谢，辛苦了
