### ISSUE TITLE
TOC bug when using with hexo-blog-encrypt

### ISSUE THREAD

**Issue by 59454anotheryanhuo** [ppoffice/hexo-theme-icarus#733]
我在用[hexo-blog-encrypt](https://github.com/MikeCoder/hexo-blog-encrypt)插件，内容和摘要都能正常显示，但是目录部分无法加载在sidebar（无论是在加密/解密刷新前后）。

**Comment by ppoffice** [comment]
@59454anotheryanhuo 请附上你网站的地址

**Comment by ppoffice** [comment]
@59454anotheryanhuo 请更新hexo-component-inferno到0.2.7版本。另外hexo-blog-encrypted会造成其他文章内容渲染的错误，在非必须加密文章的情况下不推荐使用。
