### ISSUE TITLE
关于目录显示错乱的问题

### ISSUE THREAD

**Issue by Deecyn** [ppoffice/hexo-theme-icarus#735]
**你好，当我按照以下的设置修改博客的布局后：**

![image](https://user-images.githubusercontent.com/33906598/82513560-f7c2aa00-9b45-11ea-9233-3dd4b7b550d8.png)

**当目录过长时，会出现下面这种显示比较错乱的问题：**

![image](https://user-images.githubusercontent.com/33906598/82513660-3b1d1880-9b46-11ea-8742-66048fa7cea0.png)

看着会很不美观，可以改善一下这个问题吗？

另外，**该怎么取消目录中的自动编号吗？** 像 1.1、2.1、2.2、2.2.1 这种，取消了会好很多。

**Comment by ppoffice** [comment]
1. 这不是显示错乱，是你的标题太长而你把边栏修改的太窄
2. https://github.com/ppoffice/hexo-theme-icarus/issues/374#issuecomment-609418124

**Comment by Deecyn** [comment]
> 1. 这不是显示错乱，是你的标题太长而你把边栏修改的太窄
> 2. [#374 (comment)](https://github.com/ppoffice/hexo-theme-icarus/issues/374#issuecomment-609418124)

感谢，我取消了目录的自动编号，情况好了很多。（PS：我原先的意思就是，当把边栏修改的窄一点的时候，如何让目录显示的更美观一点 😂）

**Comment by removeif** [comment]
> > 1. 这不是显示错乱，是你的标题太长而你把边栏修改的太窄
> > 2. [#374 (comment)](https://github.com/ppoffice/hexo-theme-icarus/issues/374#issuecomment-609418124)
> 
> 感谢，我取消了目录的自动编号，情况好了很多，附上 [博客链接](https://deecyn.com/) 。（PS：我原先的意思就是，当把边栏修改的窄一点的时候，如何让目录显示的更美观一点 😂）

按你这种情况，目前就有三种方式
1.就是目前这样，自动换行
2.隐藏显示不完的部分，左右滑动
3.影藏显示不完的显示为...
这三种 对比的话还是 目前方案美观适用一些吧
