### ISSUE TITLE
如何实现每篇文章所有图片居中

### ISSUE THREAD

**Issue by hi-dhl** [ppoffice/hexo-theme-icarus#736]
我参考 #386 的方案，没有实现成功

**Comment by ppoffice** [comment]
@hi-dhl #386里面的方案应该是可以的，请附上你的修改和网页地址

**Comment by hi-dhl** [comment]
@ppoffice  

$(this).wrap('<a class="gallery-item" style="display:block;text-align:center;" href="' + $(this).attr('src') + '"></a>');

我在这个地方添加了 style 可以了

**Comment by hi-dhl** [comment]
在问一个问题，如何添加版权说明

**Comment by 2w1nd** [comment]
@hi-dhl 请问在哪个文件呀？
