### ISSUE TITLE
如何修改文章的内容标题的样式

### ISSUE THREAD

**Issue by hi-dhl** [ppoffice/hexo-theme-icarus#738]
现在文章主题中 一级标题、二级标题、三级标题等等，默认的样式不够明显，想标题加粗应该如何修改

**Comment by ppoffice** [comment]
@hi-dhl
https://github.com/ppoffice/hexo-theme-icarus/blob/master/include/style/article.styl#L30-L43

**Comment by declan-haojin** [comment]
请问可以添加的属性都有哪些，比如粗体具体怎么添加，谢谢!
