### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by hi-dhl** [ppoffice/hexo-theme-icarus#739]
一个小建议，能否提供像 https://www.mdnice.com/ 这个网站一样，可以在配置文件统一更改页面的样式和代码的样式

**Comment by ppoffice** [comment]
@hi-dhl https://blog.zhangruipeng.me/hexo-theme-icarus/Configuration/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/
