### ISSUE TITLE
分享到 按钮配置问题

### ISSUE THREAD

**Issue by asker517** [ppoffice/hexo-theme-icarus#74]
@ppoffice 很Nice的一个主题。感谢作者.
请教一下您 文章右下角的分享到按钮点击后分享平台是在哪个文件中配置的？

**Comment by ppoffice** [comment]
这个是Hexo默认主题Landscape提供的插件，我直接般过来了，你可以根据需要改动这个地方：
https://github.com/ppoffice/hexo-theme-icarus/blob/master/source/js/script.js#L25

**Comment by asker517** [comment]
@ppoffice 非常感谢 :smile:
