### ISSUE TITLE
最新文章图片和分类如何删掉

### ISSUE THREAD

**Issue by hi-dhl** [ppoffice/hexo-theme-icarus#740]
请问一下 最新文章图片和分类如何删掉，没有找到入口

**Comment by ppoffice** [comment]
@hi-dhl https://blog.zhangruipeng.me/hexo-theme-icarus/Widgets/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E6%8C%82%E4%BB%B6/

**Comment by hi-dhl** [comment]
@ppoffice  作者你好，这篇文章我看过，但是并没有写 如何去掉 最新文章 显示的图片

**Comment by ppoffice** [comment]
@hi-dhl 如果你只想隐藏最新文章的图片的话，就要修改代码了

**Comment by hi-dhl** [comment]
感谢
