### ISSUE TITLE
有办法直接call一个tag吗

### ISSUE THREAD

**Issue by cybergipsy2020** [ppoffice/hexo-theme-icarus#742]
想修改tags页面给tag加上一些注释，有没有办法单独call某一个或者某几个tag

**Comment by ppoffice** [comment]
@q7nQiXMU7c 可以举个例子么？什么叫call一个tag？

**Comment by q7nQiXMU7c** [comment]
对不起我太小白了哈哈
我想要实现点进menu/tags主页以后，所有的tag可以不像两侧widget那样直接全部列出，而是列出几个我想要的，然后在后面加一段文字解释这样。所以想要单独把一个个tag分开列出来

**Comment by ppoffice** [comment]
@q7nQiXMU7c 这个实现起来较为复杂。首先，你在哪里定义你想要的tag？是不是对于不同的tag页面你想要的tags也不同？你在哪里定义tag的文字解释？如果这些问题你都考虑清楚了，你可以基于tags.jsx文件自定义tags挂件：

https://github.com/ppoffice/hexo-component-inferno/blob/master/src/view/widget/tags.jsx

**Comment by q7nQiXMU7c** [comment]
好的，感谢！请问是修改这一段吗？
```
 <Tags.Cacheable
      site={{ tags: {...} }}
      helper={{
          url_for: function() {...},
          _p: function() {...}
      }}
      tags={{...}}
      orderBy="name"
      order={1}
      amount={100}
      showCount={true} />
```

 ` tags: {...}`这里面是像
```
tags={[
          {
              url: '/path/to/category/page',
              name: 'Category name',
              count: 1
          }
      ]}
```
？

**Comment by ppoffice** [comment]
@q7nQiXMU7c 对

**Comment by q7nQiXMU7c** [comment]
哇感谢！但是这样是新定义一个tag的感觉？能具体找到已经存在的tag的count嘛
