### ISSUE TITLE
关于目录栏的滚动问题

### ISSUE THREAD

**Issue by Deecyn** [ppoffice/hexo-theme-icarus#745]
你好，在我的 icarus 主题 3.0.1 版本下：

当文章比较长的时候，如果设置整个边栏都可以滚动的话，当阅读到文章中后部的时候，目录栏已经滚动到上面去了，看不见了；如果设置边栏固定的话，在阅读文章前面的时候，又无法预览整个目录。

所以想问一下，能否实现像 [掘金](https://juejin.im) 或者 [NexT 主题](http://theme-next.iissnan.com/getting-started.html#activate-next-theme) 这样的，目录栏可以单独滚动、阅读文章的当前位置能在目录中定位的效果吗？

参考了 [#673](https://github.com/ppoffice/hexo-theme-icarus/issues/673) 和 #730 中的做法，效果不是很好。

**Comment by ppoffice** [comment]
Feature added in https://github.com/ppoffice/hexo-component-inferno/releases/tag/0.6.0
