### ISSUE TITLE
当文件名过长时，分享按钮重复出现多次

### ISSUE THREAD

**Issue by hi-dhl** [ppoffice/hexo-theme-icarus#746]
当文件名长度 >=13时，分享按钮重复出现多次，例如文件名为：寻找比目标字母大的最小字母，详情页如下所示：

![image](https://user-images.githubusercontent.com/16751752/82754016-c293b180-9dfc-11ea-9bf4-a7732dbe2723.png)

**Comment by ppoffice** [comment]
@hi-dhl 请按照issue模板提交反馈。

**Comment by ppoffice** [comment]
@hi-dhl 我这里无法复现这个问题。请检查是否是你的配置有误或是浏览器问题。

**Comment by hi-dhl** [comment]
@ppoffice  好的，后面我提交的时候，注意规范，应该是我浏览器的问题
