### ISSUE TITLE
Static Home Page

### ISSUE THREAD

**Issue by theRiddler91** [ppoffice/hexo-theme-icarus#75]
I am attempting to set up a static front (home) page -- instead of an index layout I want a page layout. I've tried making an index.md at the root of the source folder and made the layout 'page', but it doesn't make it a page layout. I know the hexo site does this so it is possible. Do I need to make a custom index.ejs at the root of the source folder or is there another way of making the home page the layout of a page? I also attempted to make pagination 0 to see if that would work and it did not.

**Comment by ppoffice** [comment]
Hexo site uses a special index layout: site/themes/navy/layout/index.swig. So you can place a layout like `__index.ejs` in the layout folder, and leave the original `index.ejs` alone. Then set `layout: __index` in your index.md.

**Comment by theRiddler91** [comment]
Okay so in the file index.ejs: `<%- partial('_partial/archive', {type: '', index: true}) %>`

I then change it to `<%- partial('_partial/homepage', {type: '__index', post: page, index: true}) %>`

Thereby making the root folder index.md would point to this if I have `layout: __index` right?

Then in the _partial/homepage, I would describe the html with the embedded js. Cool. I think this could turn out to be some cool functionality and I'll make sure I share it with you

**Comment by theRiddler91** [comment]
Doesn't hexo ignore files with leading `_`?

**Comment by theRiddler91** [comment]
https://github.com/hexojs/hexo/issues/1077 solved the problem. You can close the issue.
