### ISSUE TITLE
功能提议：在文章末尾插入［版权信息］的设置模块，谢谢！

### ISSUE THREAD

**Issue by stars-island** [ppoffice/hexo-theme-icarus#751]
> 确保你在提交功能建议之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的建议是否已经被他人提出过。

**你的功能建议与某个使用问题相关么？请详述。**

我想在博客文章末尾插入版权信息，求助网络，发现暂时没有3.0版本相关的插入版权信息的教程。
有其他高手好像是更新主题后，自己改代码什么的，所以才能够弄得出版权信息。要跑到ejs、jsx什么的文件里改配置，这超出本小白能够动手解决的能力范围了。

**描述你想要的解决方案**

盼望能加入【版权信息】的模块

**描述你考虑过的替代办法**

每次写文章都在结尾自己写一段话……？（手工业的气息）

**额外上下文**

别人家的效果是这样的。

![image](https://user-images.githubusercontent.com/66160777/83357277-145cae80-a39e-11ea-86f4-67e14cb341ad.png)

![image](https://user-images.githubusercontent.com/66160777/83357418-b8465a00-a39e-11ea-8ccb-31515c5b6f54.png)

正在努力学习GitHub文化，想自己搭个博客，自由发挥。谢谢！

**Comment by ppoffice** [comment]
Feature added in 3c9a6ca645d16a9803472572ac36e37e6b7cdcf8

**Comment by LuchaoQi** [comment]
实验了下新的功能发现当运行hexo时有如下问题:
```
INFO  === Checking package dependencies ===
INFO  === Checking theme configurations ===
WARN  Theme configurations failed one or more checks.
WARN  Icarus may still run, but you will encounter unexcepted results.
WARN  Here is some information for you to correct the configuration file.
WARN  [
  {
    keyword: 'type',
    dataPath: '.article.licenses',
    schemaPath: '/misc/poly_links.json/type',
    params: { type: 'object,null' },
    message: 'should be object,null'
  }
]
INFO  === Registering Hexo extensions ===
INFO  Deleted database.
INFO  Deleted public folder.
```

然后在更新时间后面会有个0， 效果如下：

![image](https://user-images.githubusercontent.com/46330265/91648887-3f0ce080-ea3b-11ea-9b5d-2ae474ad1a5f.png)

**Comment by ppoffice** [comment]
@LuchaoQi 你的`article.licenses`设置的值是什么？

**Comment by LuchaoQi** [comment]
> @LuchaoQi 你的`article.licenses`设置的值是什么？

不好意思, 我的问题, 重新调整设置了下`licenses`生效了

**Comment by leimao** [comment]
@ppoffice 请问能否针对个别文章去除这个license？谢谢。

**Comment by leimao** [comment]
@ppoffice 可以在这一行
https://github.com/ppoffice/hexo-theme-icarus/blob/ff5e5cb9b1252ada7b71c54ee5d731cdcbf3f188/layout/common/article.jsx#L92
加入
`config.licenses`的判断。
