### ISSUE TITLE
生成的静态网页超过设备可显示范围，没有自动适应设备的大小

### ISSUE THREAD

**Issue by Jmlong23** [ppoffice/hexo-theme-icarus#752]
![网页](https://github.com/Jmlong23/note_src/blob/master/source/images/%E7%BD%91%E9%A1%B5.png)

**Comment by Jmlong23** [comment]
点击即可看到生成网页的图片

**Comment by ppoffice** [comment]
@Jmlong23 
请按照Issue模板提交新issue。
