### ISSUE TITLE
对分类列表排序

### ISSUE THREAD

**Issue by JeanTse** [ppoffice/hexo-theme-icarus#755]
我翻了很多页issue确实没有其他人提出来。
分类列表默认是按字母顺序排序。
如果只是主分类，我还可以在主分类前添加序号手动排序，但子分类真的太多了而且随时会增加，不可能每多出一个子分类就把其他所有文章的所有序号全改一遍。
所以想问可否在config中编写分类map实现对包括子分类在内的所有类的目录排序？
（曾在主题3-hexo中用到过此功能：https://github.com/yelog/hexo-theme-3-hexo ）

**Comment by ppoffice** [comment]
@ppoffice 
1. 这个功能不应该是由主题实现，而应该是由`hexo-generator-category`实现。
2. 请按照Issue模板提交新issue。
