### ISSUE TITLE
想在单个分类页面，显示分类数量

### ISSUE THREAD

**Issue by hi-dhl** [ppoffice/hexo-theme-icarus#763]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

- [x]  [Hexo文档](https://hexo.io/zh-cn/)
- [x]  Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)
- [x]  [GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)

请问一下点击其中一个分类，进入分类界面，想在下图界面处显示当前分类的文章数量。

![image](https://user-images.githubusercontent.com/16751752/85925938-4fcf9780-b8ce-11ea-80b5-3c1b51f6a933.png)

我看了相关显示代码

```
<li class="is-active"><a href="#" aria-current="page">{page.category}</a></li>
```

page 并没有 count

**Comment by ppoffice** [comment]
@hi-dhl `category`变量下有`posts`数组，用它的`length`既可以获得文章数了

**Comment by hi-dhl** [comment]
解决了，感谢
