### ISSUE TITLE
不应当忽略_config.yml

### ISSUE THREAD

**Issue by zsh2401** [ppoffice/hexo-theme-icarus#764]
**Bug描述**
不应当在主题文件中有_config.yml，否则当使用CI（github actions）进行部署时，由于config文件没有被上传，导致没有任何配置。
这可以通过自行修改主题.gitignore文件修复

**系统与环境**
hexo: 4.2.1
hexo-cli: 3.1.0
os: Windows_NT 10.0.19041 win32 x64
node: 12.16.1

**复现方式**
使用github actions进行部署

**期望行为**
不应当在.gitignore中出现_config*.yml，这样可以通过github actions等CI正常部署。

**Comment by zsh2401** [comment]
补充,icarus版本为3.1

**Comment by ppoffice** [comment]
@zsh2401 可以在CI中添加命令拷贝配置文件：

https://github.com/ppoffice/hexo-theme-icarus/blob/site/.travis.yml#L14

**Comment by zsh2401** [comment]
> @zsh2401 可以在CI中添加命令拷贝配置文件：
> 
> https://github.com/ppoffice/hexo-theme-icarus/blob/site/.travis.yml#L14

这似乎是个不错的解决方案，但大部分情况下，大家的config.yml似乎都是放在主题文件夹下的，会被.gitignore影响。

**Comment by ppoffice** [comment]
@zsh2401 不建议不忽略_config.yml。否则每次升级主题时总会产生conflict。
