### ISSUE TITLE
translation for navigation menu

### ISSUE THREAD

**Issue by Demievil** [ppoffice/hexo-theme-icarus#77]
when I set language to zh-CN, the navigation menu doesn't translate.
see http://demievil.github.io/

**Comment by ppoffice** [comment]
You should set the config like this:
```
menu:
  主页: .
  归档: archives
  分类: categories
  标签: tags
  关于: about
```

**Comment by ppoffice** [comment]
#201

**Comment by Aironoria** [comment]
如果也想做导航的多语言，请问除了在_config.yml中硬编码是否有其他方式，比如修改languages里面的文件？
