### ISSUE TITLE
utterances 不可用

### ISSUE THREAD

**Issue by zhangxu3486432** [ppoffice/hexo-theme-icarus#770]
**Bug描述**

配置没有问题，但是使用 `issue-term` 就会报错，使用 `issue-number` 则正常。

**系统与环境**

Icarus: 3.1.1

- Hexo，操作系统，和Node.js的版本（使用`hexo version`命令来查看）

hexo: 4.2.0
hexo-cli: 3.1.0
os: Darwin 19.6.0 darwin x64
node: 12.14.1

- 站点配置文件`_config.yml`

```yaml
comment:
    # Name of the comment plugin
    type: utterances
    repo: zhangxu3486432/zhangxu3486432.github.io
    issue-term: pathname
    label: comment
    theme: github-light
```

**复现方式**

hexo s

**Error**

```
WARN  Configuration file failed one or more checks.
WARN  Icarus may still run, but you will encounter unexcepted results.
WARN  Here is some information for you to correct the configuration file.
WARN  [
  {
    keyword: 'const',
    dataPath: '.comment.type',
    schemaPath: '/comment/disqus.json/properties/type/const',
    params: { allowedValue: 'disqus' },
    message: 'should be equal to constant'
  },...
]
```

<img width="585" alt="screenshot" src="https://user-images.githubusercontent.com/30019034/88409612-c1383280-ce07-11ea-9e2f-4a0ff17e429a.png">

**Comment by ppoffice** [comment]
@zhangxu3486432 

`issue_term`, 不是`issue-term`。你配置项的名称写错了。

https://blog.zhangruipeng.me/hexo-theme-icarus/Plugins/Comment/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E7%94%A8%E6%88%B7%E8%AF%84%E8%AE%BA%E6%8F%92%E4%BB%B6/#utterances

**Comment by zhangxu3486432** [comment]
> @zhangxu3486432
> 
> `issue_term`, 不是`issue-term`。你配置项的名称写错了。
> 
> https://blog.zhangruipeng.me/hexo-theme-icarus/Plugins/Comment/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E7%94%A8%E6%88%B7%E8%AF%84%E8%AE%BA%E6%8F%92%E4%BB%B6/#utterances

已经解决，感谢！
