### ISSUE TITLE
希望适配Hexo 5.0

### ISSUE THREAD

**Issue by Flexiston** [ppoffice/hexo-theme-icarus#771]
> 确保你在提交功能建议之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的建议是否已经被他人提出过。

**你的功能建议与某个使用问题相关么？请详述。**

`hexo s` 的时候提示必须使用 Hexo 4.2.0

**描述你想要的解决方案**

希望适配Hexo 5.0

**描述你考虑过的替代办法**

简洁清晰地描述你考虑过的替代解决方案或是新功能。

**额外上下文**

附上与功能请求有关的其他上下文信息或者截图。

**Comment by ppoffice** [comment]
@Flexiston 感谢反馈。大版本更新通常会有一些问题，目前先观察一段时间，待5.0稳定之后会进行适配。若要尝鲜的话，可以修改下面这些文件：

```diff
diff --git a/package.json b/package.json
index 56d1156..a962714 100644
--- a/package.json
+++ b/package.json
@@ -21,13 +21,13 @@
   "peerDependencies": {
     "bulma-stylus": "0.8.0",
     "deepmerge": "^4.2.2",
-    "hexo": "^4.2.0",
+    "hexo": "^5.0.0",
     "hexo-component-inferno": "^0.4.0",
-    "hexo-log": "^1.0.0",
+    "hexo-log": "^2.0.0",
     "hexo-pagination": "^1.0.0",
     "hexo-renderer-inferno": "^0.1.3",
     "hexo-renderer-stylus": "^1.1.0",
-    "hexo-util": "^1.8.0",
+    "hexo-util": "^2.2.0",
     "inferno": "^7.3.3",
     "inferno-create-element": "^7.3.3",
     "moment": "^2.22.2",
```

```diff
diff --git a/include/register.js b/include/register.js
index 8847e81..3a9a530 100644
--- a/include/register.js
+++ b/include/register.js
@@ -14,7 +14,7 @@ module.exports = hexo => {
     require('hexo-component-inferno/lib/core/view').init(hexo);
 
     const hooks = [
-        'after_render:html',
+        '_after_html_render',
         'after_post_render'
     ];
     const filters = [
```

```diff
--- node_modules/hexo-component-inferno/lib/hexo/filter/locals.js.old   2020-07-29 21:06:34.800000000 -0400
+++ node_modules/hexo-component-inferno/lib/hexo/filter/locals.js       2020-07-29 21:05:03.460000000 -0400
@@ -74,24 +74,24 @@
 
     if (typeof locals._p === 'function') {
       locals.helper._p = locals._p;
     }
 
     const page = locals.page;
 
     if (page) {
       if (page.layout in ALTERNATIVE_CONFIG) {
         // load alternative config if exists
-        locals.config = Object.assign({}, Object.getPrototypeOf(locals).theme || locals.theme, ALTERNATIVE_CONFIG[page.layout]);
+        locals.config = Object.assign(locals.config || {}, Object.getPrototypeOf(locals).theme || locals.theme, ALTERNATIVE_CONFIG[page.layout]);
       } else {
         // site config already merged into theme config in hexo/lib/hexo/index.js#Hexo.prototype._generateLocals()
-        locals.config = Object.assign({}, Object.getPrototypeOf(locals).theme || locals.theme);
+        locals.config = Object.assign(locals.config || {}, Object.getPrototypeOf(locals).theme || locals.theme);
       } // merge page configs
 
 
       if (page.__post === true) {
         Object.assign(locals.config, getExtraConfig(page, RESERVED_KEYS.post));
       } else if (page.__page === true) {
         Object.assign(locals.config, getExtraConfig(page, RESERVED_KEYS.page));
       }
     }
```

**Comment by Flexiston** [comment]
@ppoffice 好的，谢谢😄

**Comment by Flexiston** [comment]
@ppoffice 请问一下，那个`locals.js`怎么修改呀

**Comment by ppoffice** [comment]
@Flexiston 在你博客下的目录里找到`node_modules/hexo-component-inferno/lib/hexo/filter/locals.js`，然后把红色行替换成绿色行即可。不过你重新使用npm或者yarn安装依赖后这个文件会还原到更改前的状态。所以记得每次`npm install`或者`yarn install`之后改过来。

**Comment by Flexiston** [comment]
好的👌谢谢

**Comment by zhutmost** [comment]
@ppoffice Hexo 5.0以后 可以通过npm 安装主题，也许我们也可以通过仓库发布主题了。
详见 https://blog.skk.moe/post/hexo-5/

**Comment by XTESLA369** [comment]
找不到啊。最新5.0的，local.js里面全部是函数。

**Comment by Langlangagojoin** [comment]
> @Flexiston 在你博客下的目录里找到`node_modules/hexo-component-inferno/lib/hexo/filter/locals.js`，然后把红色行替换成绿色行即可。不过你重新使用npm或者yarn安装依赖后这个文件会还原到更改前的状态。所以记得每次`npm install`或者`yarn install`之后改过来。

找不到这文件啊

**Comment by LuchaoQi** [comment]
我发现改版以后
发布新的post必须要在md文件最上面配置title, 不然网站无法显示新发布的post
没改版之前就算没有title也会自动把md文件的名称当作title来发布
是我的配置问题还是更新的问题?

**Comment by ppoffice** [comment]
> 
> 
> 我发现改版以后
> 发布新的post必须要在md文件最上面配置title, 不然网站无法显示新发布的post
> 没改版之前就算没有title也会自动把md文件的名称当作title来发布
> 是我的配置问题还是更新的问题?

请检查你的博客的`_config.yml`中的`permalink`是否包含`:post_title`。如果有的话文章的链接就会出错，因为此时`:post_title`为空。你可以修改成`:title`，含义参照https://hexo.io/docs/permalinks 。

至于为什么之前可以，这是因为在Hexo 5.0中允许空标题。如果你不设置标题的话，不会像之前那样默认为文章的slug：https://github.com/hexojs/hexo/pull/4344/files

**Comment by LuchaoQi** [comment]
> > 我发现改版以后
> > 发布新的post必须要在md文件最上面配置title, 不然网站无法显示新发布的post
> > 没改版之前就算没有title也会自动把md文件的名称当作title来发布
> > 是我的配置问题还是更新的问题?
> 
> @LuchaoQi 请检查你的博客的`_config.yml`中的`permalink`是否包含`:post_title`。如果有的话文章的链接就会出错，因为此时`:post_title`为空。你可以修改成`:title`，含义参照https://hexo.io/docs/permalinks 。
> 
> 至于为什么之前可以，这是因为在Hexo 5.0中允许空标题。如果你不设置标题的话，不会像之前那样默认为文章的slug：https://github.com/hexojs/hexo/pull/4344/files

我的config里面没有包含post_title 只是有title的 但好像还是不行:
https://github.com/LuchaoQi/hexo/blob/master/_config.yml
我也不知道为啥更新到5.0以后好多问题.....
而且现在最新的版本是要在_config.icarus.yml这个文件里面更改而不是在theme/icarus/config更改么?

**Comment by ppoffice** [comment]
> 
> 
> > > 我发现改版以后
> > > 发布新的post必须要在md文件最上面配置title, 不然网站无法显示新发布的post
> > > 没改版之前就算没有title也会自动把md文件的名称当作title来发布
> > > 是我的配置问题还是更新的问题?
> > 
> > 
> > @LuchaoQi 请检查你的博客的`_config.yml`中的`permalink`是否包含`:post_title`。如果有的话文章的链接就会出错，因为此时`:post_title`为空。你可以修改成`:title`，含义参照https://hexo.io/docs/permalinks 。
> > 至于为什么之前可以，这是因为在Hexo 5.0中允许空标题。如果你不设置标题的话，不会像之前那样默认为文章的slug：https://github.com/hexojs/hexo/pull/4344/files
> 
> 我的config里面没有包含`post_title` 只是包含 `title` 的 但好像还是不行:
> https://github.com/LuchaoQi/hexo/blob/master/_config.yml
> 我也不知道为啥更新到5.0以后好多问题.....

@ppoffice 你是指你放在`source/index.md`的文件么？Hexo中Posts必须放在`source/_posts`文件夹下，其他文件夹下的Markdown算作Page。Page是不会出现在archive里面的。

**Comment by LuchaoQi** [comment]
> > > > 我发现改版以后
> > > > 发布新的post必须要在md文件最上面配置title, 不然网站无法显示新发布的post
> > > > 没改版之前就算没有title也会自动把md文件的名称当作title来发布
> > > > 是我的配置问题还是更新的问题?
> > > 
> > > 
> > > @LuchaoQi 请检查你的博客的`_config.yml`中的`permalink`是否包含`:post_title`。如果有的话文章的链接就会出错，因为此时`:post_title`为空。你可以修改成`:title`，含义参照https://hexo.io/docs/permalinks 。
> > > 至于为什么之前可以，这是因为在Hexo 5.0中允许空标题。如果你不设置标题的话，不会像之前那样默认为文章的slug：https://github.com/hexojs/hexo/pull/4344/files
> > 
> > 
> > 我的config里面没有包含`post_title` 只是包含 `title` 的 但好像还是不行:
> > https://github.com/LuchaoQi/hexo/blob/master/_config.yml
> > 我也不知道为啥更新到5.0以后好多问题.....
> 
> @ppoffice 你是指你放在`source/index.md`的文件么？Hexo中Posts必须放在`source/_posts`文件夹下，其他文件夹下的Markdown算作Page。Page是不会出现在archive里面的。

不是的 我指的就是source/_posts文件夹下面, 比如我在里面新建一个 test.md
https://github.com/LuchaoQi/hexo/blob/master/source/_posts/test.md
然后config也正常的话 post 还是无法把file name 当作title

**Comment by ppoffice** [comment]
> 然后config也正常的话 post 还是无法把file name 当作title

@LuchaoQi 在Hexo 5.0中允许空标题。如果你不设置标题的话，不会像之前那样默认为文章的slug，而是默认为空：https://github.com/hexojs/hexo/pull/4344/files

**Comment by LuchaoQi** [comment]
> > 然后config也正常的话 post 还是无法把file name 当作title
> 
> @LuchaoQi 在Hexo 5.0中允许空标题。如果你不设置标题的话，不会像之前那样默认为文章的slug，而是默认为空：https://github.com/hexojs/hexo/pull/4344/files
> 
> #663
> 
> 另外以后请单开一个bug feedback issue，或者移步gitter.im讨论

好的 谢谢

**Comment by ppoffice** [comment]
Please track progress on https://github.com/ppoffice/hexo-theme-icarus/milestone/1

**Comment by jetyu** [comment]
(node:1119) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1119) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:1119) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:1119) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:1119) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:1119) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.

每次hexo s之后，就会出现这个问题，不能同步更新页面配置了，必须重新运行一遍hexo c;g;s。。。
