### ISSUE TITLE
字体图标不显示

### ISSUE THREAD

**Issue by Lyqxyz** [ppoffice/hexo-theme-icarus#779]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
页面是字体图标不是 fa fa-github 而是 fas fa-github

**系统与环境**
hexo5.0 icarus最新

- Hexo，操作系统，和Node.js的版本（使用`hexo version`命令来查看）
- 站点配置文件`_config.yml`
- 主题配置文件`_config.icarus.yml`或`themes/icarus/_config.yml`
- 其他额外的配置文件（文章front-matter，`_config.post.yml`，或`_config.page.yml`）
- 浏览器版本（如Firefox 70.0，Chrome Android 80.0）

**复现方式**
列出复现这个Bug的步骤，如：

**期望行为**
简洁清晰地描述没有这个情况下你期望得到的结果。

**截图**
![QQ截图20200820211914](https://user-images.githubusercontent.com/38280023/90775008-e0ed4880-e32a-11ea-90da-47855343c5a7.png)
![QQ截图20200820212009](https://user-images.githubusercontent.com/38280023/90775075-f19dbe80-e32a-11ea-8ce3-1a65844d0e18.png)

**额外上下文**
附上与问题有关的其他上下文信息。

**Comment by ppoffice** [comment]
@Lyqxyz https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.icarus.yml#L83

**Comment by Lyqxyz** [comment]
如果使用的fontawsome  fab fa-github不会显示

**Comment by Lyqxyz** [comment]
如果使用的fontawsome  fab fa-github不会显示

**Comment by Lyqxyz** [comment]
如果使用的fontawsome  fab fa-github不会显示

**Comment by Lyqxyz** [comment]
如果使用的fontawsome  fab fa-github不会显示

**Comment by Lyqxyz** [comment]
如果使用的fontawsome  fab fa-github不会显示

**Comment by Lyqxyz** [comment]
如果使用的fontawsome  fab fa-github不会显示

**Comment by Lyqxyz** [comment]
如果使用的fontawsome  fab fa-github不会显示

**Comment by qidai628** [comment]
国内无法访问https://use.fontawesome.com/，导致图标不能显示。请问如何主题配置里怎样替换国内的CDN？或者要修改哪个源文件。

**Comment by ee-** [comment]
@qidai628 国内可以考虑用jsdeliver 
主题配置文件`_config.icarus.yml`中
`providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL template of the webfont CDN provider
    fontcdn: google
    # Name or URL of the fontawesome icon font CDN provider
    iconcdn: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.css`
