### ISSUE TITLE
Banner & Thumbnail 设置

### ISSUE THREAD

**Issue by kapop** [ppoffice/hexo-theme-icarus#78]
请教下新建一个博客的时候，为这个篇博客添加Banner & Thumbnail，在那个地方设置呢？

**Comment by ppoffice** [comment]
在文章的头部加上：
```
banner: /hexo-theme-icarus/gallery/little-girl.jpg
thumbnail: /hexo-theme-icarus/gallery/little-girl.jpg
```

**Comment by kapop** [comment]
我图片用的外链的，下面我写的markdown文档，这样写不行啊


title: hexo写博客

tags: hexo github

thumbail: http://7xp2md.com1.z0.glb.clouddn.com/resizeApi.png

---
`

**Comment by leimao** [comment]
您好，不知道是不是错觉，感觉在Icarus主题下，banner没有用，只有thumbnail在起作用。

**Comment by lianlilin** [comment]
图片目录是中文时候不能正确加载categories设置的图片，但是在正文中插入图片是可以的
