### ISSUE TITLE
toc放在右边时，移动端功能异常

### ISSUE THREAD

**Issue by Hohalu** [ppoffice/hexo-theme-icarus#787]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
toc放在右边时，移动端功能异常。目录不能自动定位，点击后也不会跳转到相应位置。

**系统与环境**
Hexo: 5.1.1
Icarus: 4.0.0
Node.js: 12.18.3
浏览器版本: Chrome Android 85.0

**复现方式**
toc放在左边时移动端功能正常，放在右边时出现问题。

**期望行为**
toc在右边时功能也正常。

**截图**
toc放在右边时，不能自动定位，点击后不跳转到相应位置。

![001](https://user-images.githubusercontent.com/71138377/92988323-0bcb5680-f4fd-11ea-98c8-cfacbfc58d17.jpg)

放在左边时功能正常

![002](https://user-images.githubusercontent.com/71138377/92988327-0d951a00-f4fd-11ea-88e1-90a67351798e.jpg)

**额外上下文**
附上与问题有关的其他上下文信息。

**Comment by ppoffice** [comment]
@Hohalu 我这里测试没有问题。请提供一个供测试的在线页面。

**Comment by Hohalu** [comment]
> @Hohalu 我这里测试没有问题。请提供一个供测试的在线页面。

排查发现是在将 animejs 设为 `animejs: false` 后出现了这个状况，默认设置下没有问题。
提供一个 [测试页面](http://test.mosfet.xyz/posts/test/)

**Comment by ppoffice** [comment]
@Hohalu 请更新至Icarus 4.0.1并测试此问题是否仍然存在。

**Comment by Hohalu** [comment]
> @Hohalu 请更新至Icarus 4.0.1并测试此问题是否仍然存在。

非常感谢，问题已解决。
