### ISSUE TITLE
Disable "Updated On" Feature in Article licensing block

### ISSUE THREAD

**Issue by punksinatra** [ppoffice/hexo-theme-icarus#789]
Hi,

Is there a way to enable/disable the "Updated On" feature from the Article licensing block or is it something I have to configure from hexo?

**Comment by ppoffice** [comment]
@punksinatra You can not disable update date without also hiding it in the post title bar. To hide update date, set `updated_option: empty` in your site's `_config.yml`.

https://hexo.io/docs/configuration#Date-Time-format
https://github.com/ppoffice/hexo-theme-icarus/blob/site/_config.yml#L58

**Comment by ppoffice** [comment]
@punksinatra And please follow the issue template or post your question in Gitter.im.
