### ISSUE TITLE
建议添加 apple-touch-icon

### ISSUE THREAD

**Issue by satoi8080** [ppoffice/hexo-theme-icarus#791]
> 确保你在提交功能建议之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的建议是否已经被他人提出过。

**你的功能建议与某个使用问题相关么？请详述。**

我在添加书签到手机桌面的时候发现图标是网页缩略图，查看 config 之后发现只有 favicon 没有 apple-touch-icon。

**描述你想要的解决方案**

head 里添加 apple-touch-icon，我并不熟悉 hexo 开发，但是似乎相关代码在[这里](https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/head.jsx#L145)吧。

**描述你考虑过的替代办法**

并没有。

**额外上下文**

没有额外上下文了。

**Comment by ppoffice** [comment]
@satoi8080 https://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus用户指南-主题配置/#Web-App-Manifest

**Comment by satoi8080** [comment]
Manifest 并不会影响 iOS 的 PWA 图标。所以上述commit并没有完全解决 #791

**Comment by ppoffice** [comment]
@satoi8080 上面的commit不只是添加了manifest支持

**Comment by satoi8080** [comment]
不好意思我看漏了，非常感谢。

**Comment by satoi8080** [comment]
不过 apple-touch-icon 是在一个 link 不是 meta 标签里，研究了半天还是不太明白怎么改😢

**Comment by satoi8080** [comment]
找了好多资料最后发现只要 apple-touch-icon 前缀给图像命名直接放在根目录也可以起作用，HTML标签不是必需的。
总之以前还不知道，算是写在这儿留给后面来看到这儿的人吧，我是最后这样解决的。
An image file with apple-touch-icon prefix in root directory just worked, HTML tag isn't necessary.

**Comment by ppoffice** [comment]
@satoi8080 

> 
> 
> 不过 apple-touch-icon 是在一个 link 不是 meta 标签里，研究了半天还是不太明白怎么改😢


https://github.com/ppoffice/hexo-component-inferno/blob/0.10.1/src/view/misc/web_app.jsx#L51-L53
