### ISSUE TITLE
MathJax 渲染问题

### ISSUE THREAD

**Issue by Mivik** [ppoffice/hexo-theme-icarus#793]
**Bug描述**
多个公式渲染相关问题。

将`>`识别为引用：
> ![将>识别为引用](https://s1.ax1x.com/2020/09/21/wbc3nK.png)

`>`改为gt后cases压成一行：
> ![>改为gt后cases压成一行](https://s1.ax1x.com/2020/09/21/wbc80O.png)

换为手动控制的方式后错误识别公式：
> ![换为手动控制的方式后错误识别公式](https://s1.ax1x.com/2020/09/21/wbg18s.png)

更换为 Katex 后公式全部无法渲染：
> ![更换为 Katex 后公式全部无法渲染](https://s1.ax1x.com/2020/09/21/wb2VJJ.png)

[更换为 Katex 时的配置文件](https://paste.ubuntu.com/p/YqNqpXGph8/)

**系统与环境**

hexo：5.2.0
hexo-cli：3.1.0
系统：Linux 5.4.0-47-generic linux x64
node：12.16.2
浏览器：Firefox 80.0.1

**期望行为**
见 Typora 的渲染结果。

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/issues/394#issuecomment-473382263

**Comment by Mivik** [comment]
已解决。
