### ISSUE TITLE
4.0.1版本加载找不到all.css文件

### ISSUE THREAD

**Issue by sxlong0205** [ppoffice/hexo-theme-icarus#794]
**Bug描述**
架在Github上每次加载不到all.css导致无法显示右上角的搜索图标

**系统与环境**
列出你的Hexo和Icarus的版本和配置。
![image](https://user-images.githubusercontent.com/40346828/93955411-49907080-fd82-11ea-847b-925f311994fa.png)
Icarus版本 4.0.1
node.js 
![image](https://user-images.githubusercontent.com/40346828/93955524-8a888500-fd82-11ea-847d-7c40f2eadc76.png)

1. 访问博客页面
2. 页面上边的导航栏看不到搜索和Github的图标
3. 查看Network资源访问情况，发现无法访问all.css资源
![image](https://user-images.githubusercontent.com/40346828/93955727-fff45580-fd82-11ea-8cac-5d2b2ae7f09e.png)

**Comment by white-007** [comment]
> **Bug描述**
> 架在Github上每次加载不到all.css导致无法显示右上角的搜索图标
> 
> **系统与环境**
> 列出你的Hexo和Icarus的版本和配置。
> ![image](https://user-images.githubusercontent.com/40346828/93955411-49907080-fd82-11ea-847b-925f311994fa.png)
> Icarus版本 4.0.1
> node.js
> ![image](https://user-images.githubusercontent.com/40346828/93955524-8a888500-fd82-11ea-847d-7c40f2eadc76.png)
> 
> 1. 访问博客页面
> 2. 页面上边的导航栏看不到搜索和Github的图标
> 3. 查看Network资源访问情况，发现无法访问all.css资源
>    ![image](https://user-images.githubusercontent.com/40346828/93955727-fff45580-fd82-11ea-8cac-5d2b2ae7f09e.png)

那是因为需要科学上网的原因，可以使用国内cdn

修改_config.icarus.yml文件providers最后面的iconcdn为下面的地址
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.css
