### ISSUE TITLE
4.0.1文章设置两栏

### ISSUE THREAD

**Issue by Nofated095** [ppoffice/hexo-theme-icarus#795]
## 问题

Icarus 4.0.1 无法用3.x或2.x的方法将文章由三栏设置为两栏。
[Issues#658](https://github.com/ppoffice/hexo-theme-icarus/issues/658)

## 我希望的解决方案

我希望能达到下图效果
![](https://i.loli.net/2020/10/01/JCYIKFu1UkxZtyS.png)
![](https://i.loli.net/2020/10/01/Geol4Kh5i8q9fVR.png)

即主页三栏，文章两栏
并且移动端保持不变（emm是不是我的要求过分了）

## 我想过的替代方法

我没接触过jsx，但是根据其他人的解决方案，应该是icarus/layout/layou.jsx第33-34行控制的widget，所以应该是加一个判断语句，但是之前那些放在这里都是会报错的。

**Comment by Nofated095** [comment]
希望人没事，真的很喜欢这主题

**Comment by ppoffice** [comment]
@Nofated095 请阅读文档或善用issue搜索。
