### ISSUE TITLE
Feature request: Sidebar background

### ISSUE THREAD

**Issue by kp25** [ppoffice/hexo-theme-icarus#8]
The white background of the post, and the profile thing looks cleaner. Sidebar doesn't have any. I would like to have a white background for the sidebar similar to posts.
How to achieve that ?

**Comment by ppoffice** [comment]
You can edit `themes\icarus\source\css\_partial\sidebar.styl` at following lines:
```stylus
.widget-wrap
  @extend $block // add this to display thewhite&shadowed backgroud, like profile box
  padding: 15px 20px // don't forget to add padding
  margin: block-margin 10px
  @media mq-mini
    margin: block-margin 20px
```

**Comment by kp25** [comment]
Great. Here's the website [kp25.github.io/blog](http://kp25.github.io/blog). 
It looks great and seems like you should update the master branch.
