### ISSUE TITLE
toc 组件 在目录层级超过4级时会出现 错误

### ISSUE THREAD

**Issue by zapzqc** [ppoffice/hexo-theme-icarus#801]
**Bug描述**

标题层级高于4级时，toc会出错

**系统与环境**
列出你的Hexo和Icarus的版本和配置。

Icarus：4.1
Hexo 5.2.0
node.js 14.8

**期望行为**
6.2.7 后 应该时 6.2.8 但没有列出来。好几篇文章都有类似的问题。标题层级没有问题。

**截图**
![image](https://user-images.githubusercontent.com/3996569/96369405-3b205380-118c-11eb-9c34-127b678b03c3.png)

**Comment by ppoffice** [comment]
@zapzqc Please try [hexo-component-inferno@0.10.2](https://github.com/ppoffice/hexo-component-inferno/releases/tag/0.10.2).

**Comment by zapzqc** [comment]
更新 "hexo-component-inferno": "^0.10.3", 没有问题了，但是三级以后的无法展开了...最好是能够看到所有层级，哪怕规定最多6级也可以。

还有就是能否加一个默认toc展开的选项，这样看起来会方便些。

**Comment by ppoffice** [comment]
@zapzqc 请另开issue。
