### ISSUE TITLE
文章目录默认是不展开状态，如何设置文章目录默认是展开状态？

### ISSUE THREAD

**Issue by speam** [ppoffice/hexo-theme-icarus#803]
- [x] 我在提交功能建议之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)确定没找到解决办法

问题：文章目录默认是不展开状态，如何设置文章目录默认是展开状态？

</br>

**Comment by speam** [comment]
我只想展开文章的目录，像掘金的目录那样。
</br>
我看之前有人提到了这个问题，但是好像没有解决。

**Comment by ppoffice** [comment]
请按照issue模板提交issue或者在gitter上讨论。另外这个问题在其他issue中提到过，目前没有默认展开所有目录的功能。
