### ISSUE TITLE
项目安装后跑不起来

### ISSUE THREAD

**Issue by 17779286189** [ppoffice/hexo-theme-icarus#805]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
修改主题后，hexo 跑不起来，提示找不到依赖，然后npm install 后 项目跑起来页面出现这个东西，且没有_config.yml等配置
如果切换分之为site后，页面直接白屏，html结构里什么东西都没有
const { Component } = require('inferno'); const classname = require('hexo-component-inferno/lib/util/classname'); const Head = require('./common/head'); const Navbar = require('./common/navbar'); const Widgets = require('./common/widgets'); const Footer = require('./common/footer'); const Scripts = require('./common/scripts'); const Search = require('./common/search'); module.exports = class extends Component { render() { const { site, config, page, helper, body } = this.props; const language = page.lang || page.language || config.language; const columnCount = Widgets.getColumnCount(config.widgets); return
; } };

**系统与环境**
"hexo": "^5.0.0",
master 下的Icarus 没有配置，site下是默认的配置
列出你的Hexo和Icarus的版本和配置。

- Hexo，操作系统，和Node.js的版本（使用`hexo version`命令来查看）
- 站点配置文件`_config.yml`
title: Hexo
subtitle: ''
description: ''
keywords: null
author: 宿愿Cc
language: zh-CN
timezone: ''
markdown:
  render:
    html: true
    xhtmlOut: false
    langPrefix: language-
    breaks: true
    linkify: true
    typographer: true
    quotes: “”‘’
  enable_rules: null
  disable_rules: null
  plugins:
    - markdown-it-abbr
    - markdown-it-cjk-breaks
    - markdown-it-container
    - markdown-it-deflist
    - markdown-it-emoji
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: header-anchor
    permalinkSide: left
    permalinkSymbol: ¶
    case: 0
    separator: '-'
url: 'http://blog.liufengmao.cn'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: icarus
deploy:
  type: git
  repo: root@blog.liufengmao.cn/www/wwwroot/blog.liufengmao.cn/blog.git
  branch: master
search:
  path: search.xml
  field: post
  content: true
  format: html

- 主题配置文件`_config.icarus.yml`或`themes/icarus/_config.yml`
- 其他额外的配置文件（文章front-matter，`_config.post.yml`，或`_config.page.yml`）
- 浏览器版本（如Firefox 70.0，Chrome Android 80.0）

**复现方式**
列出复现这个Bug的步骤，如：
在themes下执行 git clone https://github.com/ppoffice/hexo-theme-icarus.git

1. 访问‘...’
2. 点击’...‘
3. 下拉到‘...’
4. 出现‘...’的错误

**期望行为**
简洁清晰地描述没有这个情况下你期望得到的结果。

**截图**
如果可以的话，请附上几张截图来帮助说明你遇到的问题。

**额外上下文**
附上与问题有关的其他上下文信息。

**Comment by MannyCooper** [comment]
1. 你可以使用 npm 安装最新版 icarus；
2. 如果使用 git 源码安装，可以下载 site 分支下名为 _config.icarus.yml 的配置文件到你的博客根目录，并参考 [Icarus 配置指南](https://blog.zhangruipeng.me/hexo-theme-icarus/tags/Icarus用户指南/) 进行修改；
（另，主题源码就在 master 分支下，我想是新版支持 npm 安装后，[文档](https://blog.zhangruipeng.me/hexo-theme-icarus/uncategorized/icarus快速上手/#install-source)对于传统安装方式配置文件部分的讲解有疏漏。）

**Comment by ppoffice** [comment]
你是如何修改主题的？另外请完整说明你的安装步骤？

**Comment by 17779286189** [comment]
谢谢，我后来用npm安装后根目录出现了_config.icarus.yml配置文件，然后项目跑起来的时候提示
INFO  === Checking package dependencies ===
ERROR Package bulma-stylus is not installed.
ERROR Package hexo-renderer-inferno is not installed.
ERROR Please install the missing dependencies your Hexo site root directory:
ERROR npm install --save bulma-stylus@0.8.0 hexo-renderer-inferno@^0.1.3
ERROR or:
ERROR yarn add bulma-stylus@0.8.0 hexo-renderer-inferno@^0.1.3
然后我安装这两个包就好了，

**Comment by 17779286189** [comment]
> 你是如何修改主题的？另外请完整说明你的安装步骤？

我在theme下Git clone 主分支 然后没有_config.icarus.yml这个文件，我怎么都改不动主题，我后面尝试用npm的方式成功了，但是现在代码块里面的行号没有找到取消显示行号的按钮，拷贝按钮也不显示

**Comment by ppoffice** [comment]
取消行号在根目录下的_cobfig.yml中设置。复制按钮的设置见Icarus文档网站。
