### ISSUE TITLE
Widget views only apply on server, but not generate nor deploy

### ISSUE THREAD

**Issue by ILAsoft** [ppoffice/hexo-theme-icarus#806]
**Describe the bug**
Fine adjustments done via widget views (eg. themes/icarus/layout/widget/tags.jsx) apply when running server command, but not when doing deploy or generate. 

**System and Environment**
hexo: 5.2.0
hexo-cli: 3.0.0
os: Darwin 19.6.0 darwin x64
node: 15.0.1
v8: 8.6.395.17-node.15
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 88
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0

**To Reproduce**
For example, I have changed the title on line 20 to say !!!!{title}!!!!! and able to see !!!!Tags!!!!! when running hexo server --icarus-dont-check-config --open  but when I run hexo clean --icarus-dont-check-config; hexo generate --icarus-dont-check-config the title just says Tags.

**Expected behavior**
Naturally, in my case I am actually trying to change how this (and other widgets) look and here again, it does work, but only when testing locally via hexo server, the properly generated files don't reflect my changes at all and still display the "default" HTML instead. I would expect both server and generate to work the same and to both reflect the actual changes in the widget view files.

**Screenshots**
Good: <img width="102" alt="image" src="https://user-images.githubusercontent.com/1714445/97771066-46329680-1b31-11eb-91aa-d5b855400ae7.png">
Bad:  <img width="115" alt="image" src="https://user-images.githubusercontent.com/1714445/97771071-564a7600-1b31-11eb-8fbb-17564dfe5356.png">

**Additional context**

**Comment by ppoffice** [comment]
What changes to Icarus code did you make? How did you make them? Can you post your code here?

**Comment by ppoffice** [comment]
Can you try `hexo clean` before `hexo generate`?

**Comment by ppoffice** [comment]
Do your changes reflect in your generated HTML files before you deploy them to the internet? It might be the CDN not updating the cache if you do not see your changes in the deployment.

**Comment by ILAsoft** [comment]
> Can you try `hexo clean` before `hexo generate`?

Yes, I've run full hexo clean and confirmed the folder is fully gone and the HTML gets generated from scratch. No luck. 
I also manually and specifically checked the source code of the HTML itself after the clean generate command vs the HTML produced by the server command and they are indeed very different (just as I've reported in the original report), with the generate simply using the original/default HTML. Somehow "generate" just omits the widget views... No other major differences that I can see.

**Comment by ppoffice** [comment]
@ILAsoft Could you please send me a copy of your current blog setup (with or without your posts)? It's hard to determine your issue without looking through the code.

**Comment by ILAsoft** [comment]
Sorry for the delay - I will try to package up the whole thing so it's easy to recreate and then share as soon as possible.
