### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by leshalv** [ppoffice/hexo-theme-icarus#809]
hexo s 启动后，控制台报这个错误

Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be us
ed for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.

**Comment by mendax1234** [comment]
@leshalv Have you solved this issue, l have run into the same error. If you have solved it , how do you solve it?
