### ISSUE TITLE
如何添加默认的disqus评论

### ISSUE THREAD

**Issue by jypblue** [ppoffice/hexo-theme-icarus#81]

**Comment by jypblue** [comment]
根据网上的教程，我添加了多看的评论，但是个人比较喜欢默认的评论风格，试了一下，发现虽然出现了评论两个字，但是点开还是无法加载默认的disqus评论，请教你。

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/blob/master/_config.yml.site.example#L74

**Comment by jypblue** [comment]
我知道这个名称打开，但是打开之后load不进来，是否自己要注册一个displus的账号什么的？

**Comment by ppoffice** [comment]
当然要注册账号。建议提问前充分的调查
