### ISSUE TITLE
meta name content for better SEO

### ISSUE THREAD

**Issue by nxkun** [ppoffice/hexo-theme-icarus#823]
> Make sure you go through the [Hexo docs](https://hexo.io), [Icarus user manual](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus-User-Guide/), and [GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues) to see if the feature you are requesting has been already addressed by others.

I have searched the issue list and found no one that addresses this issue

**Is your feature request related to a problem? Please describe.**
No, it just for better SEO support

A clear and concise description of what the problem is (e.g., I'm always frustrated when [...]).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

This is a default icarus generate meta tag
```
<meta
    description="Mary's simple recipe for maple bacon donuts
           makes a sticky, sweet treat with just a hint
           of salt that you'll keep coming back for.">
```

and this is the result that i need to better SEO support

```
<meta
  name="description"           
  content="Mary's simple recipe for maple bacon donuts
           makes a sticky, sweet treat with just a hint
           of salt that you'll keep coming back for.">
```

**Comment by ppoffice** [comment]
@nxkun Please upgrade `hexo-component-inferno` to [`0.10.5`](https://www.npmjs.com/package/hexo-component-inferno) to see if this problem resolves.

**Comment by nxkun** [comment]
Thanks a lot sir
