### ISSUE TITLE
刚安装hexo并下载的4.1.1版本，但hexo启动后，页面无法正常展示

### ISSUE THREAD

**Issue by northernsong** [ppoffice/hexo-theme-icarus#827]
##页面：
![image](https://user-images.githubusercontent.com/13042623/103610430-210c3b00-4f5b-11eb-9d2d-910f17d56f2a.png)

## 启动日志：
![image](https://user-images.githubusercontent.com/13042623/103610462-341f0b00-4f5b-11eb-8fc9-6efb42a6ed61.png)

hexo -v 的版本
```
INFO  === Checking package dependencies ===
INFO  === Checking theme configurations ===
INFO  === Registering Hexo extensions ===
hexo: 5.3.0
hexo-cli: 4.2.0
os: Linux 4.4.0-18362-Microsoft linux x64
node: 15.5.0
v8: 8.6.395.17-node.23
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 88
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1i
cldr: 38.0
icu: 68.1
tz: 2020b
unicode: 13.0
```

**Comment by ppoffice** [comment]
@northernsong 

1. 请按照issue模板提交issue；
2. 你的博客之前有使用过其他主题么？如果有的话请删除node_modules，移除package.json中的无关依赖，并重新安装所有依赖。
