### ISSUE TITLE
Not able to preview Icarus theme

### ISSUE THREAD

**Issue by vikilleaks** [ppoffice/hexo-theme-icarus#838]
I simple followed the instructions to install icarus theme in my new blog.
The instructions are:
1. npm install hexo-cli -g
2. hexo init blog
3. cd blog
4. npm install -S hexo-theme-icarus
5. hexo config theme icarus
6. hexo server
However on opening localhost:4000 I can only see the following:

const { Component } = require('inferno'); const classname = require('hexo-component-inferno/lib/util/classname'); const Head = require('./common/head'); const Navbar = require('./common/navbar'); const Widgets = require('./common/widgets'); const Footer = require('./common/footer'); const Scripts = require('./common/scripts'); const Search = require('./common/search'); module.exports = class extends Component { render() { const { site, config, page, helper, body } = this.props; const language = page.lang || page.language || config.language; const columnCount = Widgets.getColumnCount(config.widgets); return
; } };

**Comment by ppoffice** [comment]
@vikilleaks 
1. You did not install the dependencies as instructed by the Icarus logs.
2. Please follow the issue template.

**Comment by vikilleaks** [comment]
It worked when I installed using source instead of using npm.

**Comment by bubbleboy11** [comment]
> It worked when I installed using source instead of using npm.

how to fix it

**Comment by vikilleaks** [comment]
@bubbleboy11 I don't know how the npm approach will work.

**Comment by mavier** [comment]
I had the same issue, and it was solved by installing this package
`npm install --save hexo-renderer-inferno`
