### ISSUE TITLE
Google Adsense widget not working

### ISSUE THREAD

**Issue by vikilleaks** [ppoffice/hexo-theme-icarus#839]
On creating my google adsense account, I am only able to retrieve data-ad-client from the Adsense code.
From where can I get data-ad-slot? 

To enable adsense as per icarus user guide, we need to copy the values of data-ad-client and data-ad-slot from the AD HTML code to the client_id and slot_id setting of the widget configuration, respectively.

**Comment by vikilleaks** [comment]
<script data-ad-client="ca-pub-xxxxxxxx" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

This is the Adsense code I received after creating my Adsense account.

**Comment by nxkun** [comment]
data-ad-client it from a ads unit. Make sure your account was approved by google adsense
