### ISSUE TITLE
click logo and goto a wrong url

### ISSUE THREAD

**Issue by lightAfire** [ppoffice/hexo-theme-icarus#84]
in header.ejs, 
```
<a href="<%- url_for() %>" id="logo"> 
```
after compile it become 
```
<a href="/" id="logo">
```
and my web index url = "lightafire.github.io/blog", root="/blog/" , but click the logo it go to the url "lightafire.github.io" and got 404.

i think if it should become 
```
<a href="<%- url_for(theme.root)" id="logo">
```
?

**Comment by ppoffice** [comment]
https://hexo.io/docs/helpers.html#URL

The default `url_for()` will point to blog's root if no arguments specified.
I suppose you didn't set the right `root` in the blog's _config.yml.
https://github.com/ppoffice/hexo-theme-icarus/blob/master/_config.yml.site.example#L22

**Comment by lightAfire** [comment]
url: http://lightafire.github.io/blog
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

this is my _config.yml file.
but it doesn't work.

**Comment by lightAfire** [comment]
but if i use 
```
<%- url_for('1') %>
```
the tag will become
```
<a href="/blog/1" id="logo">
```
i don't know why

**Comment by lightAfire** [comment]
i find the answer in these code
```
function urlForHelper(path, options){
  /* jshint validthis: true */
  path = path || '/';

  var config = this.config;
  var root = config.root;
  var data = url.parse(path);

  options = _.assign({
    relative: config.relative_link
  }, options);

  // Exit if this is an external path
  if (data.protocol || path.substring(0, 2) === '//'){
    return path;
  }

  // Resolve relative url
  if (options.relative){
    return this.relative_url(this.path, path);
  }

  // Prepend root path
  if (path[0] !== '/'){
    return root + path;
  }

  return path;
}
```
if you dont't give it a path it will return '/'.
so i think should use url_for(theme.root).

**Comment by lightAfire** [comment]
it happened because i use a old version of hexo. the bug has been fixed now.

**Comment by lightAfire** [comment]
in hexo 3.1.1, url_for() is like this.
```
function urlForHelper(path, options){
  /* jshint validthis: true */
  path = path || '/';

  var config = this.config;
  var root = config.root;
  var data = url.parse(path);

  options = _.assign({
    relative: config.relative_link
  }, options);

  // Exit if this is an external path
  if (data.protocol || path.substring(0, 2) === '//'){
    return path;
  }

  // Resolve relative url
  if (options.relative){
    return this.relative_url(this.path, path);
  }

  // Prepend root path
  if (path[0] !== '/'){
    return root + path;
  }

  return path;
}
```
so if use url_for() it will return '/' instead of root.

**Comment by lightAfire** [comment]
in 3.2.0 it will be fixed, but now it doesn't work
