### ISSUE TITLE
Ability to remove footer icon

### ISSUE THREAD

**Issue by developomp** [ppoffice/hexo-theme-icarus#843]
Currently, the icarus theme adds the website icon to the footer and we have no way of disabling it.
Can we have a feature where we can enable and disable the footer icon in the config.yml file?

File to change: `layout/common/footer.jsx`
lines:
```js
<a class="footer-logo is-block mb-2" href={siteUrl}>
  {footerLogo}
</a>
```

**Comment by ppoffice** [comment]
IMO, this is a trivial feature and I don't see much use cases of it. In light of the configuration simplicity, I will leave this out to the users to customize instead of adding an option for it.

**Comment by developomp** [comment]
oh I thought I closed this already
