### ISSUE TITLE
Google auto ads won't load on article post

### ISSUE THREAD

**Issue by nxkun** [ppoffice/hexo-theme-icarus#848]
> Make sure you go through the [Hexo docs](https://hexo.io), [Icarus user manual](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus-User-Guide/), and [GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues) to see if the bug you are reporting has been already addressed by others.

**Describe the bug**

When use old Icarus (ejs version) Google auto ads is work normally on post article but when using jsx version (inferno) Google auto ads won't load on post article. this issue only happent on post article for the rest is work normally

**System and Environment**
The version and configuration of Hexo and Icarus.

Icarus version that I use when open this issue is master and here is Hexo version

```
hexo: 5.4.0
hexo-cli: 4.2.0
os: Linux 5.4.101 linux amd64
node: 14.16.0
v8: 8.4.371.19-node.18
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 83
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1j
cldr: 37.0
icu: 67.1
tz: 2020a
unicode: 13.0
```

- Hexo, OS, and node version (use `hexo version` command to view these information)
- Site configuration file `_config.yml`
- Theme configuration file `_config.icarus.yml` or `themes/icarus/_config.yml`
- Any additional theme configuration files (post front-matter, `_config.post.yml`, or `_config.page.yml`)
- Browser and version (e.g., Firefox 70.0, Chrome Android 80.0)

**To Reproduce**
Steps to reproduce the behavior, such as:

2. Click on '...'
3. Scroll down to '...'
4. '...' error appears

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ppoffice** [comment]
Do you use _config.post.yml for configuring posts separately from _config.icarus.yml?

**Comment by nxkun** [comment]
> Do you use _config.post.yml for configuring posts separately from _config.icarus.yml?

No i don't use it. My icarus config (_config.yml only this one) is located on "hexo/themes/icarus" should i use _config.post.yml to on my "hexo/themes/icarus"

**Comment by ppoffice** [comment]
@nxkun 
1. I don't recall old ejs Icarus had built-in Google AdSense support. Did you add the AD slots by yourself?
2. Make sure your slot ID and client ID are correct.
https://ppoffice.github.io/hexo-theme-icarus/Widgets/icarus-user-guide-widgets/#Google-AdSense
3. Did you override widget settings in your post's front-matter? If so, include the AdSense widget settings as well.
4. It will be helpful if you provide more information of the error. You can find it in your browser's console, or you can post a link to your website.
https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by nxkun** [comment]
@ppoffice 

1. On old ejs Icarus I just put on a Google Ads script on head.ejs bellow this [line](https://github.com/sudoliyang/hexo-theme-icarus/blob/7b224b03b218cb5b5a636e4cd3b353a0738faa77/layout/common/head.ejs#L3)

```
<script data-ad-client="ca-pub-1234567890123456" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
``` 
And Google auto Ads will auto placed by the (Google) script inside post article (markdown content) and another place such as bellow navbar, bellow widgets (profile, category, recent post) and at top of footer randomly

2. At this point I have no issue on jsx (inferno) Icarus Google Ads is show up on Widget Adsense, and places that I mention at above except inside post article (markdown content)

3. Did you mean _config.post.yml? I don't use this one. I just only use config (_config.icarus.yml) that generated by Icarus on the first run and I moved it to "hexo/themes/icarus" and renamed it to _config.yml

4. In my opinion it's not an error cause Google auto ads still loaded like I mention at above point 2.

 The issue is Google auto Ads won't show up or loaded on post article (markdown content) but if I put on a Google Ads unit on post article (Markdown Content) the Ads is loaded. 


* Google Auto Ads will places randomly by Google

* Google Ads unit user need places manually in this case Icarus places in Adsense Widget

**Comment by ppoffice** [comment]
Sorry I can't give you any advice without seeing your exact configuration or error information.

**Comment by nxkun** [comment]
What I did at point 1 already on Icarus

https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/head.jsx#L163-#L164

Oke thanks a lot for your time. I think this issue also on a React too.

Oke close this issue. Thanks a lot
