### ISSUE TITLE
多张图片能否并排显示？目前好像只支持一张图片占一行

### ISSUE THREAD

**Issue by V2beach** [ppoffice/hexo-theme-icarus#854]
> 确保你在提交功能建议之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的建议是否已经被他人提出过。

**你的功能建议与某个使用问题相关么？请详述。**

请问有办法让图片并排显示吗？我没有在issues和doc中找到解决方案。

**描述你想要的解决方案**

希望图片可以并排显示，比如有时需要两张图表的图片显示在同一行起到对比效果。

**描述你考虑过的替代办法**

考虑过把几张图片拼成一张，但显示效果有点差，修改过css但没有达到目的...

**Comment by V2beach** [comment]
还有一种替代方案，是把图片显示在一个表格里，但效果也不理想。

**Comment by ppoffice** [comment]
https://ppoffice.github.io/hexo-theme-icarus/Plugins/Other/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E5%85%B6%E4%BB%96%E6%8F%92%E4%BB%B6/#%E7%94%BB%E5%BB%8A

**Comment by V2beach** [comment]
原来如此！没有在归档里找到这个插件的文章，谢谢！

**Comment by V2beach** [comment]
> 
> 
> https://ppoffice.github.io/hexo-theme-icarus/Plugins/Other/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E5%85%B6%E4%BB%96%E6%8F%92%E4%BB%B6/#%E7%94%BB%E5%BB%8A

https://blog.v2beach.cn/2021/04/02/justified-gallery/
![justified-gallery](https://user-images.githubusercontent.com/43137418/113402516-b0e54800-93d7-11eb-87f2-ecc461c4e251.png)

请问为什么跟您的效果不一样呢...？没法按照图片个数填充满两行。
