### ISSUE TITLE
thumbnail 图片的大小怎么设置

### ISSUE THREAD

**Issue by ohmerhe** [ppoffice/hexo-theme-icarus#87]
thumbnail 图片的大小怎么设置
banner 图片的大小怎么设置

**Comment by ppoffice** [comment]
Thumbnail:
https://github.com/ppoffice/hexo-theme-icarus/blob/250600d06e38f7b3a5b34c4c640298da43c4e6ab/source/css/_partial/archive.styl#L38
https://github.com/ppoffice/hexo-theme-icarus/blob/250600d06e38f7b3a5b34c4c640298da43c4e6ab/source/css/_partial/sidebar.styl#L124
Banner:
https://github.com/ppoffice/hexo-theme-icarus/blob/f82df5f528e4e430317160a9af075f13a5f65704/source/css/_partial/article.styl#L8
