### ISSUE TITLE
“返回顶部”的按钮无效

### ISSUE THREAD

**Issue by liuling07** [ppoffice/hexo-theme-icarus#88]
为什么我的“返回顶部”的按钮点击没有效果，并且滚动到底部时按钮没有固定在下方，而是随着滚动条滚动到上面去了

**Comment by ppoffice** [comment]
应该是你的网络环境中Google的CDN被墙导致的。
可以换用USTC或者360的CDN：
https://github.com/ppoffice/hexo-theme-icarus/pull/82

**Comment by liuling07** [comment]
谢谢，修改之后好了。
