### ISSUE TITLE
文章列表显示评论数的问题

### ISSUE THREAD

**Issue by liuling07** [ppoffice/hexo-theme-icarus#89]
请问下在文章列表页面，比如点击了某个分类，文章列表只显示了文章标题和发表日期，如何添加评论数？需要修改哪个ejs文件?

**Comment by ppoffice** [comment]
如果只是添加评论数的话，可以参考以下两行修改`/layout/_partial/archive-post.ejs`文件：

> https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/_partial/article.ejs#L37
> https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/_partial/article.ejs#L39

如果要照搬首页的样式，可以将`/layout/_partial/archive.ejs`文件中的所有`archive-post`替换为`archive`。

**Comment by liuling07** [comment]
找到了，感谢。
