### ISSUE TITLE
移动端下一页无反应

### ISSUE THREAD

**Issue by Nofated095** [ppoffice/hexo-theme-icarus#896]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
在移动端，无法点开下一页（禁用了Js也没用

**系统与环境**
列出你的Hexo和Icarus的版本和配置。

Icarus 4.2.0（4.3.0同）

浏览器：

- iOS 13 Safari
- iOS 13 Microsoft Edge

**复现方式**

使用手机移动端打开由 Icarus 4.2.0 渲染的博客（文章数大于10），下拉到博客底部，找到显示Next或者下一页的按钮，出现无法点开下一页，按钮无响应

**期望行为**
按钮能引领到下一页

或者直接取消移动端的下一页，改为单页面，这样也会比较简洁

**截图**
![48CDF884-AA26-4758-ACC3-50D0AD9177BE](https://user-images.githubusercontent.com/49985975/126860099-1033f136-1601-44b4-aec6-d4882dcb947a.png)
![1227CCBB-4B11-4355-A278-C8524501B4FD](https://user-images.githubusercontent.com/49985975/126860103-9ead3f9c-e30e-4afe-8f10-ebe3772d41e8.png)

**Comment by ppoffice** [comment]
@Nofated095 点到Next文字上试一下？

**Comment by Nofated095** [comment]
确实，需要点到字上面，不过还是希望以后能将其改成整个按钮
