### ISSUE TITLE
Multiple Languages

### ISSUE THREAD

**Issue by KevinAdu** [ppoffice/hexo-theme-icarus#90]
First of I wanted to thank you, this is a very nice theme for Hexo.

I wanted to ask is there a way for the user to select what language they want.
So maybe the default is in the English and the user also has the ability to select Japanese as a language.

Is there anyway to set this in this theme?

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus#site-configuration-example
https://github.com/ppoffice/hexo-theme-icarus/blob/master/_config.yml.site.example#L15
https://github.com/ppoffice/hexo-theme-icarus/tree/master/languages

**Comment by KevinAdu** [comment]
Okay thank you, that doesn't really solve my issue though.
 In my _config.yml_ I have the following set:

    language: 
     - en
     - ja

But there is no option for the user to change the language in the actual website (like a language bar in the header which could look like **EN | JA**).

**Comment by ppoffice** [comment]
Currently you can only set different language for posts & pages according to https://hexo.io/docs/internationalization.html, languages will not be applied to homepage and this causes link confusions.
