### ISSUE TITLE
配置项中的 article.update_time 似乎不生效了

### ISSUE THREAD

**Issue by KaitoHH** [ppoffice/hexo-theme-icarus#910]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
配置项中的 article.update_time 似乎不生效了

**系统与环境**
列出你的Hexo和Icarus的版本和配置。

- Hexo: 5.4.0
- hexo-theme-icarus: 4.4.0

**复现方式**
文章开头
![image](https://user-images.githubusercontent.com/13927774/128748934-bcf1768d-8fec-4102-89e1-8b22ee13925f.png)

根据下图配置
![image](https://user-images.githubusercontent.com/13927774/128749296-2fcf6ded-b6b5-4096-9741-3a48f4b9fb39.png)

把 update_time 设置为 `false` 时，依然会显示更新时间。

![image](https://user-images.githubusercontent.com/13927774/128749139-d880a0f6-fc20-4a15-8786-5de91e958682.png)

**Comment by ppoffice** [comment]
@KaitoHH 需要通过源代码方式安装Icarus。NPM上的版本还未更新此功能。

**Comment by KaitoHH** [comment]
抱歉，没注意这是昨天才增加的feature，看到文档里有这个配置就以为很早就有了。

**Comment by KaitoHH** [comment]
请问目前版本的 update_time 选项工作正常吗？似乎不管如何设置更新时间始终会显示
![image](https://user-images.githubusercontent.com/13927774/189483809-30927a5d-7a11-45f5-9578-bca0e232aa46.png)

- Hexo: 6.2.0
- hexo-theme-icarus: 5.1.0

**Comment by ppoffice** [comment]
@KaitoHH License部分的更新时间显示不受`article.update_time`影响。
