### ISSUE TITLE
hexo server on icarus file directory not working

### ISSUE THREAD

**Issue by geek-developer** [ppoffice/hexo-theme-icarus#92]
![1](https://cloud.githubusercontent.com/assets/9413962/12744057/4ef43412-c9a7-11e5-8a62-62ba0022b231.png)
![2](https://cloud.githubusercontent.com/assets/9413962/12744058/4ef84c5a-c9a7-11e5-9afa-8671d962bf78.png)
 
this is the file directory

**Comment by ppoffice** [comment]
Icarus is only a Hexo theme.

You need to init a Hexo blog first: https://hexo.io/docs/setup.html
