### ISSUE TITLE
Bad display of sidebar caused by table of content widget

### ISSUE THREAD

**Issue by CrSjimo** [ppoffice/hexo-theme-icarus#926]
**Describe the bug**
Table of contents is the only widget included in the right sidebar. When displaying a page without table of contents (e.g. homepage), it layouts as if the right sidebar was still there (actually nothing is shown).

**System and Environment**
- hexo 5.0.2
- icarus 4.4.0
- Firefox 92.0

**Screenshots**
![Screenshot](https://pic.imgdb.cn/item/6134a2f844eaada739aa5297.jpg)

**Additional context**
The problem is probably caused by the function `hasColumn` at `widgets.jsx:22`. The function detects whether a sidebar has any widgets by traversing the configuration to check if the position is configured to any widgets. However, it does not consider whether table of contents widgets displays on current page or not, and it retures a wrong existence of widget.

**Comment by CrSjimo** [comment]
I have tried to fix the problem
If I detect whether toc exists in the function mentioned above, the bug will be fixed:

```jsx
function hasColumn(widgets, position, config, page) {
    const showToc = (config.toc === true || page.toc) && ['page', 'post'].includes(page.layout);
    if (Array.isArray(widgets)) {
        return typeof widgets.find(widget => {
            if(widget.type === 'toc' && !showToc)return false;
            return widget.position === position
        }) !== 'undefined';
    }
    return false;
}
```

But the side effect of this change is that the argument `config` and `page` should be passed to this function at every call of the function. I attempted to test it but I do not know how to test such a project. Anyhow, I indeed changed every reference of the function (in `widgets.jsx` and `layout.jsx`), adding the two arguments in the parameter list of every call and it seems work.

May I file a pr? ('・ω・')

**Comment by ppoffice** [comment]
@CrSjimo Yes, please go ahead with the PR.

Some other suggestions:

1. You can omit checking `page.toc` since this config is merged into `config` variable. An example is [here](https://github.com/ppoffice/hexo-component-inferno/blob/0.13.0/src/view/widget/toc.jsx#L173).
2. Please keep all semicolons and brackets.
