### ISSUE TITLE
代码块折叠之后滚动条依然存在，不美观

### ISSUE THREAD

**Issue by jinyiliu** [ppoffice/hexo-theme-icarus#953]
**你的功能建议与某个使用问题相关么？请详述。**

我在使用 code block 的时候，发现如果代码折叠，滚动条依然存在，感觉不是很美观。

**描述你想要的解决方案**

代码折叠的时候不出现滚动条。

**描述你考虑过的替代办法**

替代办法，就是不去管它，不是什么非常严重的问题，就是看起来稍微不那么美观。
如果你们觉得不重要的话，可以直接把这个 Issue 关闭了，不是什么太大的问题。

**额外上下文**

这是截图

<img width="618" alt="截屏2021-10-09 下午6 44 58" src="https://user-images.githubusercontent.com/23398808/136654808-623c3485-6d61-40e2-95f3-4dc495da6839.png">

**Comment by ppoffice** [comment]
@jinyiliu 无法在firefox和microsoft edge上复现。请提供一个可用的demo来展示此问题。

**Comment by jinyiliu** [comment]
抱歉！之前在 Safari 上发现了这个问题，但是这几天又没有了，应该是 Safari 自己的问题，之后如果重新出现我再去怎么回事。谢谢！
