### ISSUE TITLE
Feature Request:Consider add keywords for a post rather than tags instead

### ISSUE THREAD

**Issue by huhuapin** [ppoffice/hexo-theme-icarus#960]
Consider adding keywords at the top of each post so that the generated web page head contains meta = keywords

**Comment by Ricky-G** [comment]
@ppoffice any suggestions to get around this please.

**Comment by ppoffice** [comment]
@Ricky-G http://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus-user-guide-configuring-the-theme/#Page-Metadata
