### ISSUE TITLE
bad image

### ISSUE THREAD

**Issue by chantisnake** [ppoffice/hexo-theme-icarus#97]
![screenshot - copy](https://cloud.githubusercontent.com/assets/10100995/13119288/5d9e880c-d576-11e5-9d6a-ae10c67d4bfe.png)

on the top right corner. 
I have tried on Edge, IE, and firefox, nothing works.

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-icarus/wiki/Theme#profile

**Comment by chantisnake** [comment]
That works, Thanks.
