### ISSUE TITLE
Long tag name overflows at widget

### ISSUE THREAD

**Issue by CrSjimo** [ppoffice/hexo-theme-icarus#970]
Long tag name overflows at widget.

**To Reproduce**

Give a long name to a tag, and enable the tags widget.

**Screenshots**

Latest Firefox:
![Latest FIrefox](https://user-images.githubusercontent.com/35359408/143243529-001cbfa5-8b1c-491e-8f16-0cecb97d7470.png)

Latest Chromium:
![Latest Chromium](https://user-images.githubusercontent.com/35359408/143243623-679ae754-49fa-456e-b587-3da80b248e24.png)

**Comment by ppoffice** [comment]
@CrSjimo There is no simple way to wrap the tag title and keep both the title and the number on the same line. Tags are meant to be concise and short. And I currently have no plan to change the current behavior.
