### ISSUE TITLE
按照 #730 的方法载入 toc.jsx 文件后，跳转动画不可用

### ISSUE THREAD

**Issue by gukaifeng** [ppoffice/hexo-theme-icarus#971]
按照 #730 的方法载入 toc.jsx 文件后，点击目录，是直接跳转，而不是原来的滚动过去。
如何让目录点击滚动，而不是直接跳转？

另外，在 yaml 配置文件中关于 toc 的配置，例如 index 配置、折叠配置都不可用了。

**Comment by ppoffice** [comment]
@gukaifeng 你是怎么修改的呢？`<script>`和css都没了：
https://github.com/ppoffice/hexo-component-inferno/blob/master/src/view/widget/toc.jsx#L144-L145

**Comment by gukaifeng** [comment]
> @gukaifeng 你是怎么修改的呢？`<script>`和css都没了： https://github.com/ppoffice/hexo-component-inferno/blob/master/src/view/widget/toc.jsx#L144-L145

谢谢，问题解决了。问题原因是我在 #673 点进了 toc.jsx 页面，我以为是一样的，没有注意到那里给出的不是最新版本。
