### ISSUE TITLE
Tested ok but when deployed the website do not load js css...files

### ISSUE THREAD

**Issue by yuanchenhao** [ppoffice/hexo-theme-icarus#99]
I installed several themes of your office,all works well under debug mode in localhost:4000

But when I deployed then I always find that all the webpages load only with plain words,what happened?

[When switch to other themes they all works well ]

**Comment by ppoffice** [comment]
Do you have a good connectivity to the webpage host(GitHub pages)?

If not, you may want to replace local js libraries and web fonts with their CDN versions.

You can open the browser's inspection panel(F12) to see which files are not properly loaded.
